Repository FabricMC/yarn, pull requests merged in 2019-11, with the labels that each got.

#937 StructurePoolBasedGenerator mappings (#919)
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
Labels: new, ready to merge, snapshot

#935 Minor stuff for util package
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/util/ActionResult.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/LowercaseEnumTypeAdapterFactory.mapping
  mappings/net/minecraft/util/Pair.mapping
  mappings/net/minecraft/util/TaskPriority.mapping
  mappings/net/minecraft/util/ThreadExecutor.mapping
  mappings/net/minecraft/util/TypedActionResult.mapping
  mappings/net/minecraft/util/WeightedList.mapping
  mappings/net/minecraft/util/math/AxisCycleDirection.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Quaternion.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
Labels: new, snapshot

#936 [combat 3] chopping and stuff
  mappings/net/minecraft/class_4466.mapping
  mappings/net/minecraft/enchantment/ChoppingEnchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributes.mapping
  mappings/net/minecraft/item/MiningToolItem.mapping
  mappings/net/minecraft/item/ToolType.mapping
Labels: new

#940 Fill the names in AdvancementTabType with existing names in the context
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTabType.mapping
Labels: new, ready to merge, snapshot

#914 Produce TinyV2 mappings
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, ready to merge, toolchain

#946 Update engima to latest
  build.gradle
Labels: enhancement, toolchain

#839 Shape mappings
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/FenceBlock.mapping
  mappings/net/minecraft/block/FenceGateBlock.mapping
  mappings/net/minecraft/client/render/block/FluidRenderer.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/shape/DisjointPairList.mapping
  mappings/net/minecraft/util/shape/DoubleListPair.mapping
  mappings/net/minecraft/util/shape/FractionalPairList.mapping
  mappings/net/minecraft/util/shape/IdentityListMerger.mapping
  mappings/net/minecraft/util/shape/IdentityPairList.mapping
  mappings/net/minecraft/util/shape/PairList.mapping
  mappings/net/minecraft/util/shape/SimpleDoubleListPair.mapping
  mappings/net/minecraft/util/shape/SimplePairList.mapping
  mappings/net/minecraft/util/shape/SlicedVoxelShape.mapping
  mappings/net/minecraft/util/shape/VoxelSet.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/util/shape/VoxelShapes.mapping
Labels: new, ready to merge, refactor, snapshot

#945 Map biome color cache stuff and matrixstack pop
  mappings/net/minecraft/client/network/packet/ChunkDataS2CPacket.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/client/world/BiomeColorCache.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/world/World.mapping
Labels: new, ready to merge, snapshot

#949 Player-suggested changes
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/client/render/block/FluidRenderer.mapping
Labels: enhancement, refactor, snapshot

#955 46a new stuff
  mappings/net/minecraft/advancement/criterion/BeeNestDestroyedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BlockUsedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/Criterions.mapping
  mappings/net/minecraft/advancement/criterion/SlideDownBlockCriterion.mapping
  mappings/net/minecraft/class_4708.mapping
  mappings/net/minecraft/class_4711.mapping
  mappings/net/minecraft/class_4713.mapping
  mappings/net/minecraft/class_4715.mapping
  mappings/net/minecraft/class_4717.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractCommandBlockScreen.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/util/GlException.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/world/gen/feature/NoOpFeature.mapping
Labels: new, snapshot

#948 Produce TinyV2 mappings for 1.14.4
  build.gradle
Labels: enhancement, release, toolchain

#962 Mapped PlayerSkinTexture
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/client/texture/PlayerSkinTexture.mapping
Labels: new, snapshot

#961 New vector and direction methods used in ModelPart
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/util/math/Vector3f.mapping
  mappings/net/minecraft/util/math/Direction.mapping
Labels: new, snapshot

#950 Rename the body parts to be more descriptive
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CreeperEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ModelWithArms.mapping
  mappings/net/minecraft/client/render/entity/model/PlayerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/QuadrupedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SkeletonEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/StrayEntityModel.mapping
Labels: refactor, snapshot

#966 Fix various issues
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/predicate/StatePredicate.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: ready to merge, refactor, snapshot

#959 46b new stuff and a few fixed entity methods from 46a
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: new, refactor, snapshot

#799 Mapped several things across all the modelling classes and renderers
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/BakedQuadFactory.mapping
  mappings/net/minecraft/client/render/model/CubeFace.mapping
  mappings/net/minecraft/client/render/model/ModelBakeSettings.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/MultipartBakedModel.mapping
  mappings/net/minecraft/client/render/model/MultipartUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ItemModelGenerator.mapping
  mappings/net/minecraft/client/render/model/json/ModelElement.mapping
  mappings/net/minecraft/client/render/model/json/ModelElementTexture.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationFrameResourceMetadata.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationResourceMetadata.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/util/math/Matrix4f.mapping
  mappings/net/minecraft/client/util/math/Vector4f.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloadListener.mapping
Labels: new, ready to merge, refactor, snapshot

#968 Improve game rule mappings
  mappings/net/minecraft/world/GameRules.mapping
Labels: ready to merge, refactor, snapshot

#973 SortedArraySet mappings
  mappings/net/minecraft/util/SortedArraySet.mapping
Labels: new, ready to merge, snapshot

#981 Bee mappings
  mappings/net/minecraft/block/entity/BeeHiveBlockEntity.mapping
  mappings/net/minecraft/entity/ai/TargetFinder.mapping
  mappings/net/minecraft/entity/ai/control/LookControl.mapping
  mappings/net/minecraft/entity/ai/goal/MeleeAttackGoal.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeNavigator.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/world/World.mapping
Labels: new, ready to merge, snapshot

#975 Map some mostly world gen stuff
  mappings/net/minecraft/util/WoodType.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/decorator/TreeDecorator.mapping
  mappings/net/minecraft/world/gen/feature/AbstractTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/BranchedTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/BranchedTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/IcebergFeature.mapping
  mappings/net/minecraft/world/gen/feature/MegaTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/DefaultSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
  mappings/net/minecraft/world/level/LevelGeneratorType.mapping
Labels: new, snapshot

#977 Generate mappings for specialized methods
  build.gradle
Labels: enhancement, toolchain

#982 Model part mappings
  mappings/net/minecraft/client/render/entity/model/ArmorStandEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BeeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ChickenEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CodEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CreeperEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/DolphinEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/DonkeyEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/EvilVillagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/FoxEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/GuardianEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/HorseEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/IllagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/IronGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/LlamaEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/MagmaCubeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/OcelotEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ParrotEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/PhantomEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RabbitEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RavagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SalmonEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SlimeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SnowmanEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SpiderEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SquidEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/VexEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/VillagerResemblingModel.mapping
  mappings/net/minecraft/client/render/entity/model/WolfEntityModel.mapping
Labels: new, ready to merge, refactor, snapshot

#980 Some stuff for 1.15 pre 1 and pre2
  mappings/net/minecraft/block/AbstractSignBlock.mapping
  mappings/net/minecraft/block/DoubleBlockProperties.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/class_4732.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/options/GameOptionsScreen.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
  mappings/net/minecraft/client/render/BufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/SpriteTexturedVertexConsumer.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/VertexConsumer.mapping
  mappings/net/minecraft/client/render/VertexConsumers.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/LightmapCoordinatesRetriever.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/SpriteAtlasManager.mapping
  mappings/net/minecraft/client/resource/Format3ResourcePack.mapping
  mappings/net/minecraft/client/resource/Format4ResourcePack.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationResourceMetadata.mapping
  mappings/net/minecraft/client/texture/MipmapHelper.mapping
  mappings/net/minecraft/client/texture/MissingSprite.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/texture/NativeImageBackedTexture.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasHolder.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/StatusEffectSpriteManager.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/client/texture/TextureStitcher.mapping
  mappings/net/minecraft/client/util/SpriteIdentifier.mapping
  mappings/net/minecraft/client/util/math/Matrix3f.mapping
  mappings/net/minecraft/client/util/math/Matrix4f.mapping
  mappings/net/minecraft/client/util/math/Vector3f.mapping
  mappings/net/minecraft/client/util/math/Vector4f.mapping
  mappings/net/minecraft/datafixer/fixes/RemovePoiValidTagFix.mapping
  mappings/net/minecraft/resource/ResourcePack.mapping
  mappings/net/minecraft/util/SignType.mapping
  mappings/net/minecraft/world/WorldView.mapping
  mappings/net/minecraft/world/dimension/Dimension.mapping
Labels: new, snapshot

#985 Rendering mappings
  README.md
  mappings/net/minecraft/class_4703.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/packet/CustomPayloadS2CPacket.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/chunk/ChunkOcclusionData.mapping
  mappings/net/minecraft/client/render/chunk/ChunkOcclusionDataBuilder.mapping
  mappings/net/minecraft/client/render/debug/BeeDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/NameGenerator.mapping
  mappings/net/minecraft/client/render/debug/VillageDebugRenderer.mapping
  mappings/net/minecraft/client/resource/FoliageColormapResourceSupplier.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/world/BlockRenderView.mapping
  mappings/net/minecraft/world/IWorld.mapping
  mappings/net/minecraft/world/dimension/Dimension.mapping
Labels: new, ready to merge, snapshot

#989 pre3 new classes
  mappings/net/minecraft/block/AbstractChestBlock.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/DoubleBlockProperties.mapping
  mappings/net/minecraft/client/render/FpsSmoother.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
Labels: new, ready to merge, snapshot
