Repository FabricMC/yarn, pull requests merged in 2019-12, with the labels that each got.

#993 Finish DefaultBiomeFeatures mappings and some other stuff
  mappings/net/minecraft/world/biome/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/decorator/BeehiveTreeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/TreeDecorator.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/MegaTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SpringFeatureConfig.mapping
  mappings/net/minecraft/world/gen/stateprovider/PlainsFlowerStateProvider.mapping
Labels: new, snapshot

#972 Quarternion mappings
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/util/math/Vector3f.mapping
  mappings/net/minecraft/util/math/Quaternion.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldView.mapping
Labels: new, snapshot

#994 1.15 pre4 1
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/entity/ExperienceOrbEntityRenderer.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Quaternion.mapping
Labels: new, snapshot

#996 1.15 pre 5 new mappings and other cumulative new mappings
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/HoneyBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/InGameOverlayRenderer.mapping
  mappings/net/minecraft/client/gui/screen/SplashScreen.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
  mappings/net/minecraft/client/texture/ResourceTexture.mapping
  mappings/net/minecraft/container/AnvilContainer.mapping
  mappings/net/minecraft/container/CartographyTableContainer.mapping
  mappings/net/minecraft/container/LoomContainer.mapping
  mappings/net/minecraft/container/PlayerContainer.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityContext.mapping
  mappings/net/minecraft/entity/EntityContextImpl.mapping
  mappings/net/minecraft/entity/ExperienceOrbEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/ReloadableResourceManagerImpl.mapping
  mappings/net/minecraft/resource/ResourceReloadMonitor.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, snapshot

#999 Last minute bee stuff
  mappings/net/minecraft/block/BeeHiveBlock.mapping
  mappings/net/minecraft/block/BeehiveBlock.mapping
  mappings/net/minecraft/block/CampfireBlock.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/client/network/DebugRendererInfoManager.mapping
Labels: new, ready to merge, snapshot

#991 FirstPersonRenderer -> HeldItemRenderer
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/DiffuseLighting.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/PlayerEntityRenderer.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/json/Transformation.mapping
Labels: new, ready to merge, snapshot

#1002 Fix some world gen mappings and map some unmapped stuff
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/layer/BiomeLayers.mapping
  mappings/net/minecraft/world/gen/decorator/ChanceDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/SingleStateFeatureConfig.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/BadlandsSurfaceBuilder.mapping
Labels: new, ready to merge, snapshot

#990 Remove maven plugin (deprecated by gradle)
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, toolchain

#1016 Make packet names consistent
  mappings/net/minecraft/client/network/packet/OpenContainerS2CPacket.mapping
  mappings/net/minecraft/client/network/packet/SetTradeOffersS2CPacket.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
Labels: ready to merge, refactor, snapshot

#1007 Mapped the missing fields in HeldItemRenderer
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
Labels: new, release

#1005 BlockBreakParticle mapping (test)
  mappings/net/minecraft/client/particle/BlockDustParticle.mapping
Labels: refactor, snapshot

#1008 Model transformation mode
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelTransformation.mapping
  mappings/net/minecraft/client/render/model/json/Transformation.mapping
Labels: refactor, release

#1018 Rename Gson fields in some classes to GSON
  mappings/net/minecraft/data/report/BlockListProvider.mapping
  mappings/net/minecraft/data/report/CommandSyntaxProvider.mapping
  mappings/net/minecraft/data/report/ItemListProvider.mapping
Labels: new, ready to merge, release

#1022 Tiny quaternion fixes
  mappings/net/minecraft/client/util/math/Vector4f.mapping
  mappings/net/minecraft/util/math/Quaternion.mapping
Labels: new, refactor, snapshot

#1019 some client names and moved PageTurnWidget
  mappings/net/minecraft/client/gui/screen/AddServerScreen.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmChatLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/gui/screen/DirectConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/FatalErrorScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTab.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractCommandBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractContainerScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AnvilScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BrewingStandScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryListener.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/FurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/GrindstoneScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HopperScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HorseScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LecternScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ShulkerBoxScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmokerScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StonecutterScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/screen/options/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternatesWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookProvider.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeDisplayListener.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeGroupButtonWidget.mapping
  mappings/net/minecraft/client/gui/screen/resourcepack/ResourcePackOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/widget/AbstractButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/LockButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/PageTurnWidget.mapping
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/SoundSliderWidget.mapping
  mappings/net/minecraft/client/network/ClientAdvancementManager.mapping
  mappings/net/minecraft/client/recipe/book/ClientRecipeBook.mapping
  mappings/net/minecraft/container/Slot.mapping
Labels: new, release

#1004 ContainerLock mappings
  mappings/net/minecraft/container/ContainerLock.mapping
  mappings/net/minecraft/inventory/ContainerLock.mapping
Labels: refactor, snapshot

#1003 Document the setBlockState method
  mappings/net/minecraft/world/ModifiableWorld.mapping
Labels: javadoc, new, outdated, snapshot

#1023 Tiny Vector3f fixes
  mappings/net/minecraft/client/util/math/Vector3f.mapping
Labels: refactor, snapshot

#1030 Add missing BlockItem instance names
  mappings/net/minecraft/item/Items.mapping
Labels: new, release

#1031 Correctly label the chunk ticket expiry mechanism
  mappings/net/minecraft/server/world/ChunkTicket.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ChunkTicketType.mapping
Labels: new, snapshot

#1027 Vector3f.reciprocal -> normalize
  mappings/net/minecraft/client/util/math/Vector3f.mapping
Labels: refactor, release

#1020 Better block state flattening mappings
  mappings/net/minecraft/datafixer/fix/BlockStateFlattening.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: new, refactor, snapshot
