Repository FabricMC/yarn, pull requests merged in 2019-10, with the labels that each got.

#890 Screen/GUI fields
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTab.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/controls/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractFurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BrewingStandScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AbstractFurnaceRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/widget/ListWidget.mapping
  mappings/net/minecraft/client/network/MultiplayerServerListPinger.mapping
Labels: new

#900 Iron Golem Model Mappings
  mappings/net/minecraft/class_4595.mapping
  mappings/net/minecraft/client/render/entity/model/IronGolemEntityModel.mapping
Labels: new, ready to merge

#898 Map a filed in TridentEntity
  mappings/net/minecraft/entity/projectile/TridentEntity.mapping
Labels: new, ready to merge

#901 Fix noop mapping in ResourceReloadListener
  mappings/net/minecraft/resource/ResourceReloadListener.mapping
Labels: bug, ready to merge

#897 Rendering mappings
  mappings/net/minecraft/block/BlockRenderLayer.mapping
  mappings/net/minecraft/class_4582.mapping
  mappings/net/minecraft/class_4583.mapping
  mappings/net/minecraft/class_4584.mapping
  mappings/net/minecraft/class_4588.mapping
  mappings/net/minecraft/class_4589.mapping
  mappings/net/minecraft/class_4591.mapping
  mappings/net/minecraft/class_4607.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/WhiteRectangleGlyph.mapping
  mappings/net/minecraft/client/model/Model.mapping
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/render/AbstractVertexConsumer.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/BufferVertexConsumer.mapping
  mappings/net/minecraft/client/render/DelegatingVertexConsumer.mapping
  mappings/net/minecraft/client/render/Frustum.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/LayeredBufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/LayeredVertexConsumerStorage.mapping
  mappings/net/minecraft/client/render/MatrixVertexConsumer.mapping
  mappings/net/minecraft/client/render/OverlayTexture.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/VertexConsumer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BedBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/chunk/BlockLayeredBufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/SkinOverlayFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/SkinOverlayOwner.mapping
  mappings/net/minecraft/client/render/entity/model/PlayerEntityModel.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/client/util/math/Matrix4f.mapping
  mappings/net/minecraft/client/util/math/Vector3f.mapping
  mappings/net/minecraft/client/util/math/Vector4f.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Matrix3f.mapping
  mappings/net/minecraft/util/math/MatrixStack.mapping
  mappings/net/minecraft/util/math/Quaternion.mapping
  mappings/net/minecraft/world/BlockRenderView.mapping
Labels: new, ready to merge

#882 Entity properties
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/WaterCreatureEntity.mapping
  mappings/net/minecraft/entity/mob/WaterCreatureEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
Labels: new, ready to merge

#862 19w36a: The art of nether update
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/FenceBlock.mapping
  mappings/net/minecraft/class_4543.mapping
  mappings/net/minecraft/class_4548.mapping
  mappings/net/minecraft/util/shape/SliceVoxelShape.mapping
  mappings/net/minecraft/util/shape/VoxelShapes.mapping
  mappings/net/minecraft/world/BlockRenderView.mapping
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldView.mapping
  mappings/net/minecraft/world/biome/BiomeAccess.mapping
  mappings/net/minecraft/world/biome/BiomeAccessType.mapping
  mappings/net/minecraft/world/biome/BiomeArray.mapping
  mappings/net/minecraft/world/biome/HorizontalVoronoiBiomeAccessType.mapping
  mappings/net/minecraft/world/biome/SeedMixer.mapping
  mappings/net/minecraft/world/biome/VoronoiBiomeAccessType.mapping
  mappings/net/minecraft/world/biome/layer/CachingLayerContext.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/CheckerboardBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/CheckerboardBiomeSourceConfig.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/VanillaLayeredBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/VanillaLayeredBiomeSourceConfig.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: discussion, new, ready to merge

#879 Remap resource pack profile stuff as I revisit it during api writing
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/resourcepack/ResourcePackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/resourcepack/ResourcePackOptionsScreen.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/ClientResourcePackProfile.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/DefaultResourcePackCreator.mapping
  mappings/net/minecraft/resource/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/ResourcePackCompatibility.mapping
  mappings/net/minecraft/resource/ResourcePackContainerManager.mapping
  mappings/net/minecraft/resource/ResourcePackCreator.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/ResourcePackProvider.mapping
  mappings/net/minecraft/resource/ResourceReloadListener.mapping
  mappings/net/minecraft/resource/ResourceType.mapping
  mappings/net/minecraft/resource/VanillaDataPackProvider.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: discussion, ready to merge, refactor

#820 FishingBobberEntity Mappings
  mappings/net/minecraft/entity/projectile/FishingBobberEntity.mapping
Labels: new, ready to merge

#903 Some new stuff
  mappings/net/minecraft/block/HoneyBlock.mapping
  mappings/net/minecraft/class_4622.mapping
  mappings/net/minecraft/class_4658.mapping
  mappings/net/minecraft/class_4659.mapping
  mappings/net/minecraft/class_4660.mapping
  mappings/net/minecraft/class_4661.mapping
  mappings/net/minecraft/class_4664.mapping
  mappings/net/minecraft/class_4691.mapping
  mappings/net/minecraft/client/render/entity/feature/IronGolemCrackFeatureRenderer.mapping
  mappings/net/minecraft/datafixers/fixes/BeehiveRenameFix.mapping
  mappings/net/minecraft/datafixers/fixes/PointOfInterestRenameFIx.mapping
  mappings/net/minecraft/server/command/SpectateCommand.mapping
  mappings/net/minecraft/world/gen/decorator/AlterGroundTreeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/BeehiveTreeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/CocoaBeansTreeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/LeaveVineTreeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/TreeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/TreeDecoratorType.mapping
  mappings/net/minecraft/world/gen/decorator/TrunkVineTreeDecorator.mapping
Labels: new

#904 A few easy mappings for 41a
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: new, ready to merge, snapshot

#911 Fix MobSpawnS2CPacket velocity and rotation being swapped
  mappings/net/minecraft/client/network/packet/MobSpawnS2CPacket.mapping
Labels: bug, ready to merge, refactor, snapshot

#912 Fix dust particle effect scale misnamed as alpha
  mappings/net/minecraft/particle/DustParticleEffect.mapping
Labels: bug, ready to merge, refactor, snapshot

#913 Mapped entity rendering methods/classes & options screens
  mappings/net/minecraft/class_4592.mapping
  mappings/net/minecraft/class_4593.mapping
  mappings/net/minecraft/class_4594.mapping
  mappings/net/minecraft/class_4595.mapping
  mappings/net/minecraft/class_4606.mapping
  mappings/net/minecraft/client/gui/hud/InGameOverlayRenderer.mapping
  mappings/net/minecraft/client/gui/screen/options/AccessibilityScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/ChatOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/screen/options/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/LanguageOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/SoundOptionsScreen.mapping
  mappings/net/minecraft/client/model/Model.mapping
  mappings/net/minecraft/client/render/entity/EnderCrystalEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EnderDragonEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/PlayerEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/PufferfishEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorBipedFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/EntityEyesFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/FeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/HeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/SkinOverlayFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/AnimalModel.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BlazeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BoatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BookModel.mapping
  mappings/net/minecraft/client/render/entity/model/CompositeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ParrotEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ShulkerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TintableAnimalModel.mapping
  mappings/net/minecraft/client/render/entity/model/TintableCompositeModel.mapping
  mappings/net/minecraft/client/render/entity/model/WitchEntityModel.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
Labels: new, snapshot

#923 I know what you need
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
Labels: bug, ready to merge, refactor, snapshot

#925 Restore Source/DestFactor names
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
Labels: new, ready to merge, snapshot

#907 Map and remap things in advancement/criterion and predicate
  mappings/net/minecraft/advancement/criterion/BredAnimalsCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BrewedPotionCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ChangedDimensionCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ChanneledLightningCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConstructBeaconCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConsumeItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/CuredZombieVillagerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EffectsChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnchantedItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnterBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EntityHurtPlayerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FilledBucketCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FishingRodHookedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/InventoryChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemDurabilityChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/KilledByCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LevitationCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LocationArrivalCriterion.mapping
  mappings/net/minecraft/advancement/criterion/NetherTravelCriterion.mapping
  mappings/net/minecraft/advancement/criterion/OnKilledCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlacedBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerHurtEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/RecipeUnlockedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ShotCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SummonedEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TameAnimalCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TickCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedEnderEyeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedTotemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/predicate/PlayerPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/item/EnchantmentPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, ready to merge, snapshot

#924 lots of world gen mappings
  mappings/net/minecraft/class_4634.mapping
  mappings/net/minecraft/class_4635.mapping
  mappings/net/minecraft/class_4636.mapping
  mappings/net/minecraft/class_4638.mapping
  mappings/net/minecraft/class_4640.mapping
  mappings/net/minecraft/class_4642.mapping
  mappings/net/minecraft/class_4643.mapping
  mappings/net/minecraft/class_4653.mapping
  mappings/net/minecraft/class_4654.mapping
  mappings/net/minecraft/class_4655.mapping
  mappings/net/minecraft/class_4656.mapping
  mappings/net/minecraft/class_4657.mapping
  mappings/net/minecraft/util/WeightedList.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/decorator/Decorator.mapping
  mappings/net/minecraft/world/gen/feature/AbstractTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/BlockPileFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeature.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/FlowerFeature.mapping
  mappings/net/minecraft/world/gen/feature/FlowerFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/MegaTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/NormalTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SpringFeatureConfig.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/ForestFlowerStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/PlainFlowerStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/SimpleStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/StateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/StateProviderType.mapping
  mappings/net/minecraft/world/gen/stateprovider/WeightedStateProvider.mapping
Labels: new, ready to merge, snapshot

#888 Some entity mappings
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/packet/GameJoinS2CPacket.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/packet/ClientSettingsC2SPacket.mapping
Labels: new, ready to merge, snapshot

#906 StatusEffect mapping and Cuboid Method rename
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
Labels: new, ready to merge, refactor, snapshot

#933 Bring back BER.render()
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderer.mapping
Labels: new, ready to merge, snapshot
