Repository FabricMC/yarn, pull requests merged in 2020-12, with the labels that each got.

#1899 Game mode stuff
  mappings/net/minecraft/client/tutorial/TutorialManager.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
  mappings/net/minecraft/world/GameMode.mapping
Labels: javadoc, new, refactor

#1898 ResourceManager documentation
  mappings/net/minecraft/resource/ResourceManager.mapping
Labels: javadoc

#1901 Add some brain mappings
  mappings/net/minecraft/entity/ai/brain/EntityLookTarget.mapping
  mappings/net/minecraft/entity/ai/brain/Memory.mapping
Labels: new, outdated, snapshot

#1894 48a things
  mappings/net/minecraft/block/AbstractCauldronBlock.mapping
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/LeveledCauldronBlock.mapping
  mappings/net/minecraft/block/OperatorBlock.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/ShapeContext.mapping
  mappings/net/minecraft/class_5423.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsWorldGeneratorType.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/HeadFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/PlayerHeldItemFeatureRenderer.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemPlacementContext.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/math/Direction.mapping
Labels: new, ready to merge, snapshot

#1904 Dripstone mappings
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/world/gen/UniformFloatDistribution.mapping
  mappings/net/minecraft/world/gen/UniformIntDistribution.mapping
  mappings/net/minecraft/world/gen/feature/DripstoneClusterFeature.mapping
  mappings/net/minecraft/world/gen/feature/DripstoneClusterFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/LargeDripstoneFeature.mapping
  mappings/net/minecraft/world/gen/feature/LargeDripstoneFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SmallDripstoneFeature.mapping
  mappings/net/minecraft/world/gen/feature/SmallDripstoneFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/util/DripstoneColumn.mapping
  mappings/net/minecraft/world/gen/feature/util/DripstoneHelper.mapping
Labels: new, snapshot

#1907 Add some villager mappings
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/VillagerData.mapping
  mappings/net/minecraft/village/VillagerType.mapping
  mappings/net/minecraft/village/ZombieSiegeManager.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
Labels: new, ready to merge

#1910 Mapped parts of ScreenHandler
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/util/collection/DefaultedList.mapping
Labels: new, ready to merge, refactor

#1911 20w49a cleanup
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/FireBlock.mapping
  mappings/net/minecraft/block/PistonHeadBlock.mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
  mappings/net/minecraft/block/TurtleEggBlock.mapping
  mappings/net/minecraft/block/VineBlock.mapping
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/item/ItemUsage.mapping
  mappings/net/minecraft/particle/DustColorTransitionParticleEffect.mapping
  mappings/net/minecraft/particle/DustParticleEffect.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/Vibration.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/event/BlockPositionSource.mapping
  mappings/net/minecraft/world/event/EntityPositionSource.mapping
  mappings/net/minecraft/world/event/PositionSource.mapping
  mappings/net/minecraft/world/event/PositionSourceType.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/event/listener/SculkSensorListener.mapping
Labels: ready to merge, refactor

#1912 TreeFeature.isDirtOrGrass -> canPlaceTreeOn
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
Labels: ready to merge, refactor

#1913 ItemStack.areStacksEqual -> canCombine
  mappings/net/minecraft/item/ItemStack.mapping
Labels: bug, ready to merge, refactor

#1916 Some client javadoc
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
Labels: javadoc, new, ready to merge

#1272 Effectiveness 2
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: bug, refactor, snapshot

#1709 Mapped most of the Entity Model classes
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/render/entity/model/AbstractZombieModel.mapping
  mappings/net/minecraft/client/render/entity/model/ArmorStandEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BannerBlockEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BlazeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BoatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ChickenEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CodEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CowEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CreeperEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/DolphinEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/DonkeyEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/FoxEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/GhastEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/GuardianEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/HorseEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/IllagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/IronGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/LeashEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/LeashKnotEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/LlamaSpitEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/MagmaCubeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/MinecartEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ParrotEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/PhantomEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RabbitEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RavagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SalmonEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SheepEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ShieldEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ShulkerBulletEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ShulkerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SignBlockEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SilverfishEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SkullOverlayEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SlimeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SnowGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SnowmanEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SpiderEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SquidEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TridentEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TropicalFishEntityModelA.mapping
  mappings/net/minecraft/client/render/entity/model/TropicalFishEntityModelB.mapping
  mappings/net/minecraft/client/render/entity/model/TurtleEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/VexEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/WitchEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/WitherEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/WolfEntityModel.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
Labels: new, ready to merge

#1504 Lots of new mappings
  mappings/net/minecraft/client/render/entity/feature/HeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ShoulderParrotFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/StuckArrowsFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/TridentRiptideFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/VillagerClothingFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/VillagerResourceMetadata.mapping
  mappings/net/minecraft/container/AbstractFurnaceContainer.mapping
  mappings/net/minecraft/container/AnvilContainer.mapping
  mappings/net/minecraft/container/BeaconContainer.mapping
  mappings/net/minecraft/container/BlastFurnaceContainer.mapping
  mappings/net/minecraft/container/BlockContext.mapping
  mappings/net/minecraft/container/BrewingStandContainer.mapping
  mappings/net/minecraft/container/CartographyTableContainer.mapping
  mappings/net/minecraft/container/Container.mapping
  mappings/net/minecraft/container/ContainerListener.mapping
  mappings/net/minecraft/container/CraftingContainer.mapping
  mappings/net/minecraft/container/CraftingTableContainer.mapping
  mappings/net/minecraft/container/EnchantingTableContainer.mapping
  mappings/net/minecraft/container/FurnaceContainer.mapping
  mappings/net/minecraft/container/FurnaceFuelSlot.mapping
  mappings/net/minecraft/container/Generic3x3Container.mapping
  mappings/net/minecraft/container/GenericContainer.mapping
  mappings/net/minecraft/container/GrindstoneContainer.mapping
  mappings/net/minecraft/container/HopperContainer.mapping
  mappings/net/minecraft/container/HorseContainer.mapping
  mappings/net/minecraft/container/LecternContainer.mapping
  mappings/net/minecraft/container/LoomContainer.mapping
  mappings/net/minecraft/container/MerchantContainer.mapping
  mappings/net/minecraft/container/PlayerContainer.mapping
  mappings/net/minecraft/container/ShulkerBoxContainer.mapping
  mappings/net/minecraft/container/SimpleNamedContainerFactory.mapping
  mappings/net/minecraft/container/Slot.mapping
  mappings/net/minecraft/container/SmokerContainer.mapping
  mappings/net/minecraft/container/StonecutterContainer.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonSpawnState.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/Phase.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: new, outdated, release

#1920 Fix some boolean getter methods being prefixed with 'get'
  mappings/net/minecraft/client/realms/dto/PlayerInfo.mapping
  mappings/net/minecraft/entity/boss/BossBar.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/decoration/EndCrystalEntity.mapping
  mappings/net/minecraft/entity/mob/CreeperEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateStructureBlockC2SPacket.mapping
Labels: bug, refactor, snapshot

#1474 Fix Material.SUPPORTED -> Material.DECORATION
  mappings/net/minecraft/block/Material.mapping
Labels: outdated, refactor

#1929 Add a settings.gradle to ensure consistency
  settings.gradle
Labels: toolchain

#1927 Update ModelBakeSettings
  mappings/net/minecraft/client/render/model/ModelBakeSettings.mapping
Labels: ready to merge, refactor, snapshot

#1933 Rename the FullScreenOption class to FullscreenOption
  mappings/net/minecraft/client/option/FullScreenOption.mapping
  mappings/net/minecraft/client/option/FullscreenOption.mapping
Labels: ready to merge, refactor, snapshot

#1928 Map some of the unmapped parts of functions
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
Labels: javadoc, new, ready to merge, snapshot

#1932 Rename FenceBlock.isFence
  mappings/net/minecraft/block/FenceBlock.mapping
Labels: ready to merge, refactor, snapshot

#1939 Complete RecipesProvider mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
Labels: new, ready to merge, snapshot

#1937 Fix javadocs and update Enigma
  gradle.properties
  mappings/net/minecraft/client/render/entity/model/WolfEntityModel.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/particle/ParticleType.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
Labels: javadoc, ready to merge, snapshot, toolchain

#1936 Complete StairsBlock mapping
  mappings/net/minecraft/block/StairsBlock.mapping
Labels: new, ready to merge

#1926 GL things
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/gl/GlDebug.mapping
  mappings/net/minecraft/client/gl/GlUniform.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
Labels: new, ready to merge, refactor, snapshot

#1944 Beacon beam rendering and other be renderers
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BeaconBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BedBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BellBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/CampfireBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/ChestBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/ConduitBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/EnchantingTableBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/EndPortalBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/LecternBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/MobSpawnerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/PistonBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/ShulkerBoxBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/StructureBlockBlockEntityRenderer.mapping
  mappings/net/minecraft/util/DyeColor.mapping
Labels: javadoc, new, refactor, snapshot
