Repository FabricMC/yarn, pull requests merged in 2020-02, with the labels that each got.

#1079 1.15.2 EntityRenderer changes
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
Labels: new, ready to merge

#1083 A couple of block class renamings
  mappings/net/minecraft/block/BeehiveBlock.mapping
  mappings/net/minecraft/block/ConnectingBlock.mapping
  mappings/net/minecraft/block/Stainable.mapping
  mappings/net/minecraft/client/block/ColoredBlock.mapping
Labels: new, ready to merge, refactor

#1085 20w06a profiler mappings
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/TickDurationMonitor.mapping
  mappings/net/minecraft/util/TickTimeTracker.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
  mappings/net/minecraft/util/profiler/ProfilerSystem.mapping
Labels: new, ready to merge, snapshot

#1089 Locatebiome stuff
  mappings/net/minecraft/block/HorizontalConnectingBlock.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: new, ready to merge, snapshot

#1091 A few 1.16 mappings
  mappings/net/minecraft/block/AbstractFireBlock.mapping
  mappings/net/minecraft/block/FungiBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/NetherrackBlock.mapping
  mappings/net/minecraft/block/RootsBlock.mapping
  mappings/net/minecraft/block/SoulFireBlock.mapping
  mappings/net/minecraft/block/SproutsBlock.mapping
  mappings/net/minecraft/block/WallBlock.mapping
  mappings/net/minecraft/block/WeepingVinesBlock.mapping
  mappings/net/minecraft/block/WeepingVinesPlantBlock.mapping
  mappings/net/minecraft/block/enums/WallShape.mapping
  mappings/net/minecraft/class_4770.mapping
  mappings/net/minecraft/client/render/entity/HoglinEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/HoglinEntityModel.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/mob/HoglinEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerLidCollisions.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/util/SignType.mapping
  mappings/net/minecraft/world/biome/CrimsonForestBiome.mapping
  mappings/net/minecraft/world/biome/SoulSandValleyBiome.mapping
  mappings/net/minecraft/world/biome/WarpedForestBiome.mapping
Labels: new, ready to merge, snapshot

#1087 Biome internal mappings (not new biome types)
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/biome/BiomeParticleConfig.mapping
  mappings/net/minecraft/world/dimension/Dimension.mapping
Labels: new, ready to merge, snapshot

#1092 dfu and particles
  mappings/net/minecraft/client/particle/AscendingParticle.mapping
  mappings/net/minecraft/client/particle/AshParticle.mapping
  mappings/net/minecraft/client/particle/LargeFireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/WaterSuspendParticle.mapping
  mappings/net/minecraft/datafixer/StructureReferenceFixer.mapping
  mappings/net/minecraft/datafixer/fix/BiomeRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/FurnaceRecipesFix.mapping
  mappings/net/minecraft/datafixer/fix/StructureReferenceFix.mapping
  mappings/net/minecraft/datafixer/fix/WallPropertyFix.mapping
  mappings/net/minecraft/datafixer/schema/IdentifierNormalizingSchema.mapping
  mappings/net/minecraft/datafixer/schema/Schema100.mapping
  mappings/net/minecraft/datafixer/schema/Schema2501.mapping
  mappings/net/minecraft/datafixer/schema/Schema2502.mapping
  mappings/net/minecraft/datafixer/schema/SchemaIdentifierNormalize.mapping
Labels: new, ready to merge, refactor, snapshot

#1097 Add Feature mappings
  mappings/net/minecraft/structure/NetherFossilGenerator.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/world/gen/feature/BasaltPillarFeature.mapping
  mappings/net/minecraft/world/gen/feature/BlockPileFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungiFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungiFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/NetherForestVegetationFeature.mapping
  mappings/net/minecraft/world/gen/feature/NetherFossilFeature.mapping
  mappings/net/minecraft/world/gen/feature/NoSurfaceOreFeature.mapping
  mappings/net/minecraft/world/gen/feature/WeepingVinesFeature.mapping
Labels: new, ready to merge, snapshot

#1095 Add fluid mappings and fix some inconsistencies and typo.
  mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
  mappings/net/minecraft/fluid/BaseFluid.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/fluid/LavaFluid.mapping
Labels: new, ready to merge, refactor, snapshot

#1101 Fix missing mappings.
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/profiler/ProfileLocationInfo.mapping
  mappings/net/minecraft/world/World.mapping
Labels: bug, snapshot

#1104 Change EntityContext params from ePos to context
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BlockState.mapping
Labels: ready to merge, refactor, snapshot

#1096 Networking stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/ClientAdvancementManager.mapping
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/network/DataQueryHandler.mapping
  mappings/net/minecraft/client/network/LanServerInfo.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/entity/player/ItemCooldownManager.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/DecoderHandler.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/NetworkThreadUtils.mapping
  mappings/net/minecraft/network/Packet.mapping
  mappings/net/minecraft/network/PacketEncoder.mapping
  mappings/net/minecraft/network/PacketEncoderException.mapping
  mappings/net/minecraft/network/PacketInflater.mapping
  mappings/net/minecraft/network/listener/ClientLoginPacketListener.mapping
  mappings/net/minecraft/network/listener/ClientQueryPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerHandshakePacketListener.mapping
  mappings/net/minecraft/network/listener/ServerLoginPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerQueryPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/handshake/HandshakeC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/login/LoginHelloC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/login/LoginKeyC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/login/LoginQueryResponseC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/query/QueryPingC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SetTradeOffersS2CPacket.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/network/DebugInfoSender.mapping
  mappings/net/minecraft/server/network/DemoServerPlayerInteractionManager.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/server/network/IntegratedServerHandshakeNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerHandshakeNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerItemCooldownManager.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
  mappings/net/minecraft/server/network/ServerQueryNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerRecipeBook.mapping
Labels: new, refactor, snapshot

#1105 Random worldgen things
  mappings/net/minecraft/structure/rule/AbstractRuleTest.mapping
  mappings/net/minecraft/structure/rule/RuleTest.mapping
  mappings/net/minecraft/structure/rule/RuleTestType.mapping
  mappings/net/minecraft/world/gen/decorator/TreeDecorator.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProviderType.mapping
  mappings/net/minecraft/world/gen/stateprovider/ForestFlowerBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/PillarBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/PlainsFlowerBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/SimpleBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/StateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/WeightedBlockStateProvider.mapping
Labels: new, ready to merge, refactor, snapshot

#1100 Motive -> Painting Motive
  mappings/net/minecraft/client/texture/PaintingManager.mapping
  mappings/net/minecraft/datafixer/fix/EntityPaintingMotiveFix.mapping
  mappings/net/minecraft/entity/decoration/AbstractDecorationEntity.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingEntity.mapping
  mappings/net/minecraft/network/packet/s2c/play/PaintingSpawnS2CPacket.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: ready to merge, refactor, snapshot

#1086 ActionResult docs
  mappings/net/minecraft/util/ActionResult.mapping
Labels: javadoc, ready to merge, snapshot

#1110 Fix missing mapping RuleTest in 1.15.2
  mappings/net/minecraft/structure/rule/RuleTest.mapping
Labels: bug, new, release

#1117 BlockBox names and overloads in BlockPos
  mappings/net/minecraft/util/math/BlockBox.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
Labels: new, ready to merge, snapshot

#1109 Random fixes
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/loot/LootManager.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameMessageS2CPacket.mapping
  mappings/net/minecraft/world/ModifiableWorld.mapping
  mappings/net/minecraft/world/gen/feature/AbstractTreeFeature.mapping
Labels: bug, ready to merge, refactor, snapshot

#1114 Rename every view argument to world and random additions.
  mappings/net/minecraft/block/AbstractButtonBlock.mapping
  mappings/net/minecraft/block/AbstractFireBlock.mapping
  mappings/net/minecraft/block/AbstractRedstoneGateBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BlockEntityProvider.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/ChorusPlantBlock.mapping
  mappings/net/minecraft/block/ConcretePowderBlock.mapping
  mappings/net/minecraft/block/FluidFillable.mapping
  mappings/net/minecraft/block/PlantBlock.mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/block/StairsBlock.mapping
  mappings/net/minecraft/client/color/block/BlockColorProvider.mapping
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/color/world/BiomeColors.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/FeatureRendererContext.mapping
  mappings/net/minecraft/entity/ai/goal/StepAndDestroyBlockGoal.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/item/ArmorItem.mapping
  mappings/net/minecraft/item/ArmorMaterial.mapping
  mappings/net/minecraft/item/ArmorMaterials.mapping
Labels: new, refactor, snapshot

#1113 Standardize EntityData naming
  mappings/net/minecraft/entity/mob/SpiderEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/PassiveEntity.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/entity/passive/SchoolingFishEntity.mapping
  mappings/net/minecraft/entity/passive/TropicalFishEntity.mapping
Labels: outdated, refactor, snapshot

#1125 Map RailPlacementHelper
  mappings/net/minecraft/block/RailPlacementHelper.mapping
Labels: new, ready to merge, snapshot

#1132 Fix derp in BlockPos.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
Labels: bug, ready to merge, snapshot

#1131 map MineshaftGenerator methods
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
Labels: new, ready to merge, snapshot

#1130 small things
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: new, ready to merge, snapshot

#1127 Map LeavesFix
  mappings/net/minecraft/datafixer/fix/LeavesFix.mapping
Labels: new, ready to merge, snapshot

#1134 minusDiv -> getLerpProgress + other improvements
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: bug, ready to merge, refactor, snapshot

#1137 Map 20w09a blocks and items
  mappings/net/minecraft/advancement/criterion/Criterions.mapping
  mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
  mappings/net/minecraft/block/CryingObsidianBlock.mapping
  mappings/net/minecraft/block/NyliumBlock.mapping
  mappings/net/minecraft/block/TargetBlock.mapping
  mappings/net/minecraft/datafixer/fix/EntityZombifiedPiglinRenameFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema2509.mapping
  mappings/net/minecraft/item/Items.mapping
Labels: new, ready to merge, snapshot

#1136 Rename fungi to fungus
  mappings/net/minecraft/block/FungusBlock.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/HoglinSpecificSensor.mapping
  mappings/net/minecraft/entity/mob/HoglinBrain.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeatureConfig.mapping
Labels: ready to merge, refactor, snapshot

#1135 Eliminate all unmapped classes from yarn
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/StructurePlacementData.mapping
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
Labels: new, ready to merge, snapshot

#1139 A couple of additions to PointOfInterestStorage
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
Labels: new, ready to merge, snapshot
