Repository FabricMC/yarn, pull requests merged in 2020-08, with the labels that each got.

#1635 Text-related refactors & new text things
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/resource/language/ReorderingUtil.mapping
  mappings/net/minecraft/client/resource/language/TextReorderingProcessor.mapping
  mappings/net/minecraft/text/BaseText.mapping
  mappings/net/minecraft/text/OrderedText.mapping
  mappings/net/minecraft/text/StringVisitable.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/util/Language.mapping
Labels: new, ready to merge, refactor, snapshot

#1638 Map some lunar cycle related logic.
  mappings/net/minecraft/world/LunarWorldView.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: javadoc, new, ready to merge, snapshot

#1640 CanPickup/canPickUp -> Equipable/canEquip
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicates.mapping
Labels: ready to merge, refactor, snapshot

#1576 Corrected EyeOfEnderEntity mappings & comment
  mappings/net/minecraft/entity/EyeOfEnderEntity.mapping
Labels: javadoc, outdated, ready to merge, refactor, snapshot

#1643 Horse armor slot fix
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
Labels: bug, ready to merge, refactor, snapshot

#1651 Move nbt ops to nbt package
  mappings/net/minecraft/datafixer/NbtOps.mapping
  mappings/net/minecraft/nbt/NbtOps.mapping
Labels: bug, ready to merge, refactor, snapshot

#1648 Chest Rendering Internals
  mappings/net/minecraft/client/render/block/entity/ChestBlockEntityRenderer.mapping
Labels: new, ready to merge, snapshot

#1620 Assorted mappings and a bunch of param names
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/ArmorMaterials.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: new, ready to merge, snapshot

#1658 CreeperEntity.setIgnited -> ignite
  mappings/net/minecraft/entity/mob/CreeperEntity.mapping
Labels: ready to merge, refactor, snapshot

#1655 Make mappings for option enums consistent
  mappings/net/minecraft/client/options/AoMode.mapping
  mappings/net/minecraft/client/options/AoOption.mapping
  mappings/net/minecraft/client/options/ChatVisibility.mapping
  mappings/net/minecraft/client/options/CloudRenderMode.mapping
  mappings/net/minecraft/client/options/NarratorMode.mapping
  mappings/net/minecraft/client/options/ParticlesMode.mapping
Labels: ready to merge, refactor, snapshot

#1628 ChunkGeneratorType -> ChunkGeneratorSettings
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorType.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
Labels: new, ready to merge, refactor, snapshot

#1661 Made builtin registries match existing names
  mappings/net/minecraft/structure/pool/StructurePools.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorList.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorLists.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/SpawnSettings.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
Labels: new, outdated, ready to merge, refactor, snapshot

#1664 Worldgen stuff
  mappings/net/minecraft/client/render/SkyProperties.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeParticleConfig.mapping
  mappings/net/minecraft/world/biome/SpawnSettings.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/CheckerboardBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/FixedBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/VanillaLayeredBiomeSource.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/DebugChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGenerator.mapping
Labels: new, ready to merge, refactor, snapshot

#1663 Random client things
  mappings/net/minecraft/client/Keyboard.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/gui/WorldGenerationProgressTracker.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
Labels: bug, ready to merge, refactor, snapshot

#1660 Biome things
  mappings/net/minecraft/util/registry/RegistryLookupCodec.mapping
  mappings/net/minecraft/world/biome/Biomes.mapping
  mappings/net/minecraft/world/biome/BuiltInBiomes.mapping
Labels: new, ready to merge, refactor, snapshot

#1669 Some block javadoc
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
Labels: javadoc, ready to merge, snapshot

#1665 [1.16.2-rc1] class_5434 ->JigsawFeature
  mappings/net/minecraft/world/gen/feature/JigsawFeature.mapping
Labels: new, snapshot

#1672 Worldgen again
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/DecoratedFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/JigsawFeature.mapping
  mappings/net/minecraft/world/gen/feature/RandomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/StrongholdFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: javadoc, new, ready to merge, refactor, snapshot

#1667 Document FoodComponent and it's builder
  mappings/net/minecraft/item/FoodComponent.mapping
  mappings/net/minecraft/item/FoodComponents.mapping
Labels: javadoc, ready to merge, snapshot

#1617 Some nullable client field docs, and other misc docs
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/world/World.mapping
Labels: javadoc, ready to merge, snapshot

#1657 Remove mapYarnJar task
  build.gradle
Labels: toolchain

#1676 Fix wrong method name in ItemGroup.
  mappings/net/minecraft/item/ItemGroup.mapping
Labels: bug, javadoc

#1683 Fix all spelling errors in yarn* since 1.16
  mappings/net/minecraft/item/FoodComponent.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
Labels: bug, ready to merge, refactor

#1681 Biome class renames
  mappings/net/minecraft/world/biome/BiomeKeys.mapping
  mappings/net/minecraft/world/biome/Biomes.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
Labels: ready to merge, refactor

#1680 A couple of tag mappings
  mappings/net/minecraft/tag/BlockTags.mapping
  mappings/net/minecraft/tag/EntityTypeTags.mapping
  mappings/net/minecraft/tag/FluidTags.mapping
  mappings/net/minecraft/tag/ItemTags.mapping
Labels: new, ready to merge, refactor

#1684 Add Some Entity Equipment Update Packet Mappings
  mappings/net/minecraft/network/packet/s2c/play/EntityEquipmentUpdateS2CPacket.mapping
Labels: new, ready to merge, release

#1682 Some registry stuff
  mappings/net/minecraft/util/collection/IndexedIterable.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryKey.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
Labels: new, ready to merge, refactor

#1650 Minor nbt stuff
  mappings/net/minecraft/nbt/AbstractListTag.mapping
  mappings/net/minecraft/nbt/CompoundTag.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
Labels: new, ready to merge, snapshot

#1692 Fix For #1675
  mappings/net/minecraft/entity/projectile/FishingBobberEntity.mapping
Labels: bug, ready to merge, refactor

#1687 Map missing Framebuffer methods
  mappings/net/minecraft/client/gl/Framebuffer.mapping
Labels: new, ready to merge

#1689 Minor POI fixups
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/poi/PointOfInterest.mapping
  mappings/net/minecraft/world/poi/PointOfInterestSet.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/poi/PointOfInterestType.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
Labels: new, ready to merge

#1690 BookScreen member rename
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
Labels: new, ready to merge

#1679 1 outer class, 3 inner classes & some moves
  mappings/net/minecraft/client/realms/gui/screen/DisconnectedRealmsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/util/OrderableTooltip.mapping
  mappings/net/minecraft/entity/ai/goal/MoveToTargetPosGoal.mapping
  mappings/net/minecraft/entity/passive/StriderEntity.mapping
  mappings/net/minecraft/text/CharacterVisitor.mapping
  mappings/net/minecraft/world/biome/layer/BiomeLayers.mapping
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
Labels: bug, new, ready to merge, refactor

#1694 Foliage placer classes
  mappings/net/minecraft/world/gen/feature/JungleFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/feature/MegaPineFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/BlobFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/JungleFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/MegaPineFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/PineFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/SpruceFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/tree/TreeDecoratorType.mapping
Labels: new, refactor

#1695 Block placer & state provider classes
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/util/collection/WeightedList.mapping
  mappings/net/minecraft/world/gen/placer/BlockPlacer.mapping
  mappings/net/minecraft/world/gen/placer/BlockPlacerType.mapping
  mappings/net/minecraft/world/gen/placer/ColumnPlacer.mapping
  mappings/net/minecraft/world/gen/placer/DoublePlantPlacer.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProviderType.mapping
  mappings/net/minecraft/world/gen/stateprovider/SimpleBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/WeightedBlockStateProvider.mapping
Labels: new

#1693 Update GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
Labels: new, ready to merge, refactor

#1697 Map tracked position stuff in Entity
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityS2CPacket.mapping
Labels: new, ready to merge

#1711 Update Enigma
  gradle.properties
Labels: ready to merge, toolchain

#1715 Add a mapping for BlockPos.field_25064
  mappings/net/minecraft/util/math/BlockPos.mapping
Labels: new, ready to merge, release

#1704 Add mappings for inventory-related
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
Labels: new, ready to merge

#1700 rayTrace -> raycast
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/world/BlockView.mapping
  mappings/net/minecraft/world/RaycastContext.mapping
Labels: ready to merge, refactor

#1706 Add a mapping for method_30843 in SignBlockEntity
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
Labels: new, ready to merge, release

#1723 Clean up javadoc on Identifier(String) constructor
  mappings/net/minecraft/util/Identifier.mapping
Labels: javadoc, ready to merge

#1722 Add debugWorld mappings
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/World.mapping
Labels: new, ready to merge

#1719 Add Mapping For Valid Frame Block Predicate In AreaHelper
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
Labels: new, ready to merge

#1717 Particle and sound classes
  mappings/net/minecraft/particle/DefaultParticleType.mapping
  mappings/net/minecraft/particle/ParticleType.mapping
  mappings/net/minecraft/particle/ParticleTypes.mapping
  mappings/net/minecraft/sound/BiomeAdditionsSound.mapping
  mappings/net/minecraft/sound/BiomeMoodSound.mapping
  mappings/net/minecraft/sound/MusicSound.mapping
  mappings/net/minecraft/sound/SoundCategory.mapping
  mappings/net/minecraft/sound/SoundEvent.mapping
Labels: new, ready to merge, refactor

#1712 Add mappings for ChunkTicketType fields
  mappings/net/minecraft/server/world/ChunkTicketType.mapping
Labels: new, ready to merge, release, toolchain

#1734 Add getSkyAngle mapping
  mappings/net/minecraft/world/LunarWorldView.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: new, ready to merge

#1733 Add attributeModifiers mapping
  mappings/net/minecraft/item/SwordItem.mapping
  mappings/net/minecraft/item/TridentItem.mapping
Labels: new, ready to merge

#1732 Add mappings for SignEditScreen
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
Labels: new, ready to merge

#1731 Add mappings for Entity
  mappings/net/minecraft/entity/Entity.mapping
Labels: new, ready to merge

#1730 Add mappings for ScreenTexts
  mappings/net/minecraft/client/gui/screen/ScreenTexts.mapping
Labels: new, ready to merge

#1729 BooleanOption.set(Lnet/minecraft/class_315;)V -> toggle
  mappings/net/minecraft/client/options/BooleanOption.mapping
Labels: bug, ready to merge, refactor

#1728 Random worldgen
  mappings/net/minecraft/entity/SpawnGroup.mapping
  mappings/net/minecraft/entity/ai/brain/Memory.mapping
  mappings/net/minecraft/entity/ai/brain/MemoryModuleType.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/gen/CatSpawner.mapping
  mappings/net/minecraft/world/gen/GenerationStep.mapping
  mappings/net/minecraft/world/gen/carver/ConfiguredCarver.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/decorator/DepthAverageDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/MineshaftFeature.mapping
  mappings/net/minecraft/world/gen/feature/OceanRuinFeature.mapping
  mappings/net/minecraft/world/gen/feature/OreFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RuinedPortalFeature.mapping
  mappings/net/minecraft/world/gen/feature/size/FeatureSize.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/ConfiguredSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: new, ready to merge, refactor

#1721 Add mappings for ChatHud
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
Labels: new, ready to merge

#1720 Add a mapping for MinecraftClient.method_29041
  mappings/net/minecraft/client/MinecraftClient.mapping
Labels: new, ready to merge

#1714 Update BlockBox.mapping
  mappings/net/minecraft/util/math/BlockBox.mapping
Labels: new, ready to merge, refactor, release

#1671 Assorted mappings, mainly enchanting, some rendering params and generator type.
  mappings/net/minecraft/client/render/item/BuiltinModelItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: javadoc, new, ready to merge, refactor
