Repository FabricMC/yarn, pull requests merged in 2020-01, with the labels that each got.

#1021 Names for some fields and methods in net.minecraft.data.server
  mappings/net/minecraft/advancement/criterion/InventoryChangedCriterion.mapping
  mappings/net/minecraft/data/SnbtProvider.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
  mappings/net/minecraft/data/report/ItemListProvider.mapping
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/data/server/AdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/FishingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/HusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/LootTablesProvider.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/entity/EntityType.mapping
Labels: new, release

#1032 Some potion-related names
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/potion/Potion.mapping
Labels: new, ready to merge, refactor, release

#1038 Fix 2 name conflicts.
  mappings/net/minecraft/enchantment/ProtectionEnchantment.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
Labels: bug

#1041 Status effect inventory rendering mappings
  mappings/net/minecraft/client/gui/screen/ingame/AbstractInventoryScreen.mapping
Labels: new, refactor, release

#1040 Fixed #838, #860 and unnamed deserializers
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/world/gen/feature/BlockPileFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/BranchedTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/MegaTreeFeatureConfig.mapping
Labels: new, refactor, release

#1043 Remaining StatusEffect methods
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
Labels: new, ready to merge, snapshot

#1034 Entity tracking mappings
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
Labels: new, ready to merge, release

#1039 A couple living entity mappings
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: new, release

#1050 LivingEntity#removeStatusEffect clarification
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: refactor, snapshot

#1044 Map GameMenuScreen field and parameter to showMenu
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
Labels: new, ready to merge, snapshot

#1054 Improved Window names
  mappings/net/minecraft/client/util/Window.mapping
Labels: new, refactor, release

#1049 Make it obvious that method_10769 is for connecting to integrated servers
  mappings/net/minecraft/network/ClientConnection.mapping
Labels: ready to merge, refactor, snapshot

#1048 Use auto-generated names for registries
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: refactor, release

#1052 Mapped PistonHandler
  mappings/net/minecraft/block/piston/PistonHandler.mapping
Labels: new, snapshot

#1056 Map method_22120 to hasMovementInput
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
Labels: new, snapshot

#1059 Fix up Identifier
  mappings/net/minecraft/util/Identifier.mapping
Labels: javadoc, ready to merge, release

#1051 (Block) entity position fixes (#964, #998, #1046, #1061)
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
Labels: ready to merge, refactor, snapshot

#1063 Map the 1.15.2 changes
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/model/BakedModel.mapping
  mappings/net/minecraft/client/render/model/BasicBakedModel.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/util/Window.mapping
Labels: new, snapshot

#1064 BlockSoundGroup.field_21214 -> HONEY
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
Labels: new

#1065 2 df classes and some render layer stuff
  mappings/net/minecraft/client/render/OutlineVertexConsumerProvider.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/datafixer/fix/AdvancementRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/RecipeRenameFix.mapping
Labels: new, ready to merge, refactor, snapshot

#1058 Improve confusing names in entities classes.
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: refactor, release

#1067 Map multiplayer warning screen
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerWarningScreen.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
Labels: new, ready to merge

#1045 Map method_7288 to findRespawnPosition
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: new, outdated, ready to merge

#1066 1.15.2 Profiler mappings
  mappings/net/minecraft/util/profiler/DisableableProfiler.mapping
  mappings/net/minecraft/util/profiler/ProfileLocationInfo.mapping
  mappings/net/minecraft/util/profiler/ProfileResult.mapping
  mappings/net/minecraft/util/profiler/ProfileResultImpl.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
  mappings/net/minecraft/util/profiler/ProfilerSystem.mapping
  mappings/net/minecraft/util/profiler/ProfilerTiming.mapping
  mappings/net/minecraft/util/profiler/ReadableProfiler.mapping
Labels: new, refactor

#1068 Status effect stufff
  mappings/net/minecraft/entity/effect/DamageModifierStatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
  mappings/net/minecraft/entity/effect/StatusEffects.mapping
Labels: new, ready to merge, refactor

#1070 swap canSet(Snow|Ice)
  mappings/net/minecraft/world/biome/Biome.mapping
Labels: bug, outdated, ready to merge, refactor

#1010 Mapped FrameBufferInfo
  mappings/com/mojang/blaze3d/platform/FramebufferInfo.mapping
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
Labels: new, ready to merge, release

#1073 Carver mappings
  mappings/net/minecraft/world/gen/carver/Carver.mapping
  mappings/net/minecraft/world/gen/carver/CaveCarver.mapping
  mappings/net/minecraft/world/gen/carver/NetherCaveCarver.mapping
  mappings/net/minecraft/world/gen/carver/RavineCarver.mapping
  mappings/net/minecraft/world/gen/carver/UnderwaterCaveCarver.mapping
Labels: new

#1075 Hodgepodge mappings 1
  mappings/net/minecraft/entity/attribute/AbstractEntityAttributeContainer.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/nbt/ListTag.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/tag/RegistryTagContainer.mapping
  mappings/net/minecraft/tag/Tag.mapping
  mappings/net/minecraft/village/VillagerProfession.mapping
  mappings/net/minecraft/village/ZombieSiegeManager.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
Labels: new

#1080 LivingEntity rendering fix
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: new, refactor
