Repository FabricMC/yarn, pull requests merged in 2020-06, with the labels that each got.

#1414 Map ZOMBIE_TYPE
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
Labels: new, ready to merge, snapshot

#1411 Map new respawn anchor methods
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
Labels: new, ready to merge, snapshot

#1410 Couple of AbstractBlockState Mappings
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: refactor, snapshot

#1406 Datapack failure screen
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/DatapackFailureScreen.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, ready to merge, snapshot

#1407 World related mappings and docs
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/BlockView.mapping
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/ModifiableWorld.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldView.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
Labels: javadoc, new, ready to merge, snapshot

#1415 Feature stuff
  mappings/net/minecraft/world/gen/feature/BastionRemnantFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/BlockPileFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/BuriedTreasureFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeature.mapping
  mappings/net/minecraft/world/gen/feature/DecoratedFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/EndSpikeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/IcePatchFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/MineshaftFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RandomBooleanFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RandomPatchFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RuinedPortalFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SeaPickleFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/ShipwreckFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SimpleRandomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SingleStateFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProvider.mapping
Labels: new, refactor, snapshot

#1416 Finish mapping campfires
  mappings/net/minecraft/block/CampfireBlock.mapping
  mappings/net/minecraft/client/particle/CampfireSmokeParticle.mapping
Labels: javadoc, new, snapshot

#1424 Some small mappings
  mappings/net/minecraft/resource/ServerResourceManager.mapping
  mappings/net/minecraft/tag/RegistryTagManager.mapping
Labels: new, ready to merge, snapshot

#1421 Some small command manager things
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/SeedCommand.mapping
Labels: new, ready to merge, snapshot

#1408 Document chunk tickets
  mappings/net/minecraft/server/world/ChunkTicket.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ChunkTicketType.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
Labels: javadoc, ready to merge, snapshot

#1425 Registry codec stuff, and that thing is registry not dimension tracker
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/dynamic/ForwardingDynamicOps.mapping
  mappings/net/minecraft/util/dynamic/RegistryCodec.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/util/dynamic/RegistryReadingOps.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryTracker.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/dimension/DimensionTracker.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/GenerationStep.mapping
Labels: new, ready to merge, refactor, snapshot

#1428 Map HandledScreen label coordinates
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
Labels: new, ready to merge, snapshot

#1433 Add Some Missing Mappings
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/loot/function/LootFunction.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: new, ready to merge, snapshot

#1432 Added mappings for new fields in DefaultBiomeFeatures
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
Labels: new, ready to merge, refactor, snapshot

#1426 Map TextureUtil
  mappings/net/minecraft/client/texture/TextureUtil.mapping
Labels: new, ready to merge, snapshot

#1419 Data pack screen
  mappings/net/minecraft/client/gui/screen/pack/AbstractPackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/DataPackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackScreen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
Labels: new, ready to merge, refactor, snapshot

#1418 Map graphics modes
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
  mappings/net/minecraft/client/options/GraphicsMode.mapping
  mappings/net/minecraft/client/options/Option.mapping
  mappings/net/minecraft/client/render/RenderLayers.mapping
Labels: new, ready to merge, snapshot

#1381 GameRules docs.
  mappings/net/minecraft/world/GameRules.mapping
Labels: javadoc, new, ready to merge, snapshot

#1372 Various misc changes
  mappings/net/minecraft/advancement/CriterionMerger.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/entity/mob/EvokerEntity.mapping
Labels: javadoc, new, ready to merge, refactor, snapshot

#1429 Explosions
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
  mappings/net/minecraft/entity/damage/BadRespawnPointDamageSource.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/damage/NetherBedDamageSource.mapping
  mappings/net/minecraft/util/ActionResult.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/world/explosion/DefaultExplosionBehavior.mapping
  mappings/net/minecraft/world/explosion/EntityExplosionBehavior.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
  mappings/net/minecraft/world/explosion/ExplosionBehavior.mapping
Labels: new, refactor, snapshot

#1430 A bit entity brain/anger stuff
  mappings/net/minecraft/class_5354.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/NearestVisibleAdultSensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/LookTargetUtil.mapping
  mappings/net/minecraft/entity/ai/brain/task/TakeJobSiteTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkTowardClosestAdultTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkTowardJobSiteTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WorkStationCompetitionTask.mapping
  mappings/net/minecraft/entity/mob/Angerable.mapping
  mappings/net/minecraft/entity/mob/HoglinBrain.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/math/IntRange.mapping
Labels: new, snapshot

#1436 A bunch of param names
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/ChainBlock.mapping
  mappings/net/minecraft/block/ChorusFlowerBlock.mapping
  mappings/net/minecraft/block/FarmlandBlock.mapping
  mappings/net/minecraft/block/FenceBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/state/StateManager.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldProperties.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/chunk/ChunkProvider.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
Labels: new, snapshot

#1420 pre1 stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/FluidBlock.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/options/NarratorOption.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockRenderManager.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/data/server/recipe/SmithingRecipeJsonFactory.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/DyingPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/HoldingPatternPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/HoverPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/LandingApproachPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/LandingPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/StrafePlayerPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/TakeoffPhase.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/passive/AnimalEntity.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/recipe/SmithingRecipe.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
Labels: new, snapshot

#1279 Fix wrong NativeImage method names
  mappings/net/minecraft/client/texture/NativeImage.mapping
Labels: bug, javadoc, refactor, snapshot

#1423 Data and Server startup mappings
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/resource/DataPackSettings.mapping
  mappings/net/minecraft/resource/ResourcePackSource.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: new, ready to merge, snapshot

#1384 Added a bunch of mappings based of strings related to the custom dime…
  mappings/net/minecraft/class_5309.mapping
  mappings/net/minecraft/class_5310.mapping
  mappings/net/minecraft/class_5311.mapping
  mappings/net/minecraft/class_5313.mapping
  mappings/net/minecraft/class_5314.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseConfig.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseSamplingConfig.mapping
  mappings/net/minecraft/world/gen/chunk/SlideConfig.mapping
  mappings/net/minecraft/world/gen/chunk/StrongholdConfig.mapping
  mappings/net/minecraft/world/gen/chunk/StructureConfig.mapping
  mappings/net/minecraft/world/gen/chunk/StructuresConfig.mapping
Labels: new, ready to merge, snapshot

#1422 Some pre 2 mappings
  mappings/net/minecraft/recipe/SmithingRecipe.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/dimension/DimensionOptions.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
Labels: new, ready to merge, snapshot

#1435 Add Structure Spacing Mappings
  mappings/net/minecraft/class_5299.mapping
  mappings/net/minecraft/datafixer/fix/StructureSeparationDataFix.mapping
Labels: new, ready to merge, snapshot

#1437 Loot and JSON stuff
  mappings/net/minecraft/datafixer/NbtOps.mapping
  mappings/net/minecraft/loot/condition/AlternativeLootCondition.mapping
  mappings/net/minecraft/loot/condition/BlockStatePropertyLootCondition.mapping
  mappings/net/minecraft/loot/condition/DamageSourcePropertiesLootCondition.mapping
  mappings/net/minecraft/loot/condition/EntityPropertiesLootCondition.mapping
  mappings/net/minecraft/loot/condition/EntityScoresLootCondition.mapping
  mappings/net/minecraft/loot/condition/InvertedLootCondition.mapping
  mappings/net/minecraft/loot/condition/KilledByPlayerLootCondition.mapping
  mappings/net/minecraft/loot/condition/LocationCheckLootCondition.mapping
  mappings/net/minecraft/loot/condition/LootCondition.mapping
  mappings/net/minecraft/loot/condition/LootConditionManager.mapping
  mappings/net/minecraft/loot/condition/LootConditionTypes.mapping
  mappings/net/minecraft/loot/condition/MatchToolLootCondition.mapping
  mappings/net/minecraft/loot/condition/RandomChanceLootCondition.mapping
  mappings/net/minecraft/loot/condition/RandomChanceWithLootingLootCondition.mapping
  mappings/net/minecraft/loot/condition/ReferenceLootCondition.mapping
  mappings/net/minecraft/loot/condition/SurvivesExplosionLootCondition.mapping
  mappings/net/minecraft/loot/condition/TableBonusLootCondition.mapping
  mappings/net/minecraft/loot/condition/TimeCheckLootCondition.mapping
  mappings/net/minecraft/loot/condition/WeatherCheckLootCondition.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntry.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntryTypes.mapping
  mappings/net/minecraft/loot/function/ApplyBonusLootFunction.mapping
  mappings/net/minecraft/loot/function/ConditionalLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyNameLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyNbtLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyStateFunction.mapping
  mappings/net/minecraft/loot/function/EnchantRandomlyLootFunction.mapping
  mappings/net/minecraft/loot/function/EnchantWithLevelsLootFunction.mapping
  mappings/net/minecraft/loot/function/ExplorationMapLootFunction.mapping
  mappings/net/minecraft/loot/function/ExplosionDecayLootFunction.mapping
  mappings/net/minecraft/loot/function/FillPlayerHeadLootFunction.mapping
  mappings/net/minecraft/loot/function/FurnaceSmeltLootFunction.mapping
  mappings/net/minecraft/loot/function/LimitCountLootFunction.mapping
  mappings/net/minecraft/loot/function/LootFunctionTypes.mapping
  mappings/net/minecraft/loot/function/LootingEnchantLootFunction.mapping
  mappings/net/minecraft/loot/function/SetAttributesLootFunction.mapping
  mappings/net/minecraft/loot/function/SetContentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetCountLootFunction.mapping
  mappings/net/minecraft/loot/function/SetDamageLootFunction.mapping
  mappings/net/minecraft/loot/function/SetLootTableLootFunction.mapping
  mappings/net/minecraft/loot/function/SetLoreLootFunction.mapping
  mappings/net/minecraft/loot/function/SetNameLootFunction.mapping
  mappings/net/minecraft/loot/function/SetNbtLootFunction.mapping
  mappings/net/minecraft/loot/function/SetStewEffectLootFunction.mapping
  mappings/net/minecraft/util/JsonSerializableType.mapping
  mappings/net/minecraft/util/JsonSerializer.mapping
  mappings/net/minecraft/util/JsonSerializing.mapping
Labels: new, ready to merge, refactor, snapshot

#1385 Added names for fields based on strings in class_5315
  mappings/net/minecraft/world/level/storage/SaveVersionInfo.mapping
Labels: new, snapshot

#1439 A few soul speed mappings
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: new, ready to merge, refactor, snapshot

#1441 Four unmapped top level classes
  mappings/net/minecraft/datafixer/schema/IdentifierNormalizingSchema.mapping
  mappings/net/minecraft/datafixer/schema/Schema2551.mapping
  mappings/net/minecraft/util/dynamic/NumberCodecs.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/WordPackedArray.mapping
  mappings/net/minecraft/world/BlockCollisionSpliterator.mapping
Labels: new, snapshot

#1440 Resource pack organizer
  mappings/net/minecraft/client/gui/screen/pack/AbstractPackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/DataPackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackOrganizer.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
Labels: new, ready to merge, snapshot

#1445 TreeDecorator.getType()
  mappings/net/minecraft/world/gen/decorator/TreeDecorator.mapping
Labels: new, ready to merge, snapshot

#1431 String renderable (or visitable?)
  mappings/net/minecraft/class_5348.mapping
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/font/TextVisitFactory.mapping
  mappings/net/minecraft/client/resource/language/LanguageDefinition.mapping
  mappings/net/minecraft/client/resource/language/TranslationStorage.mapping
  mappings/net/minecraft/text/StringRenderable.mapping
  mappings/net/minecraft/text/TranslatableText.mapping
  mappings/net/minecraft/util/Language.mapping
Labels: discussion, javadoc, new, ready to merge, refactor, snapshot

#1443 Map the remaining inner classes
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/widget/AbstractButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/ButtonWidget.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/state/StateManager.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
Labels: new, snapshot

#1450 Mapped EntityS2CPacket
  mappings/net/minecraft/network/packet/s2c/play/EntityS2CPacket.mapping
Labels: new, ready to merge, snapshot

#1452 Finish ProfilerTimer mapping
  build.gradle
  mappings/net/minecraft/util/profiler/ProfilerTiming.mapping
Labels: new, outdated, ready to merge, release

#1454 Document TradeOffers.Factory and some params
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: javadoc, ready to merge, snapshot

#1455 Document drawBox methods
  mappings/net/minecraft/client/render/WorldRenderer.mapping
Labels: javadoc, ready to merge, snapshot

#1456 pre3 DimensionType
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: new, ready to merge, snapshot

#1458 Map 56 fields in the grindstone block
  mappings/net/minecraft/block/GrindstoneBlock.mapping
Labels: new, ready to merge, refactor, snapshot

#1446 Added some mappings in DynamicSerializableUuid
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableUuid.mapping
Labels: new, ready to merge, snapshot

#1472 add ITEM_TARGET RenderPhase field mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
Labels: new, ready to merge, snapshot

#1470 Added mapping TRIPWIRE RenderLayer getter
  mappings/net/minecraft/client/render/RenderLayer.mapping
Labels: new, ready to merge, snapshot

#1466 Map UUID in GameMessageS2CPacket
  mappings/net/minecraft/client/gui/ClientChatListener.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameMessageS2CPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/CommandOutput.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, ready to merge, snapshot

#1461 Map various, mostly private parts of client.texture classes
  mappings/net/minecraft/client/texture/MissingSprite.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/texture/ResourceTexture.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/TextureStitcher.mapping
  mappings/net/minecraft/client/texture/TextureUtil.mapping
Labels: new, ready to merge, snapshot

#1473 add tickRainSplashing Mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
Labels: new, ready to merge, snapshot

#1471 add Tripwire RenderLayer PhaseParameters getter
  mappings/net/minecraft/client/render/RenderLayer.mapping
Labels: new, ready to merge, snapshot

#1477 Fix a typo, thanks haykam
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
Labels: ready to merge, refactor, snapshot

#1465 Some packet parameters, I guess
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/network/packet/c2s/play/AdvancementTabC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClientCommandC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CraftRequestC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CreativeInventoryActionC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CustomPayloadC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/GuiCloseC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/JigsawGeneratingC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerActionC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractBlockC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractEntityC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractItemC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/QueryBlockNbtC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/QueryEntityNbtC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/RecipeBookDataC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/RenameItemC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ResourcePackStatusC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/SelectVillagerTradeC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateBeaconC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateCommandBlockC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateCommandBlockMinecartC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateDifficultyC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateDifficultyLockC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateSelectedSlotC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateSignC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CombatEventS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CraftFailedResponseS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityPassengersSetS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityPositionS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntitySetHeadYawS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntitySpawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityStatusS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityTrackerUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityVelocityUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/LightUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/OpenWrittenBookS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ParticleS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerActionResponseS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/RemoveEntityStatusEffectS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardDisplayS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardObjectiveUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardPlayerUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SetCameraEntityS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/StatisticsS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TeamS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TitleS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/UnlockRecipesS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/VehicleMoveS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldTimeUpdateS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/structure/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/pool/SinglePoolElement.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
Labels: new, ready to merge, snapshot

#1476 Map the new advancement trigger
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/PlayerInteractedWithEntityCriterion.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
Labels: new, ready to merge, snapshot

#1478 Port GLDebug mappings to latest
  .editorconfig
  mappings/net/minecraft/client/gl/GlDebug.mapping
Labels: new, ready to merge, snapshot, toolchain

#1475 ServerCommandOutput -> RconCommandOutput and a bunch of assorted parameter names
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/dedicated/DedicatedPlayerManager.mapping
  mappings/net/minecraft/server/dedicated/DedicatedServerWatchdog.mapping
  mappings/net/minecraft/server/dedicated/gui/DedicatedServerGui.mapping
  mappings/net/minecraft/server/dedicated/gui/PlayerListGui.mapping
  mappings/net/minecraft/server/dedicated/gui/PlayerStatsGui.mapping
  mappings/net/minecraft/server/integrated/IntegratedPlayerManager.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
  mappings/net/minecraft/server/rcon/RconCommandOutput.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/World.mapping
Labels: javadoc, new, ready to merge, refactor, snapshot

#1459 1.16 pre3 things
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/render/DiffuseLighting.mapping
  mappings/net/minecraft/client/render/SkyProperties.mapping
  mappings/net/minecraft/datafixer/fix/MissingDimensionFix.mapping
  mappings/net/minecraft/entity/ai/brain/task/FindPointOfInterestTask.mapping
  mappings/net/minecraft/entity/ai/goal/UniversalAngerGoal.mapping
  mappings/net/minecraft/entity/mob/Angerable.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameStateChangeS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/structure/processor/BlackstoneReplacementStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/BlockAgeStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/BlockIgnoreStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/BlockRotStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/GravityStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/JigsawReplacementStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/LavaSubmergedBlockStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/NopStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/RuleStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorType.mapping
  mappings/net/minecraft/tag/SetTag.mapping
Labels: new, ready to merge, snapshot

#1485 NativeImage#Format.ABGR not NativeImage#Format.AGBR
  mappings/net/minecraft/client/texture/NativeImage.mapping
Labels: bug, ready to merge, refactor, snapshot

#1489 Fix FluidState#matches not being consistent with Fluid#isIn
  mappings/net/minecraft/fluid/FluidState.mapping
Labels: bug, ready to merge, refactor, snapshot

#1488 Swap the names of the bubble and bubble column up particle classes
  mappings/net/minecraft/client/particle/BubbleColumnUpParticle.mapping
  mappings/net/minecraft/client/particle/WaterBubbleParticle.mapping
Labels: bug, ready to merge, refactor, snapshot

#1481 Some fixes
  gradle.properties
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonFactory.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/structure/RuinedPortalStructurePiece.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/gen/feature/ForestRockFeatureConfig.mapping
Labels: bug, ready to merge, refactor, snapshot

#1482 Move raid classes to village package
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
Labels: ready to merge, refactor, snapshot

#1494 Fix a typo in EntitySpawnS2CPacket
  mappings/net/minecraft/network/packet/s2c/play/EntitySpawnS2CPacket.mapping
Labels: bug, ready to merge, refactor, snapshot

#1483 Map new ModifiableWorld.setBlockState
  mappings/net/minecraft/world/ModifiableWorld.mapping
Labels: javadoc, new, ready to merge, snapshot

#1490 Rename the air material color to clear
  mappings/net/minecraft/block/MaterialColor.mapping
Labels: ready to merge, refactor, snapshot

#1495 Change hasEnchantmentGlint to hasGlint
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: ready to merge, refactor, release

#1496 Re add names to documented rules that were previously autonamed.
  mappings/net/minecraft/world/GameRules.mapping
Labels: bug, ready to merge, snapshot

#1497 Fix spacing of 'blockstate' in ModifiableWorld#setBlockState docs
  mappings/net/minecraft/world/ModifiableWorld.mapping
Labels: javadoc, ready to merge, release

#1503 Map riptide properly
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: bug, ready to merge, refactor, release

#1469 1.16-pre5 world gen mappings
  mappings/net/minecraft/world/gen/carver/Carver.mapping
  mappings/net/minecraft/world/gen/decorator/Decorator.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/size/FeatureSize.mapping
  mappings/net/minecraft/world/gen/feature/size/FeatureSizeType.mapping
  mappings/net/minecraft/world/gen/feature/size/ThreeLayersFeatureSize.mapping
  mappings/net/minecraft/world/gen/feature/size/TwoLayersFeatureSize.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacerType.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProviderType.mapping
  mappings/net/minecraft/world/gen/stateprovider/ForestFlowerBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/PillarBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/PlainsFlowerBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/SimpleBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/stateprovider/WeightedBlockStateProvider.mapping
  mappings/net/minecraft/world/gen/trunk/TrunkPlacer.mapping
  mappings/net/minecraft/world/gen/trunk/TrunkPlacerType.mapping
Labels: new, ready to merge, snapshot

#1509 Default structures and minor fixes
  mappings/net/minecraft/loot/LootTableRanges.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
Labels: new, ready to merge, refactor

#1512 desync -> dsync
  mappings/net/minecraft/world/storage/RegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
Labels: bug, ready to merge, refactor

#1505 Some Realms mappings
  mappings/com/mojang/realmsclient/RealmsMainScreen.mapping
  mappings/com/mojang/realmsclient/gui/RealmsWorldSlotButton.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsAcceptRejectButton.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsBackupInfoScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsBackupScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsBrokenWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsClientOutdatedScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsConfigureWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsConfirmScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsCreateRealmScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsDownloadLatestWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsGenericErrorScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsInviteScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsNotificationsScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsParentalConsentScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsPendingInvitesScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsPlayerScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsResetNormalWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsResetWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsSelectFileToUploadScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsSelectWorldTemplateScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsSettingsScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsSubscriptionInfoScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsTermsScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
Labels: new, ready to merge, refactor, release

#1511 Map chunk and chunk statuses (Reattached)
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/EntityView.mapping
  mappings/net/minecraft/world/StructureHolder.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/EmptyChunk.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/chunk/ReadOnlyChunk.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/gen/StructureAccessor.mapping
Labels: new, ready to merge

#1526 ButtonWidget constructor arguments
  mappings/net/minecraft/client/gui/widget/ButtonWidget.mapping
Labels: new, ready to merge

#1521 Made it more explicit why one would want to run the yarn task
  README.md
Labels: enhancement, ready to merge, toolchain

#1520 Additional breakBlock overload mapped
  mappings/net/minecraft/world/ModifiableWorld.mapping
Labels: new, ready to merge

#1517 MobEntityWithAi -> PathAwareEntity
  mappings/net/minecraft/entity/ai/goal/DoorInteractGoal.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/PathAwareEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
Labels: refactor, release

#1513 Update PiglinBrain to have more accurate names
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
Labels: new

#1527 A couple of goal fixes
  mappings/net/minecraft/entity/ai/goal/GoToEntityGoal.mapping
  mappings/net/minecraft/entity/ai/goal/StopAndLookAtEntityGoal.mapping
  mappings/net/minecraft/entity/ai/goal/WanderNearTargetGoal.mapping
Labels: bug, refactor

#1519 Add mappings for client (options and some screens/widgets).
  mappings/net/minecraft/client/gui/screen/GraphicsConfirmationScreen.mapping
  mappings/net/minecraft/client/gui/screen/VideoOptionsScreen.mapping
  mappings/net/minecraft/client/gui/widget/ButtonListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/OptionButtonWidget.mapping
  mappings/net/minecraft/client/options/BooleanOption.mapping
  mappings/net/minecraft/client/options/CyclingOption.mapping
  mappings/net/minecraft/client/options/Option.mapping
Labels: new, ready to merge
