Repository FabricMC/yarn, pull requests merged in 2020-09, with the labels that each got.

#1736 Add mappings to DefaultBiomeCreator
  mappings/net/minecraft/world/biome/DefaultBiomeCreator.mapping
Labels: new, ready to merge

#1710 Map missing client collision methods
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/world/BlockCollisionSpliterator.mapping
  mappings/net/minecraft/world/CollisionView.mapping
Labels: new, ready to merge

#1699 Various entity mappings
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/mob/DrownedEntity.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/EndermiteEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PatrolEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/RavagerEntity.mapping
  mappings/net/minecraft/entity/mob/StrayEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/BatEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/entity/passive/PassiveEntity.mapping
  mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/vehicle/TntMinecartEntity.mapping
Labels: javadoc, new, ready to merge, refactor

#1739 New Ingredient.ofStacks (single method)
  mappings/net/minecraft/recipe/Ingredient.mapping
Labels: new, ready to merge

#1755 ScreenTexts.FAILED -> CONNECT_FAILED
  mappings/net/minecraft/client/gui/screen/ScreenTexts.mapping
Labels: refactor, snapshot

#1754 Map the new fields and methods in 1.16.3-rc1
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
Labels: new, ready to merge, snapshot

#1751 Add mappings for Feature
  mappings/net/minecraft/world/gen/feature/Feature.mapping
Labels: new, ready to merge, release

#1742 Add game mode mappings
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
Labels: new, ready to merge

#1738 Some util package mappings
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableUuid.mapping
  mappings/net/minecraft/util/dynamic/GlobalPos.mapping
  mappings/net/minecraft/util/dynamic/RegistryCodec.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/dynamic/RegistryReadingOps.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: javadoc, new, outdated, ready to merge

#1750 Name New Material and JD it
  mappings/net/minecraft/block/Material.mapping
Labels: javadoc, new, ready to merge

#1749 JD for METAL material
  mappings/net/minecraft/block/Material.mapping
Labels: javadoc, ready to merge

#1761 Replace the remaining TEX suffixes for fields
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/hud/InGameOverlayRenderer.mapping
  mappings/net/minecraft/client/gui/hud/SpectatorHud.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AnimatedResultButton.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/toast/Toast.mapping
Labels: ready to merge, refactor, release

#1760 Replace generic trader naming with merchant
  mappings/net/minecraft/entity/passive/MerchantEntity.mapping
  mappings/net/minecraft/village/Merchant.mapping
  mappings/net/minecraft/village/MerchantInventory.mapping
  mappings/net/minecraft/village/SimpleMerchant.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
Labels: ready to merge, refactor, release

#1757 Some fixes
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/ChestBlockEntity.mapping
  mappings/net/minecraft/client/gui/hud/ChatHudListener.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/network/packet/c2s/play/SelectMerchantTradeC2SPacket.mapping
Labels: bug, ready to merge, refactor

#1668 Some item javadoc
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemConvertible.mapping
  mappings/net/minecraft/item/ItemUsageContext.mapping
  mappings/net/minecraft/item/NetworkSyncedItem.mapping
Labels: javadoc, outdated, ready to merge

#1763 Add javadoc for the class Element
  mappings/net/minecraft/client/gui/Element.mapping
Labels: javadoc, ready to merge

#1764 Finish mapping the CreditsScreen class
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
Labels: new, ready to merge, release

#1748 Add mappings for SurfaceBuilder
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: new, ready to merge

#1741 Add mappings to MinecraftServer
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: javadoc, new, ready to merge

#1765 Style.method_30938 -> withUnderline
  mappings/net/minecraft/text/Style.mapping
Labels: javadoc, new, ready to merge

#1768 Item.getStackForRender -> getDefaultStack
  mappings/net/minecraft/item/Item.mapping
Labels: ready to merge, refactor
