Repository FabricMC/yarn, pull requests merged in 2020-10, with the labels that each got.

#1769 Add some Javadoc for Item
  mappings/net/minecraft/item/Item.mapping
Labels: javadoc, ready to merge

#1773 method_29237 -> success
  mappings/net/minecraft/util/TypedActionResult.mapping
Labels: new, ready to merge, release

#1484 Glint layer mappings
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
Labels: new, ready to merge, refactor

#1772 I single-handed mapped the most derpy code in all of minecraft [Squid Mappings]
  mappings/net/minecraft/entity/passive/SquidEntity.mapping
Labels: javadoc, new, refactor

#1771 Add mappings for InGameHud
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
Labels: new

#1759 Entity model things
  mappings/net/minecraft/client/render/entity/model/FoxEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/GhastEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/IllagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/LargeTropicalFishEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/MinecartEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RabbitEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RavagerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SheepEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ShieldEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SilverfishEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SmallTropicalFishEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SnowGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SquidEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TridentEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TurtleEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/WitherEntityModel.mapping
Labels: new, refactor

#1713 Add mappings for vector classes
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
Labels: new, release

#1762 Remap LevelStorage parser method and LevelStorage$Session getter methods
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: new, refactor

#1758 Feature classes
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/world/gen/feature/AbstractPileFeature.mapping
  mappings/net/minecraft/world/gen/feature/BasaltColumnsFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/BlockPileFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeature.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/DeltaFeature.mapping
  mappings/net/minecraft/world/gen/feature/DeltaFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/DiskFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/EndSpikeFeature.mapping
  mappings/net/minecraft/world/gen/feature/EndSpikeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/MineshaftFeature.mapping
  mappings/net/minecraft/world/gen/feature/MineshaftFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/NetherForestVegetationFeature.mapping
  mappings/net/minecraft/world/gen/feature/NetherrackReplaceBlobsFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/OceanRuinFeature.mapping
  mappings/net/minecraft/world/gen/feature/RandomBooleanFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RandomFeatureEntry.mapping
  mappings/net/minecraft/world/gen/feature/RandomPatchFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RuinedPortalFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SimpleBlockFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructurePoolFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/size/FeatureSizeType.mapping
Labels: new, ready to merge

#1774 Entity.isCollidable & Entity.collidesWith
  mappings/net/minecraft/entity/Entity.mapping
Labels: new

#1775 Mapped MultiNoiseBiomeSource
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
Labels: new, ready to merge, release

#1780 Fix some static final fields not having uppercase names
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerWarningScreen.mapping
  mappings/net/minecraft/client/texture/TextureStitcher.mapping
  mappings/net/minecraft/command/argument/TimeArgumentType.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/entity/data/DataTracker.mapping
  mappings/net/minecraft/util/collection/Int2ObjectBiMap.mapping
  mappings/net/minecraft/util/math/noise/SimplexNoiseSampler.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
Labels: ready to merge, refactor, release

#1779 Finish ChatHud mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
Labels: new, ready to merge

#1778 Replace remaining references to generic trader naming with merchant
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
  mappings/net/minecraft/entity/ai/goal/LookAtCustomerGoal.mapping
  mappings/net/minecraft/entity/ai/goal/StopFollowingCustomerGoal.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/screen/slot/TradeOutputSlot.mapping
  mappings/net/minecraft/village/MerchantInventory.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
Labels: ready to merge, refactor, release

#1789 Add Javadoc for property classes
  mappings/net/minecraft/state/property/IntProperty.mapping
  mappings/net/minecraft/state/property/Property.mapping
Labels: javadoc, ready to merge

#1781 Fix the IdListPalette.fallback field not matching the parameter name
  mappings/net/minecraft/world/chunk/IdListPalette.mapping
Labels: ready to merge, refactor, release

#1787 Finish BlockHitResult mapping
  mappings/net/minecraft/util/hit/BlockHitResult.mapping
Labels: new, ready to merge

#1785 Add more DebugHud mappings
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
Labels: new, ready to merge

#1777 Rename villager trade select listener method to match packet name
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
Labels: refactor, release

#1776 Map class and methods in NarratorOptionsScreen
  mappings/net/minecraft/client/gui/screen/options/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/NarratorOptionsScreen.mapping
  mappings/net/minecraft/client/gui/widget/ButtonListWidget.mapping
Labels: new, release

#1791 Map most remaining BlockPos methods
  mappings/net/minecraft/util/math/BlockPos.mapping
Labels: new, refactor, release

#1788 Stronghold, fortress, mineshaft, and general structure mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/StructureStart.mapping
Labels: new, refactor

#1798 Add mapping for TallPlantBlock.method_30036
  mappings/net/minecraft/block/TallPlantBlock.mapping
Labels: javadoc, new

#1797 Completed mappings for BellBlockEntity
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: new, refactor

#1795 Finish MerchantScreen mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
Labels: new

#1790 Add javadocs convention
  CONVENTIONS.md
  gradle.properties
Labels: toolchain

#1783 Finish Option mapping
  mappings/net/minecraft/client/options/Option.mapping
  mappings/net/minecraft/util/Arm.mapping
Labels: new

#1804 Update gradle and improve realiablitity of actions
  .github/workflows/build.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: toolchain

#1718 Some dynamic registry mappings
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
Labels: javadoc, new, ready to merge

#1786 Biome sources, chunk generators and level things
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: javadoc, new, ready to merge, refactor

#1806 Add javadoc for color parameters in TextRenderer
  mappings/net/minecraft/client/font/TextRenderer.mapping
Labels: javadoc, ready to merge

#1800 Some server javadoc and mappings
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/rcon/QueryResponseHandler.mapping
  mappings/net/minecraft/server/rcon/RconListener.mapping
Labels: javadoc, new, ready to merge

#1808 Social interactions
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/SocialInteractionsManager.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
  mappings/net/minecraft/client/tutorial/TutorialManager.mapping
Labels: new

#1822 Some AgrumentType mappings
  mappings/net/minecraft/command/argument/ArgumentTypes.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
Labels: new

#1824 Sound system stuff
  mappings/net/minecraft/client/sound/SoundListener.mapping
Labels: new, ready to merge

#1803 Add mappings for Window and related classes
  mappings/net/minecraft/client/Keyboard.mapping
  mappings/net/minecraft/client/WindowEventHandler.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/client/util/WindowProvider.mapping
Labels: new, outdated, ready to merge, snapshot

#1818 ServerPlayerEntity.openHandledScreen(ScreenHandler) -> refreshScreenHandler
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: outdated, ready to merge, refactor, snapshot

#1817 Complete BookUpdateC2SPacket mappings
  mappings/net/minecraft/network/packet/c2s/play/BookUpdateC2SPacket.mapping
Labels: new, outdated, ready to merge, snapshot

#1815 Map the NetworkEncryptionException class
  mappings/net/minecraft/network/encryption/NetworkEncryptionException.mapping
Labels: new, ready to merge, snapshot

#1805 Add a simple `decompileCFR` task
  .gitignore
  README.md
  build.gradle
Labels: ready to merge, toolchain
