Repository FabricMC/yarn, pull requests merged in 2020-05, with the labels that each got.

#1313 Rcon
  mappings/net/minecraft/server/dedicated/DedicatedServer.mapping
  mappings/net/minecraft/server/rcon/RconBase.mapping
  mappings/net/minecraft/server/rcon/RconClient.mapping
  mappings/net/minecraft/server/rcon/RconListener.mapping
Labels: bug, refactor, snapshot

#1314 Restore missing BeeDebugRenderer$Bee
  mappings/net/minecraft/client/render/debug/BeeDebugRenderer.mapping
Labels: new, ready to merge, snapshot

#1307 Bring back the parameters
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/particle/AnimatedParticle.mapping
  mappings/net/minecraft/client/particle/AscendingParticle.mapping
  mappings/net/minecraft/client/particle/AshParticle.mapping
  mappings/net/minecraft/client/particle/BarrierParticle.mapping
  mappings/net/minecraft/client/particle/BlockDustParticle.mapping
  mappings/net/minecraft/client/particle/BlockFallingDustParticle.mapping
  mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
  mappings/net/minecraft/client/particle/BubbleColumnUpParticle.mapping
  mappings/net/minecraft/client/particle/BubblePopParticle.mapping
  mappings/net/minecraft/client/particle/CampfireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/CloudParticle.mapping
  mappings/net/minecraft/client/particle/CrackParticle.mapping
  mappings/net/minecraft/client/particle/CurrentDownParticle.mapping
  mappings/net/minecraft/client/particle/DamageParticle.mapping
  mappings/net/minecraft/client/particle/DragonBreathParticle.mapping
  mappings/net/minecraft/client/particle/ElderGuardianAppearanceParticle.mapping
  mappings/net/minecraft/client/particle/EmitterParticle.mapping
  mappings/net/minecraft/client/particle/EmotionParticle.mapping
  mappings/net/minecraft/client/particle/EnchantGlyphParticle.mapping
  mappings/net/minecraft/client/particle/EndRodParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionEmitterParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionLargeParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionSmokeParticle.mapping
  mappings/net/minecraft/client/particle/FireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/client/particle/FishingParticle.mapping
  mappings/net/minecraft/client/particle/FlameParticle.mapping
  mappings/net/minecraft/client/particle/ItemPickupParticle.mapping
  mappings/net/minecraft/client/particle/LargeFireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/LavaEmberParticle.mapping
  mappings/net/minecraft/client/particle/NoteParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleFactory.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/particle/RedDustParticle.mapping
  mappings/net/minecraft/client/particle/ReversePortalParticle.mapping
  mappings/net/minecraft/client/particle/SoulParticle.mapping
  mappings/net/minecraft/client/particle/SpellParticle.mapping
  mappings/net/minecraft/client/particle/SpitParticle.mapping
  mappings/net/minecraft/client/particle/SpriteBillboardParticle.mapping
  mappings/net/minecraft/client/particle/SpriteProvider.mapping
  mappings/net/minecraft/client/particle/SquidInkParticle.mapping
  mappings/net/minecraft/client/particle/SuspendParticle.mapping
  mappings/net/minecraft/client/particle/SweepAttackParticle.mapping
  mappings/net/minecraft/client/particle/TotemParticle.mapping
  mappings/net/minecraft/client/particle/WaterBubbleParticle.mapping
  mappings/net/minecraft/client/particle/WaterSplashParticle.mapping
  mappings/net/minecraft/client/particle/WaterSuspendParticle.mapping
  mappings/net/minecraft/client/particle/WhiteAshParticle.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/world/WanderingTraderManager.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/dimension/TheEndDimension.mapping
  mappings/net/minecraft/world/gen/carver/Carver.mapping
Labels: new, ready to merge, refactor, snapshot

#1316 Spawn mappings
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/math/GravityField.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
Labels: new, ready to merge, snapshot

#1323 Block Action -> Synced Block Event. Level Event -> Synced World Event
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/BlockEventS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldEventS2CPacket.mapping
  mappings/net/minecraft/server/world/BlockEvent.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/IWorld.mapping
  mappings/net/minecraft/world/World.mapping
Labels: ready to merge, refactor, snapshot

#1331 Methods and field relating to player disconnecting
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, ready to merge, snapshot

#1333 Update Enigma
  build.gradle
Labels: ready to merge, toolchain

#1322 Lots of entity mappings
  mappings/net/minecraft/client/render/entity/feature/FeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModel.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/goal/FollowTargetGoal.mapping
  mappings/net/minecraft/entity/mob/BlazeEntity.mapping
  mappings/net/minecraft/entity/mob/DrownedEntity.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/EvokerEntity.mapping
  mappings/net/minecraft/entity/mob/EvokerFangsEntity.mapping
  mappings/net/minecraft/entity/mob/GhastEntity.mapping
  mappings/net/minecraft/entity/mob/Hoglin.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PatrolEntity.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/mob/SlimeEntity.mapping
  mappings/net/minecraft/entity/mob/SpiderEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractDonkeyEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/entity/passive/ChickenEntity.mapping
  mappings/net/minecraft/entity/passive/DolphinEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/entity/passive/OcelotEntity.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/entity/passive/TraderLlamaEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/inventory/BasicInventory.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/MiningToolItem.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/village/Trader.mapping
Labels: new, ready to merge, refactor, snapshot

#1324 Screen fixes and drawTexture docs
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1327 EntityCategory -> SpawnGroup, SpawnType -> SpawnReason
  mappings/net/minecraft/data/server/EntityLootTableGenerator.mapping
  mappings/net/minecraft/entity/EntityCategory.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/SpawnGroup.mapping
  mappings/net/minecraft/entity/SpawnReason.mapping
  mappings/net/minecraft/entity/SpawnRestriction.mapping
  mappings/net/minecraft/entity/SpawnType.mapping
  mappings/net/minecraft/entity/ai/brain/task/FollowMobTask.mapping
  mappings/net/minecraft/entity/mob/DrownedEntity.mapping
  mappings/net/minecraft/entity/mob/EndermiteEntity.mapping
  mappings/net/minecraft/entity/mob/GhastEntity.mapping
  mappings/net/minecraft/entity/mob/GuardianEntity.mapping
  mappings/net/minecraft/entity/mob/HoglinEntity.mapping
  mappings/net/minecraft/entity/mob/HostileEntity.mapping
  mappings/net/minecraft/entity/mob/HuskEntity.mapping
  mappings/net/minecraft/entity/mob/MagmaCubeEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PatrolEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/SilverfishEntity.mapping
  mappings/net/minecraft/entity/mob/SlimeEntity.mapping
  mappings/net/minecraft/entity/mob/StrayEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/AnimalEntity.mapping
  mappings/net/minecraft/entity/passive/BatEntity.mapping
  mappings/net/minecraft/entity/passive/DolphinEntity.mapping
  mappings/net/minecraft/entity/passive/FishEntity.mapping
  mappings/net/minecraft/entity/passive/MooshroomEntity.mapping
  mappings/net/minecraft/entity/passive/OcelotEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/entity/passive/SquidEntity.mapping
  mappings/net/minecraft/entity/passive/StriderEntity.mapping
  mappings/net/minecraft/entity/passive/TurtleEntity.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
Labels: ready to merge, refactor, snapshot

#1336 Goal selector related mappings
  mappings/net/minecraft/entity/ai/goal/GoalSelector.mapping
  mappings/net/minecraft/entity/ai/goal/PrioritizedGoal.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1330 Command stuff
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/AdvancementCommand.mapping
  mappings/net/minecraft/server/command/BossBarCommand.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/CommandSource.mapping
  mappings/net/minecraft/server/command/DebugCommand.mapping
  mappings/net/minecraft/server/command/FillCommand.mapping
  mappings/net/minecraft/server/command/ForceLoadCommand.mapping
  mappings/net/minecraft/server/command/ListCommand.mapping
  mappings/net/minecraft/server/command/ParticleCommand.mapping
  mappings/net/minecraft/server/command/ScheduleCommand.mapping
  mappings/net/minecraft/server/command/ScoreboardCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/command/SpectateCommand.mapping
  mappings/net/minecraft/server/command/TeamCommand.mapping
  mappings/net/minecraft/server/command/TeamMsgCommand.mapping
  mappings/net/minecraft/server/command/TeleportCommand.mapping
  mappings/net/minecraft/server/command/TitleCommand.mapping
  mappings/net/minecraft/server/command/TriggerCommand.mapping
  mappings/net/minecraft/server/command/WorldBorderCommand.mapping
  mappings/net/minecraft/server/dedicated/command/BanCommand.mapping
  mappings/net/minecraft/server/dedicated/command/BanIpCommand.mapping
  mappings/net/minecraft/server/dedicated/command/BanListCommand.mapping
  mappings/net/minecraft/server/dedicated/command/DeOpCommand.mapping
  mappings/net/minecraft/server/dedicated/command/OpCommand.mapping
  mappings/net/minecraft/server/dedicated/command/PardonCommand.mapping
  mappings/net/minecraft/server/dedicated/command/PardonIpCommand.mapping
  mappings/net/minecraft/server/dedicated/command/SaveAllCommand.mapping
  mappings/net/minecraft/server/dedicated/command/SaveOffCommand.mapping
  mappings/net/minecraft/server/dedicated/command/SaveOnCommand.mapping
  mappings/net/minecraft/server/dedicated/command/SetIdleTimeoutCommand.mapping
  mappings/net/minecraft/server/dedicated/command/StopCommand.mapping
  mappings/net/minecraft/server/dedicated/command/WhitelistCommand.mapping
Labels: ready to merge, refactor, snapshot

#1340 Map FallibleItemDispenserBehavior.success accessors
  mappings/net/minecraft/block/dispenser/FallibleItemDispenserBehavior.mapping
Labels: new, snapshot

#1339 Music & fixes
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/sound/MusicSound.mapping
  mappings/net/minecraft/world/LocalDifficulty.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
Labels: bug, new, refactor, snapshot

#1341 TextRenderer.getStringWidth(Text) -> getWidth()
  mappings/net/minecraft/client/font/TextRenderer.mapping
Labels: ready to merge, refactor, snapshot

#1338 Improve Loot Table mappings
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
  mappings/net/minecraft/loot/LootChoice.mapping
  mappings/net/minecraft/loot/LootManager.mapping
  mappings/net/minecraft/loot/LootPool.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/LootTableReporter.mapping
  mappings/net/minecraft/loot/condition/BlockStatePropertyLootCondition.mapping
  mappings/net/minecraft/loot/condition/LootCondition.mapping
  mappings/net/minecraft/loot/condition/LootConditionConsumingBuilder.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/context/LootContextAware.mapping
  mappings/net/minecraft/loot/context/LootContextType.mapping
  mappings/net/minecraft/loot/entry/ItemEntry.mapping
  mappings/net/minecraft/loot/entry/LeafEntry.mapping
  mappings/net/minecraft/loot/entry/LootEntry.mapping
  mappings/net/minecraft/loot/function/LootFunction.mapping
  mappings/net/minecraft/loot/function/LootFunctionConsumingBuilder.mapping
Labels: refactor, snapshot

#1345 Entity predicates javadoc
  mappings/net/minecraft/predicate/entity/EntityPredicates.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1335 Some block methods and param names
  mappings/net/minecraft/block/AbstractRailBlock.mapping
  mappings/net/minecraft/block/AbstractRedstoneGateBlock.mapping
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/entity/LockableContainerBlockEntity.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/ChunkTickScheduler.mapping
  mappings/net/minecraft/world/Difficulty.mapping
  mappings/net/minecraft/world/EntityView.mapping
Labels: javadoc, new, ready to merge, snapshot

#1347 Nether biome sampling mappings
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSourceConfig.mapping
Labels: refactor, snapshot

#1334 Mapped random things
  mappings/net/minecraft/class_5217.mapping
  mappings/net/minecraft/class_5219.mapping
  mappings/net/minecraft/class_5221.mapping
  mappings/net/minecraft/class_5268.mapping
  mappings/net/minecraft/class_5269.mapping
  mappings/net/minecraft/client/sound/MusicType.mapping
  mappings/net/minecraft/datafixer/fix/VillagerFollowRangeFix.mapping
  mappings/net/minecraft/entity/ai/goal/IronGolemWanderAroundGoal.mapping
  mappings/net/minecraft/world/level/LevelInfo.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: new, snapshot

#1346 Start on chunk generator docs
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
Labels: javadoc, snapshot

#1349 TickableRealmsButton -> TickableElement
  mappings/net/minecraft/client/gui/screen/TickableElement.mapping
  mappings/net/minecraft/realms/TickableRealmsButton.mapping
Labels: refactor, snapshot

#1354 JigsawOrientation mapping
  mappings/net/minecraft/block/JigsawBlock.mapping
  mappings/net/minecraft/block/enums/JigsawOrientation.mapping
Labels: new, snapshot

#1350 The WorldAccesses (IWorld -> WorldAccess)
  mappings/net/minecraft/class_5281.mapping
  mappings/net/minecraft/world/ServerWorldAccess.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
Labels: new, ready to merge, refactor, snapshot

#1355 20w20b mappings
  mappings/net/minecraft/server/Main.mapping
Labels: new, ready to merge, snapshot

#1352 map chunk generators and biome sources
  mappings/net/minecraft/class_5284.mapping
  mappings/net/minecraft/world/biome/layer/BiomeLayers.mapping
  mappings/net/minecraft/world/biome/layer/SetBaseBiomesLayer.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/biome/source/BiomeArray.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/CheckerboardBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/gen/chunk/CavesChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/chunk/DebugChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/chunk/FloatingIslandsChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/OverworldChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/OverworldChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/chunk/SurfaceChunkGenerator.mapping
  mappings/net/minecraft/world/gen/foliage/SpruceFoliagePlacer.mapping
Labels: new, ready to merge, snapshot

#1358 Packet mappings and fixes
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
Labels: bug, new, ready to merge, refactor, snapshot

#1357 Fix a slight error with the loot table generator mappings
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
Labels: bug, ready to merge, refactor, snapshot

#1348 Some refactor and clean up with KeyBinding and EntryListWidget$Entry
  mappings/net/minecraft/client/gui/screen/options/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/options/KeyBinding.mapping
  mappings/net/minecraft/client/util/InputUtil.mapping
Labels: new, ready to merge, refactor, snapshot

#1190 Material Name Improvements
  mappings/net/minecraft/block/Material.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1362 Naming inconsistency in ChunkGeneratorConfig
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorConfig.mapping
Labels: ready to merge, refactor, snapshot

#1363 onBlockRemoved -> onStateReplaced
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: ready to merge, refactor, snapshot

#1351 20w20a stuff
  mappings/com/mojang/realmsclient/client/Errable.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/ItemUsedOnBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerGeneratesContainerLootCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ThrownItemPickedUpByEntityCriterion.mapping
  mappings/net/minecraft/client/gui/screen/ingame/GameModeSwitcherScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/toast/AdvancementToast.mapping
  mappings/net/minecraft/client/toast/RecipeToast.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/client/toast/Toast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/client/toast/TutorialToast.mapping
  mappings/net/minecraft/client/tutorial/CraftPlanksTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/FindTreeTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/MovementTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/NoneTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/OpenInventoryTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/PunchTreeTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/TutorialManager.mapping
  mappings/net/minecraft/client/tutorial/TutorialStep.mapping
  mappings/net/minecraft/data/server/AdvancementsProvider.mapping
  mappings/net/minecraft/data/server/NetherTabAdvancementGenerator.mapping
  mappings/net/minecraft/datafixer/fix/BitStorageAlignFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityShulkerRotationFix.mapping
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityEquipmentPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
Labels: new, ready to merge, snapshot

#1371 Rename logger print streams to not use prefix naming
  mappings/net/minecraft/util/logging/DebugLoggerPrintStream.mapping
  mappings/net/minecraft/util/logging/DebugPrintStreamLogger.mapping
  mappings/net/minecraft/util/logging/LoggerPrintStream.mapping
Labels: ready to merge, refactor, snapshot

#1368 Rename Box fields to use min/max
  mappings/net/minecraft/util/math/Box.mapping
Labels: ready to merge, refactor, snapshot

#1370 Give the NeFos and RUPO structure piece types actual names
  mappings/net/minecraft/structure/StructurePieceType.mapping
Labels: ready to merge, refactor, snapshot

#1379 Registry mappings
  mappings/net/minecraft/util/collection/Int2ObjectBiMap.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryKey.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
Labels: new, ready to merge, snapshot

#1376 Map disable multiplayer and chat command line options
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/RunArgs.mapping
Labels: new, ready to merge, snapshot

#1380 Improve state mappings for 20w21a
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: new, ready to merge, snapshot

#1378 Map most of DimensionType
  build.gradle
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: new, ready to merge, snapshot

#1353 20w20a mappings
  mappings/net/minecraft/advancement/criterion/ThrownItemPickedUpByEntityCriterion.mapping
  mappings/net/minecraft/class_5284.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/GameModeSwitcherScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/render/BackgroundRenderer.mapping
  mappings/net/minecraft/client/render/SkyProperties.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/command/arguments/UuidArgumentType.mapping
  mappings/net/minecraft/datafixer/fix/EntityShulkerRotationFix.mapping
  mappings/net/minecraft/entity/Dismounting.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/util/WorldSavePath.mapping
  mappings/net/minecraft/world/MutableWorldProperties.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldProperties.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorType.mapping
  mappings/net/minecraft/world/gen/chunk/DebugChunkGenerator.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/ServerWorldProperties.mapping
  mappings/net/minecraft/world/level/UnmodifiableLevelProperties.mapping
Labels: new, refactor, snapshot

#1383 Registry key refactors + doc
  mappings/net/minecraft/util/registry/RegistryKey.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1364 BasicInventory -> SimpleInventory
  mappings/net/minecraft/inventory/SimpleInventory.mapping
Labels: ready to merge, refactor, snapshot

#1390 Standardize attribute modifier mappings
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/item/Item.mapping
Labels: ready to merge, refactor, snapshot

#1382 Dimension tracker
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/world/dimension/DimensionTracker.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: new, snapshot

#1391 Improve and add mappings related to soul speed
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: new, snapshot

#1387 20w21a brain
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/Brain.mapping
  mappings/net/minecraft/entity/ai/brain/Memory.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/Sensor.mapping
  mappings/net/minecraft/entity/mob/ZoglinEntity.mapping
Labels: new, snapshot

#1386 Spawn locating mappings
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/SpawnLocating.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: new, snapshot

#1393 Add Structure Mappings
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/DefaultFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
Labels: new, ready to merge, snapshot

#1389 HandledScreen parameters
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
Labels: new, ready to merge, snapshot

#1395 Update CompoundTag.mapping
  mappings/net/minecraft/nbt/CompoundTag.mapping
Labels: bug, javadoc, ready to merge, refactor, snapshot

#1398 DimensionType.createTracker -> addDefaults
  mappings/net/minecraft/world/dimension/DimensionType.mapping
Labels: bug, ready to merge, refactor, snapshot

#1399 Document scrolling parameters.
  mappings/net/minecraft/client/Mouse.mapping
Labels: javadoc, ready to merge, snapshot

#1401 Misc. Issue Resolution
  mappings/net/minecraft/client/gui/screen/options/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerAbilitiesS2CPacket.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicates.mapping
  mappings/net/minecraft/server/command/SpreadPlayersCommand.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/light/SkyLightStorage.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
Labels: bug, ready to merge, refactor, snapshot

#1400 Shorten inner class names on GameRules
  mappings/net/minecraft/world/GameRules.mapping
Labels: ready to merge, refactor, snapshot

#1404 New loot registries
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/loot/condition/LootCondition.mapping
  mappings/net/minecraft/loot/condition/LootConditionType.mapping
  mappings/net/minecraft/loot/condition/LootConditionTypes.mapping
  mappings/net/minecraft/loot/entry/LootEntries.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntry.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntryType.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntryTypes.mapping
  mappings/net/minecraft/loot/function/LootFunctionType.mapping
  mappings/net/minecraft/loot/function/LootFunctionTypes.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: new, ready to merge, refactor, snapshot

#1409 remove an invalid mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
Labels: bug, ready to merge, release

#1396 backport material name improvements
  mappings/net/minecraft/block/Material.mapping
Labels: javadoc, refactor, release

#1412 Map transparency shader fields and methods
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
Labels: new, ready to merge, snapshot

#1405 Map more 1.16 additions to default biome features
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
Labels: new, ready to merge, snapshot
