Repository FabricMC/yarn, pull requests merged in 2020-03, with the labels that each got.

#1143 20w09a all classes mapped
  mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
  mappings/net/minecraft/client/sound/AudioStream.mapping
  mappings/net/minecraft/client/sound/OggAudioStream.mapping
  mappings/net/minecraft/client/sound/RepeatingAudioStream.mapping
  mappings/net/minecraft/client/sound/SoundLoader.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/util/CubicSampler.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
Labels: new, ready to merge, snapshot

#1141 isCloseToTarget -> isNearTarget
  mappings/net/minecraft/entity/passive/DolphinEntity.mapping
Labels: ready to merge, refactor, snapshot

#1149 Restore GUI names from 20w09a
  mappings/net/minecraft/class_4892.mapping
  mappings/net/minecraft/client/gui/AbstractParentElement.mapping
  mappings/net/minecraft/client/gui/Drawable.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/AbstractButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/AbstractPressableButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/AlwaysSelectedEntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ListWidget.mapping
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
Labels: ready to merge, snapshot

#1152 some gui changes
  mappings/net/minecraft/class_4892.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/GameInfoChatListener.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/AbstractButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/DoubleOptionSliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ListWidget.mapping
  mappings/net/minecraft/client/gui/widget/OptionSliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
Labels: ready to merge, refactor, snapshot

#1151 Map Chunk loading, Chunks and Chunk Generation
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: new, ready to merge, snapshot

#1150 Add Back Some Projectile Mappings
  mappings/net/minecraft/entity/projectile/Projectile.mapping
Labels: new, ready to merge, snapshot

#1144 some piglin stuff + misc
  mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
  mappings/net/minecraft/block/SlimeBlock.mapping
  mappings/net/minecraft/client/render/entity/PiglinEntityRenderer.mapping
  mappings/net/minecraft/enchantment/Enchantments.mapping
  mappings/net/minecraft/entity/decoration/ItemFrameEntity.mapping
  mappings/net/minecraft/entity/mob/HoglinBrain.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/item/HoeItem.mapping
Labels: new, ready to merge, snapshot

#1118 named and commented various seeding methods
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/gen/ChunkRandom.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1157 bedrock floor/ceiling mappings
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorConfig.mapping
Labels: ready to merge, refactor, snapshot

#1138 Cape and Elytra mappings for PlayerEntity
  mappings/net/minecraft/block/SlimeBlock.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: new, ready to merge, snapshot

#1123 Suggest mappings
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/gen/chunk/OverworldChunkGeneratorConfig.mapping
Labels: new, ready to merge, snapshot

#1156 Document changed UUID serialization methods
  mappings/net/minecraft/nbt/CompoundTag.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
Labels: new, ready to merge, refactor, snapshot

#1148 Plant block, smithing table container, data gen, dfu, dynamic seriali…
  mappings/net/minecraft/block/AbstractPlantBlock.mapping
  mappings/net/minecraft/block/AbstractPlantPartBlock.mapping
  mappings/net/minecraft/block/AbstractPlantStemBlock.mapping
  mappings/net/minecraft/block/SmithingTableBlock.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmithingScreen.mapping
  mappings/net/minecraft/client/render/entity/model/CrossbowPosing.mapping
  mappings/net/minecraft/client/sound/BiomeEffectSoundPlayer.mapping
  mappings/net/minecraft/client/sound/MovingSoundInstance.mapping
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
  mappings/net/minecraft/data/client/BlockStateDefinitionProvider.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/BlockStateSupplier.mapping
  mappings/net/minecraft/data/client/model/BlockStateVariant.mapping
  mappings/net/minecraft/data/client/model/BlockStateVariantManager.mapping
  mappings/net/minecraft/data/client/model/Model.mapping
  mappings/net/minecraft/data/client/model/ModelIds.mapping
  mappings/net/minecraft/data/client/model/Models.mapping
  mappings/net/minecraft/data/client/model/MultipartBlockStateSupplier.mapping
  mappings/net/minecraft/data/client/model/Properties.mapping
  mappings/net/minecraft/data/client/model/PropertiesEntry.mapping
  mappings/net/minecraft/data/client/model/SimpleModelSupplier.mapping
  mappings/net/minecraft/data/client/model/Texture.mapping
  mappings/net/minecraft/data/client/model/TextureKey.mapping
  mappings/net/minecraft/data/client/model/TexturedModel.mapping
  mappings/net/minecraft/data/client/model/VariantSetting.mapping
  mappings/net/minecraft/data/client/model/VariantSettings.mapping
  mappings/net/minecraft/data/client/model/VariantsBlockStateSupplier.mapping
  mappings/net/minecraft/data/client/model/When.mapping
  mappings/net/minecraft/datafixer/fix/EntityProjectileOwnerFix.mapping
  mappings/net/minecraft/resource/ResourceReloadListener.mapping
  mappings/net/minecraft/screen/ForgingScreenHandler.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/sound/SoundCategory.mapping
  mappings/net/minecraft/util/DynamicSerializableBoolean.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
Labels: new, snapshot

#1159 FoliagePlacer mapping and doc, Tree mapping, and a lot of misc feature mapping
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/world/gen/feature/AbstractPileFeature.mapping
  mappings/net/minecraft/world/gen/feature/AbstractTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/BranchedTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/BranchedTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/EndGatewayFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/EndSpikeFeature.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/FlowerFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeature.mapping
  mappings/net/minecraft/world/gen/feature/LargeOakTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/MegaJungleTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/MegaPineTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/MegaTreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/MegaTreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RandomBooleanFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RandomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RandomFeatureEntry.mapping
  mappings/net/minecraft/world/gen/feature/RandomRandomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SimpleBlockFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SimpleRandomFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/SwampHutFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/VoidStartPlatformFeature.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
Labels: new, ready to merge, snapshot

#1160 Extend structures and structure pools mappings
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/pool/FeaturePoolElement.mapping
  mappings/net/minecraft/structure/pool/ListPoolElement.mapping
  mappings/net/minecraft/structure/pool/SinglePoolElement.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
  mappings/net/minecraft/structure/processor/StructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorRule.mapping
Labels: new, ready to merge, snapshot

#1161 getMiningSpeed -> getMiningSpeedMultiplier
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
Labels: ready to merge, refactor, snapshot

#1169 tiny works on model/blockstate data gen
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/BlockStateSupplier.mapping
  mappings/net/minecraft/data/client/model/BlockStateVariant.mapping
  mappings/net/minecraft/data/client/model/BlockStateVariantMap.mapping
  mappings/net/minecraft/data/client/model/PropertiesEntry.mapping
  mappings/net/minecraft/data/client/model/PropertiesMap.mapping
  mappings/net/minecraft/data/client/model/TexturedModel.mapping
  mappings/net/minecraft/data/client/model/VariantsBlockStateSupplier.mapping
Labels: new, refactor, snapshot

#1173 EnderCrystal -> EndCrystal, #1163 improvements
  mappings/net/minecraft/client/render/entity/EndCrystalEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EnderDragonEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/StuckObjectsFeatureRenderer.mapping
  mappings/net/minecraft/entity/decoration/EndCrystalEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: ready to merge, refactor, snapshot

#1166 Followup cleanups around screen handler change
  mappings/net/minecraft/block/AnvilBlock.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/CartographyTableBlock.mapping
  mappings/net/minecraft/block/CraftingTableBlock.mapping
  mappings/net/minecraft/block/GrindstoneBlock.mapping
  mappings/net/minecraft/block/LoomBlock.mapping
  mappings/net/minecraft/block/StonecutterBlock.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BlastFurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CraftingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantmentScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/FurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreens.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmokerScreen.mapping
  mappings/net/minecraft/screen/AbstractFurnaceScreenHandler.mapping
  mappings/net/minecraft/screen/AbstractRecipeScreenHandler.mapping
  mappings/net/minecraft/screen/AnvilScreenHandler.mapping
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/screen/BlastFurnaceScreenHandler.mapping
  mappings/net/minecraft/screen/BrewingStandScreenHandler.mapping
  mappings/net/minecraft/screen/CraftingScreenHandler.mapping
  mappings/net/minecraft/screen/CraftingTableScreenHandler.mapping
  mappings/net/minecraft/screen/EnchantmentScreenHandler.mapping
  mappings/net/minecraft/screen/FurnaceScreenHandler.mapping
  mappings/net/minecraft/screen/Generic3x3ContainerScreenHandler.mapping
  mappings/net/minecraft/screen/GenericContainerScreenHandler.mapping
  mappings/net/minecraft/screen/GrindstoneScreenHandler.mapping
  mappings/net/minecraft/screen/HopperScreenHandler.mapping
  mappings/net/minecraft/screen/HorseScreenHandler.mapping
  mappings/net/minecraft/screen/LecternScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/screen/NameableScreenHandlerFactory.mapping
  mappings/net/minecraft/screen/NamedScreenHandlerFactory.mapping
  mappings/net/minecraft/screen/PlayerScreenHandler.mapping
  mappings/net/minecraft/screen/Property.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerContext.mapping
  mappings/net/minecraft/screen/ScreenHandlerListener.mapping
  mappings/net/minecraft/screen/ShulkerBoxScreenHandler.mapping
  mappings/net/minecraft/screen/SmokerScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
  mappings/net/minecraft/screen/slot/CraftingResultSlot.mapping
  mappings/net/minecraft/screen/slot/FurnaceFuelSlot.mapping
  mappings/net/minecraft/screen/slot/FurnaceOutputSlot.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
Labels: ready to merge, refactor, snapshot

#1175 Map LevelGeneratorOptions
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/world/biome/source/BiomeSourceType.mapping
  mappings/net/minecraft/world/biome/source/VanillaLayeredBiomeSourceConfig.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorFactory.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorType.mapping
  mappings/net/minecraft/world/level/LevelGeneratorOptions.mapping
  mappings/net/minecraft/world/level/LevelGeneratorType.mapping
  mappings/net/minecraft/world/level/LevelInfo.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: new, ready to merge, refactor, snapshot

#1174 Enchantments, vines, particles 11a
  mappings/net/minecraft/block/AbstractPlantPartBlock.mapping
  mappings/net/minecraft/block/AbstractPlantStemBlock.mapping
  mappings/net/minecraft/block/TwistingVinesBlock.mapping
  mappings/net/minecraft/block/TwistingVinesPlantBlock.mapping
  mappings/net/minecraft/block/VineLogic.mapping
  mappings/net/minecraft/block/WeepingVinesPlantBlock.mapping
  mappings/net/minecraft/client/particle/AbstractSlowingParticle.mapping
  mappings/net/minecraft/client/particle/FlameParticle.mapping
  mappings/net/minecraft/client/particle/SoulParticle.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/SoulSpeedEnchantment.mapping
  mappings/net/minecraft/loot/function/EnchantRandomlyLootFunction.mapping
  mappings/net/minecraft/world/gen/feature/TwistingVinesFeature.mapping
  mappings/net/minecraft/world/gen/feature/WeepingVinesFeature.mapping
Labels: new, ready to merge, refactor, snapshot

#1184 Map the rest of CommandBlockExecutor
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
Labels: new, ready to merge, snapshot

#1188 Fix ItemStack mappings
  mappings/net/minecraft/item/ItemStack.mapping
Labels: refactor, snapshot

#1168 remove blit and javadoc i need comments
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1194 Improve InventoryS2CPacket's names
  mappings/net/minecraft/network/packet/s2c/play/InventoryS2CPacket.mapping
Labels: refactor, snapshot

#1196 Fix client/server being swapped in InventoryS2CPacket's docs
  mappings/net/minecraft/network/packet/s2c/play/InventoryS2CPacket.mapping
Labels: bug, javadoc, snapshot

#1177 BlockPos mappings
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
Labels: new, ready to merge, refactor, snapshot

#1179 Map some more DataFixer code.
  mappings/net/minecraft/datafixer/NbtOps.mapping
  mappings/net/minecraft/datafixer/fix/AdvancementRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/BeehiveRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/BiomeFormatFix.mapping
  mappings/net/minecraft/datafixer/fix/BiomeRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityCustomNameToTextFix.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceFix.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceTypesFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityCustomNameToTextFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityProjectileOwnerFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityRidingToPassengerFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityShulkerColorFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityZombifiedPiglinRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemLoreToTextFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemNameFix.mapping
  mappings/net/minecraft/datafixer/fix/LeavesFix.mapping
  mappings/net/minecraft/datafixer/fix/MemoryExpiryDataFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/RecipeRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/SwimStatsRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerProfessionFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerXpRebuildFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema100.mapping
  mappings/net/minecraft/datafixer/schema/Schema102.mapping
  mappings/net/minecraft/datafixer/schema/Schema1022.mapping
  mappings/net/minecraft/datafixer/schema/Schema106.mapping
  mappings/net/minecraft/datafixer/schema/Schema107.mapping
  mappings/net/minecraft/datafixer/schema/Schema1125.mapping
  mappings/net/minecraft/datafixer/schema/Schema135.mapping
  mappings/net/minecraft/datafixer/schema/Schema143.mapping
  mappings/net/minecraft/datafixer/schema/Schema1451v1.mapping
  mappings/net/minecraft/datafixer/schema/Schema1451v4.mapping
  mappings/net/minecraft/datafixer/schema/Schema1451v6.mapping
  mappings/net/minecraft/datafixer/schema/Schema1451v7.mapping
  mappings/net/minecraft/datafixer/schema/Schema1460.mapping
  mappings/net/minecraft/datafixer/schema/Schema1466.mapping
  mappings/net/minecraft/datafixer/schema/Schema2501.mapping
  mappings/net/minecraft/datafixer/schema/Schema501.mapping
  mappings/net/minecraft/datafixer/schema/Schema700.mapping
  mappings/net/minecraft/datafixer/schema/Schema701.mapping
  mappings/net/minecraft/datafixer/schema/Schema702.mapping
  mappings/net/minecraft/datafixer/schema/Schema703.mapping
  mappings/net/minecraft/datafixer/schema/Schema704.mapping
  mappings/net/minecraft/datafixer/schema/Schema705.mapping
  mappings/net/minecraft/datafixer/schema/Schema99.mapping
Labels: new, ready to merge, snapshot

#1180 Pathfinding improvements
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BlockPlacementEnvironment.mapping
  mappings/net/minecraft/block/BlockState.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/pathing/AmphibiousPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/BirdPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/LandPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/NavigationType.mapping
  mappings/net/minecraft/entity/ai/pathing/PathMinHeap.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeType.mapping
  mappings/net/minecraft/entity/ai/pathing/SpiderNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/SwimNavigation.mapping
  mappings/net/minecraft/entity/ai/pathing/WaterPathNodeMaker.mapping
Labels: new, ready to merge, refactor, snapshot

#1183 Some parameter names and corrections
  mappings/net/minecraft/server/BanEntry.mapping
  mappings/net/minecraft/server/BannedIpEntry.mapping
  mappings/net/minecraft/server/BannedPlayerEntry.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/OperatorEntry.mapping
  mappings/net/minecraft/server/OperatorList.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/ServerConfigEntry.mapping
  mappings/net/minecraft/server/ServerConfigHandler.mapping
  mappings/net/minecraft/server/ServerConfigList.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/WhitelistEntry.mapping
  mappings/net/minecraft/server/dedicated/AbstractPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/DedicatedPlayerManager.mapping
  mappings/net/minecraft/server/dedicated/DedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
Labels: new, ready to merge, refactor, snapshot

#1182 InfoEnchantment -> EnchantmentLevelEntry (extends WeightedPicker.Entry)
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/EnchantmentLevelEntry.mapping
  mappings/net/minecraft/enchantment/InfoEnchantment.mapping
  mappings/net/minecraft/item/EnchantedBookItem.mapping
  mappings/net/minecraft/screen/EnchantmentScreenHandler.mapping
  mappings/net/minecraft/util/WeightedPicker.mapping
Labels: javadoc, ready to merge, refactor, snapshot, vote

#1171 Moved a lot of "util" classes to more appropriate packages
  mappings/net/minecraft/loot/operator/BoundedIntUnaryOperator.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/util/DebugPrintStreamLogger.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/IndexedIterable.mapping
  mappings/net/minecraft/util/LowercaseMap.mapping
  mappings/net/minecraft/util/UncaughtExceptionHandler.mapping
  mappings/net/minecraft/util/UncaughtExceptionLogger.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/collection/DefaultedList.mapping
  mappings/net/minecraft/util/collection/IdList.mapping
  mappings/net/minecraft/util/collection/IndexedIterable.mapping
  mappings/net/minecraft/util/collection/Int2ObjectBiMap.mapping
  mappings/net/minecraft/util/collection/LowercaseMap.mapping
  mappings/net/minecraft/util/collection/MapUtil.mapping
  mappings/net/minecraft/util/collection/PackedIntegerArray.mapping
  mappings/net/minecraft/util/collection/ReusableStream.mapping
  mappings/net/minecraft/util/collection/SortedArraySet.mapping
  mappings/net/minecraft/util/collection/TypeFilterableList.mapping
  mappings/net/minecraft/util/collection/WeightedList.mapping
  mappings/net/minecraft/util/collection/WeightedPicker.mapping
  mappings/net/minecraft/util/dynamic/DynamicDeserializer.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializable.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableBoolean.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableUuid.mapping
  mappings/net/minecraft/util/dynamic/Timestamp.mapping
  mappings/net/minecraft/util/function/BooleanBiFunction.mapping
  mappings/net/minecraft/util/function/MaterialPredicate.mapping
  mappings/net/minecraft/util/logging/DebugPrintStreamLogger.mapping
  mappings/net/minecraft/util/logging/PrintStreamLogger.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionHandler.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionLogger.mapping
  mappings/net/minecraft/util/profiler/CsvWriter.mapping
  mappings/net/minecraft/util/profiler/TickTimeTracker.mapping
  mappings/net/minecraft/util/shape/OffsetDoubleList.mapping
  mappings/net/minecraft/world/SectionDistanceLevelPropagator.mapping
Labels: ready to merge, refactor, snapshot

#1204 RespawnAnchorBlock & related respawn stuff
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: new, snapshot

#1203 Map methods in AbstractBlock and subclasses
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: new, ready to merge, snapshot

#1200 Quick entity fixes
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/SlimeEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
Labels: bug, ready to merge, snapshot

#1198 Slot documentation stuff
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClickWindowC2SPacket.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/slot/SlotActionType.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1199 Sorted out the projectile mess
  mappings/net/minecraft/entity/EyeOfEnderEntity.mapping
  mappings/net/minecraft/entity/FishingBobberEntity.mapping
  mappings/net/minecraft/entity/ShulkerBulletEntity.mapping
  mappings/net/minecraft/entity/projectile/FireworkRocketEntity.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/Projectile.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/entity/projectile/TridentEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EggEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EnderPearlEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/ExperienceBottleEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/SnowballEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/ThrownEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/ThrownItemEntity.mapping
Labels: ready to merge, refactor, snapshot

#1201 A few uuid fixes mapped
  mappings/net/minecraft/datafixer/fix/AbstractUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/PlayerUuidFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldUuidFix.mapping
Labels: new, ready to merge, snapshot

#1170 Realms mappings
  mappings/com/mojang/realmsclient/KeyCombo.mapping
  mappings/com/mojang/realmsclient/RealmsMainScreen.mapping
  mappings/com/mojang/realmsclient/client/FileDownload.mapping
  mappings/com/mojang/realmsclient/client/FileUpload.mapping
  mappings/com/mojang/realmsclient/client/RealmsClient.mapping
  mappings/com/mojang/realmsclient/dto/RealmsServer.mapping
  mappings/com/mojang/realmsclient/dto/RealmsWorldOptions.mapping
  mappings/com/mojang/realmsclient/dto/RegionPingResult.mapping
  mappings/com/mojang/realmsclient/dto/ValueObject.mapping
  mappings/com/mojang/realmsclient/dto/WorldTemplate.mapping
  mappings/com/mojang/realmsclient/gui/RealmsWorldSlotButton.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsConfigureWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsLongRunningMcoTaskScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsPlayerScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsResetWorldScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsScreenWithCallback.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsSelectWorldTemplateScreen.mapping
  mappings/com/mojang/realmsclient/gui/screens/RealmsSlotOptionsScreen.mapping
  mappings/net/minecraft/realms/CheckedGson.mapping
  mappings/net/minecraft/realms/Realms.mapping
  mappings/net/minecraft/realms/RealmsBridge.mapping
  mappings/net/minecraft/realms/RealmsObjectSelectionList.mapping
Labels: new, ready to merge, snapshot

#1202 New sound stuff, fish hook predicate, missed persistent state uuid fix
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/sound/BiomeEffectSoundPlayer.mapping
  mappings/net/minecraft/datafixer/fix/PersistentStateUuidFix.mapping
  mappings/net/minecraft/entity/FishingBobberEntity.mapping
  mappings/net/minecraft/predicate/entity/DistancePredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityEffectPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityEquipmentPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityFlagsPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/FishingHookPredicate.mapping
  mappings/net/minecraft/sound/BiomeAdditionsSound.mapping
  mappings/net/minecraft/sound/BiomeMoodSound.mapping
Labels: new, ready to merge, refactor, snapshot

#1207 Map class 4966 and associated chunk generator stuff
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/VerticalBlockSample.mapping
Labels: new, ready to merge, refactor, snapshot

#1206 Map reverse portal particle
  mappings/net/minecraft/client/particle/AshParticle.mapping
  mappings/net/minecraft/client/particle/BlockDustParticle.mapping
  mappings/net/minecraft/client/particle/BlockFallingDustParticle.mapping
  mappings/net/minecraft/client/particle/BubbleColumnUpParticle.mapping
  mappings/net/minecraft/client/particle/BubblePopParticle.mapping
  mappings/net/minecraft/client/particle/CampfireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/CloudParticle.mapping
  mappings/net/minecraft/client/particle/CrackParticle.mapping
  mappings/net/minecraft/client/particle/CurrentDownParticle.mapping
  mappings/net/minecraft/client/particle/DamageParticle.mapping
  mappings/net/minecraft/client/particle/DragonBreathParticle.mapping
  mappings/net/minecraft/client/particle/ElderGuardianAppearanceParticle.mapping
  mappings/net/minecraft/client/particle/EmotionParticle.mapping
  mappings/net/minecraft/client/particle/EnchantGlyphParticle.mapping
  mappings/net/minecraft/client/particle/EndRodParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionLargeParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionSmokeParticle.mapping
  mappings/net/minecraft/client/particle/FireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/client/particle/FishingParticle.mapping
  mappings/net/minecraft/client/particle/ItemPickupParticle.mapping
  mappings/net/minecraft/client/particle/LargeFireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/LavaEmberParticle.mapping
  mappings/net/minecraft/client/particle/NoteParticle.mapping
  mappings/net/minecraft/client/particle/PortalParticle.mapping
  mappings/net/minecraft/client/particle/RainSplashParticle.mapping
  mappings/net/minecraft/client/particle/RedDustParticle.mapping
  mappings/net/minecraft/client/particle/ReversePortalParticle.mapping
  mappings/net/minecraft/client/particle/SpellParticle.mapping
  mappings/net/minecraft/client/particle/SpitParticle.mapping
  mappings/net/minecraft/client/particle/SquidInkParticle.mapping
  mappings/net/minecraft/client/particle/SuspendParticle.mapping
  mappings/net/minecraft/client/particle/SweepAttackParticle.mapping
  mappings/net/minecraft/client/particle/TotemParticle.mapping
  mappings/net/minecraft/client/particle/WaterBubbleParticle.mapping
  mappings/net/minecraft/client/particle/WaterSplashParticle.mapping
  mappings/net/minecraft/client/particle/WaterSuspendParticle.mapping
Labels: new, ready to merge, snapshot

#1210 @returns -> @return
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
Labels: javadoc, ready to merge, snapshot

#1186 Mappings relating to code that uses CsvWriter
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedQuad.mapping
  mappings/net/minecraft/server/world/ChunkTaskPrioritySystem.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerTickScheduler.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/world/BlockRenderView.mapping
Labels: new, ready to merge, snapshot

#1208 Fully map out block state model generator
  mappings/net/minecraft/data/DataProvider.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/BlockStateVariant.mapping
  mappings/net/minecraft/data/client/model/Model.mapping
  mappings/net/minecraft/data/client/model/Texture.mapping
  mappings/net/minecraft/data/client/model/VariantsBlockStateSupplier.mapping
  mappings/net/minecraft/item/Items.mapping
Labels: new, ready to merge, snapshot

#1212 Update Enigma
  build.gradle
Labels: snapshot, toolchain

#1214 Javadoc to describe the block/fluid state properties Minecraft provides
  mappings/net/minecraft/state/property/DirectionProperty.mapping
  mappings/net/minecraft/state/property/EnumProperty.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: javadoc, ready to merge, snapshot

#1220 Fix PositionedSoundInstance's swapped parameter names
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
Labels: bug, ready to merge, refactor, snapshot

#1213 EntityContext -> ShapeContext, EntityContextImpl -> EntityShapeContext
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/ShapeContext.mapping
Labels: refactor, snapshot

#1223 Some block mappings
  mappings/net/minecraft/block/BellBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/PistonBlock.mapping
  mappings/net/minecraft/block/TorchBlock.mapping
  mappings/net/minecraft/block/WallRedstoneTorchBlock.mapping
  mappings/net/minecraft/block/dispenser/BoatDispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/ProjectileDispenserBehavior.mapping
Labels: new, snapshot

#1226 Minor dfu stuff
  mappings/net/minecraft/datafixer/fix/JigsawPropertiesFix.mapping
  mappings/net/minecraft/datafixer/fix/JigsawRotationFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerGossipFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema2519.mapping
Labels: new, ready to merge, snapshot

#1229 Map two new farmer tasks
  mappings/net/minecraft/block/ComposterBlock.mapping
  mappings/net/minecraft/entity/ai/brain/task/BoneMealTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/FarmerWorkTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/VillagerWorkTask.mapping
Labels: new, ready to merge, snapshot

#1219 Javadoc for some client, datafixer and other miscellaneous areas.
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/OtherClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/command/arguments/ArgumentTypes.mapping
  mappings/net/minecraft/command/arguments/TestClassArgumentType.mapping
  mappings/net/minecraft/command/arguments/serialize/ArgumentSerializer.mapping
  mappings/net/minecraft/command/suggestion/SuggestionProviders.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/server/command/CommandOutput.mapping
  mappings/net/minecraft/util/Clearable.mapping
Labels: javadoc, ready to merge, snapshot

#1228 Map two missing inner classes
  mappings/net/minecraft/entity/FishingBobberEntity.mapping
  mappings/net/minecraft/server/world/SimpleTickScheduler.mapping
  mappings/net/minecraft/util/hit/HitResult.mapping
Labels: new, ready to merge, snapshot

#1225 Strider entity mappings
  mappings/net/minecraft/class_4981.mapping
  mappings/net/minecraft/client/render/entity/StriderEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/StriderEntityModel.mapping
  mappings/net/minecraft/entity/ItemSteerable.mapping
  mappings/net/minecraft/entity/SaddledComponent.mapping
  mappings/net/minecraft/entity/passive/PigEntity.mapping
  mappings/net/minecraft/entity/passive/StriderEntity.mapping
  mappings/net/minecraft/item/CarrotOnAStickItem.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/OnAStickItem.mapping
Labels: new, ready to merge, snapshot

#1227 Jigsaw and rotation/rule test stuff
  mappings/net/minecraft/block/JigsawBlock.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/block/enums/JigsawOrientation.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/render/model/ModelRotation.mapping
  mappings/net/minecraft/client/util/math/Matrix3f.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorRule.mapping
  mappings/net/minecraft/structure/rule/AlwaysTruePosRuleTest.mapping
  mappings/net/minecraft/structure/rule/AxisAlignedLinearPosRuleTest.mapping
  mappings/net/minecraft/structure/rule/LinearPosRuleTest.mapping
  mappings/net/minecraft/structure/rule/PosRuleTest.mapping
  mappings/net/minecraft/structure/rule/PosRuleTestType.mapping
  mappings/net/minecraft/util/AxisTransformation.mapping
  mappings/net/minecraft/util/DirectionTransformation.mapping
  mappings/net/minecraft/util/math/Direction.mapping
Labels: new, snapshot

#1222 Add CONTRIBUTING.md, mention mojmap being ARR
  CONTRIBUTING.md
  CONVENTIONS.md
  README.md
Labels: enhancement

#988 Renderer mappings
  mappings/net/minecraft/client/model/Model.mapping
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/particle/ItemPickupParticle.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/ChestBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EnderDragonEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/StuckObjectsFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/BookModel.mapping
  mappings/net/minecraft/client/render/entity/model/PlayerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SkullEntityModel.mapping
  mappings/net/minecraft/client/render/item/BuiltinModelItemRenderer.mapping
Labels: new, ready to merge, refactor, snapshot

#1235 Move direction transformation and matrix3f to util math (need same package)
  mappings/net/minecraft/util/BlockMirror.mapping
  mappings/net/minecraft/util/BlockRotation.mapping
  mappings/net/minecraft/util/Language.mapping
  mappings/net/minecraft/util/dynamic/GlobalPos.mapping
  mappings/net/minecraft/util/math/AxisTransformation.mapping
  mappings/net/minecraft/util/math/DirectionTransformation.mapping
  mappings/net/minecraft/util/math/Matrix3f.mapping
  mappings/net/minecraft/util/math/Matrix4f.mapping
  mappings/net/minecraft/world/ChunkPosDistanceLevelPropagator.mapping
Labels: bug, ready to merge, refactor, snapshot

#1154 Remap inventories :D
  mappings/net/minecraft/inventory/BasicInventory.mapping
  mappings/net/minecraft/inventory/CraftingResultInventory.mapping
  mappings/net/minecraft/inventory/EnderChestInventory.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/InventoryChangedListener.mapping
  mappings/net/minecraft/inventory/InventoryListener.mapping
  mappings/net/minecraft/inventory/SidedInventory.mapping
  mappings/net/minecraft/util/Clearable.mapping
Labels: ready to merge, refactor, snapshot

#1238 Fixed Item spelling in register method
  mappings/net/minecraft/item/Items.mapping
Labels: bug, ready to merge, refactor, snapshot

#1242 Fix 2 incorrect names
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/client/sound/SoundInstanceListener.mapping
Labels: bug, refactor, snapshot

#1243 Fix two more errors with Criterions instead of Criteria
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
Labels: bug, ready to merge, refactor, snapshot
