Repository FabricMC/yarn, pull requests merged in 2020-11, with the labels that each got.

#1820 Add mappings for option screens
  mappings/net/minecraft/client/gui/screen/options/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/screen/options/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/LanguageOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/NarratorOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/options/SoundOptionsScreen.mapping
Labels: new, outdated, ready to merge, snapshot

#1821 Add mappings for RealmsClient and related classes
  mappings/net/minecraft/client/network/SocialInteractionsManager.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/RealmsError.mapping
  mappings/net/minecraft/client/realms/dto/UploadInfo.mapping
  mappings/net/minecraft/client/realms/exception/RetryCallException.mapping
Labels: new, outdated, ready to merge, snapshot

#1823 Update ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
Labels: new, ready to merge

#1801 Some Screen and ParentElement javadoc
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
Labels: javadoc, ready to merge

#1793 Map some sky properties
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
  mappings/net/minecraft/client/render/SkyProperties.mapping
Labels: javadoc, ready to merge, refactor

#1708 Update World.mapping
  mappings/net/minecraft/world/World.mapping
Labels: new, ready to merge, refactor, snapshot

#1811 Improve SuffixArray
  mappings/net/minecraft/client/search/SuffixArray.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1809 Chat filtering mappings
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/filter/TextStream.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, ready to merge, snapshot

#1831 Some 20w45a items
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/SpyglassItem.mapping
Labels: new, snapshot

#1832 Misc 20w45a things
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/fix/CauldronRenameFix.mapping
  mappings/net/minecraft/loot/function/SetBannerPatternFunction.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
Labels: javadoc, new, snapshot

#1830 Some 20w45a blocks
  mappings/net/minecraft/block/AbstractCauldronBlock.mapping
  mappings/net/minecraft/block/CauldronBlock.mapping
  mappings/net/minecraft/block/CopperBlock.mapping
  mappings/net/minecraft/block/CopperSlabBlock.mapping
  mappings/net/minecraft/block/CopperStairsBlock.mapping
  mappings/net/minecraft/block/EndRodBlock.mapping
  mappings/net/minecraft/block/LavaCauldronBlock.mapping
  mappings/net/minecraft/block/LightningRodBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/block/RodBlock.mapping
  mappings/net/minecraft/block/TintedGlassBlock.mapping
  mappings/net/minecraft/block/WaterCauldronBlock.mapping
Labels: new, snapshot

#1829 Add entity mappings
  mappings/net/minecraft/class_5568.mapping
  mappings/net/minecraft/client/render/entity/PiglinEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayer.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: javadoc, new, snapshot

#1834 Map spyglass logic
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: new, snapshot

#1845 Initial entity management mappings
  mappings/net/minecraft/class_5569.mapping
  mappings/net/minecraft/class_5570.mapping
  mappings/net/minecraft/class_5579.mapping
  mappings/net/minecraft/class_5582.mapping
  mappings/net/minecraft/class_5584.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/EntityList.mapping
  mappings/net/minecraft/world/EntityLoader.mapping
Labels: javadoc, new, ready to merge, snapshot

#1847 Geode and geode generation mappings
  mappings/net/minecraft/class_5588.mapping
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/GeodeCrackConfig.mapping
  mappings/net/minecraft/world/gen/feature/GeodeFeature.mapping
  mappings/net/minecraft/world/gen/feature/GeodeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/GeodeLayerConfig.mapping
  mappings/net/minecraft/world/gen/feature/GeodeLayerThicknessConfig.mapping
Labels: new, ready to merge, snapshot

#1397 MaterialColor -> MapColor
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/MapColor.mapping
  mappings/net/minecraft/util/DyeColor.mapping
Labels: javadoc, refactor, snapshot

#1846 Almost completed social interactions
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/network/SocialInteractionsManager.mapping
Labels: new, ready to merge, snapshot

#1842 Resource mappings.
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/DefaultClientResourcePack.mapping
  mappings/net/minecraft/client/resource/SplashTextResourceSupplier.mapping
  mappings/net/minecraft/client/resource/language/I18n.mapping
  mappings/net/minecraft/client/resource/language/LanguageManager.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationResourceMetadata.mapping
  mappings/net/minecraft/client/resource/metadata/LanguageResourceMetadata.mapping
  mappings/net/minecraft/client/resource/metadata/TextureResourceMetadata.mapping
  mappings/net/minecraft/resource/ReloadableResourceManagerImpl.mapping
  mappings/net/minecraft/resource/ResourcePackCompatibility.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/ResourcePackSource.mapping
  mappings/net/minecraft/resource/ResourceType.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
  mappings/net/minecraft/resource/VanillaDataPackProvider.mapping
Labels: new, ready to merge, snapshot

#1836 BlockEntity tick and creation
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/BlockEntityProvider.mapping
  mappings/net/minecraft/block/BlockWithEntity.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/DaylightDetectorBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityTicker.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/block/entity/BrewingStandBlockEntity.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChestBlockEntity.mapping
  mappings/net/minecraft/block/entity/ConduitBlockEntity.mapping
  mappings/net/minecraft/block/entity/EnchantingTableBlockEntity.mapping
  mappings/net/minecraft/block/entity/EndGatewayBlockEntity.mapping
  mappings/net/minecraft/block/entity/EnderChestBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/MobSpawnerBlockEntity.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/entity/ShulkerBoxBlockEntity.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/BlockEntityTickInvoker.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: new, ready to merge, snapshot

#1833 20w45a things
  mappings/net/minecraft/MinecraftVersion.mapping
  mappings/net/minecraft/block/AbstractCauldronBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/CauldronBlock.mapping
  mappings/net/minecraft/block/CopperBlock.mapping
  mappings/net/minecraft/block/CopperSlabBlock.mapping
  mappings/net/minecraft/block/CopperStairsBlock.mapping
  mappings/net/minecraft/block/MapColor.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/block/WaterCauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactories.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactory.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityModel.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderers.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ItemUsage.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/nbt/visitor/StringNbtWriter.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
Labels: javadoc, new, snapshot

#1841 Add mappings for classes related to server resource packs
  mappings/net/minecraft/network/packet/c2s/play/ResourcePackStatusC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ResourcePackSendS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, snapshot

#1843 Bundle related methods
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/util/ClickType.mapping
Labels: new, ready to merge, snapshot

#1858 Fix Entity#MAX_ENTITY_ID to Entity#ENTITY_ID_COUNTER(#1825)
  mappings/net/minecraft/entity/Entity.mapping
Labels: bug, ready to merge, refactor

#1856 Add mappings for InGameHud and related classes
  mappings/net/minecraft/client/font/TextVisitFactory.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
Labels: new

#1855 Complete WorldUpdator
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: new

#1812 Some EntryListWidget and entity methods and javadocs
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: javadoc, new

#1827 Add mappings for MoreOptionsDialog and related classes
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, refactor, release

#1860 Add LivingEntity shouldSwimInFluids
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: new, ready to merge, snapshot

#1848 Block Entity renderer factories and dirt path datafixer
  mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactory.mapping
  mappings/net/minecraft/datafixer/fix/DirtPathRenameFix.mapping
Labels: new, ready to merge, snapshot

#1838 Map chest state managers.
  mappings/net/minecraft/block/entity/BarrelBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityTicker.mapping
  mappings/net/minecraft/block/entity/ChestBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChestLidAnimator.mapping
  mappings/net/minecraft/block/entity/ChestStateManager.mapping
  mappings/net/minecraft/block/entity/EnderChestBlockEntity.mapping
Labels: javadoc, new, ready to merge, snapshot

#1859 Amethyst blocks & block sound groups
  mappings/net/minecraft/block/AmethystBlock.mapping
  mappings/net/minecraft/block/AmethystClusterBlock.mapping
  mappings/net/minecraft/block/BuddingAmethystBlock.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
Labels: new

#1862 Misc things
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/util/StringIdentifiable.mapping
  mappings/net/minecraft/util/collection/WeightedList.mapping
  mappings/net/minecraft/util/math/Matrix4f.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/biome/SpawnSettings.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
Labels: new, ready to merge, refactor

#1844 Map classes relating to candles
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractCandleBlock.mapping
  mappings/net/minecraft/block/CakeBlock.mapping
  mappings/net/minecraft/block/CandleBlock.mapping
  mappings/net/minecraft/block/CandleCakeBlock.mapping
  mappings/net/minecraft/block/SeaPickleBlock.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: new, ready to merge, snapshot

#1864 Map the candles property in the Properties class
  mappings/net/minecraft/state/property/Properties.mapping
Labels: new, snapshot

#1869 46a things
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/class_5658.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/loot/ConstantLootTableRange.mapping
  mappings/net/minecraft/loot/provider/nbt/ContextLootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProviderType.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProviderTypes.mapping
  mappings/net/minecraft/loot/provider/nbt/StorageLootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/number/BinomialLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/ConstantLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/LootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/LootNumberProviderType.mapping
  mappings/net/minecraft/loot/provider/number/LootNumberProviderTypes.mapping
  mappings/net/minecraft/loot/provider/number/ScoreLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/UniformLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/score/ContextLootScoreProvider.mapping
  mappings/net/minecraft/loot/provider/score/FixedLootScoreProvider.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProvider.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProviderType.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProviderTypes.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: new

#1866 20w46a item command
  mappings/net/minecraft/command/argument/ArgumentTypes.mapping
  mappings/net/minecraft/command/argument/IdentifierArgumentType.mapping
  mappings/net/minecraft/server/command/ItemCommand.mapping
Labels: new

#1868 20w46a new particle
  mappings/net/minecraft/client/particle/FlameParticle.mapping
  mappings/net/minecraft/client/particle/SnowflakeParticle.mapping
Labels: new

#1871 Update InGameHud
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
Labels: new, refactor, snapshot

#1867 20w46a loot stuff
  mappings/net/minecraft/loot/condition/ValueCheckLootCondition.mapping
  mappings/net/minecraft/loot/function/LootFunctionManager.mapping
  mappings/net/minecraft/loot/function/SetEnchantmentsLootFunction.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: new

#1766 couple of SplashScreen names
  mappings/net/minecraft/client/gui/screen/SplashScreen.mapping
Labels: new, outdated

#1747 Map the remaining static Text fields
  mappings/net/minecraft/client/gui/hud/spectator/RootSpectatorCommandGroup.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenu.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeamTeleportSpectatorMenu.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeleportSpectatorMenu.mapping
  mappings/net/minecraft/client/gui/screen/AddServerScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/DirectConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/DownloadingTerrainScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/OpenToLanScreen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractCommandBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AnvilScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/options/LanguageOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AnimatedResultButton.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/BlastFurnaceRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/FurnaceRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/SmokerRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsClientOutdatedScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateRealmScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsInviteScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsParentalConsentScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPendingInvitesScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetNormalWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSettingsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSubscriptionInfoScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsTermsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/toast/RecipeToast.mapping
  mappings/net/minecraft/client/util/ChatMessages.mapping
  mappings/net/minecraft/potion/PotionUtil.mapping
Labels: new, release

#1875 Fix params in RealmsSlotOptionsScreen
  mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
Labels: bug

#1872 Add mappings for option stuff
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/options/CyclingOption.mapping
  mappings/net/minecraft/client/options/DoubleOption.mapping
  mappings/net/minecraft/client/options/GameOptions.mapping
  mappings/net/minecraft/client/options/Option.mapping
Labels: new, snapshot

#1881 Map StatType.name
  mappings/net/minecraft/stat/StatType.mapping
Labels: new, ready to merge, snapshot

#1837 Map NBT tag visitors.
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/Tag.mapping
  mappings/net/minecraft/nbt/visitor/NbtOrderedStringFormatter.mapping
  mappings/net/minecraft/nbt/visitor/NbtTagVisitor.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/nbt/visitor/StringNbtWriter.mapping
Labels: javadoc, new, ready to merge, snapshot

#1880 Scoreboard mappings
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/scoreboard/AbstractTeam.mapping
  mappings/net/minecraft/scoreboard/ScoreboardCriterion.mapping
  mappings/net/minecraft/scoreboard/ScoreboardObjective.mapping
  mappings/net/minecraft/scoreboard/ScoreboardPlayerScore.mapping
  mappings/net/minecraft/scoreboard/ScoreboardState.mapping
  mappings/net/minecraft/scoreboard/Team.mapping
Labels: javadoc, new, ready to merge, refactor, snapshot

#1865 Map classes and methods relating to powder snow and freezing
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/CauldronBlock.mapping
  mappings/net/minecraft/block/FluidDrainable.mapping
  mappings/net/minecraft/block/LeveledCauldronBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/PowderSnowBlock.mapping
  mappings/net/minecraft/block/WaterCauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/item/FluidModificationItem.mapping
  mappings/net/minecraft/item/PowderSnowBucketItem.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
Labels: new, snapshot

#1882 Added GameModeSelection and CameraSubmersionEnvironment
  mappings/net/minecraft/client/gui/screen/world/GameModeSelection.mapping
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/client/render/CameraSubmersionType.mapping
Labels: new, ready to merge, snapshot

#1885 Complete DoorBlock
  mappings/net/minecraft/block/DoorBlock.mapping
Labels: new, ready to merge, snapshot

#1743 Suggest using Block#asItem instead of Item.fromBlock
  mappings/net/minecraft/item/Item.mapping
Labels: javadoc, ready to merge, snapshot

#1884 Fix javadoc warnings
  mappings/net/minecraft/client/font/TextVisitFactory.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/world/GameModeSelection.mapping
  mappings/net/minecraft/client/model/TextureDimensions.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDeltaUpdateS2CPacket.mapping
  mappings/net/minecraft/particle/ParticleType.mapping
  mappings/net/minecraft/text/StringVisitable.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/util/dynamic/RegistryReadingOps.mapping
  mappings/net/minecraft/world/EntityView.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
Labels: bug, javadoc, ready to merge

#1878 Some text renderer javadoc
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
Labels: javadoc, ready to merge

#1874 TooltipComponent related mappings
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/OrderedTextTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipComponent.mapping
  mappings/net/minecraft/client/item/BundleTooltipData.mapping
  mappings/net/minecraft/client/item/TooltipData.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: new, ready to merge, snapshot

#1896 Rename TooltipComponent factory methods to of
  mappings/net/minecraft/client/gui/tooltip/TooltipComponent.mapping
Labels: refactor, snapshot

#1895 Map tooltip rendering methods
  mappings/net/minecraft/client/gui/screen/Screen.mapping
Labels: new, ready to merge, snapshot

#1891 Dripstones
  mappings/net/minecraft/block/LandingBlock.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/enums/Thickness.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: new, ready to merge, snapshot

#1879 client.util.math.Vector3f -> util.math.Vec3f
  gradle.properties
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/potion/PotionUtil.mapping
  mappings/net/minecraft/util/math/Vec2f.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/util/math/Vec3f.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
Labels: bug, ready to merge, refactor

#1893 Map something for experience orb
  mappings/net/minecraft/entity/ExperienceOrbEntity.mapping
  mappings/net/minecraft/util/math/Box.mapping
Labels: new, ready to merge

#1888 Some client mappings
  mappings/net/minecraft/client/ClientGameSession.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/SpriteAtlasManager.mapping
  mappings/net/minecraft/client/sound/AmbientSoundLoops.mapping
  mappings/net/minecraft/client/sound/AmbientSoundPlayer.mapping
  mappings/net/minecraft/client/sound/Channel.mapping
  mappings/net/minecraft/client/sound/EntityTrackingSoundInstance.mapping
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
Labels: bug, new, ready to merge, refactor
