Repository FabricMC/yarn, pull requests merged in 2021-06, with the labels that each got.

#2437 Fix Entity.dealDamage
  mappings/net/minecraft/entity/Entity.mapping
Labels: bug, snapshot

#2441 status effect source
  mappings/net/minecraft/advancement/criterion/EffectsChangedCriterion.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
Labels: new, refactor, snapshot

#2451 Map two new classes used in profiler
  mappings/net/minecraft/util/SystemDetails.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/profiler/ZipCompressor.mapping
Labels: new, ready to merge, snapshot

#2450 Map InGameHud and its inner class
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
Labels: new, snapshot

#2456 Screenshooter -> ScreenshotRecorder
  mappings/net/minecraft/client/util/ScreenshotRecorder.mapping
Labels: bug, enhancement, refactor

#2458 Name remaining world event
  mappings/net/minecraft/world/WorldEvents.mapping
  unpick-definitions/world_events.unpick
Labels: new, snapshot, unpick

#2433 Some function stuff
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
Labels: javadoc, new, refactor, snapshot

#2436 1.17-pre1 stuff
  mappings/net/minecraft/advancement/criterion/LightningStrikeCriterion.mapping
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/entity/LightningEntity.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeNavigator.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/LightningBoltPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/command/PerfCommand.mapping
  mappings/net/minecraft/world/gen/feature/GeodeLayerConfig.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeatureConfig.mapping
Labels: new, snapshot

#2460 Map /perf command
  mappings/net/minecraft/server/dedicated/command/PerfCommand.mapping
Labels: new, ready to merge, snapshot

#2464 Map getLuminanceSupplier methods
  mappings/net/minecraft/block/CaveVines.mapping
  mappings/net/minecraft/block/GlowLichenBlock.mapping
Labels: new, ready to merge, snapshot

#2467 Remove update-base label in all cases
  .github/workflows/update-base.yml
Labels: toolchain

#2463 Random stuff
  mappings/net/minecraft/client/ClientBrandRetriever.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/entity/ai/brain/Brain.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/loot/condition/AlternativeLootCondition.mapping
  mappings/net/minecraft/loot/condition/BlockStatePropertyLootCondition.mapping
  mappings/net/minecraft/loot/condition/DamageSourcePropertiesLootCondition.mapping
  mappings/net/minecraft/loot/condition/EntityPropertiesLootCondition.mapping
  mappings/net/minecraft/loot/condition/EntityScoresLootCondition.mapping
  mappings/net/minecraft/loot/condition/InvertedLootCondition.mapping
  mappings/net/minecraft/loot/condition/LocationCheckLootCondition.mapping
  mappings/net/minecraft/loot/condition/RandomChanceLootCondition.mapping
  mappings/net/minecraft/loot/condition/RandomChanceWithLootingLootCondition.mapping
  mappings/net/minecraft/loot/condition/ReferenceLootCondition.mapping
  mappings/net/minecraft/loot/condition/TableBonusLootCondition.mapping
  mappings/net/minecraft/loot/condition/TimeCheckLootCondition.mapping
  mappings/net/minecraft/loot/condition/ValueCheckLootCondition.mapping
  mappings/net/minecraft/loot/condition/WeatherCheckLootCondition.mapping
  mappings/net/minecraft/loot/context/LootContextType.mapping
  mappings/net/minecraft/predicate/PlayerPredicate.mapping
  mappings/net/minecraft/structure/EndCityGenerator.mapping
  mappings/net/minecraft/structure/IglooGenerator.mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/NetherFossilGenerator.mapping
  mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
  mappings/net/minecraft/structure/OceanRuinGenerator.mapping
  mappings/net/minecraft/structure/RuinedPortalStructurePiece.mapping
  mappings/net/minecraft/structure/ShipwreckGenerator.mapping
  mappings/net/minecraft/structure/SimpleStructurePiece.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/StructureManager.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/StructurePieceWithDimensions.mapping
  mappings/net/minecraft/structure/StructurePlacementData.mapping
  mappings/net/minecraft/structure/SwampHutGenerator.mapping
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
  mappings/net/minecraft/structure/processor/StructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorRule.mapping
  mappings/net/minecraft/structure/rule/PosRuleTest.mapping
  mappings/net/minecraft/util/JsonSerializing.mapping
  mappings/net/minecraft/util/collection/Int2ObjectBiMap.mapping
  mappings/net/minecraft/util/crash/CrashReportSection.mapping
  mappings/net/minecraft/util/profiler/ProfilerSystem.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/TestableWorld.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/chunk/ChunkCache.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/gen/stateprovider/WeightedBlockStateProvider.mapping
Labels: bug, new, snapshot

#2459 Map perfcommand (incomplete) and fix zip compressor mappings
  mappings/net/minecraft/server/dedicated/command/PerfCommand.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/profiler/ZipCompressor.mapping
Labels: new, ready to merge, refactor, snapshot

#2457 Some world gen mappings (pre-releases)
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoodleCavesGenerator.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/RootSystemFeature.mapping
  mappings/net/minecraft/world/gen/feature/RootSystemFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeatureConfig.mapping
Labels: new, ready to merge, snapshot

#2471 Map the remaining block state fields used in configured features
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
Labels: new, ready to merge, snapshot

#2455 Map entity methods and params
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/ExperienceOrbEntity.mapping
  mappings/net/minecraft/entity/FallingBlockEntity.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/WaterCreatureEntity.mapping
  mappings/net/minecraft/entity/projectile/FireballEntity.mapping
  mappings/net/minecraft/entity/projectile/FishingBobberEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/ThrownItemEntity.mapping
  mappings/net/minecraft/entity/raid/RaiderEntity.mapping
Labels: bug, new, ready to merge, refactor, snapshot

#2461 return inlining, up to enchantment package
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/BlockWithEntity.mapping
  mappings/net/minecraft/block/FluidDrainable.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/client/font/Font.mapping
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/font/TextVisitFactory.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleGroup.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/realms/gui/FetchRateLimiter.mapping
  mappings/net/minecraft/client/render/SkyProperties.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/tutorial/TutorialManager.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
Labels: javadoc, snapshot

#2462 Map some BeeEntity constants
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
Labels: new, snapshot

#2480 1.17-rc2 stuff
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/client/texture/PlayerSkinTexture.mapping
Labels: new, ready to merge, snapshot

#2473 Structure package constants
  build.gradle
  gradle.properties
  mappings/net/minecraft/structure/EndCityGenerator.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
  mappings/net/minecraft/structure/pool/SinglePoolElement.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
Labels: new, snapshot, toolchain

#2472 About entity network ID
  mappings/net/minecraft/client/world/ClientEntityManager.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/world/entity/EntityLike.mapping
Labels: javadoc, refactor, snapshot

#2476 Random 1.17 pre-release stuff
  mappings/net/minecraft/advancement/AdvancementCriterion.mapping
  mappings/net/minecraft/advancement/AdvancementProgress.mapping
  mappings/net/minecraft/advancement/criterion/AbstractCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LocationArrivalCriterion.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/data/server/AdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/datafixer/fix/CauldronRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/StatsRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/SwimStatsRenameFix.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/item/SkullItem.mapping
  mappings/net/minecraft/predicate/entity/DistancePredicate.mapping
Labels: new, refactor, snapshot

#2477 Some block constants
  mappings/net/minecraft/block/AbstractFireBlock.mapping
  mappings/net/minecraft/block/BubbleColumnBlock.mapping
  mappings/net/minecraft/block/CaveVinesHeadBlock.mapping
  mappings/net/minecraft/block/DetectorRailBlock.mapping
  mappings/net/minecraft/block/DispenserBlock.mapping
  mappings/net/minecraft/block/FungusBlock.mapping
  mappings/net/minecraft/block/LecternBlock.mapping
  mappings/net/minecraft/block/LightningRodBlock.mapping
  mappings/net/minecraft/block/MagmaBlock.mapping
  mappings/net/minecraft/block/RedstoneTorchBlock.mapping
  mappings/net/minecraft/block/SoulSandBlock.mapping
  mappings/net/minecraft/block/TargetBlock.mapping
  mappings/net/minecraft/block/TripwireBlock.mapping
  mappings/net/minecraft/block/TripwireHookBlock.mapping
Labels: new, snapshot

#2479 Correct visibleOnly method name -> ignoreVisibility
  mappings/net/minecraft/entity/ai/TargetPredicate.mapping
Labels: bug, refactor, snapshot

#2483 Map two release constants
  mappings/net/minecraft/SharedConstants.mapping
Labels: new, ready to merge, release

#2481 Some client mappings
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/AxolotlEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BoatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/HoglinEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/OcelotEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ShulkerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SnowGolemEntityModel.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
Labels: new, refactor, snapshot

#2485 Document the ProjectileDispenserBehavior class
  mappings/net/minecraft/block/dispenser/ProjectileDispenserBehavior.mapping
Labels: javadoc, ready to merge, release

#2488 Mapping for `TextRenderer method_37296`
  mappings/net/minecraft/client/font/TextRenderer.mapping
Labels: new, ready to merge, release

#2491 Rename fontRenderer to textRenderer
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantingPhrases.mapping
Labels: ready to merge, refactor, release

#2487 Some constants
  mappings/net/minecraft/scoreboard/AbstractTeam.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ScoreboardCriterion.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/WanderingTraderManager.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
  mappings/net/minecraft/world/gen/trunk/TrunkPlacer.mapping
  mappings/net/minecraft/world/level/storage/AnvilLevelStorage.mapping
Labels: new, ready to merge, release

#2489 Add mappings to StructurePoolElement
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
Labels: new, ready to merge, release

#2494 change SplashScreen to SplashOverlay
  mappings/net/minecraft/client/gui/screen/SplashOverlay.mapping
Labels: bug, ready to merge, refactor, release

#2495 Map SplashOverlay.renderProgressBar
  mappings/net/minecraft/client/gui/screen/SplashOverlay.mapping
Labels: new, ready to merge, snapshot

#2484 Add and remove release/snapshot labels when updating branch
  .github/workflows/update-base.yml
Labels: ready to merge, toolchain

#2509 Use "tooltip" instead of "toolTip"
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
Labels: ready to merge, refactor, snapshot

#2508 Rename the createTreeFeature and createLargeTreeFeature methods to indicate that they return a constant reference to a configured feature
  mappings/net/minecraft/block/sapling/LargeTreeSaplingGenerator.mapping
  mappings/net/minecraft/block/sapling/SaplingGenerator.mapping
Labels: bug, ready to merge, refactor, snapshot

#2505 Map realms, again
  mappings/net/minecraft/client/realms/FileDownload.mapping
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsAcceptRejectButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBrokenWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfirmScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsDownloadLatestWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsInviteScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongConfirmationScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningMcoTaskScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsNotificationsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsParentalConsentScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPendingInvitesScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSettingsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/UploadResult.mapping
  mappings/net/minecraft/client/realms/task/OpenServerTask.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
Labels: new, ready to merge, refactor, snapshot

#2499 Fix the update base script calling a non-existent contains function
  .github/workflows/update-base.yml
Labels: ready to merge, snapshot, toolchain

#2502 some util dynamic stuff
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableUuid.mapping
Labels: new, ready to merge, snapshot

#2516 Map lambda parameters in the BooleanBiFunction class
  mappings/net/minecraft/util/function/BooleanBiFunction.mapping
Labels: ready to merge, snapshot

#2515 Map resource package params
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/DirectResourceIndex.mapping
  mappings/net/minecraft/client/resource/Format3ResourcePack.mapping
  mappings/net/minecraft/client/resource/Format4ResourcePack.mapping
  mappings/net/minecraft/client/resource/ResourceIndex.mapping
  mappings/net/minecraft/client/resource/ResourceReloadLogger.mapping
  mappings/net/minecraft/client/resource/SplashTextResourceSupplier.mapping
  mappings/net/minecraft/client/resource/language/TextReorderingProcessor.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationFrameResourceMetadata.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationResourceMetadata.mapping
  mappings/net/minecraft/client/resource/metadata/LanguageResourceMetadataReader.mapping
  mappings/net/minecraft/resource/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/ProfiledResourceReload.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/ResourcePackSource.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
Labels: new, ready to merge, snapshot

#2500 1.17.1-pre1 stuff
  mappings/net/minecraft/block/CauldronBlock.mapping
  mappings/net/minecraft/client/font/UnicodeTextureFont.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSubscriptionInfoScreen.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/network/packet/c2s/play/BookUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClickSlotC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/InventoryS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScreenHandlerSlotUpdateS2CPacket.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/util/collection/DefaultedList.mapping
  mappings/net/minecraft/util/crash/CrashMemoryReserve.mapping
Labels: new, ready to merge, snapshot

#2501 More 1.17-pre1 stuff
  mappings/net/minecraft/block/CauldronBlock.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSubscriptionInfoScreen.mapping
  mappings/net/minecraft/entity/ai/brain/task/RamImpactTask.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/c2s/play/BookUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClickSlotC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/InventoryS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScreenHandlerSlotUpdateS2CPacket.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/world/gen/HeightContext.mapping
Labels: new, ready to merge, snapshot

#2521 Document EntityVelocityUpdateS2CPacket and ExplosionS2CPacket
  mappings/net/minecraft/network/packet/s2c/play/EntityVelocityUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExplosionS2CPacket.mapping
Labels: javadoc, ready to merge, snapshot

#2520 Map debug renderers stuff
  mappings/net/minecraft/client/render/debug/BeeDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/ChunkLoadingDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameEventDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameTestDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GoalSelectorDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/HeightmapDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/PathfindingDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/RaidCenterDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/SkyLightDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/StructureDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/VillageDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/VillageSectionsDebugRenderer.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
Labels: new, ready to merge, snapshot

#2523 Map screen handlers
  mappings/net/minecraft/screen/AbstractFurnaceScreenHandler.mapping
  mappings/net/minecraft/screen/AnvilScreenHandler.mapping
  mappings/net/minecraft/screen/CartographyTableScreenHandler.mapping
  mappings/net/minecraft/screen/CraftingScreenHandler.mapping
  mappings/net/minecraft/screen/EnchantmentScreenHandler.mapping
  mappings/net/minecraft/screen/ForgingScreenHandler.mapping
  mappings/net/minecraft/screen/GrindstoneScreenHandler.mapping
  mappings/net/minecraft/screen/HorseScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerContext.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
Labels: new, ready to merge, snapshot

#2522 Some NativeImage methods
  mappings/net/minecraft/client/texture/NativeImage.mapping
Labels: new, ready to merge, snapshot

#2512 Random server mappings
  gradle.properties
  mappings/net/minecraft/server/ServerConfigEntry.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/dedicated/ServerMBean.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesLoader.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/util/math/BlockPointer.mapping
Labels: ready to merge, refactor, snapshot

#2498 Document the DyedCarpetBlock class
  mappings/net/minecraft/block/DyedCarpetBlock.mapping
Labels: javadoc, ready to merge, snapshot

#2497 41 client constants
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/SkyProperties.mapping
  mappings/net/minecraft/client/render/block/entity/BeaconBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/block/entity/CampfireBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/ModelRotation.mapping
  mappings/net/minecraft/client/render/model/json/ModelElement.mapping
  mappings/net/minecraft/client/render/model/json/ModelElementFace.mapping
  mappings/net/minecraft/client/render/model/json/ModelElementTexture.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariant.mapping
Labels: new, ready to merge, snapshot

#2478 Sampler changes
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/util/ClientSamplerSource.mapping
  mappings/net/minecraft/client/util/profiler/DebugRecorder.mapping
  mappings/net/minecraft/client/util/profiler/DummyRecorder.mapping
  mappings/net/minecraft/client/util/profiler/ProfilerDumper.mapping
  mappings/net/minecraft/client/util/profiler/Recorder.mapping
  mappings/net/minecraft/client/util/profiler/SamplingRecorder.mapping
  mappings/net/minecraft/entity/ai/Durations.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/command/PerfCommand.mapping
  mappings/net/minecraft/util/CsvWriter.mapping
  mappings/net/minecraft/util/TimeHelper.mapping
  mappings/net/minecraft/util/ZipCompressor.mapping
  mappings/net/minecraft/util/profiler/DebugRecorder.mapping
  mappings/net/minecraft/util/profiler/Deviation.mapping
  mappings/net/minecraft/util/profiler/DummyRecorder.mapping
  mappings/net/minecraft/util/profiler/MetricSamplerSupplier.mapping
  mappings/net/minecraft/util/profiler/MetricSuppliers.mapping
  mappings/net/minecraft/util/profiler/ProfileLocationInfo.mapping
  mappings/net/minecraft/util/profiler/ProfileResultImpl.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
  mappings/net/minecraft/util/profiler/ProfilerSystem.mapping
  mappings/net/minecraft/util/profiler/ReadableProfiler.mapping
  mappings/net/minecraft/util/profiler/RecordDumper.mapping
  mappings/net/minecraft/util/profiler/Recorder.mapping
  mappings/net/minecraft/util/profiler/SampleType.mapping
  mappings/net/minecraft/util/profiler/Sampler.mapping
  mappings/net/minecraft/util/profiler/SamplerFactory.mapping
  mappings/net/minecraft/util/profiler/SamplerSource.mapping
  mappings/net/minecraft/util/profiler/ServerSamplerSource.mapping
  mappings/net/minecraft/util/thread/ExecutorSampling.mapping
  mappings/net/minecraft/util/thread/SampleableExecutor.mapping
Labels: new, ready to merge, refactor, snapshot

#2533 Name missing handled screen method
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
Labels: new, ready to merge, snapshot
