Repository FabricMC/yarn, pull requests merged in 2021-07, with the labels that each got.

#2535 1.17.1-pre2/pre3 stuff
  mappings/net/minecraft/block/TallPlantBlock.mapping
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/client/util/GlAllocationUtils.mapping
  mappings/net/minecraft/client/util/MacWindowUtil.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/Sensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/AquaticStrollTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GoTowardsLookTarget.mapping
  mappings/net/minecraft/entity/ai/brain/task/HoldTradeOffersTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/StrollTask.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlBrain.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/c2s/play/BookUpdateC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClickSlotC2SPacket.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/light/SkyLightStorage.mapping
Labels: new, ready to merge, snapshot

#2539 Document `SpawnEggItem.getColor`
  mappings/net/minecraft/item/SpawnEggItem.mapping
Labels: javadoc, ready to merge, snapshot

#2536 Some datafixer methods and fields
  mappings/net/minecraft/datafixer/fix/BlockStateFlattening.mapping
  mappings/net/minecraft/datafixer/fix/StructureSeparationDataFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema100.mapping
  mappings/net/minecraft/datafixer/schema/Schema1800.mapping
  mappings/net/minecraft/datafixer/schema/Schema1928.mapping
  mappings/net/minecraft/datafixer/schema/Schema501.mapping
  mappings/net/minecraft/datafixer/schema/Schema700.mapping
  mappings/net/minecraft/datafixer/schema/Schema701.mapping
  mappings/net/minecraft/datafixer/schema/Schema702.mapping
  mappings/net/minecraft/datafixer/schema/Schema704.mapping
  mappings/net/minecraft/datafixer/schema/Schema705.mapping
  mappings/net/minecraft/datafixer/schema/Schema808.mapping
  mappings/net/minecraft/datafixer/schema/Schema99.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
Labels: new, ready to merge, snapshot

#2531 Mapped ore vein and noodle caves generator
  mappings/net/minecraft/world/gen/ChunkRandom.mapping
  mappings/net/minecraft/world/gen/OreVeinGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoodleCavesGenerator.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
Labels: new, ready to merge, snapshot

#2543 Bump enigma
  build.gradle
  gradle.properties
Labels: snapshot, toolchain

#2540 1.17.1-rc1 stuff
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/util/ScreenshotRecorder.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntitiesDestroyS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityDestroyS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/UserCache.mapping
Labels: new, ready to merge, refactor, snapshot

#2538 `Block.addStacksForDisplay` -> `appendStacks` + docs
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/item/Item.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2514 PortalUtil -> BlockLocating, and findColumnEnd
  mappings/net/minecraft/world/BlockLocating.mapping
Labels: new, ready to merge, refactor, snapshot

#2547 A few unnamed item renderer stuff
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
Labels: new, ready to merge, snapshot

#2559 Misc structure gen mappings
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/world/gen/feature/JigsawFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/StructurePoolFeatureConfig.mapping
Labels: new, ready to merge, snapshot

#2558 Rename BlockBox#empty to BlockBox#infinite
  mappings/net/minecraft/util/math/BlockBox.mapping
Labels: bug, ready to merge, refactor, snapshot

#2546 Map more screens stuff
  mappings/net/minecraft/client/gui/Selectable.mapping
  mappings/net/minecraft/client/gui/screen/BackupPromptScreen.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/LevelLoadingScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ProgressScreen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTab.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTabType.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CommandBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StonecutterScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/narration/Narration.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackOrganizer.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AnimatedResultButton.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookResults.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/AlwaysSelectedEntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/ElementListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/TexturedButtonWidget.mapping
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
Labels: new, ready to merge, snapshot

#2532 Camera projection
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/client/render/CameraSubmersionType.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
Labels: new, ready to merge, snapshot

#2511 ItemStack refactor and documentation.
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: javadoc, ready to merge, refactor, release, vote

#2570 Fix the parameter of SliderWidget.setValue
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
Labels: bug, ready to merge, release

#2568 Travel javadocs
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: javadoc, ready to merge, release

#2567 Block render mappings
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModels.mapping
  mappings/net/minecraft/client/render/block/FluidRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BedBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactories.mapping
  mappings/net/minecraft/client/render/block/entity/EndPortalBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/StructureBlockBlockEntityRenderer.mapping
Labels: new, ready to merge, release

#2565 rc2 stuff
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/PacketInflater.mapping
  mappings/net/minecraft/util/thread/TaskExecutor.mapping
  mappings/net/minecraft/world/storage/ChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
Labels: new, ready to merge, release

#2549 Recipe docs
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/RecipeSerializer.mapping
  mappings/net/minecraft/recipe/RecipeType.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
Labels: javadoc, ready to merge, refactor, release

#2566 Some entity renderer and model mappings
  mappings/net/minecraft/client/render/entity/ExperienceOrbEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/FlyingItemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/GuardianEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ItemFrameEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/LightningEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/MobEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/PaintingEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ProjectileEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ShulkerEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/MooshroomMushroomFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/HorseEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/RabbitEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/WitherEntityModel.mapping
Labels: new, ready to merge, release

#2575 AxolotlEntity.Variant naming fix
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
Labels: bug, ready to merge, refactor, release

#2577 Rename "bind" and "upload" to "unbind" and "bind" in Shader
  mappings/net/minecraft/client/render/Shader.mapping
Labels: bug, ready to merge, release

#2578 Map Mojang's GLFW constants
  mappings/net/minecraft/client/util/InputUtil.mapping
Labels: new, ready to merge, release

#2589 Map and document the maximum redirect distance constant in the LightningRodBlock class
  mappings/net/minecraft/block/LightningRodBlock.mapping
Labels: javadoc, new, ready to merge, release

#2591 Map stuff in LightmapTextureManager.
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
Labels: javadoc, new, ready to merge, release

#2554 Loot/JSON serialisation improvements
  mappings/net/minecraft/loot/provider/nbt/ContextLootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProviderTypes.mapping
  mappings/net/minecraft/loot/provider/number/LootNumberProviderTypes.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProviderTypes.mapping
  mappings/net/minecraft/util/JsonSerializing.mapping
Labels: javadoc, new, ready to merge, refactor, release

#2564 Rename *Criterion.test methods to trigger
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/advancement/criterion/AbstractCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BeeNestDestroyedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/CriterionProgress.mapping
  mappings/net/minecraft/advancement/criterion/InventoryChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemUsedOnBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LightningStrikeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerGeneratesContainerLootCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerInteractedWithEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SlideDownBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/StartedRidingCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsingItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
Labels: ready to merge, refactor, release

#2580 new game version stuff
  mappings/net/minecraft/GameVersion.mapping
  mappings/net/minecraft/MinecraftVersion.mapping
  mappings/net/minecraft/SaveVersion.mapping
  mappings/net/minecraft/world/level/storage/SaveVersionInfo.mapping
Labels: new, refactor, snapshot

#2582 1.18-es1 JFR stuff
  mappings/net/minecraft/server/command/JfrCommand.mapping
  mappings/net/minecraft/server/command/ResetChunksCommand.mapping
  mappings/net/minecraft/util/math/Quantiles.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrJsonReport.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrProfile.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrProfileRecorder.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrProfiler.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrReport.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrTextReport.mapping
  mappings/net/minecraft/util/profiling/jfr/event/StackTracelessEvent.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/ChunkGenerationSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/CpuLoadSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/FileIoSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/GcHeapSummarySample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/LongRunningSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/LongRunningSampleStatistics.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/PacketSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/ServerTickTimeSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/ThreadAllocationStatisticsSample.mapping
  mappings/net/minecraft/util/profiling/jfr/sample/TimedSample.mapping
Labels: new, snapshot

#2583 1.18 es1 biome stuff
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeCreator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/util/FeatureContext.mapping
  mappings/net/minecraft/world/gen/stateprovider/MeadowFlowerProvider.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/ConfiguredSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/GroveSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/LoftyPeaksSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/NewMountainSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SnowcappedPeaksSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SnowySlopesSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: new, snapshot

#2581 Run generatePackageInfoMappings
  mappings/net/minecraft/unused/packageinfo/PackageInfo6423.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6424.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6425.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6426.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6427.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6431.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6435.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6451.mapping
Labels: new, snapshot

#2584 Mapped variables of class_6461
  mappings/net/minecraft/class_6461.mapping
Labels: new, snapshot

#2545 Rename BakedModel#getSprite to more intuitive name
  mappings/net/minecraft/client/render/block/BlockModels.mapping
  mappings/net/minecraft/client/render/item/ItemModels.mapping
  mappings/net/minecraft/client/render/model/BakedModel.mapping
Labels: javadoc, ready to merge, refactor, release

#2569 Ingame screen constant mappings
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StonecutterScreen.mapping
Labels: new, release

#2571 Use automapped names for documented fields
  build.gradle
  gradle.properties
  mappings/net/minecraft/item/ArmorMaterials.mapping
  mappings/net/minecraft/screen/slot/SlotActionType.mapping
  mappings/net/minecraft/util/ActionResult.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
Labels: bug, ready to merge, release, toolchain

#2553 Color provider improvements
  mappings/net/minecraft/client/color/block/BlockColorProvider.mapping
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/color/item/ItemColorProvider.mapping
  mappings/net/minecraft/client/color/item/ItemColors.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
Labels: javadoc, new, ready to merge, refactor, release

#2585 Rename optional tag provider builder
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
Labels: bug, ready to merge, refactor, release

#2598 Game test fixes and additional docs
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/test/AfterBatch.mapping
  mappings/net/minecraft/test/BeforeBatch.mapping
  mappings/net/minecraft/test/TestFunction.mapping
  mappings/net/minecraft/test/TestFunctions.mapping
Labels: bug, javadoc, ready to merge, refactor, release

#2604 ElderGuardianAppearanceParticle#LAYER -> layer
  mappings/net/minecraft/client/particle/ElderGuardianAppearanceParticle.mapping
Labels: bug, ready to merge, refactor, release

#2602 ChestStateManager -> ViewerCountManager
  mappings/net/minecraft/block/entity/ChestStateManager.mapping
  mappings/net/minecraft/block/entity/ViewerCountManager.mapping
Labels: ready to merge, refactor, release

#2596 1.17.1 util.math stuff
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: new, ready to merge, release

#2595 Unpick lightmap constants.
  mappings/net/minecraft/client/render/entity/ExperienceOrbEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/PaintingEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ProjectileEntityRenderer.mapping
  unpick-definitions/lightmap_coordinates.unpick
Labels: new, ready to merge, release, unpick

#2608 Remove all instances of 'ZERO WIDTH NON-JOINER' (U+200C) present in mappings.
  mappings/net/minecraft/state/property/Properties.mapping
Labels: bug, javadoc, release

#2606 1.17.1 arguments stuff
  mappings/net/minecraft/command/argument/AngleArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockPosArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockStateArgumentType.mapping
  mappings/net/minecraft/command/argument/ColorArgumentType.mapping
  mappings/net/minecraft/command/argument/ColumnPosArgumentType.mapping
  mappings/net/minecraft/command/argument/CommandFunctionArgumentType.mapping
  mappings/net/minecraft/command/argument/CoordinateArgument.mapping
  mappings/net/minecraft/command/argument/DimensionArgumentType.mapping
  mappings/net/minecraft/command/argument/EnchantmentArgumentType.mapping
  mappings/net/minecraft/command/argument/EntityAnchorArgumentType.mapping
  mappings/net/minecraft/command/argument/EntityArgumentType.mapping
  mappings/net/minecraft/command/argument/EntitySummonArgumentType.mapping
  mappings/net/minecraft/command/argument/GameProfileArgumentType.mapping
  mappings/net/minecraft/command/argument/IdentifierArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStackArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/LookingPosArgument.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/NbtCompoundArgumentType.mapping
  mappings/net/minecraft/command/argument/NbtElementArgumentType.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/command/argument/OperationArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/RotationArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreboardCriterionArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreboardObjectiveArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreboardSlotArgumentType.mapping
  mappings/net/minecraft/command/argument/StatusEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/SwizzleArgumentType.mapping
  mappings/net/minecraft/command/argument/TeamArgumentType.mapping
  mappings/net/minecraft/command/argument/TestClassArgumentType.mapping
  mappings/net/minecraft/command/argument/TestFunctionArgumentType.mapping
  mappings/net/minecraft/command/argument/TextArgumentType.mapping
  mappings/net/minecraft/command/argument/TimeArgumentType.mapping
  mappings/net/minecraft/command/argument/Vec3ArgumentType.mapping
  mappings/net/minecraft/command/argument/serialize/ArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/ConstantArgumentSerializer.mapping
Labels: new, ready to merge, release
