Repository FabricMC/yarn, pull requests merged in 2021-08, with the labels that each got.

#2599 World gen mappings for 1.18 experimental snapshot 2
  mappings/net/minecraft/class_6452.mapping
  mappings/net/minecraft/class_6466.mapping
  mappings/net/minecraft/util/function/ToFloatFunction.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Spline.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
Labels: experimental, new

#2610 Add javadoc to getItemBarStep
  mappings/net/minecraft/item/ItemStack.mapping
Labels: javadoc, ready to merge, release

#2620 ChunkRegion block placement validation mappings
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/StructureWorldAccess.mapping
Labels: new, release

#2613 Mapped class_6461 (vanilla biome parameters)
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/class_6461.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
Labels: new, experimental

#2607 clarify single player of a server
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: bug, refactor, release, javadoc

#2597 1.18_exp2 stuff
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/ForcedChunkState.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/StructureWorldAccess.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeCreator.mapping
  mappings/net/minecraft/world/biome/GenerationSettings.mapping
  mappings/net/minecraft/world/chunk/light/SkyLightStorage.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeature.mapping
  mappings/net/minecraft/world/gen/feature/DecoratedFeature.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/DefaultSurfaceBuilder.mapping
Labels: new, experimental

#2624 Use upper snake case with static final fields
  mappings/net/minecraft/block/AzaleaBlock.mapping
  mappings/net/minecraft/client/gl/GlDebug.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmChatLinkScreen.mapping
  mappings/net/minecraft/client/option/KeyBinding.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServerPlayerList.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsDownloadLatestWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongConfirmationScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningMcoTaskScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSubscriptionInfoScreen.mapping
  mappings/net/minecraft/client/realms/util/RealmsTextureManager.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
  mappings/net/minecraft/client/realms/util/UploadTokenCache.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderers.mapping
  mappings/net/minecraft/client/render/entity/feature/VillagerResourceMetadata.mapping
  mappings/net/minecraft/client/render/entity/model/SilverfishEntityModel.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/command/argument/ArgumentTypes.mapping
  mappings/net/minecraft/command/argument/EntityAnchorArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
  mappings/net/minecraft/datafixer/fix/ChunkStatusFix2.mapping
  mappings/net/minecraft/datafixer/fix/ChunkStructuresTemplateRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/RecipeFix.mapping
  mappings/net/minecraft/datafixer/fix/RecipeRenamingFix.mapping
  mappings/net/minecraft/enchantment/DamageEnchantment.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/test/TestFunctions.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/world/level/storage/AlphaChunkIo.mapping
Labels: refactor, release

#2628 Fix the names of style fields in the CommandSuggestor class indicating the wrong type
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
Labels: bug, refactor, release

#2611 Document whether inclusive or not
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/intprovider/BiasedToBottomIntProvider.mapping
  mappings/net/minecraft/util/math/intprovider/UniformIntProvider.mapping
  mappings/net/minecraft/world/gen/decorator/Decoratable.mapping
  mappings/net/minecraft/world/gen/heightprovider/TrapezoidHeightProvider.mapping
  mappings/net/minecraft/world/gen/heightprovider/UniformHeightProvider.mapping
Labels: ready to merge, release, javadoc

#2631 Fixed A Mapping Mismatch in A Constructor Method
  mappings/net/minecraft/block/Material.mapping
Labels: bug, ready to merge, release

#2640 Document key binding instances
  mappings/net/minecraft/client/option/GameOptions.mapping
Labels: ready to merge, release, javadoc

#2630 1.18-exp3 spawning
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/world/SpawnDensityCapper.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
Labels: new, ready to merge, experimental

#2641 Fix Element#mouseScrolled jd
  mappings/net/minecraft/client/gui/Element.mapping
Labels: bug, ready to merge, release, javadoc

#2629 1.18-exp3 stuff
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeCreator.mapping
  mappings/net/minecraft/world/chunk/light/LightingView.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/DripstoneClusterFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/EmeraldOreFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/GlowLichenFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/OreFeature.mapping
  mappings/net/minecraft/world/gen/feature/OreFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SimpleBlockFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/UnderwaterMagmaFeatureConfig.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/StonyPeaksSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: refactor, new, ready to merge, experimental

#2619 Improve ChunkStatus mappings
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
Labels: new, ready to merge, release

#2632 grid nibble array
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/GridNibbleArray.mapping
Labels: refactor, new, ready to merge, javadoc, experimental

#2635 Rename and document HoeItem tilling names
  mappings/net/minecraft/item/HoeItem.mapping
Labels: refactor, ready to merge, release, javadoc

#2644 Update method mappings in RecipesProvider
  mappings/net/minecraft/data/server/RecipesProvider.mapping
Labels: bug, ready to merge, release

#2493 Document the BooleanBiFunction interface
  mappings/net/minecraft/util/function/BooleanBiFunction.mapping
Labels: ready to merge, release, javadoc

#2647 Rename the GameModeSelectionScreen.GameMode class to GameModeSelection
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
Labels: refactor, ready to merge, release

#2648 Rename the StatusEffectType class to StatusEffectCategory
  mappings/net/minecraft/entity/effect/DamageModifierStatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectCategory.mapping
Labels: refactor, ready to merge, release

#2651 Rename and document the BedBlock.isOverworld method
  mappings/net/minecraft/block/BedBlock.mapping
Labels: bug, refactor, javadoc

#2649 Add a note for where to get server's actual dynamic registry entries
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
Labels: release, javadoc
