Repository FabricMC/yarn, pull requests merged in 2021-03, with the labels that each got.

#2103 Title packets
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/ClearTitleS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/OverlayMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SubtitleS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TitleFadeS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TitleS2CPacket.mapping
Labels: new, ready to merge, snapshot

#2113 Improve github actions for updating the base of a PR
  .github/workflows/update-base.yml
Labels: toolchain

#2055 Mapped some stuff in tags
  mappings/net/minecraft/network/packet/s2c/play/SynchronizeTagsS2CPacket.mapping
  mappings/net/minecraft/tag/RequiredTagList.mapping
  mappings/net/minecraft/tag/RequiredTagListRegistry.mapping
  mappings/net/minecraft/tag/TagGroup.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/tag/TagManager.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
Labels: new, ready to merge, refactor, snapshot

#2085 Text Filtering additions
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/filter/TextStream.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, ready to merge, refactor, snapshot

#2060 Map cycling button widget and cycling options
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/option/CyclingOption.mapping
Labels: new, ready to merge, refactor, snapshot

#2114 Fix javadoc error in SleepManager
  mappings/net/minecraft/server/world/SleepManager.mapping
Labels: bug, javadoc, ready to merge, snapshot

#2121 Fix typos in realms classes
  mappings/net/minecraft/client/realms/gui/screen/RealmsDownloadLatestWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
Labels: bug, ready to merge, snapshot

#2104 21w08a Packet stuff
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/SpriteBillboardParticle.mapping
  mappings/net/minecraft/client/particle/WaterSuspendParticle.mapping
  mappings/net/minecraft/entity/boss/ServerBossBar.mapping
  mappings/net/minecraft/entity/damage/DamageTracker.mapping
  mappings/net/minecraft/nbt/NbtTagSizeTracker.mapping
  mappings/net/minecraft/nbt/PositionTracker.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractEntityC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerMoveC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/DeathMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EndCombatS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EnterCombatS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityAttributesS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExperienceOrbSpawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExplosionS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/TeamS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderCenterChangedS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderInitializeS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderInterpolateSizeS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderSizeChangedS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderWarningBlocksChangedS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderWarningTimeChangedS2CPacket.mapping
  mappings/net/minecraft/server/filter/TextStream.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/text/Texts.mapping
  mappings/net/minecraft/world/WorldView.mapping
Labels: new, ready to merge, refactor, snapshot

#2123 Map the refactor for item frames and glow item frames
  mappings/net/minecraft/entity/decoration/AbstractDecorationEntity.mapping
  mappings/net/minecraft/entity/decoration/GlowItemFrameEntity.mapping
  mappings/net/minecraft/entity/decoration/ItemFrameEntity.mapping
Labels: new, ready to merge, snapshot

#2124 21w10a things
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
Labels: new, ready to merge, snapshot

#2126 Add missing methods for util math from 10a update
  mappings/net/minecraft/util/math/BlockBox.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
Labels: javadoc, new, ready to merge, snapshot

#2133 World generation in 21w10a
  mappings/net/minecraft/world/gen/decorator/CaveSurfaceDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/CaveSurfaceDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/decorator/DecoratorContext.mapping
  mappings/net/minecraft/world/gen/decorator/HeightmapDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/decorator/WaterThresholdDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/WaterThresholdDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/FossilFeature.mapping
  mappings/net/minecraft/world/gen/feature/FossilFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/GrowingPlantFeature.mapping
  mappings/net/minecraft/world/gen/feature/GrowingPlantFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/RootSystemFeature.mapping
  mappings/net/minecraft/world/gen/feature/RootSystemFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPatchFeature.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPatchFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/WaterloggedVegetationPatchFeature.mapping
  mappings/net/minecraft/world/gen/feature/util/CaveSurface.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/RandomSpreadFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/trunk/BendingTrunkPlacer.mapping
  mappings/net/minecraft/world/gen/trunk/TrunkPlacer.mapping
Labels: new, ready to merge, refactor, snapshot

#2118 Map block entitiy methods
  mappings/net/minecraft/block/entity/EndGatewayBlockEntity.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
Labels: new, ready to merge, snapshot

#2132 Fix reported Javadoc problems
  build.gradle
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/world/gen/feature/StructurePoolFeatureConfig.mapping
Labels: javadoc, ready to merge, snapshot

#2128 Map vertical surfaces
  mappings/net/minecraft/util/math/VerticalSurfaceType.mapping
  mappings/net/minecraft/world/gen/decorator/CaveSurfaceDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPatchFeatureConfig.mapping
Labels: new, ready to merge, snapshot

#2122 Map an inner class in server play network handler
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: new, ready to merge, snapshot

#2129 Map randomized int block state providers
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/stateprovider/RandomizedIntBlockStateProvider.mapping
Labels: new, ready to merge, snapshot

#2127 Map resource factory
  mappings/net/minecraft/class_5912.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
Labels: new, ready to merge, refactor, snapshot

#2139 Document TradeOffer and improve various names
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/village/Merchant.mapping
  mappings/net/minecraft/village/MerchantInventory.mapping
  mappings/net/minecraft/village/SimpleMerchant.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2140 Improve ScreenHandlerContext mappings
  mappings/net/minecraft/screen/ScreenHandlerContext.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2137 Village and POI stuff
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/passive/WanderingTraderEntity.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
  mappings/net/minecraft/world/poi/PointOfInterest.mapping
  mappings/net/minecraft/world/poi/PointOfInterestSet.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/poi/PointOfInterestType.mapping
Labels: new, ready to merge, refactor, snapshot

#2138 Mapped world gen noise interpolator
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/NoiseInterpolator.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
Labels: new, ready to merge, snapshot

#2143 some world stuff
  mappings/net/minecraft/world/BlockCollisionSpliterator.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/WanderingTraderManager.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/DefaultBiomeCreator.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/biome/source/BiomeArray.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
  mappings/net/minecraft/world/gen/YOffset.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
Labels: new, ready to merge, refactor, snapshot

#2146 PlayerListS2CPacket names
  mappings/net/minecraft/network/packet/s2c/play/PlayerListS2CPacket.mapping
Labels: new, ready to merge, snapshot

#2145 TeamS2CPacket names
  mappings/net/minecraft/network/packet/s2c/play/TeamS2CPacket.mapping
Labels: new, ready to merge, snapshot

#2149 Make BossBar names more consistent
  mappings/net/minecraft/entity/boss/BossBar.mapping
  mappings/net/minecraft/network/packet/s2c/play/BossBarS2CPacket.mapping
Labels: ready to merge, refactor, snapshot

#2147 Some lambda parameters in packets
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/MapUpdateS2CPacket.mapping
Labels: new, ready to merge, snapshot

#2152 Fixed an incorrect name
  mappings/net/minecraft/block/OxidizableBlock.mapping
  mappings/net/minecraft/block/OxidizableSlabBlock.mapping
  mappings/net/minecraft/block/OxidizableStairsBlock.mapping
Labels: bug, ready to merge, refactor, snapshot

#2135 ScreenHandler adjacent
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClickSlotC2SPacket.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerSyncHandler.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: new, ready to merge, refactor, snapshot

#2144 Map some parts of the OpenGL state managing mechanisms
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/render/BufferRenderer.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
Labels: new, ready to merge, refactor, snapshot

#2155 DirtPathRenameFix -> JigsawBlockNameFix
  mappings/net/minecraft/datafixer/fix/DirtPathRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/JigsawBlockNameFix.mapping
Labels: refactor, snapshot

#2148 Two methods used on client player respawn
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
Labels: new, snapshot

#2142 Finish mappings for dragon and dragon fight
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/ChargingPlayerPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/HoldingPatternPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/LandingApproachPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/Phase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/SittingFlamingPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/StrafePlayerPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/TakeoffPhase.mapping
Labels: new, ready to merge, snapshot

#2158 Map the LightningRodBlock.WATERLOGGED field
  mappings/net/minecraft/block/LightningRodBlock.mapping
Labels: new, ready to merge, snapshot

#2162 Map the RootedDirtBlock class
  mappings/net/minecraft/block/RootedDirtBlock.mapping
Labels: new, ready to merge, snapshot

#2090 Refactor the whole net.minecraft.nbt package.
  mappings/net/minecraft/nbt/AbstractListTag.mapping
  mappings/net/minecraft/nbt/AbstractNbtList.mapping
  mappings/net/minecraft/nbt/AbstractNbtNumber.mapping
  mappings/net/minecraft/nbt/AbstractNumberTag.mapping
  mappings/net/minecraft/nbt/ByteArrayTag.mapping
  mappings/net/minecraft/nbt/DoubleTag.mapping
  mappings/net/minecraft/nbt/EndTag.mapping
  mappings/net/minecraft/nbt/FloatTag.mapping
  mappings/net/minecraft/nbt/IntArrayTag.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/nbt/NbtByteArray.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtIntArray.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtLongArray.mapping
  mappings/net/minecraft/nbt/NbtNull.mapping
  mappings/net/minecraft/nbt/NbtOps.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/nbt/NbtType.mapping
  mappings/net/minecraft/nbt/NbtTypes.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/nbt/Tag.mapping
  mappings/net/minecraft/nbt/TagReaders.mapping
  mappings/net/minecraft/nbt/visitor/NbtElementVisitor.mapping
  mappings/net/minecraft/nbt/visitor/NbtOrderedStringFormatter.mapping
  mappings/net/minecraft/nbt/visitor/NbtTagVisitor.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/nbt/visitor/StringNbtWriter.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2164 Map dispenser behavior
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
Labels: new, ready to merge, snapshot

#2165 Map and document the boolean parameter of the Explosion.affectWorld method
  mappings/net/minecraft/world/explosion/Explosion.mapping
Labels: javadoc, new, ready to merge, snapshot

#2156 Xp dropping in living entity
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: javadoc, new, ready to merge, refactor, snapshot

#2160 21w11a stuff
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/Degradable.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/block/OxidizableBlock.mapping
  mappings/net/minecraft/block/OxidizableSlabBlock.mapping
  mappings/net/minecraft/block/OxidizableStairsBlock.mapping
  mappings/net/minecraft/block/SmallDripleafBlock.mapping
  mappings/net/minecraft/class_5955.mapping
  mappings/net/minecraft/client/particle/GlowParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/Shader.mapping
  mappings/net/minecraft/client/render/VertexFormats.mapping
  mappings/net/minecraft/entity/LightningEntity.mapping
  mappings/net/minecraft/item/AxeItem.mapping
  mappings/net/minecraft/item/HoneycombItem.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
Labels: new, ready to merge, snapshot

#2166 Map enchantments
  mappings/net/minecraft/enchantment/DamageEnchantment.mapping
  mappings/net/minecraft/enchantment/ProtectionEnchantment.mapping
  mappings/net/minecraft/enchantment/SweepingEnchantment.mapping
  mappings/net/minecraft/enchantment/ThornsEnchantment.mapping
Labels: new, ready to merge, snapshot

#2167 Map item methods
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/FluidModificationItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/PickaxeItem.mapping
Labels: new, ready to merge, snapshot

#2173 Fixes around blocks
  gradle.properties
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/piston/PistonHandler.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/world/BlockStateRaycastContext.mapping
Labels: bug, refactor, snapshot

#2172 Map a lot of util methods and stuff
  mappings/net/minecraft/util/ChatUtil.mapping
  mappings/net/minecraft/util/EightWayDirection.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/ProgressListener.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/collection/TypeFilterableList.mapping
  mappings/net/minecraft/util/crash/CrashReport.mapping
  mappings/net/minecraft/util/crash/CrashReportSection.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableUuid.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: new, ready to merge, snapshot

#2171 Book mappings (but targeting the right branch)
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/util/SelectionManager.mapping
Labels: new, ready to merge, refactor, snapshot

#2170 Add misc javadoc
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
Labels: javadoc, snapshot

#2154 A few more block state model gen stuff
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/PropertiesMap.mapping
  mappings/net/minecraft/data/client/model/Texture.mapping
  mappings/net/minecraft/data/client/model/TexturedModel.mapping
  mappings/net/minecraft/state/property/Property.mapping
Labels: new, ready to merge, refactor, snapshot

#2161 Map changes to block changes in 21w11a
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/item/AxeItem.mapping
  mappings/net/minecraft/item/HoneycombItem.mapping
Labels: javadoc, new, ready to merge, snapshot

#2175 Refactor some worldgen names
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/world/gen/NoiseCaveSampler.mapping
  mappings/net/minecraft/world/gen/NoiseInterpolator.mapping
  mappings/net/minecraft/world/gen/feature/EndSpikeFeature.mapping
  mappings/net/minecraft/world/gen/feature/RootSystemFeature.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPatchFeature.mapping
Labels: new, ready to merge, refactor, snapshot

#2183 Backport unmapped classes to release branch
  mappings/net/minecraft/class_5423.mapping
  mappings/net/minecraft/class_5459.mapping
  mappings/net/minecraft/client/font/MultilineText.mapping
  mappings/net/minecraft/entity/ai/NavigationConditions.mapping
  mappings/net/minecraft/world/PortalUtil.mapping
  mappings/net/minecraft/world/RegistryWorldView.mapping
Labels: new, ready to merge, release

#2131 Resource reload renames
  mappings/net/minecraft/client/gui/screen/SplashScreen.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/ProfiledResourceReload.mapping
  mappings/net/minecraft/resource/ReloadableResourceManager.mapping
  mappings/net/minecraft/resource/ReloadableResourceManagerImpl.mapping
  mappings/net/minecraft/resource/ResourceReload.mapping
  mappings/net/minecraft/resource/ResourceReloadListener.mapping
  mappings/net/minecraft/resource/ResourceReloadMonitor.mapping
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
  mappings/net/minecraft/resource/SimpleResourceReload.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloadListener.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloader.mapping
  mappings/net/minecraft/resource/SynchronousResourceReloadListener.mapping
  mappings/net/minecraft/resource/SynchronousResourceReloader.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#1952 Constant Unpicking
  README.md
  build.gradle
  src/constants/java/net/fabricmc/yarn/constants/SetBlockStateFlags.java
  unpick-definitions/set_block_state_flags.unpick
  unpick-definitions/unpick.json
Labels: enhancement, outdated, ready to merge, toolchain

#2180 Map many block methods and params
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
  mappings/net/minecraft/block/AbstractPlantBlock.mapping
  mappings/net/minecraft/block/AnvilBlock.mapping
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/BeehiveBlock.mapping
  mappings/net/minecraft/block/BigDripleafBlock.mapping
  mappings/net/minecraft/block/BubbleColumnBlock.mapping
  mappings/net/minecraft/block/CampfireBlock.mapping
  mappings/net/minecraft/block/CartographyTableBlock.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/ComposterBlock.mapping
  mappings/net/minecraft/block/ConnectingBlock.mapping
  mappings/net/minecraft/block/CraftingTableBlock.mapping
  mappings/net/minecraft/block/Degradable.mapping
  mappings/net/minecraft/block/EnchantingTableBlock.mapping
  mappings/net/minecraft/block/EnderChestBlock.mapping
  mappings/net/minecraft/block/GlowLichenBlock.mapping
  mappings/net/minecraft/block/GrassBlock.mapping
  mappings/net/minecraft/block/GrindstoneBlock.mapping
  mappings/net/minecraft/block/LoomBlock.mapping
  mappings/net/minecraft/block/PistonHeadBlock.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/PumpkinBlock.mapping
  mappings/net/minecraft/block/RedstoneTorchBlock.mapping
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
  mappings/net/minecraft/block/ShulkerBoxBlock.mapping
  mappings/net/minecraft/block/SmithingTableBlock.mapping
  mappings/net/minecraft/block/TallPlantBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/block/sapling/LargeTreeSaplingGenerator.mapping
  mappings/net/minecraft/block/sapling/SaplingGenerator.mapping
Labels: new, ready to merge, refactor, snapshot

#2189 Fix unpick log spamming
  build.gradle
  unpick-logging.properties
Labels: bug, toolchain, unpick

#2169 Some server javadoc
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: javadoc, ready to merge, snapshot

#2184 Document ItemEntity and improve a few names
  gradle.properties
  mappings/net/minecraft/entity/ItemEntity.mapping
Labels: bug, javadoc, ready to merge, refactor, snapshot

#2176 Particle group
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleGroup.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
Labels: new, ready to merge, snapshot

#2179 Massive networking renames
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/network/ServerAddress.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/util/NetworkUtils.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/OffThreadException.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/RateLimitedConnection.mapping
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/server/network/IntegratedServerHandshakeNetworkHandler.mapping
  mappings/net/minecraft/server/network/LocalServerHandshakeNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2196 RenderPhase and RenderLayer Mappings
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
Labels: new, ready to merge, snapshot

#2198 Book using
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: ready to merge, refactor, snapshot

#2177 Two new data fixes
  mappings/net/minecraft/datafixer/fix/ArrowPickupFix.mapping
  mappings/net/minecraft/datafixer/fix/StructureFeatureChildrenPoolElementFix.mapping
Labels: new, ready to merge, snapshot

#2185 More set block state flags
  gradle.properties
  src/constants/java/net/fabricmc/yarn/constants/SetBlockStateFlags.java
  unpick-definitions/set_block_state_flags.unpick
Labels: new, snapshot, unpick

#2200 Minor javadoc updates around unpick
  .github/workflows/build.yml
  HEADER
  build.gradle
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/world/ModifiableWorld.mapping
  src/constants/java/net/fabricmc/yarn/constants/SetBlockStateFlags.java
  src/constants/java/net/fabricmc/yarn/constants/package-info.java
Labels: javadoc, ready to merge, toolchain

#2188 World Events and Global Events Unpicked
  src/constants/java/net/fabricmc/yarn/constants/WorldEvents.java
  unpick-definitions/world_events.unpick
Labels: new, ready to merge, snapshot, unpick

#2201 Nbt type ids unpicked
  mappings/net/minecraft/nbt/AbstractNbtNumber.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/nbt/NbtByteArray.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtIntArray.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtLongArray.mapping
  mappings/net/minecraft/nbt/NbtNull.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  src/constants/java/net/fabricmc/yarn/constants/NbtTypeIds.java
  unpick-definitions/nbt_type_ids.unpick
Labels: javadoc, new, ready to merge, unpick

#2202 Some world stuff
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/level/ColorResolver.mapping
  mappings/net/minecraft/world/level/storage/AnvilLevelStorage.mapping
  mappings/net/minecraft/world/storage/RegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
Labels: new, snapshot

#2197 CommandBlockExecutor name modernization
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
Labels: refactor, snapshot

#2191 Animal Variants unpicked
  src/constants/java/net/fabricmc/yarn/constants/CatTypes.java
  src/constants/java/net/fabricmc/yarn/constants/LlamaVariants.java
  src/constants/java/net/fabricmc/yarn/constants/ParrotVariants.java
  src/constants/java/net/fabricmc/yarn/constants/RabbitTypes.java
  unpick-definitions/cat_types.unpick
  unpick-definitions/llama_variants.unpick
  unpick-definitions/parrot_variants.unpick
  unpick-definitions/rabbit_types.unpick
Labels: new, ready to merge, snapshot, unpick

#2190 Mining Levels unpicked
  src/constants/java/net/fabricmc/yarn/constants/MiningLevels.java
  unpick-definitions/mining_levels.unpick
Labels: new, snapshot, unpick

#2207 Fix some wrong mappings
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: bug, refactor, snapshot

#2193 Key codes unpicked
  unpick-definitions/key_codes.unpick
Labels: new, snapshot, unpick

#2205 Add package javadoc support
  build.gradle
  src/packageDocs/java/net/minecraft/package-info.java
  src/packageDocs/java/net/minecraft/resource/package-info.java
Labels: javadoc, snapshot, toolchain

#2199 Clarify server player's watching position
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: javadoc, refactor, snapshot

#2215 Map light blocks
  mappings/net/minecraft/block/LightBlock.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/item/Items.mapping
Labels: new, ready to merge, snapshot

#2214 Map MathConstants
  mappings/net/minecraft/util/math/MathConstants.mapping
Labels: new, ready to merge, snapshot

#2213 Readd lost mappings
  mappings/net/minecraft/world/entity/EntityLike.mapping
Labels: javadoc, ready to merge, snapshot

#2211 class_5945 -> net/minecraft/client/util/ParticleUtil
  mappings/net/minecraft/client/util/ParticleUtil.mapping
Labels: new, ready to merge, snapshot
