Repository FabricMC/yarn, pull requests merged in 2021-02, with the labels that each got.

#2002 Document one interesting method
  mappings/net/minecraft/class_5459.mapping
Labels: new, ready to merge, snapshot

#2007 Element charTyped wrong parameter
  mappings/net/minecraft/client/gui/Element.mapping
Labels: javadoc, ready to merge, snapshot

#2001 codec utilities
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, refactor, snapshot

#1994 Util package stuff
  mappings/net/minecraft/util/BlockMirror.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/JsonSerializing.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/collection/WeightedPicker.mapping
  mappings/net/minecraft/util/crash/CrashReportSection.mapping
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/util/logging/LoggerPrintStream.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionLogger.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/util/math/Vec3f.mapping
  mappings/net/minecraft/util/registry/DefaultedRegistry.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/RegistryKey.mapping
  mappings/net/minecraft/util/registry/RegistryLookupCodec.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/util/shape/SlicedVoxelShape.mapping
  mappings/net/minecraft/util/shape/VoxelSet.mapping
  mappings/net/minecraft/util/shape/VoxelShapes.mapping
Labels: new, snapshot

#2009 Map moss
  mappings/net/minecraft/block/DyedCarpetBlock.mapping
  mappings/net/minecraft/block/MossBlock.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
Labels: new, ready to merge, snapshot

#2012 Game options visitor
  mappings/net/minecraft/client/option/GameOptions.mapping
Labels: new, ready to merge, snapshot

#2013 New inner classes in model overrides
  mappings/net/minecraft/client/item/ModelPredicateProvider.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverride.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverrideList.mapping
Labels: new, snapshot

#2014 2 new particle nested classes
  mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
  mappings/net/minecraft/client/particle/WaterSuspendParticle.mapping
Labels: new, ready to merge, snapshot

#2016 21w05a worldgen mappings
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoise.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/OctaveSimplexNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/PerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/SimplexNoiseSampler.mapping
  mappings/net/minecraft/util/thread/LockHelper.mapping
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/gen/ChunkRandom.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
  mappings/net/minecraft/world/gen/SimpleRandom.mapping
  mappings/net/minecraft/world/gen/StructureWeightSampler.mapping
  mappings/net/minecraft/world/gen/WorldGenRandom.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/util/FeatureContext.mapping
Labels: new, ready to merge, snapshot

#2017 21w05a stuff
  mappings/net/minecraft/block/AbstractPlantBlock.mapping
  mappings/net/minecraft/block/AbstractPlantStemBlock.mapping
  mappings/net/minecraft/block/AzaleaBlock.mapping
  mappings/net/minecraft/block/BigDripleafBlock.mapping
  mappings/net/minecraft/block/BigDripleafStemBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/CaveVines.mapping
  mappings/net/minecraft/block/CaveVinesBodyBlock.mapping
  mappings/net/minecraft/block/CaveVinesHeadBlock.mapping
  mappings/net/minecraft/block/Degradable.mapping
  mappings/net/minecraft/block/HangingRootsBlock.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/block/OxidizableBlock.mapping
  mappings/net/minecraft/block/OxidizableSlab.mapping
  mappings/net/minecraft/block/OxidizableStairs.mapping
  mappings/net/minecraft/block/SmallDripleafBlock.mapping
  mappings/net/minecraft/block/SporeBlossomBlock.mapping
  mappings/net/minecraft/block/enums/Tilt.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: new, ready to merge, snapshot

#2019 Add Javadoc for runDirectory and itemUseCooldown
  mappings/net/minecraft/client/MinecraftClient.mapping
Labels: javadoc, ready to merge

#2022 Add unnecessary Eclipse files to .gitignore
  .gitignore
Labels: ready to merge, toolchain

#2021 Document the BellBlockEntity class
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
Labels: javadoc, ready to merge, snapshot

#2010 Mapped some stuff in util.math
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
Labels: new, outdated, ready to merge, snapshot

#2008 Element charTyped int parameter name (release)
  mappings/net/minecraft/client/gui/Element.mapping
Labels: bug, javadoc, ready to merge, release

#1996 Structure package stuff
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
  mappings/net/minecraft/structure/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/ShipwreckGenerator.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/StructureManager.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/SwampHutGenerator.mapping
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
  mappings/net/minecraft/structure/pool/FeaturePoolElement.mapping
  mappings/net/minecraft/structure/pool/SinglePoolElement.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElementType.mapping
  mappings/net/minecraft/structure/processor/BlockAgeStructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessor.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorLists.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorRule.mapping
  mappings/net/minecraft/structure/rule/PosRuleTest.mapping
Labels: new, ready to merge, snapshot

#2020 Some block params and stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractCandleBlock.mapping
  mappings/net/minecraft/block/BellBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/CampfireBlock.mapping
  mappings/net/minecraft/block/LecternBlock.mapping
  mappings/net/minecraft/block/LightningRodBlock.mapping
  mappings/net/minecraft/block/OxidizableSlabBlock.mapping
  mappings/net/minecraft/block/OxidizableStairsBlock.mapping
  mappings/net/minecraft/block/PaneBlock.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/PoweredRailBlock.mapping
  mappings/net/minecraft/block/SaplingBlock.mapping
  mappings/net/minecraft/block/entity/ShulkerBoxBlockEntity.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
Labels: new, ready to merge, refactor, snapshot

#2029 Fix getStateForNeighborUpdate parameters and document it
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: bug, javadoc, ready to merge, refactor, snapshot

#2027 Refactored some cursed height limit view names
  mappings/net/minecraft/class_5459.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
  mappings/net/minecraft/world/BlockView.mapping
  mappings/net/minecraft/world/HeightLimitView.mapping
Labels: bug, javadoc, ready to merge, refactor, snapshot

#2026 class_5423 -> RegistryWorldView
  mappings/net/minecraft/class_5423.mapping
  mappings/net/minecraft/world/RegistryWorldView.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
Labels: new, ready to merge, snapshot

#2025 Map one class in rendersytem
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/render/VertexFormat.mapping
Labels: new, ready to merge, snapshot

#2011 Bundle tutorial
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/tutorial/BundleTutorial.mapping
  mappings/net/minecraft/client/tutorial/PunchTreeTutorialStepHandler.mapping
  mappings/net/minecraft/client/tutorial/TutorialManager.mapping
  mappings/net/minecraft/client/tutorial/TutorialStepHandler.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
Labels: new, ready to merge, refactor, snapshot

#2036 Worldgen javadoc
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
  mappings/net/minecraft/world/gen/StructureWeightSampler.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: javadoc, ready to merge, snapshot

#2032 item slot
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/inventory/CommandItemSlot.mapping
Labels: new, ready to merge, snapshot

#2031 2 realms classes and some associated new stuff
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetNormalWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/realms/task/ResettingNormalWorldTask.mapping
  mappings/net/minecraft/client/realms/task/ResettingWorldTask.mapping
  mappings/net/minecraft/client/realms/task/ResettingWorldTemplateTask.mapping
Labels: new, ready to merge, snapshot

#2039 Map lambda parameters in the CauldronBehavior class
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
Labels: new, ready to merge, snapshot

#1967 Entity stuff, see #1905
  mappings/net/minecraft/class_5565.mapping
  mappings/net/minecraft/class_5569.mapping
  mappings/net/minecraft/class_5570.mapping
  mappings/net/minecraft/class_5577.mapping
  mappings/net/minecraft/class_5582.mapping
  mappings/net/minecraft/class_5584.mapping
  mappings/net/minecraft/client/world/ClientEntityManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/command/EntitySelector.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityLike.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/server/world/ServerEntityManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/TypeFilter.mapping
  mappings/net/minecraft/util/collection/TypeFilterableList.mapping
  mappings/net/minecraft/util/thread/MessageListener.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/EntityList.mapping
  mappings/net/minecraft/world/EntityLoader.mapping
  mappings/net/minecraft/world/EntityView.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/ChunkDataAccess.mapping
  mappings/net/minecraft/world/chunk/ChunkDataList.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ChunkStatusChangeListener.mapping
  mappings/net/minecraft/world/chunk/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/entity/EntityChangeListener.mapping
  mappings/net/minecraft/world/entity/EntityHandler.mapping
  mappings/net/minecraft/world/entity/EntityIndex.mapping
  mappings/net/minecraft/world/entity/EntityLike.mapping
  mappings/net/minecraft/world/entity/EntityLookup.mapping
  mappings/net/minecraft/world/entity/EntityTrackingSection.mapping
  mappings/net/minecraft/world/entity/EntityTrackingStatus.mapping
  mappings/net/minecraft/world/entity/SectionedEntityCache.mapping
  mappings/net/minecraft/world/entity/SimpleEntityLookup.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
Labels: discussion, new, ready to merge, refactor, snapshot

#2041 21w06a stuff
  mappings/net/minecraft/block/BigDripleafBlock.mapping
  mappings/net/minecraft/block/BigDripleafStemBlock.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  mappings/net/minecraft/world/gen/feature/UnderwaterMagmaFeature.mapping
  mappings/net/minecraft/world/gen/feature/UnderwaterMagmaFeatureConfig.mapping
Labels: new, ready to merge, snapshot

#2042 Map fields and methods that prevent old worlds from loading on 21w06a
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: javadoc, new, snapshot

#2043 Map new methods added to the MathHelper class in 21w06a
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: new, ready to merge, refactor, snapshot

#2044 Map the remaining fields and methods related to mineshaft generation
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/world/gen/feature/MineshaftFeature.mapping
Labels: javadoc, new, ready to merge, snapshot

#2047 21w06a worldgen mappings
  mappings/net/minecraft/world/gen/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/NoiseCaveSampler.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
  mappings/net/minecraft/world/gen/NoiseHelper.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
Labels: new, ready to merge, snapshot

#2054 Map atomic stack
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/util/thread/AtomicStack.mapping
  mappings/net/minecraft/util/thread/LockHelper.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
Labels: new, ready to merge, snapshot

#2045 Game events stuff. Map 2 unmapped top level classes
  mappings/net/minecraft/class_5711.mapping
  mappings/net/minecraft/class_5713.mapping
  mappings/net/minecraft/client/render/debug/GameEventDebugRenderer.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/network/DebugInfoSender.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/event/PositionSource.mapping
  mappings/net/minecraft/world/event/listener/EntityGameEventHandler.mapping
  mappings/net/minecraft/world/event/listener/GameEventDispatcher.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/event/listener/SculkSensorListener.mapping
  mappings/net/minecraft/world/event/listener/SimpleGameEventDispatcher.mapping
Labels: new, refactor, snapshot

#2052 Mappings for nether portal-related functionality
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/world/PortalForcer.mapping
  mappings/net/minecraft/world/PortalUtil.mapping
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
Labels: new, snapshot

#2053 Biome coords class. One more top level unmapped class left
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/biome/source/BiomeCoords.mapping
Labels: javadoc, new, snapshot

#2056 Some client nested classes
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipComponent.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/resource/metadata/AnimationResourceMetadata.mapping
Labels: new, snapshot

#2059 pos -> power
  mappings/net/minecraft/entity/projectile/ExplosiveProjectileEntity.mapping
Labels: bug, ready to merge, refactor, snapshot

#2061 Move VideoOptionsScreen to option package
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
Labels: bug, ready to merge, refactor, snapshot

#2064 Skeleton conversion
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/SaddledComponent.mapping
  mappings/net/minecraft/entity/ai/brain/Brain.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/SkeletonEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
Labels: new, snapshot

#2065 Maps an exception thrown by snbt compression in data generator
  mappings/net/minecraft/data/SnbtProvider.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
Labels: new, snapshot

#2063 Level summary unmapped nested enum
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: new, snapshot

#2058 Map Sprite sub classes
  mappings/net/minecraft/client/texture/Sprite.mapping
Labels: new, snapshot

#2033 entity tracking listener
  mappings/net/minecraft/class_5629.mapping
  mappings/net/minecraft/server/world/EntityTrackingListener.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: new, refactor, snapshot

#2066 Make mapping check work again
  build.gradle
Labels: bug, toolchain

#2074 Move affine transformation and vector 4f to regular util math
  mappings/net/minecraft/util/math/AffineTransformation.mapping
  mappings/net/minecraft/util/math/AffineTransformations.mapping
  mappings/net/minecraft/util/math/Vector4f.mapping
Labels: refactor, snapshot

#2081 Complete CheckboxWidget
  mappings/net/minecraft/client/gui/widget/CheckboxWidget.mapping
Labels: new, ready to merge, snapshot

#2079 TextFieldWidget tweaks
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
Labels: ready to merge, refactor, snapshot

#2073 Move dilation to be with modelcuboid data that accesses its package
  mappings/net/minecraft/client/model/Dilation.mapping
Labels: ready to merge, refactor, snapshot

#2070 Move chunk data access related stuff to storage
  mappings/net/minecraft/world/storage/ChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/ChunkDataList.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
Labels: ready to merge, refactor, snapshot

#2068 Move registry lookup codec to dynamic
  mappings/net/minecraft/util/dynamic/RegistryLookupCodec.mapping
Labels: ready to merge, refactor, snapshot

#2062 Entity move effect and player position look packet's one field
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerPositionLookS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: new, ready to merge, refactor, snapshot

#2037 Refactor toTag/fromTag to follow current conventions.
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/SaddledComponent.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeModifier.mapping
  mappings/net/minecraft/entity/boss/BossBarManager.mapping
  mappings/net/minecraft/entity/boss/CommandBossBar.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/mob/Angerable.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/player/HungerManager.mapping
  mappings/net/minecraft/inventory/ContainerLock.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/item/CompassItem.mapping
  mappings/net/minecraft/item/EnchantedBookItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/map/MapFrameMarker.mapping
  mappings/net/minecraft/predicate/NbtPredicate.mapping
  mappings/net/minecraft/recipe/book/RecipeBookOptions.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ScoreboardState.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerRecipeBook.mapping
  mappings/net/minecraft/server/world/ServerTickScheduler.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/StructureStart.mapping
  mappings/net/minecraft/structure/pool/FeaturePoolElement.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/PersistentState.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/chunk/BiMapPalette.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/Palette.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/timer/Timer.mapping
Labels: discussion, ready to merge, refactor, snapshot

#2040 Refactor and document some world border names
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderS2CPacket.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/storage/SectorMap.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2084 Codecs.XorCodec
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, ready to merge, snapshot

#2089 21w07a worldgen mappings
  mappings/net/minecraft/class_5857.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/BlockInterpolator.mapping
  mappings/net/minecraft/world/gen/ChunkRandom.mapping
  mappings/net/minecraft/world/gen/GrimstoneInterpolator.mapping
  mappings/net/minecraft/world/gen/NoiseCaveSampler.mapping
  mappings/net/minecraft/world/gen/StructureWeightSampler.mapping
  mappings/net/minecraft/world/gen/StructureWeightType.mapping
  mappings/net/minecraft/world/gen/YOffset.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/decorator/AbstractBiasedRangeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/AbstractCountDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/AbstractRangeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/BaseRangeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/BiasedRangeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/BiasedRangedDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/decorator/CarvingMaskDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/decorator/Decoratable.mapping
  mappings/net/minecraft/world/gen/decorator/DepthAverageDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/decorator/IcebergDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/NopeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/RangeDecorator.mapping
  mappings/net/minecraft/world/gen/decorator/RangeDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/decorator/VeryBiasedRangeDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OreFeature.mapping
Labels: new, ready to merge, refactor, snapshot

#2088 21w07a stuff
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
  mappings/net/minecraft/block/BigDripleafBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/LightningRodBlock.mapping
  mappings/net/minecraft/block/MossBlock.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/SculkSensorBlock.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/world/gen/decorator/DecoratorContext.mapping
Labels: new, ready to merge, refactor, snapshot

#2086 Map ChatRestriction inner class
  mappings/net/minecraft/client/MinecraftClient.mapping
Labels: new, ready to merge, snapshot

#2091 Rename the FeatureContext#pos field to origin
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeature.mapping
  mappings/net/minecraft/world/gen/feature/util/FeatureContext.mapping
Labels: ready to merge, refactor, snapshot

#2096 Fix the name of and add documentation to the ItemStack#isSectionVisible method
  mappings/net/minecraft/item/ItemStack.mapping
Labels: bug, javadoc, ready to merge, refactor, snapshot

#2048 Many client side GUI mappings
  mappings/net/minecraft/client/gui/MapRenderer.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/hud/spectator/RootSpectatorCommandGroup.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenu.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenuCommand.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeamTeleportSpectatorMenu.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeleportSpectatorMenu.mapping
  mappings/net/minecraft/client/gui/screen/AddServerScreen.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/DatapackFailureScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/gui/screen/DirectConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/DownloadingTerrainScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/OpenToLanScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractCommandBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AnvilScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantingPhrases.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AnimatedResultButton.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/BlastFurnaceRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/FurnaceRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeResultCollection.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/SmokerRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/CheckboxWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
Labels: new, ready to merge, refactor, release

#2098 Port some stuff from #2048 to snapshot
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/DatapackFailureScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeResultCollection.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
Labels: javadoc, new, ready to merge, refactor, snapshot

#2094 Make named jar use jetbrain annotations
  build.gradle
  gradle.properties
Labels: enhancement, toolchain

#2030 Some path targeting stuff
  mappings/net/minecraft/entity/ai/AboveGroundTargeting.mapping
  mappings/net/minecraft/entity/ai/FuzzyPositions.mapping
  mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
  mappings/net/minecraft/entity/ai/NavigationConditions.mapping
  mappings/net/minecraft/entity/ai/NoPenaltySolidTargeting.mapping
  mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
  mappings/net/minecraft/entity/ai/NoWaterTargeting.mapping
Labels: new, ready to merge, snapshot

#2101 21w08a stuff
  mappings/net/minecraft/item/FoodComponents.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
Labels: new, ready to merge, refactor, snapshot

#2099 Map some mouse event parameter names
  mappings/net/minecraft/client/Mouse.mapping
Labels: new, outdated, ready to merge, snapshot

#2100 Rename the MineshaftFeature.Type#wood field to log
  mappings/net/minecraft/world/gen/feature/MineshaftFeature.mapping
Labels: outdated, ready to merge, refactor, snapshot

#2087 Map the new SleepManager
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/SleepManager.mapping
Labels: new, outdated, ready to merge, snapshot

#2082 A few entity methods
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/task/StayAboveWaterTask.mapping
Labels: new, outdated, ready to merge, snapshot

#2083 Some util mappings
  mappings/net/minecraft/util/Util.mapping
Labels: new, outdated, ready to merge, snapshot

#1993 Server package stuff
  mappings/net/minecraft/server/BannedIpList.mapping
  mappings/net/minecraft/server/BannedPlayerList.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/command/FillCommand.mapping
  mappings/net/minecraft/server/command/ItemCommand.mapping
  mappings/net/minecraft/server/command/ListCommand.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/command/ReloadCommand.mapping
  mappings/net/minecraft/server/command/ScheduleCommand.mapping
  mappings/net/minecraft/server/command/SpreadPlayersCommand.mapping
  mappings/net/minecraft/server/command/SummonCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/dedicated/AbstractPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/EulaReader.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesLoader.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/network/DebugInfoSender.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerRecipeBook.mapping
  mappings/net/minecraft/server/rcon/QueryResponseHandler.mapping
  mappings/net/minecraft/server/rcon/RconListener.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/PlayerChunkWatchingManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/server/world/ServerTickScheduler.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/SimpleTickScheduler.mapping
Labels: new, ready to merge, snapshot

#2106 Carver mappings
  mappings/net/minecraft/class_5868.mapping
  mappings/net/minecraft/world/gen/DeepslateInterpolator.mapping
  mappings/net/minecraft/world/gen/HeightContext.mapping
  mappings/net/minecraft/world/gen/carver/Carver.mapping
  mappings/net/minecraft/world/gen/carver/CarverConfig.mapping
  mappings/net/minecraft/world/gen/carver/CarverContext.mapping
  mappings/net/minecraft/world/gen/carver/CarverDebugConfig.mapping
  mappings/net/minecraft/world/gen/carver/CaveCarver.mapping
  mappings/net/minecraft/world/gen/carver/RavineCarver.mapping
  mappings/net/minecraft/world/gen/carver/RavineCarverConfig.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/feature/GeodeFeatureConfig.mapping
Labels: new, ready to merge, snapshot

#2105 Some packet byte buf stuff
  mappings/net/minecraft/network/PacketByteBuf.mapping
Labels: javadoc, new, ready to merge, snapshot

#2097 Fixes SpawnGroup.isAnimal
  mappings/net/minecraft/entity/SpawnGroup.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
Labels: javadoc, outdated, ready to merge, refactor, snapshot

#2102 boss bar packet restored
  mappings/net/minecraft/network/packet/s2c/play/BossBarS2CPacket.mapping
Labels: new, refactor, snapshot
