Repository FabricMC/yarn, pull requests merged in 2021-12, with the labels that each got.

#2892 Move the EightWayDirection class to the net.minecraft.util.math package
  mappings/net/minecraft/util/math/EightWayDirection.mapping
Labels: refactor, ready to merge, snapshot

#2894 Rename the ServerWorld#getSurface method to getLightningPos
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: refactor, ready to merge, snapshot

#2902 1.18.1-pre1 stuff
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/collection/IndexedIterable.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/tick/WorldTickScheduler.mapping
Labels: new, snapshot

#2899 add getSkyColor mapping to ClientWorld
  mappings/net/minecraft/client/world/ClientWorld.mapping
Labels: outdated, new, release

#2906 Fix typo
  mappings/net/minecraft/loot/function/SetBannerPatternFunction.mapping
Labels: bug, snapshot

#2909 Minor Block javadoc improvements
  mappings/net/minecraft/block/Block.mapping
Labels: bug, ready to merge, release, javadoc

#2908 1.18.1-rc1 stuff
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/exception/RealmsServiceException.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsGenericErrorScreen.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: bug, refactor, new, ready to merge, release

#2927 Fix typo
  mappings/net/minecraft/world/gen/feature/OrePlacedFeatures.mapping
Labels: bug, ready to merge, release

#2928 Fix typos
  mappings/net/minecraft/GameVersion.mapping
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlBrain.mapping
  mappings/net/minecraft/entity/player/HungerConstants.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/function/SetDamageLootFunction.mapping
  mappings/net/minecraft/resource/Resource.mapping
  mappings/net/minecraft/server/ServerNetworkIo.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/util/collection/LinkedBlockPosHashSet.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/PaletteResizeListener.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/chunk/SingularPalette.mapping
Labels: bug, refactor, release, javadoc

#2929 Rename the LootContextParameter#getIdentifier method to getId
  mappings/net/minecraft/loot/context/LootContextParameter.mapping
Labels: bug, refactor, ready to merge, release

#2934 Update WAXED_COPPER, DEEPSLATE_WALL and AZALEA_LEAVES_FLOWERS
  mappings/net/minecraft/item/Items.mapping
Labels: bug, refactor, ready to merge, release

#2939 Fix the parameter of ItemDispenserBehavior.spawnItem
  mappings/net/minecraft/block/dispenser/ItemDispenserBehavior.mapping
Labels: bug, ready to merge, release

#2937 Fix the parameter of MultiNoiseUtil.SearchTree.TreeNode constructor
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
Labels: bug, ready to merge, release

#2936 Fix the parameter of DefaultedList.add
  mappings/net/minecraft/util/collection/DefaultedList.mapping
Labels: bug, ready to merge, release

#2940 Fix AbstractBlock.getMaxModelOffset
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: bug, refactor, ready to merge, release

#2941 Fix TimeHelper.SECOND_IN_MILLIS
  mappings/net/minecraft/util/TimeHelper.mapping
Labels: bug, refactor, ready to merge, release

#2930 Document Vec3i
  mappings/net/minecraft/util/math/Vec3i.mapping
Labels: release, javadoc

#2915 Rename the BackgroundHelper class to ColorHelper
  mappings/net/minecraft/util/math/ColorHelper.mapping
Labels: bug, refactor, release, impactful

#2942 Fix MoveToTargetPosGoal.getDesiredSquaredDistanceToTarget
  mappings/net/minecraft/entity/ai/goal/MoveToTargetPosGoal.mapping
Labels: bug, refactor, release

#2943 Screen#{isPauseScreen -> shouldPause}
  mappings/net/minecraft/client/gui/screen/Screen.mapping
Labels: refactor, release, impactful

#2945 Fix door open and close sound world event id method names being swapped
  mappings/net/minecraft/block/DoorBlock.mapping
Labels: bug, refactor, ready to merge, release

#2951 lure and LOTS levels were swapped
  mappings/net/minecraft/entity/projectile/FishingBobberEntity.mapping
Labels: bug, ready to merge, release

#2950 Hoppers are not an example of SidedInventory
  mappings/net/minecraft/inventory/SidedInventory.mapping
Labels: bug, ready to merge, release, javadoc

#2949 BookScreen.getTextAt -> getTextStyleAt
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
Labels: bug, refactor, ready to merge, release

#2884 Rename NbtNull to NbtEnd
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtEnd.mapping
  mappings/net/minecraft/nbt/NbtNull.mapping
  mappings/net/minecraft/nbt/scanner/NbtScanner.mapping
  mappings/net/minecraft/nbt/visitor/NbtElementVisitor.mapping
  unpick-definitions/nbt_type_ids.unpick
Labels: refactor, release, vote, impactful
