Repository FabricMC/yarn, pull requests merged in 2021-10, with the labels that each got.

#2712 Map block column itf used for surface build
  mappings/net/minecraft/class_6557.mapping
  mappings/net/minecraft/world/gen/chunk/BlockColumn.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/DefaultSurfaceBuilder.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/SurfaceBuilder.mapping
Labels: new, snapshot

#2714 simulation distance level propagator
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/world/SimulationDistanceLevelPropagator.mapping
Labels: new, snapshot

#2713 Map chunk and light data, used for packet transport and async reading
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkData.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDataS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/LightData.mapping
  mappings/net/minecraft/network/packet/s2c/play/LightUpdateS2CPacket.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightStorage.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
Labels: new, snapshot

#2715 Improve ProjectileEntity
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
Labels: refactor, snapshot, javadoc

#2720 More 21w39a stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/SocialInteractionsManager.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/goal/Goal.mapping
  mappings/net/minecraft/entity/ai/goal/GoalSelector.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/server/chase/ChaseClient.mapping
  mappings/net/minecraft/server/chase/ChaseServer.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: new, snapshot

#2697 Terrain generation mappings for 21w37a
  mappings/net/minecraft/class_6568.mapping
  mappings/net/minecraft/class_6574.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/gen/BlockSource.mapping
  mappings/net/minecraft/world/gen/ChainedBlockSource.mapping
  mappings/net/minecraft/world/gen/DeepslateBlockSource.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
  mappings/net/minecraft/world/gen/chunk/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
Labels: new, snapshot

#2684 changed flyingSpeed to airStrafingSpeed
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: refactor, ready to merge, snapshot

#2728 21w39a util
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/dynamic/Range.mapping
Labels: new, snapshot

#2727 Fix build errors
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/DefaultSurfaceBuilder.mapping
Labels: bug, snapshot

#2724 21w39a MinecraftClient mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
Labels: new, snapshot

#2722 Rename the MushroomStewItem class to StewItem
  mappings/net/minecraft/item/MushroomStewItem.mapping
  mappings/net/minecraft/item/StewItem.mapping
Labels: bug, refactor, snapshot

#2711 Map topological sort; used by vanilla to sort feature generation
  mappings/net/minecraft/util/TopologicalSorts.mapping
Labels: new, snapshot

#2513 Revamp control to be more accurate
  mappings/net/minecraft/entity/ai/control/AquaticLookControl.mapping
  mappings/net/minecraft/entity/ai/control/BodyControl.mapping
  mappings/net/minecraft/entity/ai/control/LookControl.mapping
  mappings/net/minecraft/entity/ai/control/YawAdjustingLookControl.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: refactor, new, ready to merge, snapshot, javadoc

#2730 Add mappings for BedBlock methods
  mappings/net/minecraft/block/BedBlock.mapping
Labels: bug, new, ready to merge, snapshot

#2799 Fix the issue where superinterfaces are not included in record signatures
  record_signatures.json
Labels: bug, snapshot

#2798 Document the BlockStateProvider class
  mappings/net/minecraft/world/gen/stateprovider/BlockStateProvider.mapping
Labels: snapshot, javadoc

#2795 Fix MinecraftClient inconsistencies
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTab.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookResults.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
Labels: refactor, snapshot

#2791 21w43a datafixers
  mappings/net/minecraft/datafixer/fix/ChunkLevelTagRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ProtoChunkTickListFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema2842.mapping
Labels: new, snapshot

#2796 Fix ItemRenderer.getHeldItemModel
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
Labels: bug, snapshot
