Repository FabricMC/yarn, pull requests merged in 2021-05, with the labels that each got.

#2369 Fix swapped names
  mappings/net/minecraft/client/resource/language/LanguageDefinition.mapping
  mappings/net/minecraft/network/packet/s2c/play/WorldBorderCenterChangedS2CPacket.mapping
Labels: bug, ready to merge, snapshot

#2366 Refactor coordinate names to follow conventions
  mappings/net/minecraft/advancement/AdvancementDisplay.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/GlyphRenderer.mapping
  mappings/net/minecraft/client/font/TrueTypeFont.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/render/chunk/ChunkRendererRegion.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/entity/ai/FuzzyPositions.mapping
  mappings/net/minecraft/entity/ai/NoPenaltySolidTargeting.mapping
  mappings/net/minecraft/entity/ai/goal/DolphinJumpGoal.mapping
  mappings/net/minecraft/entity/ai/goal/DoorInteractGoal.mapping
  mappings/net/minecraft/entity/ai/pathing/MobNavigation.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/shape/BitSetVoxelSet.mapping
  mappings/net/minecraft/util/shape/CroppedVoxelSet.mapping
  mappings/net/minecraft/util/shape/VoxelSet.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/util/shape/VoxelShapes.mapping
Labels: ready to merge, refactor, snapshot

#2368 Unpick entity flags and pufferfish states
  unpick-definitions/entity_flags.unpick
  unpick-definitions/pufferfish_states.unpick
Labels: ready to merge, snapshot, unpick

#2376 random misc things
  mappings/net/minecraft/advancement/AdvancementRewards.mapping
  mappings/net/minecraft/advancement/criterion/ConstructBeaconCriterion.mapping
  mappings/net/minecraft/block/BigDripleafBlock.mapping
  mappings/net/minecraft/block/FireBlock.mapping
  mappings/net/minecraft/block/InfestedBlock.mapping
  mappings/net/minecraft/block/KelpBlock.mapping
  mappings/net/minecraft/block/SnowyBlock.mapping
  mappings/net/minecraft/block/dispenser/BlockPlacementDispenserBehavior.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/EndGatewayBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/piston/PistonHandler.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/gui/hud/ClientBossBar.mapping
  mappings/net/minecraft/client/gui/hud/InGameOverlayRenderer.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/screen/SplashScreen.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
Labels: new, ready to merge, refactor, snapshot

#2364 Map math classes
  mappings/net/minecraft/client/util/Rect2i.mapping
  mappings/net/minecraft/client/util/math/Rect2i.mapping
  mappings/net/minecraft/util/math/AxisCycleDirection.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/math/ColumnPos.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/math/DirectionTransformation.mapping
  mappings/net/minecraft/util/math/EulerAngle.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Vec2f.mapping
  mappings/net/minecraft/util/math/Vec3f.mapping
  mappings/net/minecraft/util/math/Vector4f.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
Labels: new, ready to merge, snapshot

#2375 Document property classes
  mappings/net/minecraft/state/property/BooleanProperty.mapping
  mappings/net/minecraft/state/property/DirectionProperty.mapping
  mappings/net/minecraft/state/property/EnumProperty.mapping
  mappings/net/minecraft/state/property/IntProperty.mapping
  mappings/net/minecraft/state/property/Property.mapping
Labels: javadoc, snapshot

#2372 Map command stuff
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/command/FloatRangeArgument.mapping
  mappings/net/minecraft/command/argument/BlockStateArgument.mapping
  mappings/net/minecraft/command/argument/DefaultPosArgument.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/command/argument/NumberRangeArgumentType.mapping
  mappings/net/minecraft/command/argument/Vec2ArgumentType.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/server/command/DebugCommand.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
Labels: new, snapshot

#2379 Improve documentation for teleport targets
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/world/TeleportTarget.mapping
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
Labels: javadoc, snapshot

#2380 Readd parameter names removed by the update to 21w18a
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: snapshot

#2382 Map new methods added to the AbstractBlock.Settings class in 21w18a
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: new, ready to merge, snapshot

#2388 Rename the BlockEntity#getSquaredRenderDistance method to getRenderDistance
  mappings/net/minecraft/block/entity/BlockEntity.mapping
Labels: bug, ready to merge, refactor, release

#2381 Client resource reload stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/resource/ResourceReloadLogger.mapping
Labels: new, snapshot

#2383 Map client stuff
  mappings/com/mojang/blaze3d/platform/GlDebugInfo.mapping
  mappings/net/minecraft/client/Keyboard.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/gl/GlUniform.mapping
  mappings/net/minecraft/client/gl/Program.mapping
  mappings/net/minecraft/client/gl/ShaderParseException.mapping
  mappings/net/minecraft/client/gl/Uniform.mapping
Labels: new, snapshot

#2384 Drop invalid mappings
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonFactory.mapping
  mappings/net/minecraft/data/server/recipe/SingleItemRecipeJsonFactory.mapping
Labels: snapshot

#2385 Map screen stuff
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/SplashScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
Labels: new, snapshot

#2387 Map worldgen stuff
  mappings/net/minecraft/world/gen/CatSpawner.mapping
  mappings/net/minecraft/world/gen/ChunkRandom.mapping
  mappings/net/minecraft/world/gen/DeepslateBlockSource.mapping
  mappings/net/minecraft/world/gen/carver/Carver.mapping
  mappings/net/minecraft/world/gen/carver/CarverConfig.mapping
  mappings/net/minecraft/world/gen/carver/CarverDebugConfig.mapping
  mappings/net/minecraft/world/gen/carver/CaveCarverConfig.mapping
  mappings/net/minecraft/world/gen/carver/RavineCarverConfig.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorLayer.mapping
  mappings/net/minecraft/world/gen/decorator/Decoratable.mapping
  mappings/net/minecraft/world/gen/decorator/RangeDecoratorConfig.mapping
  mappings/net/minecraft/world/gen/feature/BuriedTreasureFeature.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/GeodeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/OreFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/util/CaveSurface.mapping
  mappings/net/minecraft/world/gen/placer/ColumnPlacer.mapping
Labels: new, refactor, snapshot

#2391 Map the AbstractBlock#getHardness method
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: new, ready to merge, snapshot

#2393 Document KeyBinding.isPressed and KeyBinding.wasPressed
  mappings/net/minecraft/client/option/KeyBinding.mapping
Labels: javadoc, ready to merge, snapshot

#2394 21w19a network stuff
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/Address.mapping
  mappings/net/minecraft/client/network/AddressResolver.mapping
  mappings/net/minecraft/client/network/AllowedAddressResolver.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/network/LanServerQueryManager.mapping
  mappings/net/minecraft/client/network/MultiplayerServerListPinger.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/network/RedirectResolver.mapping
  mappings/net/minecraft/client/network/ServerAddress.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/encryption/PacketDecryptor.mapping
  mappings/net/minecraft/network/encryption/PacketEncryptionManager.mapping
  mappings/net/minecraft/network/encryption/PacketEncryptor.mapping
  mappings/net/minecraft/server/LanServerPinger.mapping
Labels: new, ready to merge, snapshot

#2397 Map command stuff, again
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/CommandOutput.mapping
  mappings/net/minecraft/server/command/DebugCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/FillCommand.mapping
  mappings/net/minecraft/server/command/ForceLoadCommand.mapping
  mappings/net/minecraft/server/command/GiveCommand.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/server/command/SpreadPlayersCommand.mapping
  mappings/net/minecraft/server/command/TeleportCommand.mapping
  mappings/net/minecraft/server/command/WeatherCommand.mapping
Labels: new, ready to merge, snapshot

#2396 Fix GameModeCommand.setGameMode
  mappings/net/minecraft/server/command/GameModeCommand.mapping
Labels: bug, snapshot

#2400 Fixes #2399
  build.gradle
  gradle.properties
Labels: bug, javadoc, ready to merge, snapshot, toolchain

#2051 More comprehensive javadoc conventions
  CONVENTIONS.md
Labels: discussion, enhancement, ready to merge

#2398 Update to Filament 0.3.0
  build.gradle
Labels: ready to merge, snapshot, toolchain

#2401 Map some easy packet classes and a package info
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayPongC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayPingS2CPacket.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6372.mapping
Labels: new, ready to merge, snapshot

#2409 misc things
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/loot/LootPool.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/predicate/PlayerPredicate.mapping
  mappings/net/minecraft/predicate/StatePredicate.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/stat/Stats.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/state/property/Property.mapping
  mappings/net/minecraft/tag/RequiredTagList.mapping
  mappings/net/minecraft/tag/Tag.mapping
  mappings/net/minecraft/tag/TagGroup.mapping
  mappings/net/minecraft/tag/TagManager.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/util/JsonSerializing.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/collection/Weighted.mapping
  mappings/net/minecraft/util/collection/WeightedList.mapping
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/util/function/MaterialPredicate.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/thread/TaskExecutor.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
  mappings/net/minecraft/world/ChunkSectionCache.mapping
  mappings/net/minecraft/world/FeatureUpdater.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: new, ready to merge, snapshot

#2407 Abstract button widget renames
  mappings/net/minecraft/client/gui/widget/AbstractPressableButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/PressableWidget.mapping
  unpick-definitions/gui_widget.unpick
Labels: ready to merge, refactor, snapshot, unpick

#2404 Map noodle cave and aquifer abstracts
  mappings/net/minecraft/class_6350.mapping
  mappings/net/minecraft/class_6357.mapping
  mappings/net/minecraft/world/gen/carver/Carver.mapping
  mappings/net/minecraft/world/gen/carver/UnderwaterCaveCarver.mapping
  mappings/net/minecraft/world/gen/chunk/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoodleCavesGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/WeightSampler.mapping
Labels: new, ready to merge, refactor, snapshot

#2403 Ram
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/TargetPredicate.mapping
  mappings/net/minecraft/entity/ai/brain/task/PrepareRamTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/RamImpactTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/RamTask.mapping
  mappings/net/minecraft/entity/passive/GoatBrain.mapping
Labels: new, refactor, snapshot

#2406 Checks entity flags to unpick
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/entity/decoration/ArmorStandEntity.mapping
  mappings/net/minecraft/entity/mob/BlazeEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/SpiderEntity.mapping
  mappings/net/minecraft/entity/passive/BatEntity.mapping
  mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/util/math/EulerAngle.mapping
  unpick-definitions/entity_flags.unpick
Labels: new, refactor, snapshot, unpick

#2412 21w20a blocks
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractCandleBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/BuddingAmethystBlock.mapping
  mappings/net/minecraft/block/LeveledCauldronBlock.mapping
  mappings/net/minecraft/block/PowderSnowCauldronBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
Labels: new, ready to merge, snapshot

#2414 Fix English errors in CONVENTIONS.md and README.md
  CONVENTIONS.md
  README.md
Labels: ready to merge

#2415 Rename gamemode to gameMode
  mappings/net/minecraft/predicate/PlayerPredicate.mapping
Labels: ready to merge, refactor, snapshot

#2419 Two package info mappings from generatePackageInfoMappings
  mappings/net/minecraft/unused/packageinfo/PackageInfo6389.mapping
  mappings/net/minecraft/unused/packageinfo/PackageInfo6391.mapping
Labels: new, ready to merge, snapshot

#2413 21w20a entity
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/LightningEntity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/PufferfishEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/entity/projectile/AbstractFireballEntity.mapping
Labels: new, ready to merge, snapshot

#2422 21w20a world stuff
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/biome/GenerationSettings.mapping
  mappings/net/minecraft/world/biome/SpawnSettings.mapping
  mappings/net/minecraft/world/biome/source/BiomeArray.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightingView.mapping
  mappings/net/minecraft/world/gen/WorldGenRandom.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
Labels: new, ready to merge, snapshot

#2423 Rename NPC to Npc
  mappings/net/minecraft/client/realms/dto/RealmsWorldOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
Labels: ready to merge, refactor, snapshot

#2424 21w20a util stuff
  mappings/net/minecraft/client/util/CharPredicate.mapping
  mappings/net/minecraft/client/util/ChatMessages.mapping
  mappings/net/minecraft/client/util/Clipboard.mapping
  mappings/net/minecraft/client/util/GlAllocationUtils.mapping
  mappings/net/minecraft/client/util/GlException.mapping
  mappings/net/minecraft/client/util/InputUtil.mapping
  mappings/net/minecraft/client/util/ModelIdentifier.mapping
  mappings/net/minecraft/client/util/Monitor.mapping
  mappings/net/minecraft/client/util/MonitorTracker.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
  mappings/net/minecraft/client/util/NetworkUtils.mapping
  mappings/net/minecraft/client/util/PngFile.mapping
  mappings/net/minecraft/client/util/RawTextureDataLoader.mapping
  mappings/net/minecraft/client/util/VideoMode.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/client/util/profiler/DebugRecorder.mapping
  mappings/net/minecraft/client/util/profiler/ProfilerDumper.mapping
  mappings/net/minecraft/client/util/profiler/SamplingRecorder.mapping
  mappings/net/minecraft/text/Texts.mapping
  mappings/net/minecraft/util/profiler/CsvWriter.mapping
  mappings/net/minecraft/util/profiler/ProfileResult.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
Labels: new, ready to merge, snapshot

#2426 Restore lost arguments and map some random stuff
  mappings/net/minecraft/client/gui/screen/ConfirmScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/option/FullscreenOption.mapping
  mappings/net/minecraft/client/option/ServerList.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/screen/CartographyTableScreenHandler.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/util/shape/SimplePairList.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
Labels: new, ready to merge, snapshot

#2417 21w20a stuff
  mappings/net/minecraft/client/item/UnclampedModelPredicateProvider.mapping
  mappings/net/minecraft/client/render/entity/model/AxolotlEntityModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverrideList.mapping
  mappings/net/minecraft/entity/AngledModelEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/entity/player/ItemCooldownManager.mapping
  mappings/net/minecraft/item/FoodComponent.mapping
  mappings/net/minecraft/item/HoeItem.mapping
  mappings/net/minecraft/structure/processor/ProtectedBlocksStructureProcessor.mapping
  mappings/net/minecraft/world/gen/feature/Feature.mapping
  unpick-definitions/entity_status.unpick
Labels: new, snapshot, unpick

#2418 Block list checker for the allowed address resolver
  mappings/net/minecraft/client/network/AllowedAddressResolver.mapping
  mappings/net/minecraft/client/network/BlockListChecker.mapping
Labels: new, snapshot

#2420 Model predicate provider registry minor stuff
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
Labels: new, refactor, snapshot

#2432 Map Minecraft logo outline method
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
Labels: new, ready to merge, snapshot

#2428 Map server stuff
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/QueueingWorldGenerationProgressListener.mapping
  mappings/net/minecraft/server/ServerConfigList.mapping
  mappings/net/minecraft/server/ServerNetworkIo.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/dedicated/AbstractPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/ServerMBean.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/gui/DedicatedServerGui.mapping
  mappings/net/minecraft/server/dedicated/gui/PlayerStatsGui.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/network/DebugInfoSender.mapping
  mappings/net/minecraft/server/network/DemoServerPlayerInteractionManager.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerRecipeBook.mapping
  mappings/net/minecraft/server/rcon/DataStreamHelper.mapping
  mappings/net/minecraft/server/rcon/QueryResponseHandler.mapping
  mappings/net/minecraft/server/rcon/RconCommandOutput.mapping
  mappings/net/minecraft/server/rcon/RconListener.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkTaskPrioritySystem.mapping
  mappings/net/minecraft/server/world/ChunkTicketType.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/SimpleTickScheduler.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: new, ready to merge, snapshot

#2425 Screen Narration stuff
  mappings/net/minecraft/client/gui/Narratable.mapping
  mappings/net/minecraft/client/gui/Selectable.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/narration/Narration.mapping
  mappings/net/minecraft/client/gui/screen/narration/NarrationMessageBuilder.mapping
  mappings/net/minecraft/client/gui/screen/narration/NarrationPart.mapping
  mappings/net/minecraft/client/gui/screen/narration/ScreenNarrator.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
Labels: new, ready to merge, snapshot

#2440 Rename ShapedRecipe#getItemStack to getItem
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
Labels: bug, ready to merge, refactor, snapshot

#2434 Rename HandledScreen.displayName -> playerInventoryTitle
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
Labels: bug, ready to merge, refactor, snapshot

#2435 1.17-pre1 criteria
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/LightningStrikeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/StartedRidingCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsingItemCriterion.mapping
Labels: new, ready to merge, snapshot

#2445 Build javadoc with JDK 17 to fix #2429
  .github/workflows/build.yml
  .github/workflows/publish.yml
  build.gradle
Labels: toolchain

#2439 Map player list hud
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
Labels: new, ready to merge, refactor, snapshot

#2452 Slot.isEnabled and CommandItemSlot -> StackReference
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/HorseBaseEntity.mapping
  mappings/net/minecraft/inventory/CommandItemSlot.mapping
  mappings/net/minecraft/inventory/StackReference.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
Labels: javadoc, ready to merge, refactor, snapshot

#2447 Map some shared constants
  mappings/net/minecraft/SharedConstants.mapping
Labels: new, ready to merge, snapshot

#2444 Some collision stuff, fixes #2443
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/world/BlockCollisionSpliterator.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  unpick-definitions/jdk.unpick
Labels: new, refactor, snapshot, unpick

#2442 Some required tag details
  mappings/net/minecraft/tag/RequiredTagList.mapping
  mappings/net/minecraft/tag/RequiredTagListRegistry.mapping
Labels: javadoc, new, refactor, snapshot

#2449 Map TradeOffers constants
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: new, snapshot

#2453 Fix swapped names in Matrix3f and Matrix4f
  mappings/net/minecraft/util/math/Matrix3f.mapping
  mappings/net/minecraft/util/math/Matrix4f.mapping
Labels: bug, refactor, snapshot
