Repository FabricMC/yarn, pull requests merged in 2021-01, with the labels that each got.

#1946 `getFirst` -> `build`
  mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
Labels: refactor, snapshot

#1945 Map some BE renderers
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BedBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/block/entity/ConduitBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/EndPortalBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/PistonBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/StructureBlockBlockEntityRenderer.mapping
Labels: javadoc, new, snapshot

#1947 Random stuff
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/util/collection/WeightedPicker.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/biome/source/BiomeAccess.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ColumnChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/level/UnmodifiableLevelProperties.mapping
Labels: new, refactor

#1948 Complete mapping for `ModelVariant`
  mappings/net/minecraft/client/render/model/json/ModelVariant.mapping
Labels: new

#1849 Update MapColor field names
  mappings/net/minecraft/block/MapColor.mapping
Labels: discussion, javadoc, refactor

#1949 Complete LeverBlock
  mappings/net/minecraft/block/LeverBlock.mapping
Labels: new, ready to merge

#1950 Rename command arguments to align with value types
  mappings/net/minecraft/command/argument/AngleArgumentType.mapping
  mappings/net/minecraft/command/argument/CommandFunctionArgumentType.mapping
  mappings/net/minecraft/command/argument/EnchantmentArgumentType.mapping
  mappings/net/minecraft/command/argument/NumberRangeArgumentType.mapping
  mappings/net/minecraft/command/argument/ObjectiveCriteriaArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreboardCriterionArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreboardObjectiveArgumentType.mapping
  mappings/net/minecraft/command/argument/StatusEffectArgumentType.mapping
Labels: ready to merge, refactor

#1953 World stuff
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/NetherFortressGenerator.mapping
  mappings/net/minecraft/structure/SimpleStructurePiece.mapping
  mappings/net/minecraft/structure/StrongholdGenerator.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/dimension/DimensionOptions.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/gen/feature/FlowerFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeature.mapping
  mappings/net/minecraft/world/gen/feature/RuinedPortalFeature.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/level/storage/SessionLock.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
Labels: new, ready to merge, snapshot

#1957 Map the new method in 1.16.5-rc1
  mappings/net/minecraft/util/math/Direction.mapping
Labels: new, snapshot

#1955 Client stuff and MultilineText class
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/MultilineText.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/resource/VideoWarningManager.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/PropertiesMap.mapping
  mappings/net/minecraft/data/client/model/Texture.mapping
  mappings/net/minecraft/data/client/model/TextureKey.mapping
Labels: new, snapshot

#1958 Server data generator stuff
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/BlockTagsProvider.mapping
  mappings/net/minecraft/data/server/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/EntityTypeTagsProvider.mapping
  mappings/net/minecraft/data/server/FluidTagsProvider.mapping
  mappings/net/minecraft/data/server/GameEventTagsProvider.mapping
  mappings/net/minecraft/data/server/ItemTagsProvider.mapping
  mappings/net/minecraft/data/server/LootTablesProvider.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/validate/StructureValidatorProvider.mapping
  mappings/net/minecraft/recipe/RecipeType.mapping
  mappings/net/minecraft/recipe/RecipeUnlocker.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
Labels: new, ready to merge, snapshot

#1961 Complete Util mappings
  mappings/net/minecraft/util/Util.mapping
Labels: new, ready to merge

#1959 Readd documentation for the ServerPlayerEntity.closeHandledScreen method
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: bug, ready to merge

#1962 Backport getBoxAt
  .gitignore
  mappings/net/minecraft/entity/EntityDimensions.mapping
Labels: new, ready to merge, release

#1934 Switch to mappingpoet 0.2.0
  build.gradle
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/server/LanServerPinger.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/gen/feature/StructurePoolFeatureConfig.mapping
Labels: enhancement, javadoc, ready to merge, toolchain

#1965 Map block families
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/class_5797.mapping
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/family/BlockFamilies.mapping
  mappings/net/minecraft/data/family/BlockFamily.mapping
  mappings/net/minecraft/data/server/RecipesProvider.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonFactory.mapping
Labels: javadoc, new, ready to merge, snapshot

#1966 Realms data fetch stuff
  mappings/net/minecraft/client/realms/gui/BasicFetchRateLimiter.mapping
  mappings/net/minecraft/client/realms/gui/DummyFetchRateLimiter.mapping
  mappings/net/minecraft/client/realms/gui/FetchRateLimiter.mapping
  mappings/net/minecraft/client/realms/gui/FetchTask.mapping
  mappings/net/minecraft/client/realms/gui/RealmsDataFetcher.mapping
  mappings/net/minecraft/client/realms/util/RealmsPersistence.mapping
Labels: new, ready to merge, snapshot

#1968 Block package stuff
  mappings/net/minecraft/block/AbstractFireBlock.mapping
  mappings/net/minecraft/block/AbstractPlantPartBlock.mapping
  mappings/net/minecraft/block/AbstractPressurePlateBlock.mapping
  mappings/net/minecraft/block/AbstractSignBlock.mapping
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlastFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/block/entity/BrewingStandBlockEntity.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChestStateManager.mapping
  mappings/net/minecraft/block/entity/CommandBlockBlockEntity.mapping
  mappings/net/minecraft/block/entity/ComparatorBlockEntity.mapping
  mappings/net/minecraft/block/entity/ConduitBlockEntity.mapping
  mappings/net/minecraft/block/entity/DaylightDetectorBlockEntity.mapping
  mappings/net/minecraft/block/entity/DispenserBlockEntity.mapping
  mappings/net/minecraft/block/entity/EnchantingTableBlockEntity.mapping
  mappings/net/minecraft/block/entity/EndGatewayBlockEntity.mapping
  mappings/net/minecraft/block/entity/EndPortalBlockEntity.mapping
  mappings/net/minecraft/block/entity/FurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/block/entity/JukeboxBlockEntity.mapping
  mappings/net/minecraft/block/entity/LecternBlockEntity.mapping
  mappings/net/minecraft/block/entity/LootableContainerBlockEntity.mapping
  mappings/net/minecraft/block/entity/MobSpawnerBlockEntity.mapping
  mappings/net/minecraft/block/entity/ShulkerBoxBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/block/entity/SmokerBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/block/enums/StructureBlockMode.mapping
  mappings/net/minecraft/block/pattern/BlockPattern.mapping
  mappings/net/minecraft/block/piston/PistonHandler.mapping
  mappings/net/minecraft/block/sapling/LargeTreeSaplingGenerator.mapping
  mappings/net/minecraft/block/sapling/SaplingGenerator.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
Labels: new, ready to merge, snapshot

#1969 Add and update filled map related mappings.
  mappings/net/minecraft/client/gui/MapRenderer.mapping
  mappings/net/minecraft/client/render/MapRenderer.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/map/MapBannerMarker.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/network/packet/s2c/play/MapUpdateS2CPacket.mapping
  mappings/net/minecraft/world/PersistentState.mapping
Labels: new, ready to merge, snapshot

#1971 Advancement package stuff
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementPositioner.mapping
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/advancement/criterion/BeeNestDestroyedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BredAnimalsCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConstructBeaconCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemDurabilityChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemUsedOnBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ThrownItemPickedUpByEntityCriterion.mapping
Labels: new, ready to merge, snapshot

#1975 Client/gui package stuff
  mappings/net/minecraft/client/gui/hud/InGameOverlayRenderer.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/hud/SpectatorHud.mapping
  mappings/net/minecraft/client/gui/hud/SubtitlesHud.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenuCommand.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenuState.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeamTeleportSpectatorMenu.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeFlatLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/FatalErrorScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/LevelLoadingScreen.mapping
  mappings/net/minecraft/client/gui/screen/NoticeScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ScreenTexts.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTab.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTabType.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CommandBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantingPhrases.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/FurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LecternScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmokerScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StonecutterScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackOrganizer.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookResults.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/OrderedTextTooltipComponent.mapping
  mappings/net/minecraft/client/gui/widget/AbstractButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/ButtonListWidget.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/DoubleOptionSliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/gui/widget/TexturedButtonWidget.mapping
Labels: new, ready to merge, snapshot

#1976 Client package stuff
  mappings/net/minecraft/client/Keyboard.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/TrueTypeFont.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/item/BundleTooltipData.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/LanServerQueryManager.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/option/CloudRenderMode.mapping
  mappings/net/minecraft/client/option/HotbarStorageEntry.mapping
  mappings/net/minecraft/client/option/ServerList.mapping
  mappings/net/minecraft/client/recipebook/ClientRecipeBook.mapping
  mappings/net/minecraft/client/recipebook/RecipeBookGroup.mapping
  mappings/net/minecraft/client/resource/Format3ResourcePack.mapping
  mappings/net/minecraft/client/sound/AbstractBeeSoundInstance.mapping
  mappings/net/minecraft/client/sound/AggressiveBeeSoundInstance.mapping
  mappings/net/minecraft/client/sound/PassiveBeeSoundInstance.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/client/util/InputUtil.mapping
  mappings/net/minecraft/client/util/SelectionManager.mapping
  mappings/net/minecraft/client/util/VideoMode.mapping
  mappings/net/minecraft/client/world/GeneratorType.mapping
Labels: new, ready to merge, snapshot

#1974 Client/realms package stuff
  mappings/net/minecraft/client/realms/FileUpload.mapping
  mappings/net/minecraft/client/realms/RealmsLabel.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/dto/RealmsWorldOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/DisconnectedRealmsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsAcceptRejectButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupInfoScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBrokenWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsDownloadLatestWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsInviteScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongConfirmationScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningMcoTaskScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsNotificationsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsParentalConsentScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPendingInvitesScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/ResetWorldInfo.mapping
  mappings/net/minecraft/client/realms/task/LongRunningTask.mapping
  mappings/net/minecraft/client/realms/task/RealmsConnectTask.mapping
  mappings/net/minecraft/client/realms/task/ResettingWorldTask.mapping
  mappings/net/minecraft/client/realms/util/Errable.mapping
  mappings/net/minecraft/client/realms/util/RealmsTextureManager.mapping
Labels: new, ready to merge, snapshot

#1981 GrassPathBlock -> DirtPathBlock
  mappings/net/minecraft/block/DirtPathBlock.mapping
  mappings/net/minecraft/block/GrassPathBlock.mapping
Labels: ready to merge, refactor, snapshot

#1978 Schemas
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/schema/Schema2100.mapping
  mappings/net/minecraft/datafixer/schema/Schema2501.mapping
  mappings/net/minecraft/datafixer/schema/Schema2502.mapping
  mappings/net/minecraft/datafixer/schema/Schema2505.mapping
  mappings/net/minecraft/datafixer/schema/Schema2509.mapping
  mappings/net/minecraft/datafixer/schema/Schema2519.mapping
  mappings/net/minecraft/datafixer/schema/Schema2522.mapping
  mappings/net/minecraft/datafixer/schema/Schema2568.mapping
  mappings/net/minecraft/datafixer/schema/Schema2684.mapping
  mappings/net/minecraft/datafixer/schema/Schema2686.mapping
  mappings/net/minecraft/datafixer/schema/Schema2688.mapping
Labels: new, ready to merge, refactor

#1982 Map custom packet identifiers for game event debugging
  mappings/net/minecraft/network/packet/s2c/play/CustomPayloadS2CPacket.mapping
Labels: new, ready to merge, snapshot

#1972 Client/render package stuff
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayers.mapping
  mappings/net/minecraft/client/render/SkyProperties.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModels.mapping
  mappings/net/minecraft/client/render/block/BlockRenderManager.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/block/entity/PistonBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkRendererRegion.mapping
  mappings/net/minecraft/client/render/debug/BlockOutlineDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/ChunkLoadingDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameEventDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GoalSelectorDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/RaidCenterDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/StructureDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/VillageDebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/AxolotlEntityModel.mapping
  mappings/net/minecraft/client/render/item/BuiltinModelItemRenderer.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemModels.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/BasicBakedModel.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/json/ItemModelGenerator.mapping
Labels: new, ready to merge, snapshot

#1977 Added some recipe things
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeFinder.mapping
  mappings/net/minecraft/recipe/SmithingRecipe.mapping
Labels: bug, new, ready to merge, snapshot

#1973 Client/particle package stuff
  mappings/net/minecraft/client/particle/BarrierParticle.mapping
  mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
  mappings/net/minecraft/client/particle/DustColorTransitionParticle.mapping
  mappings/net/minecraft/client/particle/GlowParticle.mapping
  mappings/net/minecraft/client/particle/ItemPickupParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/RedDustParticle.mapping
  mappings/net/minecraft/client/particle/SpellParticle.mapping
  mappings/net/minecraft/client/particle/SquidInkParticle.mapping
  mappings/net/minecraft/client/particle/VibrationParticle.mapping
  mappings/net/minecraft/client/particle/WaterBubbleParticle.mapping
Labels: new, ready to merge, snapshot

#1984 Item package stuff
  mappings/net/minecraft/item/BucketItem.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/map/MapState.mapping
Labels: new, ready to merge, snapshot

#1983 Clarify the methods relating to entities ticking in the void
  mappings/net/minecraft/entity/Entity.mapping
Labels: javadoc, refactor, snapshot

#1985 Update enigma and javadoc
  build.gradle
  gradle.properties
  mappings/net/minecraft/block/MapColor.mapping
Labels: javadoc, ready to merge, snapshot, toolchain

#1990 Rename class_5778 -> AbstractLichenBlock and some field.
  mappings/net/minecraft/block/AbstractLichenBlock.mapping
Labels: new, ready to merge, snapshot

#1988 Loot package stuff
  mappings/net/minecraft/loot/LootManager.mapping
  mappings/net/minecraft/loot/LootPool.mapping
  mappings/net/minecraft/loot/condition/BlockStatePropertyLootCondition.mapping
  mappings/net/minecraft/loot/condition/EntityScoresLootCondition.mapping
  mappings/net/minecraft/loot/condition/LocationCheckLootCondition.mapping
  mappings/net/minecraft/loot/condition/LootConditionManager.mapping
  mappings/net/minecraft/loot/condition/ValueCheckLootCondition.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/context/LootContextTypes.mapping
  mappings/net/minecraft/loot/entry/CombinedEntry.mapping
  mappings/net/minecraft/loot/entry/LootPoolEntryTypes.mapping
  mappings/net/minecraft/loot/entry/SequenceEntry.mapping
  mappings/net/minecraft/loot/entry/TagEntry.mapping
  mappings/net/minecraft/loot/function/CopyStateFunction.mapping
  mappings/net/minecraft/loot/function/EnchantRandomlyLootFunction.mapping
  mappings/net/minecraft/loot/function/ExplorationMapLootFunction.mapping
  mappings/net/minecraft/loot/function/LootFunctionManager.mapping
  mappings/net/minecraft/loot/function/LootFunctionTypes.mapping
  mappings/net/minecraft/loot/function/SetAttributesLootFunction.mapping
  mappings/net/minecraft/loot/function/SetCountLootFunction.mapping
  mappings/net/minecraft/loot/function/SetDamageLootFunction.mapping
  mappings/net/minecraft/loot/function/SetEnchantmentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetStewEffectLootFunction.mapping
  mappings/net/minecraft/loot/operator/BoundedIntUnaryOperator.mapping
  mappings/net/minecraft/loot/provider/nbt/ContextLootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProvider.mapping
  mappings/net/minecraft/loot/provider/nbt/LootNbtProviderTypes.mapping
  mappings/net/minecraft/loot/provider/number/ConstantLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/number/LootNumberProviderTypes.mapping
  mappings/net/minecraft/loot/provider/number/ScoreLootNumberProvider.mapping
  mappings/net/minecraft/loot/provider/score/ContextLootScoreProvider.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProvider.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProviderTypes.mapping
Labels: new, ready to merge, snapshot

#1991 Test package stuff
  mappings/net/minecraft/test/GameTest.mapping
  mappings/net/minecraft/test/NotEnoughSuccessesError.mapping
  mappings/net/minecraft/test/StructureTestListener.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestCompletionListener.mapping
  mappings/net/minecraft/test/TestFailureLogger.mapping
  mappings/net/minecraft/test/TestFunction.mapping
  mappings/net/minecraft/test/TestFunctions.mapping
  mappings/net/minecraft/test/TestListener.mapping
  mappings/net/minecraft/test/TestRunner.mapping
  mappings/net/minecraft/test/TestSet.mapping
  mappings/net/minecraft/test/TestUtil.mapping
Labels: new, ready to merge, snapshot

#1987 Various stuff
  mappings/net/minecraft/block/FluidDrainable.mapping
  mappings/net/minecraft/client/gui/widget/DoubleOptionSliderWidget.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/state/StateManager.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
  mappings/net/minecraft/util/ItemScatterer.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/shape/BitSetVoxelSet.mapping
  mappings/net/minecraft/util/shape/CroppedVoxelSet.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/util/shape/VoxelShapes.mapping
Labels: bug, javadoc, new, ready to merge, refactor

#1995 Village package stuff
  mappings/net/minecraft/village/Merchant.mapping
  mappings/net/minecraft/village/MerchantInventory.mapping
  mappings/net/minecraft/village/SimpleMerchant.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
Labels: new, ready to merge, snapshot

#1997 Predicate package stuff
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/FluidPredicate.mapping
  mappings/net/minecraft/predicate/block/BlockStatePredicate.mapping
  mappings/net/minecraft/predicate/entity/DamageSourcePredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityFlagsPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicates.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/predicate/item/EnchantmentPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
Labels: new, ready to merge, snapshot

#1998 Recipe package stuff
  mappings/net/minecraft/recipe/BrewingRecipeRegistry.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/InputSlotFiller.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeFinder.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/RepairItemRecipe.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/SmithingRecipe.mapping
  mappings/net/minecraft/recipe/book/RecipeBookOptions.mapping
Labels: new, ready to merge, snapshot

#1999 Resource package stuff
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
Labels: new, ready to merge, snapshot

#2000 Scoreboard package stuff
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ServerScoreboard.mapping
  mappings/net/minecraft/scoreboard/Team.mapping
Labels: new, ready to merge, snapshot
