Repository FabricMC/yarn, pull requests merged in 2022-10, with the labels that each got.

#3306 Map some entity constants
  mappings/net/minecraft/entity/effect/StatusEffects.mapping
  mappings/net/minecraft/entity/mob/ElderGuardianEntity.mapping
  mappings/net/minecraft/entity/mob/HoglinEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBruteBrain.mapping
  mappings/net/minecraft/entity/mob/WardenBrain.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/mob/ZoglinEntity.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
Labels: new, ready to merge, release

#3307 Map some block entity constants
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/block/entity/BellBlockEntity.mapping
  mappings/net/minecraft/block/entity/BrewingStandBlockEntity.mapping
  mappings/net/minecraft/block/entity/ConduitBlockEntity.mapping
  mappings/net/minecraft/block/entity/DispenserBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSpreadManager.mapping
  mappings/net/minecraft/block/entity/ShulkerBoxBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/screen/LecternScreenHandler.mapping
  mappings/net/minecraft/screen/ShulkerBoxScreenHandler.mapping
Labels: new, ready to merge, release

#3316 NarratorMode and NarratorManager docs and minor renames
  mappings/net/minecraft/client/option/NarratorMode.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
Labels: refactor, ready to merge, release, javadoc

#3312 Map animation-related functions
  mappings/net/minecraft/client/render/entity/animation/AnimationHelper.mapping
  mappings/net/minecraft/client/render/entity/animation/Transformation.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: new, ready to merge, release

#3317 Document cauldrons
  mappings/net/minecraft/block/AbstractCauldronBlock.mapping
  mappings/net/minecraft/block/CauldronBlock.mapping
  mappings/net/minecraft/block/LavaCauldronBlock.mapping
  mappings/net/minecraft/block/LeveledCauldronBlock.mapping
  mappings/net/minecraft/block/PowderSnowCauldronBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  src/packageDocs/java/net/minecraft/block/cauldron/package-info.java
Labels: new, release, javadoc

#3320 Map some particles and sounds constants
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/particle/DragonBreathParticle.mapping
  mappings/net/minecraft/client/particle/GlowParticle.mapping
  mappings/net/minecraft/client/particle/VibrationParticle.mapping
  mappings/net/minecraft/client/particle/WhiteAshParticle.mapping
  mappings/net/minecraft/client/sound/AbstractSoundInstance.mapping
  mappings/net/minecraft/client/sound/AmbientSoundLoops.mapping
  mappings/net/minecraft/client/sound/AmbientSoundPlayer.mapping
  mappings/net/minecraft/client/sound/BiomeEffectSoundPlayer.mapping
  mappings/net/minecraft/client/sound/GuardianAttackSoundInstance.mapping
  mappings/net/minecraft/client/sound/MusicTracker.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
Labels: new, release

#3304 Document registry
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/DefaultedRegistry.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryCodecs.mapping
  mappings/net/minecraft/util/registry/RegistryEntry.mapping
  mappings/net/minecraft/util/registry/RegistryEntryList.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  src/packageDocs/java/net/minecraft/util/registry/package-info.java
Labels: release, javadoc

#3314 Map some item constants
  mappings/net/minecraft/fluid/LavaFluid.mapping
  mappings/net/minecraft/item/BowItem.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/FireworkRocketItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ShieldItem.mapping
  mappings/net/minecraft/item/TridentItem.mapping
  mappings/net/minecraft/item/WrittenBookItem.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
Labels: new, release

#3305 Document some math stuff
  mappings/net/minecraft/util/math/BlockBox.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/math/ColorHelper.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: release, javadoc

#3321 Add Documentation for core Particle classes
  mappings/net/minecraft/client/particle/BillboardParticle.mapping
  mappings/net/minecraft/client/particle/NoRenderParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleTextureSheet.mapping
  mappings/net/minecraft/client/particle/SpriteBillboardParticle.mapping
Labels: release, javadoc

#3326 22w42a datafixers
  mappings/net/minecraft/datafixer/fix/OptionsProgrammerArtFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3202.mapping
  mappings/net/minecraft/datafixer/schema/Schema3203.mapping
  mappings/net/minecraft/datafixer/schema/Schema3204.mapping
Labels: new, snapshot

#3329 22w42a resource
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/resource/DefaultClientResourcePack.mapping
  mappings/net/minecraft/client/resource/DefaultClientResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/ResourceIndex.mapping
  mappings/net/minecraft/client/resource/ServerResourcePackProvider.mapping
  mappings/net/minecraft/client/sound/Sound.mapping
  mappings/net/minecraft/resource/AbstractFileResourcePack.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/DefaultResourcePackBuilder.mapping
  mappings/net/minecraft/resource/DirectoryResourcePack.mapping
  mappings/net/minecraft/resource/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/InputSupplier.mapping
  mappings/net/minecraft/resource/LifecycledResourceManagerImpl.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/Resource.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
  mappings/net/minecraft/resource/ResourceFinder.mapping
  mappings/net/minecraft/resource/ResourcePack.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/ResourcePackSource.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloader.mapping
  mappings/net/minecraft/resource/VanillaDataPackProvider.mapping
  mappings/net/minecraft/resource/VanillaResourcePackProvider.mapping
  mappings/net/minecraft/resource/ZipResourcePack.mapping
  mappings/net/minecraft/resource/fs/ResourceFile.mapping
  mappings/net/minecraft/resource/fs/ResourceFileAttributes.mapping
  mappings/net/minecraft/resource/fs/ResourceFileStore.mapping
  mappings/net/minecraft/resource/fs/ResourceFileSystem.mapping
  mappings/net/minecraft/resource/fs/ResourceFileSystemProvider.mapping
  mappings/net/minecraft/resource/fs/ResourcePath.mapping
  mappings/net/minecraft/resource/metadata/PackResourceMetadata.mapping
  mappings/net/minecraft/resource/metadata/ResourceFilter.mapping
  mappings/net/minecraft/resource/metadata/ResourceMetadata.mapping
  mappings/net/minecraft/resource/metadata/ResourceMetadataMap.mapping
  mappings/net/minecraft/resource/metadata/ResourceMetadataSerializer.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/command/DatapackCommand.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/text/TextReorderingProcessor.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/Identifier.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3324 Rename the DynamicSerializableUuid class to Uuids
  mappings/net/minecraft/util/Uuids.mapping
Labels: bug, refactor, snapshot, impactful

#3332 22w42a itemgroups
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/ItemStackSet.mapping
Labels: new, snapshot

#3325 22w42a Camels
  mappings/net/minecraft/client/render/entity/CamelEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/animation/CamelAnimations.mapping
  mappings/net/minecraft/client/render/entity/model/CamelEntityModel.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/JumpingMount.mapping
  mappings/net/minecraft/entity/Saddleable.mapping
  mappings/net/minecraft/entity/ai/brain/task/RandomLookAroundTask.mapping
  mappings/net/minecraft/entity/ai/goal/AmbientStandGoal.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/entity/passive/CamelBrain.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
Labels: new, snapshot

#3327 22w42a Chiseled Bookshelves and Bamboo stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractButtonBlock.mapping
  mappings/net/minecraft/block/AbstractSignBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/ChiseledBookshelfBlock.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/PressurePlateBlock.mapping
  mappings/net/minecraft/block/WeightedPressurePlateBlock.mapping
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/class_7755.mapping
  mappings/net/minecraft/client/render/entity/model/BoatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ChestBoatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ChestRaftEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/client/render/entity/model/ModelWithWaterPatch.mapping
  mappings/net/minecraft/client/render/entity/model/RaftEntityModel.mapping
  mappings/net/minecraft/item/BannerItem.mapping
  mappings/net/minecraft/item/BlockItem.mapping
  mappings/net/minecraft/item/GoatHornItem.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/util/SignType.mapping
Labels: new, snapshot

#3309 Rename OreBlock to ExperienceDroppingBlock
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/ExperienceDroppingBlock.mapping
Labels: refactor, snapshot, impactful

#3330 22w42a datagen and recipecategory stuff
  mappings/net/minecraft/class_7791.mapping
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/DataOutput.mapping
  mappings/net/minecraft/data/MetadataProvider.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/ModelIds.mapping
  mappings/net/minecraft/data/client/TextureMap.mapping
  mappings/net/minecraft/data/family/BlockFamilies.mapping
  mappings/net/minecraft/data/family/BlockFamily.mapping
  mappings/net/minecraft/data/server/AbstractItemTagProvider.mapping
  mappings/net/minecraft/data/server/AdvancementProvider.mapping
  mappings/net/minecraft/data/server/AdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/BundleRecipeProvider.mapping
  mappings/net/minecraft/data/server/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/LootTableGenerator.mapping
  mappings/net/minecraft/data/server/LootTableProvider.mapping
  mappings/net/minecraft/data/server/OneTwentyBlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/OneTwentyBlockTagProvider.mapping
  mappings/net/minecraft/data/server/OneTwentyItemTagProvider.mapping
  mappings/net/minecraft/data/server/OneTwentyLootTableProviders.mapping
  mappings/net/minecraft/data/server/OneTwentyRecipeProvider.mapping
  mappings/net/minecraft/data/server/RecipeProvider.mapping
  mappings/net/minecraft/data/server/VanillaAdvancementProviders.mapping
  mappings/net/minecraft/data/server/VanillaBlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/VanillaEntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/VanillaLootTableProviders.mapping
  mappings/net/minecraft/data/server/VanillaRecipeProvider.mapping
  mappings/net/minecraft/data/server/recipe/ComplexRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/RecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/ShapelessRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SingleItemRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SmithingRecipeJsonBuilder.mapping
  mappings/net/minecraft/recipe/book/CookingRecipeCategory.mapping
  mappings/net/minecraft/recipe/book/CraftingRecipeCategory.mapping
  mappings/net/minecraft/recipe/book/RecipeCategory.mapping
Labels: refactor, new, snapshot

#3336 Fix typo
  mappings/net/minecraft/data/server/loottable/BlockLootTableGenerator.mapping
Labels: bug, ready to merge, snapshot

#3331 22w42a hanging signs
  mappings/net/minecraft/block/HangingSignBlock.mapping
  mappings/net/minecraft/block/SideShapeType.mapping
  mappings/net/minecraft/block/WallHangingSignBlock.mapping
  mappings/net/minecraft/block/entity/HangingSignBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractSignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HangingSignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/item/HangingSignItem.mapping
  mappings/net/minecraft/item/WallStandingBlockItem.mapping
  mappings/net/minecraft/util/math/RotationPropertyHelper.mapping
Labels: new, snapshot

#3328 22w42a Added Feature Toggle Mappings
  mappings/net/minecraft/resource/featuretoggle/FeatureFlag.mapping
  mappings/net/minecraft/resource/featuretoggle/FeatureFlags.mapping
  mappings/net/minecraft/resource/featuretoggle/FeatureManager.mapping
  mappings/net/minecraft/resource/featuretoggle/FeatureSet.mapping
  mappings/net/minecraft/resource/featuretoggle/FeatureUniverse.mapping
Labels: new, snapshot

#3337 22w42a util stuff
  mappings/net/minecraft/util/PathUtil.mapping
  mappings/net/minecraft/util/collection/WeightedList.mapping
  mappings/net/minecraft/util/profiler/ProfilerTiming.mapping
Labels: refactor, snapshot

#3165 Rename tick scheduling methods
  mappings/net/minecraft/world/WorldAccess.mapping
Labels: refactor, snapshot, impactful

#3333 22w42a registry
  mappings/net/minecraft/client/network/ClientDynamicRegistryType.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/CombinedDynamicRegistries.mapping
  mappings/net/minecraft/util/registry/DefaultedRegistry.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryCodecs.mapping
  mappings/net/minecraft/util/registry/RegistryEntry.mapping
  mappings/net/minecraft/util/registry/RegistryEntryList.mapping
  mappings/net/minecraft/util/registry/RegistryLoader.mapping
  mappings/net/minecraft/util/registry/SerializableRegistries.mapping
  mappings/net/minecraft/util/registry/ServerDynamicRegistryType.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/dimension/DimensionOptionsRegistryHolder.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/WorldGenSettings.mapping
Labels: refactor, new, snapshot, javadoc

#3345 Rename StackAdder to Entries
  mappings/net/minecraft/item/ItemGroup.mapping
Labels: refactor, snapshot

#3343 22w42a loot table
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/function/SetInstrumentLootFunction.mapping
Labels: bug, refactor, snapshot

#3341 22w42a blocks and items
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/SculkShriekerWarningManager.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/VerticallyAttachableBlockItem.mapping
  mappings/net/minecraft/item/WallStandingBlockItem.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3339 22w42a world
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/resource/featuretoggle/ToggleableFeature.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/EntityView.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/PortalForcer.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/WorldView.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/biome/BiomeParticleConfig.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/biome/GenerationSettings.mapping
  mappings/net/minecraft/world/event/listener/GameEventDispatchManager.mapping
  mappings/net/minecraft/world/event/listener/GameEventDispatcher.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
  mappings/net/minecraft/world/event/listener/VibrationSelector.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/poi/PointOfInterestTypes.mapping
  mappings/net/minecraft/world/spawner/CatSpawner.mapping
  mappings/net/minecraft/world/tick/TickPriority.mapping
Labels: bug, refactor, new, snapshot

#3347 Map method_45317 to setRunning
  mappings/net/minecraft/entity/AnimationState.mapping
Labels: new, snapshot

#3346 22w42a command
  mappings/net/minecraft/command/CommandRegistryAccess.mapping
  mappings/net/minecraft/command/CommandRegistryWrapper.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/EntitySelector.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/command/argument/BlockArgumentParser.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryPredicateArgumentType.mapping
  mappings/net/minecraft/server/command/AttributeCommand.mapping
  mappings/net/minecraft/server/command/EffectCommand.mapping
  mappings/net/minecraft/server/command/EnchantCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/ParticleCommand.mapping
  mappings/net/minecraft/server/command/PlaceCommand.mapping
  mappings/net/minecraft/server/command/SummonCommand.mapping
Labels: new, snapshot

#3354 22w42a recipe
  mappings/net/minecraft/recipe/AbstractCookingRecipe.mapping
  mappings/net/minecraft/recipe/BlastingRecipe.mapping
  mappings/net/minecraft/recipe/CampfireCookingRecipe.mapping
  mappings/net/minecraft/recipe/CookingRecipeSerializer.mapping
  mappings/net/minecraft/recipe/CraftingRecipe.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SmeltingRecipe.mapping
  mappings/net/minecraft/recipe/SmokingRecipe.mapping
  mappings/net/minecraft/recipe/SpecialCraftingRecipe.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
Labels: new, snapshot

#3353 Clarify required/enabled feature set
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/resource/featuretoggle/ToggleableFeature.mapping
Labels: refactor, snapshot

#3348 22w42a Experimental Warning Screen
  mappings/net/minecraft/client/gui/screen/pack/ExperimentalWarningScreen.mapping
Labels: new, snapshot

#3350 22w42a entity stuff
  mappings/net/minecraft/client/render/entity/animation/CamelAnimations.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/entity/passive/FrogBrain.mapping
Labels: refactor, new, snapshot

#3351 22w42a world stuff
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/gen/noise/BuiltinNoiseParameters.mapping
  mappings/net/minecraft/world/gen/structure/Structures.mapping
Labels: new, snapshot

#3349 22w42a data stuff
  mappings/net/minecraft/data/MetadataProvider.mapping
  mappings/net/minecraft/data/family/BlockFamily.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/resource/metadata/PackFeatureSetMetadata.mapping
Labels: new, snapshot

#3340 22w42a worldgen
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/util/math/noise/OctavePerlinNoiseSampler.mapping
  mappings/net/minecraft/world/gen/StructureAccessor.mapping
  mappings/net/minecraft/world/gen/StructureWeightSampler.mapping
  mappings/net/minecraft/world/gen/blockpredicate/BlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/HasSturdyFacePredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/InsideWorldBoundsBlockPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/MatchingBlockTagPredicate.mapping
  mappings/net/minecraft/world/gen/blockpredicate/SolidBlockPredicate.mapping
  mappings/net/minecraft/world/gen/carver/CaveCarverConfig.mapping
  mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/DebugChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorLayer.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/placement/ConcentricRingsStructurePlacement.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructurePlacement.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructurePlacementType.mapping
Labels: new, snapshot

#3334 22w42a world loading
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/LevelScreenProvider.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/world/GeneratorOptionsHolder.mapping
  mappings/net/minecraft/obfuscate/DontObfuscate.mapping
  mappings/net/minecraft/resource/DataConfiguration.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/SaveLoader.mapping
  mappings/net/minecraft/server/SaveLoading.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/biome/ColorResolver.mapping
  mappings/net/minecraft/world/dimension/DimensionsRegistryHolder.mapping
  mappings/net/minecraft/world/gen/FlatLevelGeneratorPreset.mapping
  mappings/net/minecraft/world/gen/FlatLevelGeneratorPresets.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/gen/WorldPreset.mapping
  mappings/net/minecraft/world/gen/WorldPresets.mapping
  mappings/net/minecraft/world/level/LevelInfo.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
  mappings/net/minecraft/world/storage/RegionBasedStorage.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3301 Rewrite mc downloading in filament
  .github/workflows/release-filament.yml
  build.gradle
  filament/build.gradle
  filament/gradle.properties
  filament/src/main/java/net/fabricmc/filament/FilamentExtension.java
  filament/src/main/java/net/fabricmc/filament/FilamentGradlePlugin.java
  filament/src/main/java/net/fabricmc/filament/task/DownloadTask.java
  filament/src/main/java/net/fabricmc/filament/task/JavadocLintTask.java
  filament/src/main/java/net/fabricmc/filament/task/MapJarTask.java
  filament/src/main/java/net/fabricmc/filament/task/base/FilamentTask.java
  filament/src/main/java/net/fabricmc/filament/task/base/FileOutputTask.java
  filament/src/main/java/net/fabricmc/filament/task/minecraft/ExtractBundledServerTask.java
  filament/src/main/java/net/fabricmc/filament/task/minecraft/MergeMinecraftTask.java
  filament/src/main/java/net/fabricmc/filament/task/minecraft/MinecraftLibrariesTask.java
  filament/src/main/java/net/fabricmc/filament/task/minecraft/MinecraftVersionMetaTask.java
  filament/src/test/resources/projects/javadocLint/build.gradle
  filament/src/test/resources/projects/unpickDef/build.gradle
  gradle.properties
Labels: toolchain

#3357 Update enigma
  gradle.properties
Labels: toolchain

#3355 22w42a everything else
  mappings/net/minecraft/Bootstrap.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/entity/EquipmentSlot.mapping
  mappings/net/minecraft/entity/ai/brain/task/BiasedLongJumpTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GiveInventoryToLookTargetTask.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtOps.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/structure/StructureTemplate.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryEntry.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3358 Rename the AbstractButtonBlock class to ButtonBlock
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/ButtonBlock.mapping
Labels: bug, refactor, snapshot

#3359 Rename CommandBlockItem
  mappings/net/minecraft/item/CommandBlockItem.mapping
  mappings/net/minecraft/item/OperatorOnlyBlockItem.mapping
Labels: bug, refactor, snapshot

#3342 22w42a sprites
  mappings/net/minecraft/class_7764.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/CamelEntityModel.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/Baker.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/render/model/MultipartUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/SpriteAtlasManager.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverrideList.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
  mappings/net/minecraft/client/render/model/json/WeightedUnbakedModel.mapping
  mappings/net/minecraft/client/texture/Animator.mapping
  mappings/net/minecraft/client/texture/MipmapHelper.mapping
  mappings/net/minecraft/client/texture/MissingSprite.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasHolder.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/SpriteContents.mapping
  mappings/net/minecraft/client/texture/SpriteDimensions.mapping
  mappings/net/minecraft/client/texture/SpriteLoader.mapping
  mappings/net/minecraft/client/texture/TextureStitcher.mapping
  mappings/net/minecraft/client/util/ModelIdentifier.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: new, snapshot

#3352 22w42a client
  mappings/net/minecraft/client/RunArgs.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/UnicodeTextureFont.mapping
  mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SoundOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/item/ClampedModelPredicateProvider.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/particle/BillboardParticle.mapping
  mappings/net/minecraft/client/particle/NoRenderParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/particle/ParticleTextureSheet.mapping
  mappings/net/minecraft/client/particle/SpriteBillboardParticle.mapping
  mappings/net/minecraft/client/particle/SpriteProvider.mapping
  mappings/net/minecraft/client/particle/VibrationParticle.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/render/block/BlockModels.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
  mappings/net/minecraft/client/sound/SoundLoader.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/util/MacWindowUtil.mapping
  mappings/net/minecraft/client/util/TelemetrySender.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/text/TextVisitFactory.mapping
  mappings/net/minecraft/util/TelemetryConstants.mapping
Labels: bug, refactor, new, snapshot

#3363 22w43a data stuff
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/DataProvider.mapping
  mappings/net/minecraft/data/Main.mapping
  mappings/net/minecraft/data/MetadataProvider.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
  mappings/net/minecraft/data/report/BlockListProvider.mapping
  mappings/net/minecraft/data/report/CommandSyntaxProvider.mapping
  mappings/net/minecraft/data/report/RegistryDumpProvider.mapping
  mappings/net/minecraft/data/report/WorldgenProvider.mapping
  mappings/net/minecraft/data/server/advancement/AdvancementProvider.mapping
  mappings/net/minecraft/data/server/loottable/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/LootTableProvider.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
Labels: new, snapshot

#3364 22w43a misc block and item stuff
  mappings/net/minecraft/block/CarvedPumpkinBlock.mapping
  mappings/net/minecraft/block/FenceGateBlock.mapping
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/block/entity/MobSpawnerBlockEntity.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/item/SkullItem.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
Labels: new, snapshot

#3362 22w43a entity stuff
  mappings/net/minecraft/block/LandingBlock.mapping
  mappings/net/minecraft/client/render/entity/animation/CamelAnimations.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/JumpingMount.mapping
  mappings/net/minecraft/entity/damage/BadRespawnPointDamageSource.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/damage/PositionedDamageSource.mapping
  mappings/net/minecraft/entity/damage/ProjectileDamageSource.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/passive/CamelBrain.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
Labels: refactor, new, snapshot

#3368 22w43a datagen part two
  mappings/net/minecraft/data/DataCache.mapping
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/SnbtProvider.mapping
  mappings/net/minecraft/data/client/ModelProvider.mapping
  mappings/net/minecraft/data/client/PropertiesMap.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
  mappings/net/minecraft/data/report/WorldgenProvider.mapping
  mappings/net/minecraft/data/server/loottable/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/LootTableProvider.mapping
  mappings/net/minecraft/data/server/tag/AbstractTagProvider.mapping
Labels: refactor, new, snapshot

#3370 Update javadoc links
  build.gradle
Labels: snapshot, javadoc, toolchain
