Repository FabricMC/yarn, pull requests merged in 2022-05, with the labels that each got.

#3122 Refactor vertex format stuff
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/VertexFormat.mapping
  mappings/net/minecraft/client/render/VertexFormatElement.mapping
  mappings/net/minecraft/client/render/VertexFormats.mapping
  unpick-definitions/gl.unpick
Labels: refactor, snapshot, javadoc

#3120 22w17a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/SculkShriekerBlock.mapping
  mappings/net/minecraft/block/entity/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/entity/InventoryOwner.mapping
  mappings/net/minecraft/entity/ai/brain/task/RamImpactTask.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeMaker.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/passive/AllayBrain.mapping
  mappings/net/minecraft/entity/passive/GoatBrain.mapping
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/item/GoatHornItem.mapping
  mappings/net/minecraft/loot/function/SetGoatHornSoundLootFunction.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/sound/SoundEvents.mapping
  mappings/net/minecraft/structure/StructureSets.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/root/RootPlacer.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
Labels: refactor, new, ready to merge, snapshot

#3127 Document deep dark preview series
  mappings/net/minecraft/SaveVersion.mapping
Labels: snapshot, javadoc

#3123 22w17a network stuff: part 2
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/ClientChatListener.mapping
  mappings/net/minecraft/client/gui/hud/ChatHudListener.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
  mappings/net/minecraft/client/util/ProfileKeys.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/network/ChatMessageSender.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/encryption/NetworkEncryptionException.mapping
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
  mappings/net/minecraft/network/encryption/PlayerKeyPair.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/network/packet/c2s/login/LoginKeyC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/CommandOutput.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: bug, outdated, refactor, new, ready to merge, snapshot, javadoc

#2992 Rename the ArmorStandEntity#slotFromPosition method to getSlotFromPosition
  mappings/net/minecraft/entity/decoration/ArmorStandEntity.mapping
Labels: refactor, ready to merge, snapshot

#3130 Fix javadoc of NetworkEncryptionUtils.encodeRsaPublicKey
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
Labels: snapshot, javadoc

#3131 Fix duplicate UUID entry in PacketByteBuf javadoc
  mappings/net/minecraft/network/PacketByteBuf.mapping
Labels: snapshot, javadoc

#3135 Map changes to banner patterns in 22w18a
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/entity/BannerPatterns.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/data/server/BannerPatternTagProvider.mapping
  mappings/net/minecraft/item/BannerItem.mapping
  mappings/net/minecraft/item/BannerPatternItem.mapping
  mappings/net/minecraft/loot/function/SetBannerPatternFunction.mapping
  mappings/net/minecraft/tag/BannerPatternTags.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: new, snapshot

#3136 Map message type and format
  mappings/net/minecraft/client/option/NarratorMode.mapping
  mappings/net/minecraft/network/MessageFormat.mapping
  mappings/net/minecraft/network/MessageType.mapping
Labels: new, snapshot

#3139 Small amount of Block Mappings + Game Events
  mappings/net/minecraft/block/CandleBlock.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/PropaguleBlock.mapping
  mappings/net/minecraft/block/SculkSpreadable.mapping
  mappings/net/minecraft/block/entity/EnchantingTableBlockEntity.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/event/GameEvent.mapping
  mappings/net/minecraft/world/event/listener/GameEventDispatcher.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/event/listener/SimpleGameEventDispatcher.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
Labels: new, ready to merge, snapshot

#3137 22w18a stuff
  mappings/net/minecraft/block/MultifaceGrowthBlock.mapping
  mappings/net/minecraft/block/entity/BannerPatterns.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/particle/SonicBoomParticle.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/data/client/Models.mapping
  mappings/net/minecraft/data/server/BiomeTagProvider.mapping
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/InstrumentTagProvider.mapping
  mappings/net/minecraft/datafixer/fix/GoatHornIdFix.mapping
  mappings/net/minecraft/entity/AnimationState.mapping
  mappings/net/minecraft/entity/ai/WardenAngerManager.mapping
  mappings/net/minecraft/entity/mob/Angriness.mapping
  mappings/net/minecraft/entity/mob/PathAwareEntity.mapping
  mappings/net/minecraft/item/GoatHornItem.mapping
  mappings/net/minecraft/item/Instrument.mapping
  mappings/net/minecraft/item/Instruments.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/PlaceCommand.mapping
  mappings/net/minecraft/server/command/PlaceFeatureCommand.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/sound/SoundEvent.mapping
  mappings/net/minecraft/sound/SoundEvents.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/tag/InstrumentTags.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/event/GameEvent.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
  mappings/net/minecraft/world/gen/StructureAccessor.mapping
  mappings/net/minecraft/world/gen/carver/CarverContext.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/DebugChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/util/FeatureContext.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/heightprovider/HeightProvider.mapping
  mappings/net/minecraft/world/gen/noise/NoiseRouter.mapping
  mappings/net/minecraft/world/gen/placementmodifier/AbstractConditionalPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/AbstractCountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/PlacementModifier.mapping
Labels: refactor, new, snapshot

#3134 Document net.minecraft.nbt package
  mappings/net/minecraft/nbt/AbstractNbtList.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/nbt/NbtByteArray.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtElement.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtIntArray.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtLongArray.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/nbt/NbtTagSizeTracker.mapping
  mappings/net/minecraft/nbt/NbtType.mapping
  mappings/net/minecraft/nbt/NbtTypes.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/nbt/visitor/NbtOrderedStringFormatter.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/nbt/visitor/StringNbtWriter.mapping
  src/packageDocs/java/net/minecraft/nbt/package-info.java
Labels: snapshot, javadoc

#3145 Rename identifierCodec and stringCodec in TagKey
  mappings/net/minecraft/tag/TagKey.mapping
Labels: refactor, snapshot

#3141 22w18a texts and utils
  mappings/net/minecraft/network/MessageFormat.mapping
  mappings/net/minecraft/text/BlockNbtDataSource.mapping
  mappings/net/minecraft/text/Decoration.mapping
  mappings/net/minecraft/text/EntityNbtDataSource.mapping
  mappings/net/minecraft/text/KeybindTextContent.mapping
  mappings/net/minecraft/text/KeybindTranslations.mapping
  mappings/net/minecraft/text/MutableText.mapping
  mappings/net/minecraft/text/NbtTextContent.mapping
  mappings/net/minecraft/text/OrderedText.mapping
  mappings/net/minecraft/text/ScoreTextContent.mapping
  mappings/net/minecraft/text/SelectorTextContent.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/text/TextColor.mapping
  mappings/net/minecraft/text/TranslatableTextContent.mapping
  mappings/net/minecraft/util/Formatting.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/StringHelper.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: refactor, new, snapshot, javadoc

#3149 22w18a misc
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
  mappings/net/minecraft/command/CommandRegistryAccess.mapping
  mappings/net/minecraft/command/CommandRegistryWrapper.mapping
  mappings/net/minecraft/command/argument/RegistryKeyArgumentType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/loot/condition/LootConditionConsumingBuilder.mapping
  mappings/net/minecraft/loot/entry/AlternativeEntry.mapping
  mappings/net/minecraft/loot/function/LootFunctionConsumingBuilder.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
  mappings/net/minecraft/tag/TagPacketSerializer.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
  mappings/net/minecraft/world/event/listener/EntityGameEventHandler.mapping
Labels: refactor, new, snapshot, javadoc

#3156 22w19a stuff
  mappings/net/minecraft/block/entity/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/command/argument/BlockMirrorArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockRotationArgumentType.mapping
  mappings/net/minecraft/command/argument/EnumArgumentType.mapping
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/client/ModelProvider.mapping
  mappings/net/minecraft/data/server/AbstractTagProvider.mapping
  mappings/net/minecraft/data/server/AdvancementProvider.mapping
  mappings/net/minecraft/data/server/BiomeParametersProvider.mapping
  mappings/net/minecraft/data/server/LootTableProvider.mapping
  mappings/net/minecraft/data/server/PointOfInterestTypeTagProvider.mapping
  mappings/net/minecraft/data/server/RecipeProvider.mapping
  mappings/net/minecraft/entity/ai/WardenAngerManager.mapping
  mappings/net/minecraft/entity/ai/brain/task/FindPointOfInterestTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/FindWalkTargetTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/ForgetAttackTargetTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/ForgetCompletedPointOfInterestTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GiveGiftsToHeroTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GoToCelebrateTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GoToIfNearbyTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/GoToNearbyPositionTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/HideInHomeTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/RoarTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/SniffTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/SonicBoomTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/TakeJobSiteTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/VillagerBreedTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/VillagerWorkTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkHomeTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkTowardJobSiteTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/WorkStationCompetitionTask.mapping
  mappings/net/minecraft/entity/ai/goal/MoveThroughVillageGoal.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/item/GoatHornItem.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/PlaceCommand.mapping
  mappings/net/minecraft/tag/PointOfInterestTypeTags.mapping
  mappings/net/minecraft/tag/TagBuilder.mapping
  mappings/net/minecraft/tag/TagEntry.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/util/BlockMirror.mapping
  mappings/net/minecraft/util/BlockRotation.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/village/VillagerProfession.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/poi/PointOfInterestType.mapping
  mappings/net/minecraft/world/poi/PointOfInterestTypes.mapping
Labels: refactor, new, snapshot

#3160 22w19a buffer builder
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/BufferRenderer.mapping
Labels: new, snapshot, javadoc

#3154 Rename partialTicks to tickDelta
  mappings/net/minecraft/entity/player/ItemCooldownManager.mapping
Labels: snapshot

#3159 22w19a misc
  mappings/net/minecraft/block/FrogspawnBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
  mappings/net/minecraft/client/realms/util/Realms32BitWarningChecker.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/entity/animation/AnimationHelper.mapping
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/command/CommandRegistryAccess.mapping
  mappings/net/minecraft/entity/AnimationState.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNode.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeNavigator.mapping
  mappings/net/minecraft/entity/passive/TadpoleEntity.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
  mappings/net/minecraft/world/gen/structure/StructureType.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
Labels: refactor, new, snapshot

#3140 Random renames
  mappings/net/minecraft/util/math/random/AbstractRandom.mapping
  mappings/net/minecraft/util/math/random/AsyncRandom.mapping
  mappings/net/minecraft/util/math/random/BaseRandom.mapping
  mappings/net/minecraft/util/math/random/CheckedRandom.mapping
  mappings/net/minecraft/util/math/random/GaussianGenerator.mapping
  mappings/net/minecraft/util/math/random/LocalRandom.mapping
  mappings/net/minecraft/util/math/random/Random.mapping
  mappings/net/minecraft/util/math/random/RandomDeriver.mapping
  mappings/net/minecraft/util/math/random/RandomSeed.mapping
  mappings/net/minecraft/util/math/random/RandomSplitter.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/gen/random/RandomSeed.mapping
Labels: refactor, snapshot

#3118 Move the ScreenTexts class to the net.minecraft.screen package
  mappings/net/minecraft/screen/ScreenTexts.mapping
Labels: refactor, ready to merge, snapshot

#3146 Fix name conflict with getPrimeSuspect
  mappings/net/minecraft/entity/ai/WardenAngerManager.mapping
Labels: bug, refactor, snapshot

#3163 1.19-pre1 stuff
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/class_7505.mapping
  mappings/net/minecraft/datafixer/fix/GoatHornIdFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemNbtFix.mapping
  mappings/net/minecraft/datafixer/fix/OminousBannerItemRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestRemoveFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveFilteredBookTextFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveFilteredSignTextFix.mapping
  mappings/net/minecraft/datafixer/fix/RenameVariantsFix.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/server/command/PlaceCommand.mapping
  mappings/net/minecraft/tag/TagEntry.mapping
  mappings/net/minecraft/tag/TagFile.mapping
  mappings/net/minecraft/util/LargeEntitySpawnHelper.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/StructureHolder.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/BiomeSources.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/dimension/DimensionTypeRegistrar.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerators.mapping
Labels: refactor, new, snapshot

#3176 Fix javadoc error caused by ScreenTexts repackaging
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
Labels: bug, snapshot, javadoc

#3174 Rename/repackage ChestAnimationProgress
  mappings/net/minecraft/block/entity/LidOpenable.mapping
  mappings/net/minecraft/client/block/ChestAnimationProgress.mapping
Labels: bug, refactor, snapshot, javadoc

#3172 Rename Text#copy and shallowCopy
  mappings/net/minecraft/text/Text.mapping
Labels: bug, refactor, snapshot

#3173 Move LargeEntitySpawnHelper to entity
  mappings/net/minecraft/entity/LargeEntitySpawnHelper.mapping
Labels: refactor, snapshot

#3164 1.19-pre1 networking
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/class_7516.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ChatPreviewWarningScreen.mapping
  mappings/net/minecraft/client/network/ChatPreviewRequester.mapping
  mappings/net/minecraft/client/network/ChatPreviewer.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/ServerList.mapping
  mappings/net/minecraft/client/util/ProfileKeys.mapping
  mappings/net/minecraft/command/argument/DecoratableArgumentType.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/network/ChatDecorator.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/encryption/ArgumentSignatureDataMap.mapping
  mappings/net/minecraft/network/encryption/ChatMessageSignature.mapping
  mappings/net/minecraft/network/encryption/ChatMessageSigner.mapping
  mappings/net/minecraft/network/encryption/CommandArgumentSigner.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/network/encryption/SignatureUpdatable.mapping
  mappings/net/minecraft/network/encryption/SignatureVerifier.mapping
  mappings/net/minecraft/network/encryption/SignedChatMessage.mapping
  mappings/net/minecraft/network/encryption/Signer.mapping
  mappings/net/minecraft/network/packet/c2s/login/LoginKeyC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/command/MessageCommand.mapping
  mappings/net/minecraft/server/command/SayCommand.mapping
  mappings/net/minecraft/server/command/TeamMsgCommand.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/filter/FilteredMessage.mapping
  mappings/net/minecraft/server/filter/Message.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/filter/TextStream.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/util/ApiServices.mapping
  mappings/net/minecraft/util/PendingTaskRunner.mapping
Labels: refactor, new, snapshot, javadoc

#3178 Rename AsyncRandom and nextPredictable
  mappings/net/minecraft/util/math/random/Random.mapping
  mappings/net/minecraft/util/math/random/ThreadSafeRandom.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/world/World.mapping
Labels: refactor, snapshot

#3189 1.19-pre2 stuff
  mappings/net/minecraft/block/JukeboxBlock.mapping
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/datafixer/fix/GoatMissingStateFix.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/DismountVehicleTask.mapping
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
  mappings/net/minecraft/entity/mob/GhastEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoiseSampler.mapping
  mappings/net/minecraft/village/VillagerProfession.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/VanillaSurfaceRules.mapping
Labels: new, snapshot

#3167 1.19-pre1 stuff
  mappings/net/minecraft/client/gui/screen/world/LevelScreenProvider.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsClientOutdatedScreen.mapping
  mappings/net/minecraft/data/DataCache.mapping
  mappings/net/minecraft/data/DataProvider.mapping
  mappings/net/minecraft/data/DataWriter.mapping
  mappings/net/minecraft/data/SnbtProvider.mapping
  mappings/net/minecraft/data/dev/NbtProvider.mapping
  mappings/net/minecraft/datafixer/fix/ItemNbtFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestFix.mapping
  mappings/net/minecraft/datafixer/fix/PointOfInterestRemoveFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveFilteredSignTextFix.mapping
  mappings/net/minecraft/datafixer/fix/RenameVariantsFix.mapping
  mappings/net/minecraft/entity/AnimationState.mapping
  mappings/net/minecraft/entity/ai/WardenAngerManager.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/server/command/PlaceCommand.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/registry/RegistryFixedCodec.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/source/BiomeSource.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/TheEndBiomeSource.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorConfig.mapping
Labels: new, snapshot

#3166 Map PlacedFeatureIndexer
  mappings/net/minecraft/class_7510.mapping
  mappings/net/minecraft/world/gen/feature/util/PlacedFeatureIndexer.mapping
Labels: new, snapshot, javadoc

#3192 Fix WorldEvents javadoc
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: snapshot, javadoc

#3190 1.19-pre3 stuff
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/FrogAttackablesSensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/FrogEatEntityTask.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/test/TestContext.mapping
Labels: new, snapshot

#3191 1.19-pre3 remaining stuff
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/network/encryption/ChatMessageSignature.mapping
Labels: new, snapshot, javadoc

#3193 Add `yarnCommon` task that opens enigma with only common classes
  README.md
  build.gradle
Labels: toolchain

#3187 Rename LivingEntity#applyEnchantmentsToDamage
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: bug, refactor, snapshot, javadoc

#3203 Fix typo
  mappings/net/minecraft/datafixer/fix/ItemNbtFix.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
  mappings/net/minecraft/world/StructureHolder.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
Labels: bug, snapshot
