Repository FabricMC/yarn, pull requests merged in 2022-01, with the labels that each got.

#2954 Fix more typos
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/entity/ai/pathing/AmphibiousPathNodeMaker.mapping
  mappings/net/minecraft/util/SystemDetails.mapping
  mappings/net/minecraft/world/gen/NoiseColumnSampler.mapping
Labels: bug, refactor, release

#2935 Drop 'color' prefix from color components
  mappings/net/minecraft/client/particle/AnimatedParticle.mapping
  mappings/net/minecraft/client/particle/BlockFallingDustParticle.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
Labels: refactor, release, impactful

#2938 Fix fov multiplier stuff
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
Labels: bug, refactor, release

#2952 Document what deprecated means in AbstractBlock
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: release, javadoc

#2948 Add mc version id into jar manifest
  build.gradle
Labels: enhancement, toolchain

#2955 Fix ClientWorld.Properties.setTime param
  mappings/net/minecraft/client/world/ClientWorld.mapping
Labels: bug, release

#2963 Fix ChunkGeneratorSettings param
  mappings/net/minecraft/world/gen/chunk/ChunkGeneratorSettings.mapping
Labels: bug, release

#2960 Rename remaining Tag to Nbt
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/datafixer/fix/StriderGravityFix.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/item/BlockItem.mapping
  mappings/net/minecraft/loot/function/CopyNbtLootFunction.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
Labels: bug, refactor, release

#2958 Swap the names of the VertexBuffer#vertexFormat and VertexBuffer#elementFormat fields
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
Labels: bug, refactor, release

#2956 Document MathHelper.binarySearch
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: release, javadoc

#2922 Rename Entity#inanimate
  mappings/net/minecraft/entity/Entity.mapping
Labels: bug, refactor, javadoc

#2903 Rename incorrectly-named intersectsEntities methods
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/EntityView.mapping
Labels: bug, refactor, release, impactful

#2914 Rename the ClientWorld#netHandler field to networkHandler
  mappings/net/minecraft/client/world/ClientWorld.mapping
Labels: bug, refactor, release

#2964 1.18.1 server.world stuff
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerEntityManager.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
Labels: new, release

#2895 Use suffixes for key binding fields in the GameOptions class
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
Labels: refactor, snapshot, impactful

#2970 Map the FogShape class
  mappings/net/minecraft/client/render/FogShape.mapping
  mappings/net/minecraft/client/render/Shader.mapping
Labels: new, snapshot

#2968 Rename 'integer' parameter and add name for lambda parameter in CampfireBlockEntity
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
Labels: new, ready to merge, snapshot

#2972 Rename the BlockStateModelGenerator#registerCauldron method to registerCauldrons
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
Labels: bug, refactor, snapshot

#2980 Rename FoodComponents#create -> createStew
  mappings/net/minecraft/item/FoodComponents.mapping
Labels: bug, refactor, ready to merge, snapshot

#2975 Fix entity param name for updateKilledAdvancementCriterion
  mappings/net/minecraft/entity/Entity.mapping
Labels: bug, ready to merge, snapshot

#2967 22w03a command stuff
  mappings/net/minecraft/command/argument/IdentifierArgumentType.mapping
  mappings/net/minecraft/command/suggestion/SuggestionProviders.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/PlaceFeatureCommand.mapping
  mappings/net/minecraft/server/command/SpreadPlayersCommand.mapping
Labels: new, ready to merge, snapshot

#2981 Rename AbstractBlock#hasSolidTopSurface to isSolidSurface
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: bug, refactor, ready to merge, snapshot

#2986 Rename net.minecraft.world.gen.decorator package to placementmodifier
  mappings/net/minecraft/world/gen/feature/FeaturePlacementContext.mapping
  mappings/net/minecraft/world/gen/feature/RangeFeatureConfig.mapping
  mappings/net/minecraft/world/gen/placementmodifier/AbstractConditionalPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/AbstractCountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/BiomePlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/BlockFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/CarvingMaskPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/CountMultilayerPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/CountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/EnvironmentScanPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/HeightRangePlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/HeightmapPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/NoiseBasedCountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/NoiseThresholdCountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/PlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/PlacementModifierType.mapping
  mappings/net/minecraft/world/gen/placementmodifier/RandomOffsetPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/RarityFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/SquarePlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/SurfaceThresholdFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/SurfaceWaterDepthFilterPlacementModifier.mapping
Labels: refactor, ready to merge, snapshot

#2985 Map some fields and params based around the dragon battle
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonSpawnState.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/ChargingPlayerPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/SittingAttackingPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/SittingFlamingPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/SittingScanningPhase.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/StrafePlayerPhase.mapping
Labels: new, ready to merge, snapshot

#2990 Pattern name BACKSLASH_S_PATTERN does not indicate what the pattern does
  mappings/net/minecraft/client/gui/screen/CommandSuggestor.mapping
Labels: bug, refactor, ready to merge, snapshot
