Repository FabricMC/yarn, pull requests merged in 2022-06, with the labels that each got.

#3039 Fix registry value being named key
  mappings/net/minecraft/util/registry/RegistryEntry.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
Labels: bug, ready to merge, snapshot

#3200 Rename ChatDecorator to MessageDecorator
  mappings/net/minecraft/network/ChatDecorator.mapping
  mappings/net/minecraft/network/MessageDecorator.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
Labels: refactor, snapshot, javadoc

#3198 Clarify that the "task runner" eats tasks
  mappings/net/minecraft/util/PendingTaskRunner.mapping
Labels: refactor, snapshot

#3185 Move message related stuff to a new package
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/network/message/ArgumentSignatureDataMap.mapping
  mappings/net/minecraft/network/message/ChatMessageSigner.mapping
  mappings/net/minecraft/network/message/CommandArgumentSigner.mapping
  mappings/net/minecraft/network/message/MessageDecorator.mapping
  mappings/net/minecraft/network/message/MessageSender.mapping
  mappings/net/minecraft/network/message/MessageSignature.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: refactor, snapshot

#3206 Improve MessageDecorator javadoc
  mappings/net/minecraft/network/message/MessageDecorator.mapping
Labels: bug, ready to merge, release, javadoc

#3208 peaks/valleys noise is a function of weirdness
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctions.mapping
Labels: refactor, new, release

#3211 Move the LanServerPinger class to the net.minecraft.client.network package
  mappings/net/minecraft/client/network/LanServerPinger.mapping
Labels: bug, refactor, release

#3199 1.19-pre4 stuff
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
Labels: new, release, javadoc

#3217 22w24a misc stuff
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/client/main/Main.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/client/util/ExponentialBackoff.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
Labels: new, snapshot

#3213 22w24a Allay Duplication mechanic and related
  mappings/net/minecraft/block/entity/JukeboxBlockEntity.mapping
  mappings/net/minecraft/client/render/entity/model/AllayEntityModel.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/item/MusicDiscItem.mapping
Labels: new, snapshot

#3219 Fix Type-O? getChtOpacity -> getChatOpacity
  mappings/net/minecraft/client/option/GameOptions.mapping
Labels: bug, snapshot

#3212 Add and fix mappings for structure placements
  mappings/net/minecraft/world/gen/chunk/placement/RandomSpreadStructurePlacement.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructurePlacement.mapping
Labels: bug, refactor, new, snapshot

#3207 Map density function (yikes)
  mappings/net/minecraft/world/gen/densityfunction/DensityFunction.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctionTypes.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctions.mapping
Labels: refactor, new, snapshot

#3204 1.19-pre5 stuff
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/chunk/ReadableContainer.mapping
  mappings/net/minecraft/world/gen/WorldPreset.mapping
Labels: new, snapshot, javadoc

#3227 Repackage abusereport
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/RunningTaskScreen.mapping
  mappings/net/minecraft/client/gui/screen/TaskScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/abusereport/ChatReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/report/AbuseReportReasonScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatSelectionScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/realms/util/RealmsPersistence.mapping
  mappings/net/minecraft/client/report/AbuseReportContext.mapping
  mappings/net/minecraft/client/report/AbuseReportReason.mapping
  mappings/net/minecraft/client/report/ChatLog.mapping
  mappings/net/minecraft/client/report/ChatLogImpl.mapping
  mappings/net/minecraft/client/report/GroupedMessagesCollector.mapping
  mappings/net/minecraft/client/report/ReceivedMessage.mapping
  mappings/net/minecraft/client/report/ReporterEnvironment.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/datafixer/fix/BlendingDataFix.mapping
  mappings/net/minecraft/datafixer/fix/BlendingDataRemoveFromNetherEndFix.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/NearestItemsSensor.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
Labels: refactor, snapshot
