Repository FabricMC/yarn, pull requests merged in 2022-04, with the labels that each got.

#3071 22w13a client
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/option/CloudRenderMode.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
Labels: new, snapshot, javadoc

#3075 Fix wrong mappings at InGameHud
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
Labels: bug, snapshot

#3081 22w14a stuff
  mappings/net/minecraft/class_7373.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/realms/FileDownload.mapping
  mappings/net/minecraft/client/realms/exception/RealmsDefaultUncaughtExceptionHandler.mapping
  mappings/net/minecraft/client/sound/AbstractSoundInstance.mapping
  mappings/net/minecraft/client/sound/EntityTrackingSoundInstance.mapping
  mappings/net/minecraft/client/sound/PositionedSoundInstance.mapping
  mappings/net/minecraft/client/sound/Sound.mapping
  mappings/net/minecraft/client/sound/SoundContainer.mapping
  mappings/net/minecraft/client/sound/SoundInstance.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/texture/ResourceTexture.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/datafixer/fix/AdvancementCriteriaRenameFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandler.mapping
  mappings/net/minecraft/entity/passive/AllayBrain.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntitySpawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlaySoundFromEntityS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlaySoundIdS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlaySoundS2CPacket.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/Resource.mapping
  mappings/net/minecraft/resource/metadata/ResourceMetadata.mapping
  mappings/net/minecraft/sound/SoundEvents.mapping
  mappings/net/minecraft/util/dynamic/EntryLoader.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/util/math/floatprovider/FloatSupplier.mapping
  mappings/net/minecraft/util/math/floatprovider/MultipliedFloatSupplier.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/entity/EntityHandler.mapping
  mappings/net/minecraft/world/event/listener/SculkSensorListener.mapping
Labels: new, snapshot

#3085 22w14a stuff 2: electric boogaloo
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/render/entity/feature/WardenFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/client/render/entity/model/WardenEntityModel.mapping
  mappings/net/minecraft/data/server/EntityLootTableGenerator.mapping
  mappings/net/minecraft/entity/ai/WardenAngerManager.mapping
  mappings/net/minecraft/entity/ai/brain/task/GiveInventoryToLookTargetTask.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/passive/AllayBrain.mapping
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/PlayerPredicate.mapping
  mappings/net/minecraft/predicate/entity/TypeSpecificPredicate.mapping
  mappings/net/minecraft/predicate/entity/VariantPredicates.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/event/listener/EntityGameEventHandler.mapping
  mappings/net/minecraft/world/event/listener/GameEventDispatcher.mapping
  mappings/net/minecraft/world/event/listener/SimpleGameEventDispatcher.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/DiskFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/EndSpikeFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/HugeMushroomFeature.mapping
  mappings/net/minecraft/world/gen/feature/MiscConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/MiscPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/MultifaceGrowthFeature.mapping
  mappings/net/minecraft/world/gen/feature/MultifaceGrowthFeatureConfig.mapping
  mappings/net/minecraft/world/gen/feature/SmallDripstoneFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreePlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/TwistingVinesFeature.mapping
  mappings/net/minecraft/world/gen/feature/UndergroundConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/UndergroundPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPatchFeature.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/WeepingVinesFeature.mapping
  mappings/net/minecraft/world/gen/treedecorator/TreeDecorator.mapping
  unpick-definitions/cat_types.unpick
  unpick-definitions/entity_model_parts.unpick
Labels: refactor, new, ready to merge, snapshot

#3088 Fix typo: FrogEntityModel.rightLEg -> rightLeg
  mappings/net/minecraft/client/render/entity/model/FrogEntityModel.mapping
Labels: bug, ready to merge, snapshot

#3089 22w14a typo fixing
  mappings/net/minecraft/client/gui/screen/option/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
  mappings/net/minecraft/datafixer/fix/AdvancementCriteriaRenameFix.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/loot/function/SetContentsLootFunction.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  unpick-definitions/entity_status.unpick
Labels: refactor, ready to merge, snapshot

#3077 Codec Mappings and some misc stuff
  mappings/net/minecraft/structure/pool/SinglePoolElement.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
  mappings/net/minecraft/structure/pool/StructurePoolElement.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorType.mapping
  mappings/net/minecraft/util/math/noise/DoublePerlinNoiseSampler.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunction.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctionTypes.mapping
Labels: refactor, new, snapshot

#3079 22w14a de-featured structures
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/gen/feature/BasicTempleStructureFeature.mapping
  mappings/net/minecraft/world/gen/feature/BuriedTreasureFeature.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeatureKeys.mapping
  mappings/net/minecraft/world/gen/feature/DesertPyramidFeature.mapping
  mappings/net/minecraft/world/gen/feature/EndCityFeature.mapping
  mappings/net/minecraft/world/gen/feature/IglooFeature.mapping
  mappings/net/minecraft/world/gen/feature/JungleTempleFeature.mapping
  mappings/net/minecraft/world/gen/feature/NetherFossilFeature.mapping
  mappings/net/minecraft/world/gen/feature/OceanRuinFeature.mapping
  mappings/net/minecraft/world/gen/feature/ShipwreckFeature.mapping
  mappings/net/minecraft/world/gen/feature/StrongholdFeature.mapping
  mappings/net/minecraft/world/gen/feature/SwampHutFeature.mapping
  mappings/net/minecraft/world/gen/feature/WoodlandMansionFeature.mapping
  mappings/net/minecraft/world/gen/structure/BasicTempleStructure.mapping
  mappings/net/minecraft/world/gen/structure/BuriedTreasureStructure.mapping
  mappings/net/minecraft/world/gen/structure/DesertPyramidStructure.mapping
  mappings/net/minecraft/world/gen/structure/EndCityStructure.mapping
  mappings/net/minecraft/world/gen/structure/IglooStructure.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
  mappings/net/minecraft/world/gen/structure/JungleTempleStructure.mapping
  mappings/net/minecraft/world/gen/structure/MineshaftStructure.mapping
  mappings/net/minecraft/world/gen/structure/NetherFortressStructure.mapping
  mappings/net/minecraft/world/gen/structure/NetherFossilStructure.mapping
  mappings/net/minecraft/world/gen/structure/OceanMonumentStructure.mapping
  mappings/net/minecraft/world/gen/structure/OceanRuinStructure.mapping
  mappings/net/minecraft/world/gen/structure/RuinedPortalStructure.mapping
  mappings/net/minecraft/world/gen/structure/ShipwreckStructure.mapping
  mappings/net/minecraft/world/gen/structure/StrongholdStructure.mapping
  mappings/net/minecraft/world/gen/structure/StructureType.mapping
  mappings/net/minecraft/world/gen/structure/StructureTypeKeys.mapping
  mappings/net/minecraft/world/gen/structure/StructureTypes.mapping
  mappings/net/minecraft/world/gen/structure/SwampHutStructure.mapping
  mappings/net/minecraft/world/gen/structure/WoodlandMansionStructure.mapping
Labels: refactor, snapshot

#3090 22w15a stuff
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: refactor, new, ready to merge, snapshot

#3074 Fix several mapping bugs (1.18.2 backport)
  mappings/net/minecraft/block/AbstractRailBlock.mapping
  mappings/net/minecraft/block/RailPlacementHelper.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/util/registry/RegistryEntry.mapping
Labels: bug, release

#3092 22w15a more stuff
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/resource/ClientBuiltinResourcePackProvider.mapping
  mappings/net/minecraft/data/DataCache.mapping
  mappings/net/minecraft/data/DataGenerator.mapping
  mappings/net/minecraft/data/DataProvider.mapping
  mappings/net/minecraft/data/DataWriter.mapping
  mappings/net/minecraft/data/Main.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/BlendingDataFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/world/World.mapping
Labels: refactor, new, snapshot, javadoc

#3093 Update deps
  .gitattributes
  .github/workflows/build.yml
  HEADER
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/constants/java/net/fabricmc/yarn/constants/package-info.java
  src/packageDocs/java/net/minecraft/package-info.java
  src/packageDocs/java/net/minecraft/resource/package-info.java
  unpick-logging.properties
Labels: toolchain

#3094 Fix typo in SimpleOptions
  mappings/net/minecraft/client/option/SimpleOption.mapping
Labels: bug, snapshot, javadoc

#3041 Map woodland mansion generation
  mappings/net/minecraft/structure/WoodlandMansionGenerator.mapping
  unpick-definitions/woodland_mansion.unpick
Labels: bug, new, ready to merge, snapshot, javadoc, unpick

#3099 Rename the Bucketable#getBucketedSound method to getBucketFillSound
  mappings/net/minecraft/entity/Bucketable.mapping
Labels: bug, refactor, ready to merge

#3098 Rename the HorseBaseEntity class to AbstractHorseEntity
  mappings/net/minecraft/client/render/entity/AbstractHorseEntityRenderer.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  unpick-definitions/entity_flags.unpick
Labels: refactor, ready to merge

#3106 Fix AtomicSimpleRandom package
  mappings/net/minecraft/util/math/random/AtomicSimpleRandom.mapping
Labels: bug, ready to merge, snapshot

#3107 22w16b client
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/screen/LoadingDisplay.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/util/GlException.mapping
Labels: new, snapshot

#3105 Text renames
  mappings/net/minecraft/class_7417.mapping
  mappings/net/minecraft/class_7419.mapping
  mappings/net/minecraft/text/BlockNbtDataSource.mapping
  mappings/net/minecraft/text/EntityNbtDataSource.mapping
  mappings/net/minecraft/text/KeybindTextContent.mapping
  mappings/net/minecraft/text/KeybindTranslations.mapping
  mappings/net/minecraft/text/LiteralTextContent.mapping
  mappings/net/minecraft/text/MutableText.mapping
  mappings/net/minecraft/text/NbtDataSource.mapping
  mappings/net/minecraft/text/NbtTextContent.mapping
  mappings/net/minecraft/text/ScoreTextContent.mapping
  mappings/net/minecraft/text/SelectorTextContent.mapping
  mappings/net/minecraft/text/StorageNbtDataSource.mapping
  mappings/net/minecraft/text/StorageNbtText.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/text/TextContent.mapping
  mappings/net/minecraft/text/Texts.mapping
  mappings/net/minecraft/text/TranslatableTextContent.mapping
Labels: refactor, new, ready to merge, snapshot

#3104 Simplify codec names in `MaterialRules`
  mappings/net/minecraft/world/gen/surfacebuilder/MaterialRules.mapping
Labels: refactor, ready to merge, snapshot

#3109 22w16b stuff
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/datafixer/fix/EntityPaintingFieldsRenameFix.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/server/ServerConfigHandler.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/test/GameTestException.mapping
  mappings/net/minecraft/test/TickLimitExceededException.mapping
  mappings/net/minecraft/util/InvalidIdentifierException.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/collection/PackedIntegerArray.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/level/storage/LevelStorageException.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
Labels: refactor, new, ready to merge, snapshot

#3097 Rename the PotionEntity#damageEntitiesHurtByWater method to applyWater
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
Labels: bug, refactor, snapshot

#3116 Rename the CampfireBlock#doesBlockCauseSignalFire method to isSignalFireBaseBlock
  mappings/net/minecraft/block/CampfireBlock.mapping
Labels: refactor, snapshot

#3117 Rename the ChestBlock.hasOcelotOnTop method to hasCatOnTop
  mappings/net/minecraft/block/ChestBlock.mapping
Labels: refactor, snapshot

#3119 Fix some registry key fields not being suffixed
  mappings/net/minecraft/util/registry/Registry.mapping
Labels: bug, refactor, ready to merge, snapshot

#3121 22w17a: Network stuff + more
  mappings/net/minecraft/entity/passive/GoatEntity.mapping
  mappings/net/minecraft/network/ChatMessageSender.mapping
  mappings/net/minecraft/network/encryption/NetworkEncryptionUtils.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameMessageS2CPacket.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, ready to merge, snapshot

#3126 Fix LevelStorageException name conflict
  mappings/net/minecraft/world/level/storage/LevelStorageException.mapping
Labels: bug, ready to merge, snapshot

#3124 22w17a stuff
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
  mappings/net/minecraft/util/TextifiedException.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, ready to merge, snapshot, javadoc
