Repository FabricMC/yarn, pull requests merged in 2022-09, with the labels that each got.

#3283 Document some rendering stuff
  mappings/net/minecraft/client/gl/GlUniform.mapping
  mappings/net/minecraft/client/gl/Program.mapping
  mappings/net/minecraft/client/gl/Uniform.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/BufferRenderer.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/Shader.mapping
  mappings/net/minecraft/client/render/Tessellator.mapping
  mappings/net/minecraft/client/render/VertexConsumer.mapping
  mappings/net/minecraft/client/render/VertexConsumerProvider.mapping
  mappings/net/minecraft/client/render/VertexFormat.mapping
  mappings/net/minecraft/client/render/VertexFormats.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: release, javadoc

#3290 Fix typo and outdated javadoc
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerType.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
Labels: release, javadoc

#3291 Rename the AbstractClientPlayerEntity#cachedScoreboardEntry field to playerListEntry
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
Labels: bug, refactor, release

#3293 Document screen narration
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/narration/Narration.mapping
  mappings/net/minecraft/client/gui/screen/narration/NarrationMessageBuilder.mapping
  mappings/net/minecraft/client/gui/screen/narration/NarrationPart.mapping
  mappings/net/minecraft/client/gui/screen/narration/ScreenNarrator.mapping
  src/packageDocs/java/net/minecraft/client/gui/screen/narration/package-info.java
Labels: bug, release, javadoc

#3294 Resolve more javadoc links
  build.gradle
Labels: release, javadoc, toolchain

#3296 Move filament into yarn repo.
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/update-base.yml
  build.gradle
  filament/build.gradle
  filament/checkstyle.xml
  filament/settings.gradle
  filament/src/main/java/net/fabricmc/filament/FilamentGradlePlugin.java
  filament/src/main/java/net/fabricmc/filament/task/CombineUnpickDefinitionsTask.java
  filament/src/main/java/net/fabricmc/filament/task/GeneratePackageInfoMappingsTask.java
  filament/src/main/java/net/fabricmc/filament/task/JavadocLintTask.java
  filament/src/main/java/net/fabricmc/filament/task/RemapUnpickDefinitionsTask.java
  filament/src/main/java/net/fabricmc/filament/util/FileUtil.java
  filament/src/main/java/net/fabricmc/filament/util/UnpickUtil.java
  filament/src/test/README.md
  filament/src/test/java/net/fabricmc/filament/test/FileUtilTest.java
  filament/src/test/java/net/fabricmc/filament/test/JavadocLintTest.java
  filament/src/test/java/net/fabricmc/filament/test/ProjectTest.java
  filament/src/test/java/net/fabricmc/filament/test/UnpickDefinitionsTest.java
  filament/src/test/resources/projects/javadocLint/build.gradle
  filament/src/test/resources/projects/javadocLint/mappings/ParamInMethod.mapping
  filament/src/test/resources/projects/javadocLint/mappings/ParamPeriod.mapping
  filament/src/test/resources/projects/javadocLint/mappings/Successful.mapping
  filament/src/test/resources/projects/javadocLint/mappings/UppercaseParam.mapping
  filament/src/test/resources/projects/javadocLint/settings.gradle
  filament/src/test/resources/projects/sharedData/yarn-mappings-v2.tiny
  filament/src/test/resources/projects/unpickDef/build.gradle
  filament/src/test/resources/projects/unpickDef/expected_intermediary.unpick
  filament/src/test/resources/projects/unpickDef/expected_named.unpick
  filament/src/test/resources/projects/unpickDef/settings.gradle
  filament/src/test/resources/projects/unpickDef/unpick-definitions/screen_handler_slot_ids.unpick
  filament/src/test/resources/projects/unpickDef/unpick-definitions/set_block_state_flags.unpick
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: toolchain

#3298 Fix method name for `CsvWriter#print`
  mappings/net/minecraft/util/CsvWriter.mapping
Labels: bug, refactor, ready to merge, release

#3302 Fix javadoc for PacketByteBuf#writeIdentifier
  mappings/net/minecraft/network/PacketByteBuf.mapping
Labels: ready to merge, release, javadoc

#3300 Move jar remapping to Filament
  build.gradle
  filament/build.gradle
  filament/src/main/java/net/fabricmc/filament/task/MapJarTask.java
Labels: release, toolchain

#3297 Document net.minecraft.util
  mappings/net/minecraft/util/ActionResult.mapping
  mappings/net/minecraft/util/ApiServices.mapping
  mappings/net/minecraft/util/Arm.mapping
  mappings/net/minecraft/util/Clearable.mapping
  mappings/net/minecraft/util/DyeColor.mapping
  mappings/net/minecraft/util/FileNameUtil.mapping
  mappings/net/minecraft/util/FixedBufferInputStream.mapping
  mappings/net/minecraft/util/Hand.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/InvalidIdentifierException.mapping
  mappings/net/minecraft/util/ItemScatterer.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/Lazy.mapping
  mappings/net/minecraft/util/Nameable.mapping
  mappings/net/minecraft/util/StringHelper.mapping
  mappings/net/minecraft/util/StringIdentifiable.mapping
  mappings/net/minecraft/util/SystemDetails.mapping
  mappings/net/minecraft/util/TextifiedException.mapping
  mappings/net/minecraft/util/TimeHelper.mapping
  mappings/net/minecraft/util/TranslatableOption.mapping
  mappings/net/minecraft/util/Util.mapping
  src/packageDocs/java/net/minecraft/util/package-info.java
Labels: release, javadoc
