Repository FabricMC/yarn, pull requests merged in 2022-02, with the labels that each got.

#2993 22w05a stuff
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/datafixer/fix/WeaponsmithChestLootTableFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/goal/EscapeDangerGoal.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredFeature.mapping
  mappings/net/minecraft/world/gen/feature/util/DripstoneHelper.mapping
Labels: new, snapshot, javadoc

#2962 Move, rename and document spawners
  mappings/net/minecraft/world/gen/CatSpawner.mapping
  mappings/net/minecraft/world/gen/PhantomSpawner.mapping
  mappings/net/minecraft/world/gen/PillagerSpawner.mapping
  mappings/net/minecraft/world/gen/Spawner.mapping
  mappings/net/minecraft/world/spawner/CatSpawner.mapping
  mappings/net/minecraft/world/spawner/PatrolSpawner.mapping
  mappings/net/minecraft/world/spawner/PhantomSpawner.mapping
  mappings/net/minecraft/world/spawner/Spawner.mapping
Labels: refactor, snapshot

#2971 22w03a stuff
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/gui/screen/DownloadingTerrainScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/entity/FallingBlockEntity.mapping
  mappings/net/minecraft/entity/ai/goal/MoveToRaidCenterGoal.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/item/BoneMealItem.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/scanner/ExclusiveNbtCollector.mapping
  mappings/net/minecraft/nbt/scanner/NbtScanQuery.mapping
  mappings/net/minecraft/nbt/scanner/NbtTreeNode.mapping
  mappings/net/minecraft/nbt/scanner/SelectiveNbtCollector.mapping
  mappings/net/minecraft/nbt/scanner/Tree.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/network/listener/ServerPacketListener.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/world/ChunkTaskPrioritySystem.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/LevelPrioritizedQueue.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerEntityManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/thread/TaskExecutor.mapping
  mappings/net/minecraft/util/thread/ThreadExecutor.mapping
  mappings/net/minecraft/world/RaycastContext.mapping
  mappings/net/minecraft/world/gen/feature/CoralFeature.mapping
  mappings/net/minecraft/world/gen/heightprovider/UniformHeightProvider.mapping
  mappings/net/minecraft/world/gen/treedecorator/BeehiveTreeDecorator.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
Labels: new, ready to merge, snapshot

#2953 Map spline
  mappings/net/minecraft/util/math/Spline.mapping
Labels: new, snapshot

#2891 Document ServerWorld stuff
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/BlockRenderView.mapping
  mappings/net/minecraft/world/BlockView.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/EntityView.mapping
  mappings/net/minecraft/world/ModifiableWorld.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/WorldView.mapping
Labels: snapshot, javadoc

#2987 Rename Screen#removed and Screen#onClose
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
Labels: refactor, snapshot

#2973 Rename the BlockStateModelGenerator#registerCarpet method to registerWoolAndCarpet
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
Labels: bug, refactor, snapshot

#2984 Rename NarratorOptionsScreen -> SimpleOptionsScreen
  mappings/net/minecraft/client/gui/screen/option/SimpleOptionsScreen.mapping
Labels: refactor, snapshot

#2974 Rename the Texture class to TextureMap
  mappings/net/minecraft/data/client/model/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/model/Model.mapping
  mappings/net/minecraft/data/client/model/Models.mapping
  mappings/net/minecraft/data/client/model/TextureMap.mapping
  mappings/net/minecraft/data/client/model/TexturedModel.mapping
Labels: refactor, snapshot, impactful

#2969 some random stuff
  mappings/net/minecraft/block/PointedDripstoneBlock.mapping
  mappings/net/minecraft/block/dispenser/ShearsDispenserBehavior.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/Shader.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/task/OpenDoorsTask.mapping
  mappings/net/minecraft/server/world/ChunkTaskPrioritySystem.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerEntityManager.mapping
  mappings/net/minecraft/world/RaycastContext.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
  mappings/net/minecraft/world/chunk/ChunkManager.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/gen/surfacebuilder/MaterialRules.mapping
Labels: new, snapshot

#2978 Fix some setters not matching fields and params
  mappings/net/minecraft/block/entity/EnchantingTableBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/gl/GlUniform.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/realms/task/LongRunningTask.mapping
  mappings/net/minecraft/client/render/debug/RaidCenterDebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/ai/pathing/Path.mapping
  mappings/net/minecraft/entity/boss/BossBar.mapping
  mappings/net/minecraft/entity/mob/Angerable.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/EvokerEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/VexEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/ChickenEntity.mapping
  mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/passive/WanderingTraderEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/player/HungerManager.mapping
  mappings/net/minecraft/entity/raid/RaiderEntity.mapping
  mappings/net/minecraft/entity/vehicle/HopperMinecartEntity.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateJigsawC2SPacket.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/structure/Structure.mapping
  mappings/net/minecraft/village/Merchant.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/MutableWorldProperties.mapping
  mappings/net/minecraft/world/SaveProperties.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/entity/EntityLike.mapping
  mappings/net/minecraft/world/level/ServerWorldProperties.mapping
Labels: bug, refactor, snapshot

#3001 Map the RegistryEntryList class
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/registry/RegistryEntryList.mapping
Labels: new, snapshot

#2996 22w06a stuff
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/class_6864.mapping
  mappings/net/minecraft/datafixer/fix/StructureSettingsFlattenFix.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/ai/goal/PowderSnowJumpGoal.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/tag/Tag.mapping
  mappings/net/minecraft/tag/TagKey.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
  mappings/net/minecraft/util/collection/IndexedIterable.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/DefaultedRegistry.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/MutableRegistry.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryEntry.mapping
  mappings/net/minecraft/util/registry/RegistryEntryList.mapping
  mappings/net/minecraft/util/registry/RegistryEntryListCodec.mapping
  mappings/net/minecraft/util/registry/RegistryFixedCodec.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/biome/GenerationSettings.mapping
  mappings/net/minecraft/world/event/GameEvent.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeatures.mapping
  mappings/net/minecraft/world/gen/feature/PlacedFeatures.mapping
Labels: new, snapshot

#2997 Map structure placements
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/placement/ConcentricRingsStructurePlacement.mapping
  mappings/net/minecraft/world/gen/chunk/placement/RandomSpreadStructurePlacement.mapping
  mappings/net/minecraft/world/gen/chunk/placement/SpreadType.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructurePlacement.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructurePlacementType.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructuresConfig.mapping
Labels: new, snapshot

#2921 Rename some builder classes
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/data/server/recipe/ComplexRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/ShapelessRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SingleItemRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SmithingRecipeJsonBuilder.mapping
Labels: outdated, refactor, snapshot, impactful

#2994 Map some random entity stuff
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/goal/FollowGroupLeaderGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FollowParentGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FormCaravanGoal.mapping
Labels: refactor, new, snapshot

#2998 22w06a resources
  mappings/net/minecraft/resource/LifecycledResourceManager.mapping
  mappings/net/minecraft/resource/LifecycledResourceManagerImpl.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/ProfiledResourceReload.mapping
  mappings/net/minecraft/resource/ReloadableResourceManagerImpl.mapping
  mappings/net/minecraft/resource/ResourcePack.mapping
  mappings/net/minecraft/resource/ResourceReload.mapping
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
  mappings/net/minecraft/resource/SimpleResourceReload.mapping
  src/packageDocs/java/net/minecraft/resource/package-info.java
Labels: new, snapshot, javadoc

#3003 22w06a more tags/registries stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/command/argument/BlockPredicateArgumentType.mapping
  mappings/net/minecraft/data/server/AdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/item/BlockPredicatesChecker.mapping
  mappings/net/minecraft/item/BoneMealItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/entry/TagEntry.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/village/VillagerType.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/StructureLocator.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/feature/CoralFeature.mapping
Labels: new, snapshot

#3006 Map some fields related to stats and structures
  mappings/net/minecraft/stat/Stat.mapping
  mappings/net/minecraft/stat/StatFormatter.mapping
  mappings/net/minecraft/stat/StatType.mapping
  mappings/net/minecraft/structure/DesertTempleGenerator.mapping
  mappings/net/minecraft/structure/IglooGenerator.mapping
  mappings/net/minecraft/structure/JungleTempleGenerator.mapping
  mappings/net/minecraft/structure/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/StructureManager.mapping
  mappings/net/minecraft/structure/pool/FeaturePoolElement.mapping
  mappings/net/minecraft/structure/pool/ListPoolElement.mapping
  mappings/net/minecraft/structure/processor/BlackstoneReplacementStructureProcessor.mapping
Labels: new, snapshot

#3004 22w06a more cursed stuff
  mappings/net/minecraft/class_6864.mapping
  mappings/net/minecraft/class_6895.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/tag/TagPacketSerializer.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/ForwardingDynamicOps.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/dynamic/RegistryLoader.mapping
  mappings/net/minecraft/util/dynamic/RegistryOps.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/util/registry/RegistryCodecs.mapping
  mappings/net/minecraft/util/registry/RegistryEntryListCodec.mapping
  mappings/net/minecraft/util/registry/RegistryFixedCodec.mapping
  mappings/net/minecraft/util/registry/RegistryKey.mapping
  mappings/net/minecraft/util/registry/SimpleRegistry.mapping
Labels: new, snapshot

#3011 Fix broken javadoc jar
  .github/workflows/build.yml
  .github/workflows/publish.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, toolchain

#3005 Rename misleading VertexBuffer-related names
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/VertexFormat.mapping
Labels: bug, refactor, snapshot

#3015 Update arg to be consistent with its block counterpart
  mappings/net/minecraft/client/render/RenderLayers.mapping
Labels: new, snapshot

#3021 Remove reference to wool
  mappings/net/minecraft/util/DyeColor.mapping
Labels: bug, snapshot

#3025 Map RegistryPredicateArgumentType
  mappings/net/minecraft/command/argument/RegistryPredicateArgumentType.mapping
Labels: new, ready to merge, snapshot

#3027 1.18.2 pre2 stuff
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/widget/PressableTextWidget.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/Spline.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: new, snapshot

#2965 Rename Panda flag from 'scared' to 'sitting'
  mappings/net/minecraft/client/render/entity/model/PandaEntityModel.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  unpick-definitions/entity_flags.unpick
Labels: bug, refactor, snapshot

#3023 1.18.2 pre1 stuff
  mappings/net/minecraft/client/font/MultilineText.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/Realms32BitWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/WarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerWarningScreen.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/command/argument/ArgumentTypes.mapping
  mappings/net/minecraft/loot/function/ExplorationMapLootFunction.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/server/command/LocateBiomeCommand.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesLoader.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/tag/TagKey.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/FeatureUpdater.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
Labels: new, snapshot

#3022 1.18.2-pre1 stuff
  mappings/net/minecraft/class_6954.mapping
  mappings/net/minecraft/data/server/BiomeTagProvider.mapping
  mappings/net/minecraft/data/server/ConfiguredStructureFeatureTagProvider.mapping
  mappings/net/minecraft/structure/StructureSet.mapping
  mappings/net/minecraft/structure/StructureSetKeys.mapping
  mappings/net/minecraft/structure/StructureSets.mapping
  mappings/net/minecraft/tag/BiomeTags.mapping
  mappings/net/minecraft/tag/ConfiguredStructureFeatureTags.mapping
  mappings/net/minecraft/util/math/noise/InterpolatedNoiseSampler.mapping
  mappings/net/minecraft/util/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/util/registry/Registry.mapping
  mappings/net/minecraft/world/StructureSpawns.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunction.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctionTypes.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctions.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeatureKeys.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeatures.mapping
  mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
  mappings/net/minecraft/world/gen/noise/NoiseType.mapping
Labels: new, snapshot

#3017 Map class_6904 and related stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/resource/ServerResourceManager.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/SaveLoader.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
Labels: new, snapshot

#3030 1.18.2-pre3 stuff
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/util/MonitorTracker.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/argument/RegistryKeyArgumentType.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/server/command/PlaceFeatureCommand.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: new, snapshot

#3029 Rename ServerResourceManager
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/resource/SimpleResourceReload.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/SaveLoader.mapping
  mappings/net/minecraft/test/TestServer.mapping
Labels: bug, refactor, snapshot, javadoc

#3018 A tiny bit of work on Deep Dark snapshot 1
  mappings/net/minecraft/client/render/entity/WardenEntityRenderer.mapping
  mappings/net/minecraft/entity/Animation.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/server/command/WardenSpawnTrackerCommand.mapping
Labels: new, experimental

#3033 1.19-exp1 removed duplicate mapping
  mappings/net/minecraft/entity/Animation.mapping
Labels: bug, experimental

#3035 Fix javadoc error
  mappings/net/minecraft/server/DataPackContents.mapping
Labels: bug, snapshot

#3031 1.18.2-pre3 stuff
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/fix/StructuresToConfiguredStructuresFix.mapping
  mappings/net/minecraft/structure/StructureSet.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunction.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctionTypes.mapping
  mappings/net/minecraft/world/gen/feature/PlacedFeature.mapping
  mappings/net/minecraft/world/gen/noise/SimpleNoiseRouter.mapping
Labels: new, snapshot

#3034 Use camelCase for fields in VanillaBiomeParameters
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
Labels: bug, refactor, snapshot

#3032 Moved a couple classes
  mappings/net/minecraft/data/client/TextureMap.mapping
  mappings/net/minecraft/world/gen/noise/NoiseHelper.mapping
Labels: refactor, ready to merge, snapshot, impactful

#3036 Fix chest model part names being swapped
  mappings/net/minecraft/client/render/block/entity/ChestBlockEntityRenderer.mapping
Labels: bug, refactor, ready to merge, snapshot

#3037 best pr ever
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: bug, snapshot
