Repository FabricMC/yarn, pull requests merged in 2022-08, with the labels that each got.

#3260 1.19.1-rc3 networking
  mappings/net/minecraft/client/gui/hud/MessageIndicator.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/PacketCallbacks.mapping
  mappings/net/minecraft/network/message/FilterMask.mapping
  mappings/net/minecraft/network/message/MessageChain.mapping
  mappings/net/minecraft/network/message/MessageDecorator.mapping
  mappings/net/minecraft/network/message/MessageVerifier.mapping
  mappings/net/minecraft/network/message/SentMessage.mapping
  mappings/net/minecraft/network/message/SignedCommandArguments.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/s2c/play/MessageHeaderS2CPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/MeCommand.mapping
  mappings/net/minecraft/server/command/MessageCommand.mapping
  mappings/net/minecraft/server/command/SayCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/command/TeamMsgCommand.mapping
  mappings/net/minecraft/server/filter/FilteredMessage.mapping
  mappings/net/minecraft/server/filter/TextFilterer.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: refactor, new, release, javadoc

#3276 Rename the BlockLootTableGenerator.addDoorDrop method to doorDrops
  mappings/net/minecraft/data/server/BlockLootTableGenerator.mapping
Labels: bug, refactor, release

#3264 Fix typo, javadoc, etc
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/client/render/entity/model/ShieldEntityModel.mapping
  mappings/net/minecraft/command/CommandRegistryWrapper.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/inventory/StackReference.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ItemUsage.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/collection/LinkedBlockPosHashSet.mapping
  mappings/net/minecraft/util/math/random/RandomSeed.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
Labels: bug, refactor, release, javadoc

#3258 Document ScreenHandler
  mappings/net/minecraft/screen/NamedScreenHandlerFactory.mapping
  mappings/net/minecraft/screen/PropertyDelegate.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerContext.mapping
  mappings/net/minecraft/screen/ScreenHandlerFactory.mapping
  mappings/net/minecraft/screen/ScreenHandlerType.mapping
  mappings/net/minecraft/screen/SimpleNamedScreenHandlerFactory.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
Labels: release, javadoc

#3268 1.19.1 mapping bonanza 1: world
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/ChunkUpdateState.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/GameMode.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
  mappings/net/minecraft/world/PortalForcer.mapping
  mappings/net/minecraft/world/SpawnHelper.mapping
  mappings/net/minecraft/world/StructureSpawns.mapping
  mappings/net/minecraft/world/WanderingTraderManager.mapping
  mappings/net/minecraft/world/chunk/ArrayPalette.mapping
  mappings/net/minecraft/world/chunk/BelowZeroRetrogen.mapping
  mappings/net/minecraft/world/chunk/BiMapPalette.mapping
  mappings/net/minecraft/world/chunk/ChunkCache.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/EmptyChunk.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/chunk/UpgradeData.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/dimension/AreaHelper.mapping
  mappings/net/minecraft/world/event/BlockPositionSource.mapping
  mappings/net/minecraft/world/event/EntityPositionSource.mapping
  mappings/net/minecraft/world/level/LevelInfo.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/poi/PointOfInterest.mapping
  mappings/net/minecraft/world/poi/PointOfInterestSet.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/storage/ChunkStreamVersion.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/timer/Timer.mapping
  mappings/net/minecraft/world/timer/TimerCallbackSerializer.mapping
Labels: bug, new, release

#3269 1.19.1 mapping bonanza 2: client
  mappings/net/minecraft/client/Keyboard.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/color/item/ItemColors.mapping
  mappings/net/minecraft/client/color/world/FoliageColors.mapping
  mappings/net/minecraft/client/item/CompassAnglePredicateProvider.mapping
  mappings/net/minecraft/client/particle/ShriekParticle.mapping
  mappings/net/minecraft/client/recipebook/ClientRecipeBook.mapping
  mappings/net/minecraft/client/sound/SoundEntryDeserializer.mapping
  mappings/net/minecraft/client/sound/SoundLoader.mapping
Labels: new, release

#3270 1.19.1 mapping bonanza 3: datagen
  mappings/net/minecraft/data/client/BlockStateVariant.mapping
  mappings/net/minecraft/data/client/BlockStateVariantMap.mapping
  mappings/net/minecraft/data/client/ModelProvider.mapping
  mappings/net/minecraft/data/client/MultipartBlockStateSupplier.mapping
  mappings/net/minecraft/data/client/TexturedModel.mapping
  mappings/net/minecraft/data/client/VariantsBlockStateSupplier.mapping
  mappings/net/minecraft/data/report/WorldgenProvider.mapping
  mappings/net/minecraft/data/server/BiomeParametersProvider.mapping
  mappings/net/minecraft/data/server/GameEventTagProvider.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonBuilder.mapping
Labels: new, release

#3271 1.19.1 mapping bonanza 4: data pack stuff
  mappings/net/minecraft/advancement/AdvancementManager.mapping
  mappings/net/minecraft/advancement/AdvancementProgress.mapping
  mappings/net/minecraft/advancement/AdvancementRewards.mapping
  mappings/net/minecraft/advancement/CriterionMerger.mapping
  mappings/net/minecraft/loot/condition/LootConditionManager.mapping
  mappings/net/minecraft/loot/entry/EntryCombiner.mapping
  mappings/net/minecraft/loot/entry/GroupEntry.mapping
  mappings/net/minecraft/loot/function/CopyStateFunction.mapping
  mappings/net/minecraft/loot/function/LootFunctionManager.mapping
  mappings/net/minecraft/loot/function/SetEnchantmentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetGoatHornSoundLootFunction.mapping
  mappings/net/minecraft/predicate/entity/AdvancementEntityPredicateDeserializer.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicates.mapping
  mappings/net/minecraft/predicate/entity/LightningBoltPredicate.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/predicate/entity/TypeSpecificPredicate.mapping
  mappings/net/minecraft/recipe/FireworkStarRecipe.mapping
  mappings/net/minecraft/recipe/book/RecipeBookOptions.mapping
  mappings/net/minecraft/tag/TagEntry.mapping
  mappings/net/minecraft/tag/TagFile.mapping
  mappings/net/minecraft/tag/TagGroupLoader.mapping
  mappings/net/minecraft/tag/TagManagerLoader.mapping
  mappings/net/minecraft/tag/TagPacketSerializer.mapping
Labels: new, release

#3272 1.19.1 bonanza 5: util
  mappings/net/minecraft/util/LowercaseEnumTypeAdapterFactory.mapping
  mappings/net/minecraft/util/MetricsData.mapping
  mappings/net/minecraft/util/collection/DataPool.mapping
  mappings/net/minecraft/util/collection/Int2ObjectBiMap.mapping
  mappings/net/minecraft/util/collection/SortedArraySet.mapping
  mappings/net/minecraft/util/crash/CrashReportSection.mapping
  mappings/net/minecraft/util/logging/LoggerPrintStream.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionHandler.mapping
  mappings/net/minecraft/util/logging/UncaughtExceptionLogger.mapping
  mappings/net/minecraft/util/profiling/jfr/JfrListener.mapping
Labels: new, release

#3273 1.19.1 bonanza 6: everything else
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/block/BeetrootsBlock.mapping
  mappings/net/minecraft/block/BellBlock.mapping
  mappings/net/minecraft/block/FrostedIceBlock.mapping
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/block/ShapeContext.mapping
  mappings/net/minecraft/block/entity/SculkShriekerWarningManager.mapping
  mappings/net/minecraft/datafixer/fix/ChunkHeightAndBiomeFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityBlockStateFix.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/data/DataTracker.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandler.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/mob/PiglinBruteBrain.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/particle/ShriekParticleEffect.mapping
  mappings/net/minecraft/particle/VibrationParticleEffect.mapping
  mappings/net/minecraft/resource/ResourceFactory.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/FunctionLoader.mapping
  mappings/net/minecraft/stat/ServerStatHandler.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/village/VillageGossipType.mapping
  mappings/net/minecraft/village/VillagerData.mapping
  mappings/net/minecraft/village/VillagerGossips.mapping
Labels: new, release

#3277 ArmorFeatureRenderer renames and fixes
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
Labels: bug, refactor, release

#3278 Rename MathHelper.(clamped)lerpFromProgress -> (clamped)map, add docs
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: refactor, release, javadoc

#3274 1.19.2-rc1/rc2 stuff
  mappings/net/minecraft/client/util/ProfileKeys.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: new, release, javadoc
