Repository FabricMC/yarn, pull requests merged in 2022-07, with the labels that each got.

#3228 1.19.1-pre2 stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/hud/ChatHudLine.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/MessageIndicator.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/AbuseReportReasonScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatSelectionScreen.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/client/network/message/MessageTrustStatus.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/NarratorMode.mapping
  mappings/net/minecraft/client/realms/RepeatedNarrator.mapping
  mappings/net/minecraft/client/report/AbuseReportSender.mapping
  mappings/net/minecraft/client/report/ChatAbuseReport.mapping
  mappings/net/minecraft/client/report/MessagesListAdder.mapping
  mappings/net/minecraft/client/report/ReceivedMessage.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
  mappings/net/minecraft/client/util/Session.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/network/message/MessageSender.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/text/StringVisitable.mapping
  mappings/net/minecraft/text/Text.mapping
Labels: refactor, new, snapshot, javadoc

#3232 1.19.1-pre3 chat mappings
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/message/MessageSender.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatSuggestionsS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/MessageCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/text/Decoration.mapping
Labels: refactor, new, ready to merge, snapshot

#3233 1.19.1-pre3 stuff
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/hud/MessageIndicator.mapping
  mappings/net/minecraft/client/gui/screen/ChatInputSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/text/Decoration.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
Labels: refactor, new, snapshot, javadoc

#3237 1.19.1-pre4 stuff
  mappings/net/minecraft/client/gui/EditBox.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/message/ArgumentSignatureDataMap.mapping
  mappings/net/minecraft/network/message/ChatMessageSigner.mapping
  mappings/net/minecraft/network/message/CommandArgumentSigner.mapping
  mappings/net/minecraft/network/message/MessageBody.mapping
  mappings/net/minecraft/network/message/MessageChain.mapping
  mappings/net/minecraft/network/message/MessageDecorator.mapping
  mappings/net/minecraft/network/message/MessageHeader.mapping
  mappings/net/minecraft/network/message/MessageMetadata.mapping
  mappings/net/minecraft/network/message/MessageSender.mapping
  mappings/net/minecraft/network/message/MessageSignature.mapping
  mappings/net/minecraft/network/message/MessageSignatureData.mapping
  mappings/net/minecraft/network/message/MessageSourceProfile.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/message/MessageVerifier.mapping
  mappings/net/minecraft/network/message/SentMessage.mapping
  mappings/net/minecraft/network/message/SignedCommandArguments.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/HideMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/MessageHeaderS2CPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/MessageCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/command/TeamMsgCommand.mapping
  mappings/net/minecraft/server/filter/FilteredMessage.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/text/Decoration.mapping
  mappings/net/minecraft/util/dynamic/DynamicSerializableUuid.mapping
Labels: refactor, new, snapshot, javadoc

#3250 Fixed typo in ChunkNoiseSampler
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
Labels: bug, refactor, ready to merge, snapshot

#3247 1.19.1-pre5 misc stuff
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/command/argument/EnumArgumentType.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/crash/CrashReport.mapping
Labels: refactor, new, snapshot

#3248 1.19.1-pre5 networking
  mappings/net/minecraft/class_7633.mapping
  mappings/net/minecraft/class_7635.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/SignedArgumentType.mapping
  mappings/net/minecraft/command/argument/TextConvertibleArgumentType.mapping
  mappings/net/minecraft/network/listener/ServerPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/TickablePacketListener.mapping
  mappings/net/minecraft/network/message/AcknowledgmentValidator.mapping
  mappings/net/minecraft/network/message/ArgumentSignatureDataMap.mapping
  mappings/net/minecraft/network/message/DecoratedContents.mapping
  mappings/net/minecraft/network/message/LastSeenMessageList.mapping
  mappings/net/minecraft/network/message/LastSeenMessagesCollector.mapping
  mappings/net/minecraft/network/message/MessageBody.mapping
  mappings/net/minecraft/network/message/MessageChain.mapping
  mappings/net/minecraft/network/message/MessageChainTaskQueue.mapping
  mappings/net/minecraft/network/message/MessageDecorator.mapping
  mappings/net/minecraft/network/message/MessageSignatureData.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/message/MessageVerifier.mapping
  mappings/net/minecraft/network/message/SignedCommandArguments.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/MessageAcknowledgmentC2SPacket.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/filter/FilteredMessage.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/util/thread/FutureQueue.mapping
Labels: refactor, new, snapshot, javadoc

#3249 1.19.1-pre5 client networking
  mappings/net/minecraft/client/gui/screen/ChatInputSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/ChatPreviewBackground.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ChatPreviewWarningScreen.mapping
  mappings/net/minecraft/client/network/ChatPreviewer.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/client/network/message/MessageTrustStatus.mapping
  mappings/net/minecraft/client/option/ChatPreviewMode.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/report/ChatAbuseReport.mapping
  mappings/net/minecraft/client/report/log/ChatLog.mapping
  mappings/net/minecraft/client/report/log/ChatLogEntry.mapping
  mappings/net/minecraft/client/report/log/ChatLogImpl.mapping
  mappings/net/minecraft/client/report/log/HeaderEntry.mapping
  mappings/net/minecraft/client/report/log/ReceivedMessage.mapping
Labels: refactor, new, snapshot, javadoc

#3257 Rename argument in `PaintingManager#getPaintingSprite`
  mappings/net/minecraft/client/texture/PaintingManager.mapping
Labels: bug, snapshot

#3256 Rename `EmptyEntry#Serializer` to `builder`
  mappings/net/minecraft/loot/entry/EmptyEntry.mapping
Labels: bug, refactor, snapshot

#3255 Rename `ServerPlayerEntity#sendInitialChunkPackets` to `sendChunkPacket`
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: bug, refactor, snapshot

#3054 1.18.2 javadoc fixes
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/tag/TagPacketSerializer.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/world/gen/feature/ConfiguredStructureFeature.mapping
  mappings/net/minecraft/world/gen/placementmodifier/PlacementModifier.mapping
  mappings/net/minecraft/world/spawner/CatSpawner.mapping
  mappings/net/minecraft/world/spawner/PatrolSpawner.mapping
  mappings/net/minecraft/world/spawner/Spawner.mapping
  src/packageDocs/java/net/minecraft/resource/package-info.java
Labels: release, javadoc

#3226 Document AbstractBlock and Block
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
Labels: snapshot, javadoc

#3230 Document Item
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ItemUsage.mapping
Labels: snapshot, javadoc

#3254 Fix entity mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/goal/AnimalMateGoal.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
Labels: bug, refactor, snapshot

#3243 Document BlockEntity
  mappings/net/minecraft/block/BlockEntityProvider.mapping
  mappings/net/minecraft/block/BlockWithEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/BlockEntityTicker.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
Labels: snapshot, javadoc

#3251 More 1.19 worldgen mappings
  mappings/net/minecraft/util/function/ToFloatFunction.mapping
  mappings/net/minecraft/util/math/Spline.mapping
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaTerrainParametersCreator.mapping
  mappings/net/minecraft/world/gen/chunk/AquiferSampler.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctionTypes.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunctions.mapping
Labels: refactor, new, snapshot, javadoc

#3253 1.19.1-pre6 stuff
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/datafixer/fix/ItemRemoveBlockEntityTagFix.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
Labels: new, snapshot

#3252 1.19.1-pre6/rc2 networking
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/hud/MessageIndicator.mapping
  mappings/net/minecraft/client/gui/screen/ChatInputSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/SleepingChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatReportScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/client/report/AbuseReportReason.mapping
  mappings/net/minecraft/client/report/ChatAbuseReport.mapping
  mappings/net/minecraft/client/report/MessagesListAdder.mapping
  mappings/net/minecraft/command/argument/DecoratableArgumentList.mapping
  mappings/net/minecraft/command/argument/DecoratableArgumentType.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/network/message/ArgumentSignatureDataMap.mapping
  mappings/net/minecraft/network/message/CachedDecoratorResult.mapping
  mappings/net/minecraft/network/message/MessageBody.mapping
  mappings/net/minecraft/network/message/MessageDecorator.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/message/MessageVerifier.mapping
  mappings/net/minecraft/network/message/SentMessage.mapping
  mappings/net/minecraft/network/message/SignedCommandArguments.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/s2c/play/ServerMetadataS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: refactor, new, snapshot, javadoc

#3262 Switch 'GroupEntry' and 'SequenceEntry'
  mappings/net/minecraft/loot/entry/GroupEntry.mapping
  mappings/net/minecraft/loot/entry/SequenceEntry.mapping
Labels: bug, refactor, release

#3263 Rename the WorldRenderer#lastCloudsRenderMode field to lastCloudRenderMode
  mappings/net/minecraft/client/render/WorldRenderer.mapping
Labels: bug, refactor, release

#3241 Document entity
  mappings/net/minecraft/entity/Entity.mapping
Labels: release, javadoc

#3261 1.19.1-rc3 stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/EmptyGlyphRenderer.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/client/toast/Toast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
Labels: new, release

#3265 Fix GameOptions#getCloudRenderMod
  mappings/net/minecraft/client/option/GameOptions.mapping
Labels: bug, refactor, release

#3266 Fix typo in `getEntityRenderDIspatcher`
  mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactory.mapping
Labels: bug, refactor, release
