Repository FabricMC/yarn, pull requests merged in 2022-03, with the labels that each got.

#3038 Map VeinCreator (class_6955)
  mappings/net/minecraft/class_6955.mapping
  mappings/net/minecraft/world/gen/OreVeinSampler.mapping
Labels: new, release

#3045 22w11a save loading
  mappings/net/minecraft/class_7237.mapping
  mappings/net/minecraft/client/world/GeneratorOptionsHolder.mapping
  mappings/net/minecraft/server/SaveLoader.mapping
  mappings/net/minecraft/server/SaveLoading.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
Labels: new, snapshot

#3047 22w11a neighbor update
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractRailBlock.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/block/ChainRestrictedNeighborUpdater.mapping
  mappings/net/minecraft/world/block/NeighborUpdater.mapping
  mappings/net/minecraft/world/block/SimpleNeighborUpdater.mapping
Labels: new, snapshot

#3048 22w11a resource
  mappings/net/minecraft/client/resource/PeriodicNotificationManager.mapping
  mappings/net/minecraft/client/resource/ResourceIndex.mapping
  mappings/net/minecraft/client/resource/language/TranslationStorage.mapping
  mappings/net/minecraft/resource/DataPackSettings.mapping
  mappings/net/minecraft/resource/DefaultResourcePack.mapping
  mappings/net/minecraft/resource/DirectoryResourcePack.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/LifecycledResourceManagerImpl.mapping
  mappings/net/minecraft/resource/NamespaceResourceManager.mapping
  mappings/net/minecraft/resource/ResourceManager.mapping
  mappings/net/minecraft/resource/ResourcePack.mapping
  mappings/net/minecraft/resource/ResourceRef.mapping
  mappings/net/minecraft/resource/metadata/ResourceFilter.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/EntryLoader.mapping
  mappings/net/minecraft/util/dynamic/RegistryLoader.mapping
Labels: new, snapshot

#3052 22w11a commands
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/command/argument/ArgumentHelper.mapping
  mappings/net/minecraft/command/argument/ArgumentTypes.mapping
  mappings/net/minecraft/command/argument/BlockArgumentParser.mapping
  mappings/net/minecraft/command/argument/BlockPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/BlockStateArgumentType.mapping
  mappings/net/minecraft/command/argument/EntityArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStackArgument.mapping
  mappings/net/minecraft/command/argument/ItemStackArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryKeyArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/command/argument/serialize/ArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/ConstantArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/DoubleArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/FloatArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/IntegerArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/LongArgumentSerializer.mapping
  mappings/net/minecraft/command/argument/serialize/StringArgumentSerializer.mapping
  mappings/net/minecraft/command/suggestion/SuggestionProviders.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/command/ChaseCommand.mapping
  mappings/net/minecraft/server/command/ClearCommand.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/FillCommand.mapping
  mappings/net/minecraft/server/command/ForceLoadCommand.mapping
  mappings/net/minecraft/server/command/GameModeCommand.mapping
  mappings/net/minecraft/server/command/GiveCommand.mapping
  mappings/net/minecraft/server/command/ItemCommand.mapping
  mappings/net/minecraft/server/command/LootCommand.mapping
  mappings/net/minecraft/server/command/ResetChunksCommand.mapping
  mappings/net/minecraft/server/command/SayCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/command/SetBlockCommand.mapping
Labels: new, snapshot

#3049 22w11a client
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/BuiltinEmptyGlyph.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/Glyph.mapping
  mappings/net/minecraft/client/font/RenderableGlyph.mapping
  mappings/net/minecraft/client/font/SpaceFont.mapping
  mappings/net/minecraft/client/font/TrueTypeFont.mapping
  mappings/net/minecraft/client/gl/GlTimer.mapping
  mappings/net/minecraft/client/gui/hud/BossBarHud.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/screen/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/MessageScreen.mapping
  mappings/net/minecraft/client/gui/screen/OutOfMemoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/PresetsScreen.mapping
  mappings/net/minecraft/client/gui/screen/SaveLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/option/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SoundOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/LevelScreenProvider.mapping
  mappings/net/minecraft/client/gui/screen/world/MoreOptionsDialog.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/DoubleOptionSliderWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/network/PendingUpdateManager.mapping
  mappings/net/minecraft/client/network/SequencedPacketCreator.mapping
  mappings/net/minecraft/client/option/DoubleOption.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/HotbarStorage.mapping
  mappings/net/minecraft/client/option/Option.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
  mappings/net/minecraft/client/particle/SculkChargeParticle.mapping
  mappings/net/minecraft/client/particle/SculkChargePopParticle.mapping
  mappings/net/minecraft/client/particle/SoulParticle.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/client/util/MacWindowUtil.mapping
  mappings/net/minecraft/client/util/ParticleUtil.mapping
  mappings/net/minecraft/client/util/PngFile.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/client/world/ScreenProvider.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerActionC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractBlockC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractItemC2SPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/profiler/DebugRecorder.mapping
  mappings/net/minecraft/util/profiler/Recorder.mapping
Labels: new, snapshot

#3053 22w11a misc stuff
  mappings/net/minecraft/entity/ai/brain/task/LookTargetUtil.mapping
  mappings/net/minecraft/entity/passive/PassiveEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/s2c/play/StatisticsS2CPacket.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/noise/NoiseConfig.mapping
Labels: new, snapshot

#3055 22w11a javadoc fixes
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/tag/TagPacketSerializer.mapping
  mappings/net/minecraft/util/dynamic/RegistryElementCodec.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/util/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/world/gen/placementmodifier/PlacementModifier.mapping
  mappings/net/minecraft/world/spawner/CatSpawner.mapping
  mappings/net/minecraft/world/spawner/PatrolSpawner.mapping
  mappings/net/minecraft/world/spawner/Spawner.mapping
  src/packageDocs/java/net/minecraft/resource/package-info.java
Labels: javadoc

#3056 swap parameter names
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
Labels: snapshot

#3058 22w12a chest boat
  mappings/net/minecraft/class_7248.mapping
  mappings/net/minecraft/class_7265.mapping
  mappings/net/minecraft/client/render/entity/BoatEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/BoatEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/entity/RideableInventory.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/entity/vehicle/ChestBoatEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleInventory.mapping
  mappings/net/minecraft/item/BoatItem.mapping
Labels: new, snapshot

#3063 22w12a datafixer and codecs
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/schema/Schema3081.mapping
  mappings/net/minecraft/datafixer/schema/Schema3082.mapping
  mappings/net/minecraft/util/dynamic/CodecHolder.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, snapshot

#3067 Chunk generator stuff
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGenerator.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorConfig.mapping
  mappings/net/minecraft/world/gen/chunk/NoiseChunkGenerator.mapping
Labels: new, snapshot
