Repository FabricMC/yarn, pull requests merged in 2023-08, with the labels that each got.

#3613 More 23w31a stuff
  mappings/net/minecraft/advancement/AdvancementFrame.mapping
  mappings/net/minecraft/block/AbstractSignBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/CropBlock.mapping
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/FlowerbedBlock.mapping
  mappings/net/minecraft/block/PitcherCropBlock.mapping
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/PathAwareEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/shape/VoxelShape.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/gen/feature/OreConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/OrePlacedFeatures.mapping
Labels: new, snapshot

#3614 23w31a commands and functions
  mappings/net/minecraft/command/DataCommandStorage.mapping
  mappings/net/minecraft/server/command/ChaseCommand.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/DebugConfigCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/FunctionCommand.mapping
  mappings/net/minecraft/server/command/RandomCommand.mapping
  mappings/net/minecraft/server/command/ReturnCommand.mapping
  mappings/net/minecraft/server/command/ScoreboardCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/server/function/MacroException.mapping
  mappings/net/minecraft/world/PersistentState.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
Labels: refactor, new, snapshot

#3617 23w31a resource
  mappings/net/minecraft/resource/DirectoryResourcePack.mapping
  mappings/net/minecraft/resource/FileResourcePackProvider.mapping
  mappings/net/minecraft/resource/OverlayResourcePack.mapping
  mappings/net/minecraft/resource/ResourcePackCompatibility.mapping
  mappings/net/minecraft/resource/ResourcePackOpener.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/resource/VanillaResourcePackProvider.mapping
  mappings/net/minecraft/resource/ZipResourcePack.mapping
  mappings/net/minecraft/resource/metadata/PackFeatureSetMetadata.mapping
  mappings/net/minecraft/resource/metadata/PackOverlaysMetadata.mapping
  mappings/net/minecraft/resource/metadata/PackResourceMetadata.mapping
  mappings/net/minecraft/resource/metadata/ResourceMetadata.mapping
Labels: refactor, new, snapshot

#3622 23w31a block, item, entity stuff
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/TemptTask.mapping
  mappings/net/minecraft/entity/ai/pathing/Path.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/entity/passive/CamelBrain.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/item/trim/ArmorTrim.mapping
Labels: bug, refactor, new, snapshot

#3623 23w31a everything else
  mappings/net/minecraft/datafixer/fix/DropInvalidSignDatafixDataFix.mapping
  mappings/net/minecraft/datafixer/fix/RandomSequenceSettingsFix.mapping
  mappings/net/minecraft/datafixer/fix/StatsCounterFix.mapping
  mappings/net/minecraft/datafixer/fix/UpdateSignTextFormatFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema1451v6.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ScoreboardState.mapping
  mappings/net/minecraft/scoreboard/ServerScoreboard.mapping
  mappings/net/minecraft/screen/EnchantmentScreenHandler.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/util/Colors.mapping
  mappings/net/minecraft/util/collection/ArrayListDeque.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/Range.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/random/RandomSequence.mapping
  mappings/net/minecraft/util/math/random/RandomSequencesState.mapping
  mappings/net/minecraft/util/path/SymlinkFinder.mapping
  mappings/net/minecraft/util/profiling/jfr/FlightProfiler.mapping
  mappings/net/minecraft/util/profiling/jfr/event/PacketEvent.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
  mappings/net/minecraft/world/ChunkUpdateState.mapping
  mappings/net/minecraft/world/ForcedChunkState.mapping
  mappings/net/minecraft/world/IdCountsState.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: bug, refactor, new, snapshot

#3619 23w31a client
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/TextHandler.mapping
  mappings/net/minecraft/client/font/TrueTypeFontLoader.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/option/CloudRenderMode.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/RealmsAvailability.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/RealmsError.mapping
  mappings/net/minecraft/client/realms/dto/PlayerInfo.mapping
  mappings/net/minecraft/client/realms/exception/RealmsServiceException.mapping
  mappings/net/minecraft/client/realms/util/Errable.mapping
  mappings/net/minecraft/client/realms/util/Realms32BitWarningChecker.mapping
  mappings/net/minecraft/client/realms/util/RealmsServerFilterer.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
  mappings/net/minecraft/client/render/BuiltChunkStorage.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/debug/BeeDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameEventDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GoalSelectorDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/StructureDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/VillageDebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderers.mapping
  mappings/net/minecraft/client/resource/DefaultClientResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/metadata/GuiResourceMetadata.mapping
  mappings/net/minecraft/client/texture/MissingSprite.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/client/texture/Scaling.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteLoader.mapping
  mappings/net/minecraft/client/texture/SpriteOpener.mapping
  mappings/net/minecraft/client/texture/atlas/AtlasLoader.mapping
  mappings/net/minecraft/client/texture/atlas/AtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/PalettedPermutationsAtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/UnstitchAtlasSource.mapping
  mappings/net/minecraft/client/util/CommandHistoryManager.mapping
  mappings/net/minecraft/client/util/DefaultSkinHelper.mapping
  mappings/net/minecraft/client/util/Session.mapping
  mappings/net/minecraft/client/util/SkinTextures.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
Labels: bug, refactor, new, snapshot

#3620 23w31a client gui
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/PlayerSkinDrawer.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/MessageIndicator.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeamTeleportSpectatorMenu.mapping
  mappings/net/minecraft/client/gui/hud/spectator/TeleportToSpecificPlayerSpectatorCommand.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingButtons.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryEventWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryInfoScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AbstractFurnaceRecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookResults.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SymlinkWarningScreen.mapping
  mappings/net/minecraft/client/gui/widget/AxisGridWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/DirectionalLayoutWidget.mapping
  mappings/net/minecraft/client/gui/widget/EditBoxWidget.mapping
  mappings/net/minecraft/client/gui/widget/GridWidget.mapping
  mappings/net/minecraft/client/gui/widget/IconWidget.mapping
  mappings/net/minecraft/client/gui/widget/NarratedMultilineTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextIconButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextWidget.mapping
  mappings/net/minecraft/client/gui/widget/ThreePartsLayoutWidget.mapping
  mappings/net/minecraft/client/realms/gui/RealmsLoadingWidget.mapping
  mappings/net/minecraft/client/realms/gui/screen/BuyRealmsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsClientIncompatibleScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateRealmScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsNotificationsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPendingInvitesScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetNormalWorldScreen.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3624 Network related notes and changes
  mappings/net/minecraft/network/encoding/VarInts.mapping
  mappings/net/minecraft/network/encoding/VarLongs.mapping
  mappings/net/minecraft/network/listener/ClientCommonPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerCommonPacketListener.mapping
  mappings/net/minecraft/network/listener/TickablePacketListener.mapping
  mappings/net/minecraft/network/packet/BrandCustomPayload.mapping
  mappings/net/minecraft/network/packet/Packet.mapping
  mappings/net/minecraft/network/packet/c2s/common/CommonPongC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/handshake/ConnectionIntent.mapping
  mappings/net/minecraft/network/packet/s2c/common/CommonPingS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerConfigurationNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: refactor, snapshot

#3625 23w32a networking
  mappings/net/minecraft/class_8740.mapping
  mappings/net/minecraft/class_8763.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/MessageIndicator.mapping
  mappings/net/minecraft/client/network/ChunkBatchSizeCalculator.mapping
  mappings/net/minecraft/client/network/ClientCommonNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/PingMeasurer.mapping
  mappings/net/minecraft/client/network/message/MessageHandler.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/encryption/PublicPlayerSession.mapping
  mappings/net/minecraft/network/handler/PacketSizeLogger.mapping
  mappings/net/minecraft/network/handler/SplitterHandler.mapping
  mappings/net/minecraft/network/listener/ClientPingResultPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerQueryPingPacketListener.mapping
  mappings/net/minecraft/network/message/MessageVerifier.mapping
  mappings/net/minecraft/network/packet/s2c/query/PingResultS2CPacket.mapping
  mappings/net/minecraft/server/network/ServerCommonNetworkHandler.mapping
  mappings/net/minecraft/util/profiler/PerformanceLog.mapping
Labels: refactor, new, snapshot, javadoc

#3636 Add default namespace behavior docs in Identifier
  mappings/net/minecraft/util/Identifier.mapping
Labels: snapshot, javadoc

#3629 23w32a more stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/debug/DebugChart.mapping
  mappings/net/minecraft/client/gui/hud/debug/PacketSizeChart.mapping
  mappings/net/minecraft/client/gui/hud/debug/PingChart.mapping
  mappings/net/minecraft/client/gui/hud/debug/RenderingChart.mapping
  mappings/net/minecraft/client/gui/hud/debug/TickChart.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/command/FloatRangeArgument.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/listener/ClientPingResultPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerQueryPingPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/common/CommonPingS2CPacket.mapping
  mappings/net/minecraft/registry/SimpleRegistry.mapping
  mappings/net/minecraft/registry/entry/RegistryEntryList.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/stat/StatType.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3606 RangedAttackMob.attack -> RangedAttackMob.shootAt
  mappings/net/minecraft/entity/ai/RangedAttackMob.mapping
Labels: refactor, snapshot

#3635 Rename confusing names and add some javadoc in n.m.server.world
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
Labels: snapshot

#3637 23w33a stuff
  mappings/net/minecraft/class_8768.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/QuickPlay.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/report/AbuseReportTypeScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ChatSelectionScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/ReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/SkinReportScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/UsernameReportScreen.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/LayoutWidgets.mapping
  mappings/net/minecraft/client/gui/widget/PlayerSkinWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/report/AbuseReport.mapping
  mappings/net/minecraft/client/report/AbuseReportSender.mapping
  mappings/net/minecraft/client/report/AbuseReportType.mapping
  mappings/net/minecraft/client/report/ChatAbuseReport.mapping
  mappings/net/minecraft/client/report/Draft.mapping
  mappings/net/minecraft/client/report/SkinAbuseReport.mapping
  mappings/net/minecraft/client/report/UsernameAbuseReport.mapping
  mappings/net/minecraft/client/util/Bans.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/predicate/StatePredicate.mapping
  mappings/net/minecraft/predicate/entity/VariantPredicates.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/test/TestRunner.mapping
Labels: refactor, new, snapshot

#3638 23w33a more stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/report/ReportScreen.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupInfoScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/report/ChatAbuseReport.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/network/message/SentMessage.mapping
  mappings/net/minecraft/predicate/NumberRange.mapping
  mappings/net/minecraft/predicate/entity/TypeSpecificPredicate.mapping
  mappings/net/minecraft/predicate/entity/VariantPredicates.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/test/TestRunner.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3641 Document inventories
  mappings/net/minecraft/inventory/CraftingInventory.mapping
  mappings/net/minecraft/inventory/CraftingResultInventory.mapping
  mappings/net/minecraft/inventory/DoubleInventory.mapping
  mappings/net/minecraft/inventory/EnderChestInventory.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/InventoryChangedListener.mapping
  mappings/net/minecraft/inventory/RecipeInputInventory.mapping
  mappings/net/minecraft/inventory/SidedInventory.mapping
  mappings/net/minecraft/inventory/SimpleInventory.mapping
  mappings/net/minecraft/inventory/SingleStackInventory.mapping
Labels: snapshot, javadoc

#3643 Document missing properties & improve a few names
  mappings/net/minecraft/block/BlockWithEntity.mapping
  mappings/net/minecraft/block/ConnectingBlock.mapping
  mappings/net/minecraft/block/enums/BlockFace.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: bug, refactor, javadoc

#3645 Recipe stuff
  mappings/net/minecraft/recipe/AbstractCookingRecipe.mapping
  mappings/net/minecraft/recipe/BlastingRecipe.mapping
  mappings/net/minecraft/recipe/CampfireCookingRecipe.mapping
  mappings/net/minecraft/recipe/CookingRecipeSerializer.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeSerializer.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SmeltingRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTransformRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTrimRecipe.mapping
  mappings/net/minecraft/recipe/SmokingRecipe.mapping
  mappings/net/minecraft/recipe/SpecialCraftingRecipe.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
  mappings/net/minecraft/recipe/StonecuttingRecipe.mapping
Labels: refactor, new
