Repository FabricMC/yarn, pull requests merged in 2023-09, with the labels that each got.

#3344 Add documentation for ToolMaterial & ToolItem classes
  mappings/net/minecraft/item/ToolItem.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
  mappings/net/minecraft/item/ToolMaterials.mapping
Labels: snapshot, javadoc

#3323 Add jdocs for ArmorMaterial class
  mappings/net/minecraft/item/ArmorMaterial.mapping
Labels: snapshot, javadoc

#3646 23w35a stuff
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementCriterion.mapping
  mappings/net/minecraft/advancement/AdvancementEntry.mapping
  mappings/net/minecraft/advancement/AdvancementManager.mapping
  mappings/net/minecraft/advancement/AdvancementPositioner.mapping
  mappings/net/minecraft/advancement/AdvancementProgress.mapping
  mappings/net/minecraft/advancement/AdvancementRequirements.mapping
  mappings/net/minecraft/advancement/PlacedAdvancement.mapping
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/advancement/criterion/AbstractCriterion.mapping
  mappings/net/minecraft/advancement/criterion/AbstractCriterionConditions.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/Criterion.mapping
  mappings/net/minecraft/class_4558.mapping
  mappings/net/minecraft/class_8782.mapping
  mappings/net/minecraft/data/server/recipe/ComplexRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/CookingRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/RecipeExporter.mapping
  mappings/net/minecraft/data/server/recipe/RecipeJsonProvider.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SingleItemRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SmithingTransformRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SmithingTrimRecipeJsonBuilder.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/InputSlotFiller.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/RecipeCodecs.mapping
  mappings/net/minecraft/recipe/RecipeEntry.mapping
  mappings/net/minecraft/recipe/RecipeGridAligner.mapping
  mappings/net/minecraft/recipe/RecipeMatcher.mapping
  mappings/net/minecraft/recipe/RecipeUnlocker.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/book/RecipeBook.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/command/AdvancementCommand.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: refactor, new, snapshot

#3652 Update javadoc links
  build.gradle
Labels: snapshot, toolchain

#3649 23w35a more recipes
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookGhostSlots.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeResultCollection.mapping
  mappings/net/minecraft/client/recipebook/ClientRecipeBook.mapping
  mappings/net/minecraft/client/toast/RecipeToast.mapping
  mappings/net/minecraft/data/server/recipe/CraftingRecipeJsonBuilder.mapping
  mappings/net/minecraft/network/packet/c2s/play/CraftRequestC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/RecipeBookDataC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CraftFailedResponseS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SynchronizeRecipesS2CPacket.mapping
  mappings/net/minecraft/recipe/CookingRecipeSerializer.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/recipe/RecipeCodecs.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTransformRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTrimRecipe.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
  mappings/net/minecraft/screen/AbstractRecipeScreenHandler.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
Labels: new, snapshot

#3650 23w35a misc
  mappings/net/minecraft/block/AbstractRedstoneGateBlock.mapping
  mappings/net/minecraft/block/AbstractSkullBlock.mapping
  mappings/net/minecraft/block/BlockEntityProvider.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementTab.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/network/ClientAdvancementManager.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/data/client/ModelProvider.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/datafixer/fix/StatusEffectFix.mapping
  mappings/net/minecraft/entity/ai/goal/MeleeAttackGoal.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/network/packet/s2c/play/AdvancementUpdateS2CPacket.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/PlayerPredicate.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, snapshot

#3648 23w35a realms
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningMcoTaskScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningTickableTaskScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetNormalWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsResetWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/realms/task/CloseServerTask.mapping
  mappings/net/minecraft/client/realms/task/DownloadTask.mapping
  mappings/net/minecraft/client/realms/task/LongRunningTask.mapping
  mappings/net/minecraft/client/realms/task/OpenServerTask.mapping
  mappings/net/minecraft/client/realms/task/RealmsConnectTask.mapping
  mappings/net/minecraft/client/realms/task/RealmsGetServerDetailsTask.mapping
  mappings/net/minecraft/client/realms/task/RestoreTask.mapping
  mappings/net/minecraft/client/realms/task/SwitchMinigameTask.mapping
  mappings/net/minecraft/client/realms/task/SwitchSlotTask.mapping
  mappings/net/minecraft/client/realms/task/WorldCreationTask.mapping
Labels: refactor, new, snapshot

#3653 Repackage ChatVisibility
  mappings/net/minecraft/network/message/ChatVisibility.mapping
Labels: bug, refactor, snapshot

#3655 1.20.2-pre1 stuff
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/main/Main.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/data/server/loottable/rebalance/TradeRebalanceChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/rebalance/TradeRebalanceLootTableProviders.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/passive/MerchantEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/encryption/PlayerKeyPair.mapping
  mappings/net/minecraft/network/encryption/PlayerPublicKey.mapping
  mappings/net/minecraft/network/listener/ServerCommonPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/common/ClientOptionsC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/common/SyncedClientOptions.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameStateChangeS2CPacket.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/network/ConnectedClientData.mapping
  mappings/net/minecraft/server/network/ServerCommonNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerConfigurationNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/Arm.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/GameRules.mapping
Labels: bug, refactor, new, snapshot

#3656 1.20.2-pre2 stuff
  mappings/net/minecraft/client/gui/screen/ChatInputSuggestor.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/search/SearchManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/data/server/tag/rebalance/RebalanceStructureTagProvider.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/structure/StructureUpdateEntrypoint.mapping
Labels: new, snapshot

#3654 Remove remaining paragraph ending tags
  CONVENTIONS.md
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/recipe/RecipeMatcher.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
Labels: snapshot, javadoc

#3659 Document ButtonTextures and fix constructor parameters
  mappings/net/minecraft/client/gui/screen/ButtonTextures.mapping
Labels: bug, snapshot, javadoc

#3657 Fix box length methods not following conventions
  mappings/net/minecraft/util/math/Box.mapping
Labels: refactor, snapshot, javadoc

#3662 Vanilla biome parameter tweaks
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
Labels: refactor, new, snapshot

#3658 Rename SkullItem to PlayerHeadItem
  mappings/net/minecraft/item/PlayerHeadItem.mapping
Labels: refactor

#3660 Rename BackgroundRenderer#setFogBlack, map constants
  mappings/net/minecraft/client/render/BackgroundRenderer.mapping
Labels: refactor, new, snapshot

#3663 1.20.2-pre3 stuff
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBrokenWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsTermsScreen.mapping
  mappings/net/minecraft/client/realms/task/OpenServerTask.mapping
  mappings/net/minecraft/client/realms/task/RealmsGetServerDetailsTask.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/nbt/NbtByteArray.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtIntArray.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtLongArray.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtSizeValidationException.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/nbt/NbtTagSizeTracker.mapping
  mappings/net/minecraft/nbt/NbtType.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/StonecuttingRecipe.mapping
  mappings/net/minecraft/util/PngMetadata.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOfferList.mapping
Labels: refactor, new, snapshot, javadoc

#3665 Map changes to dispensers in 1.20.2 pre-release 4
  mappings/net/minecraft/block/DispenserBlock.mapping
  mappings/net/minecraft/block/DropperBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: new, snapshot, javadoc

#3667 1.20.2-pre4 small stuff
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: snapshot

#3669 AbstractClientPlayerEntity.getSkinTextures
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
Labels: new, snapshot

#3673 1.20.2-rc2 stuff
  mappings/net/minecraft/entity/mob/EndermiteEntity.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
Labels: new, snapshot

#3678 Rename the AbstractFurnaceBlock.checkType method to validateTicker
  mappings/net/minecraft/block/AbstractFurnaceBlock.mapping
Labels: bug, refactor, release
