Repository FabricMC/yarn, pull requests merged in 2023-04, with the labels that each got.

#3532 Vote Update: Map blocks and items
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/CheeseBlock.mapping
  mappings/net/minecraft/block/CopperSinkBlock.mapping
  mappings/net/minecraft/block/CopperSpleavesBlock.mapping
  mappings/net/minecraft/block/FilledCopperSinkBlock.mapping
  mappings/net/minecraft/block/PackedAirBlock.mapping
  mappings/net/minecraft/block/PickaxeBlock.mapping
  mappings/net/minecraft/block/PlaceBlock.mapping
  mappings/net/minecraft/block/WorldModifyingBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/item/DupeHackItem.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/NbtItem.mapping
  mappings/net/minecraft/item/NbtNameItem.mapping
  mappings/net/minecraft/item/PlaceBlockItemPlacementContext.mapping
  mappings/net/minecraft/world/World.mapping
Labels: new, snapshot

#3540 More 23w14a stuff
  mappings/net/minecraft/block/CarvedPumpkinBlock.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/WitherSkullBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/QuickPlayLogger.mapping
  mappings/net/minecraft/client/gui/LogoDrawer.mapping
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/gui/screen/DisconnectedScreen.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/input/KeyCodes.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPendingInvitesScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/world/event/listener/VibrationListener.mapping
Labels: refactor, new, snapshot

#3541 Fix mixed up getRed/getBlue names in ColorHelper.Abgr
  mappings/net/minecraft/util/math/ColorHelper.mapping
Labels: bug, refactor, release

#3542 Fix mixed up getRed/getBlue names in ColorHelper.Abgr (23w14a)
  mappings/net/minecraft/util/math/ColorHelper.mapping
Labels: bug, refactor, snapshot

#3543 23w14a loot stuff
  mappings/net/minecraft/data/server/loottable/LootTableProvider.mapping
  mappings/net/minecraft/loot/LootDataKey.mapping
  mappings/net/minecraft/loot/LootDataLookup.mapping
  mappings/net/minecraft/loot/LootDataType.mapping
  mappings/net/minecraft/loot/LootManager.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/LootTableReporter.mapping
  mappings/net/minecraft/loot/condition/ReferenceLootCondition.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/entry/LootTableEntry.mapping
  mappings/net/minecraft/loot/function/ReferenceLootFunction.mapping
Labels: bug, refactor, new, snapshot

#3538 Map sign changes
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
Labels: new, snapshot

#3547 Item group registry names
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
Labels: enhancement, new, snapshot

#3550 22w16a stuff
  mappings/net/minecraft/advancement/criterion/RecipeCraftedCriterion.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/CalibratedSculkSensorBlock.mapping
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/DecoratedPotPatterns.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/entity/CalibratedSculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/block/enums/Instrument.mapping
  mappings/net/minecraft/class_8514.mapping
  mappings/net/minecraft/client/gui/screen/SplashTextRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/DecoratedPotBlockEntityRenderer.mapping
  mappings/net/minecraft/client/util/Icons.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/datafixer/fix/DecoratedPotFieldRenameFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/inventory/CraftingInventory.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/recipe/RecipeUnlocker.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
  mappings/net/minecraft/structure/processor/StructureProcessorLists.mapping
  mappings/net/minecraft/world/event/Vibrations.mapping
  mappings/net/minecraft/world/event/listener/GameEventListener.mapping
Labels: refactor, new, snapshot

#3551 More 23w16a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/SculkSensorBlock.mapping
  mappings/net/minecraft/block/entity/SculkCatalystBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenuCommand.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/tooltip/HoveredTooltipPositioner.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipPositioner.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/LightDebugRenderer.mapping
  mappings/net/minecraft/data/server/loottable/BlockLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/fix/RenameChunkStatusFix.mapping
  mappings/net/minecraft/network/encryption/PublicPlayerSession.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/Language.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkSkyLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightStorage.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
  mappings/net/minecraft/world/event/Vibrations.mapping
  mappings/net/minecraft/world/event/listener/SimpleGameEventDispatcher.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3552 23w17a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaHusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/data/server/recipe/VanillaRecipeProvider.mapping
  mappings/net/minecraft/datafixer/fix/ChunkDeleteLightFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/task/FleeTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/TemptTask.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/recipe/CraftingDecoratedPotRecipe.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeature.mapping
  mappings/net/minecraft/world/gen/feature/HugeFungusFeatureConfig.mapping
Labels: refactor, new, snapshot

#3553 Add mappings for font and light handling
  mappings/net/minecraft/class_8527.mapping
  mappings/net/minecraft/class_8528.mapping
  mappings/net/minecraft/client/font/BitmapFont.mapping
  mappings/net/minecraft/client/font/FontLoader.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/GlyphAtlasTexture.mapping
  mappings/net/minecraft/client/font/GlyphContainer.mapping
  mappings/net/minecraft/client/font/GlyphRenderer.mapping
  mappings/net/minecraft/client/font/ReferenceFont.mapping
  mappings/net/minecraft/client/font/TextRenderLayerSet.mapping
  mappings/net/minecraft/client/font/TrueTypeFontLoader.mapping
  mappings/net/minecraft/client/font/UnicodeTextureFont.mapping
  mappings/net/minecraft/registry/tag/TagGroupLoader.mapping
  mappings/net/minecraft/resource/DependencyTracker.mapping
  mappings/net/minecraft/util/collection/PaletteStorage.mapping
  mappings/net/minecraft/util/math/ChunkSectionPos.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/light/ChunkBlockLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkSkyLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightSourceView.mapping
  mappings/net/minecraft/world/chunk/light/LightStorage.mapping
  mappings/net/minecraft/world/chunk/light/LightingProvider.mapping
  mappings/net/minecraft/world/chunk/light/LightingView.mapping
  mappings/net/minecraft/world/chunk/light/SkyLightStorage.mapping
Labels: refactor, new, snapshot

#3554 23w17a stuff
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/platform/TextureUtil.mapping
  mappings/net/minecraft/client/font/BitmapFont.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/GlyphAtlasTexture.mapping
  mappings/net/minecraft/client/font/GlyphContainer.mapping
  mappings/net/minecraft/client/font/ReferenceFont.mapping
  mappings/net/minecraft/client/font/TrueTypeFontLoader.mapping
  mappings/net/minecraft/client/font/UnihexFont.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/network/encryption/SignatureVerifier.mapping
  mappings/net/minecraft/registry/tag/TagGroupLoader.mapping
  mappings/net/minecraft/util/ApiServices.mapping
  mappings/net/minecraft/world/ModifiableWorld.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkNibbleArray.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/WrapperProtoChunk.mapping
  mappings/net/minecraft/world/chunk/light/ChunkSkyLight.mapping
  mappings/net/minecraft/world/chunk/light/LightSourceView.mapping
  unpick-definitions/entity_status.unpick
  unpick-definitions/gl.unpick
  unpick-definitions/key_bindings.unpick
  unpick-definitions/network_packets.unpick
  unpick-definitions/set_block_state_flags.unpick
Labels: bug, refactor, new, snapshot, javadoc, unpick

#3555 Fix wrong `projectile` argument name in `CrossbowItem#loadProjectiles`
  mappings/net/minecraft/item/CrossbowItem.mapping
Labels: bug, snapshot

#3556 Update Gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: toolchain

#3558 Rename the StatusEffectUtil.durationToString method to getDurationText
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
Labels: refactor, snapshot
