Repository FabricMC/yarn, pull requests merged in 2023-03, with the labels that each got.

#3518 1.19.4-pre2 stuff
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/navigation/FocusedRect.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldCreator.mapping
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/data/server/tag/TagProvider.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/screen/ScreenTexts.mapping
Labels: new, snapshot, javadoc

#3520 Improve ambiguous brain tasks
  mappings/net/minecraft/entity/ai/brain/task/FleeTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LookAtMobTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LookAtMobWithIntervalTask.mapping
Labels: bug, refactor, snapshot, impactful

#3521 1.19.4 pre3 stuff
  mappings/net/minecraft/client/Keyboard.mapping
  mappings/net/minecraft/client/gui/ScreenPos.mapping
  mappings/net/minecraft/client/gui/ScreenRect.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/tab/TabManager.mapping
  mappings/net/minecraft/client/gui/widget/TabNavigationWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/texture/DynamicTexture.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/SpriteLoader.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/client/texture/TextureStitcher.mapping
  mappings/net/minecraft/entity/ai/brain/Brain.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3522 Improve some worldgen parameters
  mappings/net/minecraft/world/gen/feature/PlacedFeature.mapping
  mappings/net/minecraft/world/gen/feature/PlacedFeatures.mapping
  mappings/net/minecraft/world/gen/treedecorator/TreeDecorator.mapping
Labels: bug, refactor, snapshot

#3523 1.19.4-pre4/rc stuff
  mappings/net/minecraft/client/color/world/GrassColors.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/CreditsAndAttributionScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/widget/ThreePartsLayoutWidget.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/entity/data/DataTracker.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/passive/AxolotlBrain.mapping
  mappings/net/minecraft/entity/projectile/ShulkerBulletEntity.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/Urls.mapping
  mappings/net/minecraft/util/math/GivensPair.mapping
  mappings/net/minecraft/util/math/MatrixUtil.mapping
Labels: refactor, new, snapshot, javadoc

#3526 23w12a stuff
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/systems/VertexSorter.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/LeavesBlock.mapping
  mappings/net/minecraft/block/SpongeBlock.mapping
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignText.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/block/entity/BrushableBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/data/server/loottable/vanilla/VanillaBlockLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/fix/BiomesFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityBlockStateFix.mapping
  mappings/net/minecraft/datafixer/fix/GameEventRenamesFix.mapping
  mappings/net/minecraft/datafixer/fix/ObjectiveRenderTypeFix.mapping
  mappings/net/minecraft/datafixer/fix/RecipeFix.mapping
  mappings/net/minecraft/datafixer/fix/RecipeRenamingFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveFeatureTogglesFix.mapping
  mappings/net/minecraft/datafixer/fix/RenameBlockEntityFix.mapping
  mappings/net/minecraft/datafixer/mapping/FlatteningBiomeMapping.mapping
  mappings/net/minecraft/datafixer/mapping/FlatteningRecipeMapping.mapping
  mappings/net/minecraft/datafixer/mapping/WoodRecipeMapping.mapping
  mappings/net/minecraft/entity/ai/brain/task/WanderAroundTask.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/item/SignItem.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/structure/rule/blockentity/AppendLootRuleBlockEntityModifier.mapping
  mappings/net/minecraft/structure/rule/blockentity/AppendStaticRuleBlockEntityModifier.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/world/RedstoneView.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3527 Update World Events unpick
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  unpick-definitions/world_events.unpick
Labels: bug, new, snapshot, javadoc, unpick

#3528 Fix typo + map 1 method
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/registry/Registry.mapping
Labels: bug, new, snapshot

#3530 23w13a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractSignBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/Material.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/render/entity/animation/SnifferAnimations.mapping
  mappings/net/minecraft/client/render/entity/model/SnifferEntityModel.mapping
  mappings/net/minecraft/client/sound/MusicTracker.mapping
  mappings/net/minecraft/data/client/Models.mapping
  mappings/net/minecraft/data/client/TextureMap.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/structure/StructureTemplate.mapping
  mappings/net/minecraft/structure/processor/StructureProcessor.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
Labels: bug, refactor, new, snapshot

#3531 More 23w13a stuff
  mappings/net/minecraft/block/HangingSignBlock.mapping
  mappings/net/minecraft/block/WallHangingSignBlock.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/predicate/entity/PlayerPredicate.mapping
  mappings/net/minecraft/structure/processor/CappedStructureProcessor.mapping
  mappings/net/minecraft/world/chunk/light/ChunkBlockLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/LevelPropagator.mapping
  mappings/net/minecraft/world/chunk/light/PendingUpdateQueue.mapping
Labels: new, snapshot
