Repository FabricMC/yarn, pull requests merged in 2023-02, with the labels that each got.

#3471 Fix some data fix classes not being suffixed
  mappings/net/minecraft/datafixer/fix/BlockEntityKeepPackedFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityTheRenameningBlockFix.mapping
Labels: bug, refactor, snapshot

#3469 23w05a stuff
  mappings/net/minecraft/class_8100.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingButtons.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/GridScreenTab.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmithingScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldCreator.mapping
  mappings/net/minecraft/client/gui/tab/Tab.mapping
  mappings/net/minecraft/client/gui/tab/TabManager.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/GridWidget.mapping
  mappings/net/minecraft/client/gui/widget/IconButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabNavigationWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/datafixer/fix/StatusEffectDurationFix.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/passive/CamelBrain.mapping
  mappings/net/minecraft/item/Wearable.mapping
  mappings/net/minecraft/item/trim/ArmorTrim.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/screen/ScreenTexts.mapping
  mappings/net/minecraft/server/command/EffectCommand.mapping
  mappings/net/minecraft/world/Difficulty.mapping
Labels: new, snapshot

#3473 Fix wrong name of `method_10772`.
  mappings/net/minecraft/network/ClientConnection.mapping
Labels: bug, refactor, snapshot

#3472 More 23w05a stuff
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gui/navigation/Navigable.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldScreenOptionGrid.mapping
  mappings/net/minecraft/client/gui/tooltip/WidgetTooltipPositioner.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/data/client/Models.mapping
  mappings/net/minecraft/data/client/TextureMap.mapping
  mappings/net/minecraft/entity/LimbAnimator.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/item/trim/ArmorTrim.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPattern.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/util/math/ColorHelper.mapping
  mappings/net/minecraft/util/math/MatrixUtil.mapping
Labels: new, snapshot

#3477 23w06a Display Entities
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/ArmorEntityModel.mapping
  mappings/net/minecraft/client/render/model/json/Mode.mapping
  mappings/net/minecraft/client/render/model/json/ModelTransformationMode.mapping
  mappings/net/minecraft/datafixer/schema/Schema3325.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/decoration/Brightness.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/AffineTransformation.mapping
  mappings/net/minecraft/util/math/ColorHelper.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: refactor, new, snapshot

#3479 Fix #3455 - Inconsistent DrawableHelper methods
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
Labels: refactor, snapshot

#3484 23w06a misc stuff
  mappings/net/minecraft/block/entity/JukeboxBlockEntity.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/widget/TabNavigationWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingEntity.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/potion/Potions.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/RideCommand.mapping
  mappings/net/minecraft/server/command/SummonCommand.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/AffineTransformation.mapping
Labels: refactor, new, snapshot

#3485 23w06a, more stuff
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/widget/AbstractTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/MultilineTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/NarratedMultilineTextWidget.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/damage/DamageTracker.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/item/Equipment.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityDamageS2CPacket.mapping
  mappings/net/minecraft/predicate/TagPredicate.mapping
  mappings/net/minecraft/predicate/entity/DamageSourcePredicate.mapping
  mappings/net/minecraft/screen/PlayerScreenHandler.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/world/World.mapping
Labels: refactor, new, snapshot

#3478 Fix #3434 - getStarBrightness -> getSkyBrightness
  mappings/net/minecraft/client/world/ClientWorld.mapping
Labels: bug, refactor, snapshot

#3482 23w06a - Experiments Screen
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/screen/world/ExperimentsScreen.mapping
Labels: new, snapshot

#3480 #3308 - Rename scoreboardTag methods to commandTag
  mappings/net/minecraft/entity/Entity.mapping
Labels: refactor, snapshot

#3486 Fix typo in RecipeProvider
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
Labels: bug, snapshot

#3487 Rename the Vec3d#withBias method to offset
  mappings/net/minecraft/util/math/Vec3d.mapping
Labels: refactor, snapshot

#3490 23w06a stuff
  mappings/net/minecraft/block/CaveVines.mapping
  mappings/net/minecraft/block/ComposterBlock.mapping
  mappings/net/minecraft/block/FarmlandBlock.mapping
  mappings/net/minecraft/block/LecternBlock.mapping
  mappings/net/minecraft/block/RespawnAnchorBlock.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/damage/DamageEffects.mapping
  mappings/net/minecraft/entity/decoration/Brightness.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleInventory.mapping
  mappings/net/minecraft/item/DecorationItem.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/util/CachedMapper.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/Nullables.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/AffineTransformation.mapping
  mappings/net/minecraft/util/math/AffineTransformations.mapping
  mappings/net/minecraft/world/World.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3489 23w06a client
  mappings/net/minecraft/class_8133.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryEventWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryInfoScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/ExperimentalWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/ExperimentsScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldScreenOptionGrid.mapping
  mappings/net/minecraft/client/gui/widget/LayoutWidget.mapping
  mappings/net/minecraft/client/gui/widget/MultilineTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/gui/widget/ThreePartsLayoutWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/realms/util/RealmsTextureManager.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/debug/BeeDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/ChunkBorderDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameEventDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GameTestDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/GoalSelectorDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/PathfindingDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/RaidCenterDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/VillageDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/VillageSectionsDebugRenderer.mapping
Labels: bug, refactor, new, snapshot

#3491 23w07a worldgen mappings
  mappings/net/minecraft/util/math/intprovider/IntProvider.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
  mappings/net/minecraft/world/gen/foliage/CherryFoliagePlacer.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/trunk/CherryTrunkPlacer.mapping
Labels: refactor, new, snapshot

#3497 23w07a misc
  mappings/com/mojang/blaze3d/platform/TextureUtil.mapping
  mappings/net/minecraft/advancement/criterion/TickCriterion.mapping
  mappings/net/minecraft/block/AbstractPressurePlateBlock.mapping
  mappings/net/minecraft/block/ButtonBlock.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/FenceGateBlock.mapping
  mappings/net/minecraft/block/PressurePlateBlock.mapping
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/block/WeightedPressurePlateBlock.mapping
  mappings/net/minecraft/block/entity/JukeboxBlockEntity.mapping
  mappings/net/minecraft/entity/Attackable.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkTowardsLookTargetTask.mapping
  mappings/net/minecraft/entity/ai/goal/FollowOwnerGoal.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/entity/passive/AllayBrain.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/registry/BuiltinRegistries.mapping
  mappings/net/minecraft/registry/OneTwentyBuiltinRegistries.mapping
  mappings/net/minecraft/registry/RegistryBuilder.mapping
  mappings/net/minecraft/structure/processor/StructureProcessor.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/util/VanillaBiomeParameters.mapping
  mappings/net/minecraft/world/gen/WorldPresets.mapping
  mappings/net/minecraft/world/gen/feature/DesertWellFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
  mappings/net/minecraft/world/gen/trunk/CherryTrunkPlacer.mapping
Labels: new, snapshot, javadoc

#3495 23w07a networking
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/MultiplayerServerListPinger.mapping
  mappings/net/minecraft/client/network/OtherClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/report/AbuseReportReason.mapping
  mappings/net/minecraft/client/util/BanReason.mapping
  mappings/net/minecraft/client/util/Bans.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/s2c/play/ServerMetadataS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/ServerMetadata.mapping
  mappings/net/minecraft/server/network/ServerQueryNetworkHandler.mapping
Labels: refactor, new, snapshot, javadoc

#3496 23w07a client
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingButtons.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/client/render/item/BuiltinModelItemRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
Labels: new, snapshot

#3494 Map interaction entity
  mappings/net/minecraft/entity/decoration/InteractionEntity.mapping
Labels: new, snapshot

#3501 Fix some typos
  mappings/net/minecraft/entity/damage/DamageTypes.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/item/ItemGroups.mapping
  mappings/net/minecraft/server/command/RideCommand.mapping
  mappings/net/minecraft/text/Text.mapping
Labels: bug, refactor, snapshot

#3509 Map ChestBlockEntity.VIEWER_COUNT_UPDATE_EVENT_TYPE
  mappings/net/minecraft/block/entity/ChestBlockEntity.mapping
Labels: new, snapshot

#3505 Improve methods related to closing handled screens
  mappings/net/minecraft/block/entity/ChestBlockEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
Labels: bug, refactor, snapshot, javadoc

#3508 ItemUsageContext.getPlayerFacing -> getHorizontalPlayerFacing
  mappings/net/minecraft/item/ItemUsageContext.mapping
Labels: refactor, snapshot, impactful

#3507 Improve option widget names
  mappings/net/minecraft/client/gui/widget/OptionListWidget.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
Labels: bug, refactor, snapshot, impactful

#3506 Rename tree/mushroom modifier methods in VegetationPlacedFeatures
  mappings/net/minecraft/world/gen/feature/VegetationPlacedFeatures.mapping
Labels: refactor, snapshot

#3504 Minor fixes
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/gl/GlImportProcessor.mapping
  mappings/net/minecraft/client/render/block/BlockRenderManager.mapping
  mappings/net/minecraft/screen/ScreenHandlerFactory.mapping
Labels: bug, refactor, snapshot

#3512 ChunkNoiseSampler and DensityFunction renames and documentation
  mappings/net/minecraft/world/gen/chunk/BlendingData.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkNoiseSampler.mapping
  mappings/net/minecraft/world/gen/chunk/GenerationShapeConfig.mapping
  mappings/net/minecraft/world/gen/densityfunction/DensityFunction.mapping
Labels: refactor, snapshot, javadoc

#3516 More 1.19.4-pre1 stuff
  mappings/net/minecraft/SharedConstants.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/navigation/FocusedRect.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackOrganizer.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/ExperimentsScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldCreator.mapping
  mappings/net/minecraft/client/gui/tab/GridScreenTab.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/PressableWidget.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabNavigationWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/CheckedGson.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/RealmsPeriodicCheckers.mapping
  mappings/net/minecraft/client/realms/dto/RealmsNotification.mapping
  mappings/net/minecraft/client/realms/dto/RealmsText.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsNotificationsScreen.mapping
  mappings/net/minecraft/client/realms/util/JsonUtils.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/resource/DefaultClientResourcePackProvider.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/data/server/BiomeParametersProvider.mapping
  mappings/net/minecraft/data/server/tag/ItemTagProvider.mapping
  mappings/net/minecraft/data/server/tag/TagProvider.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/entity/SaddledComponent.mapping
  mappings/net/minecraft/entity/ai/brain/task/WalkTask.mapping
  mappings/net/minecraft/entity/damage/DamageSources.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/entity/passive/StriderEntity.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkBiomeDataS2CPacket.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/StringIdentifiable.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/biome/SpawnSettings.mapping
  mappings/net/minecraft/world/biome/source/MultiNoiseBiomeSource.mapping
  mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  mappings/net/minecraft/world/gen/WorldPresets.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3511 Rename `FilledMapItem#getOrCreateMapState` to `getMapState`
  mappings/net/minecraft/item/FilledMapItem.mapping
Labels: bug, refactor, snapshot

#3510 Fix wrong `showIcons` argument names in `MapState` and `MapUpdateS2CPacket`
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/network/packet/s2c/play/MapUpdateS2CPacket.mapping
Labels: bug, refactor, snapshot

#3517 Misc small things
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/entity/ai/control/LookControl.mapping
  mappings/net/minecraft/entity/mob/IllusionerEntity.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/structure/MineshaftGenerator.mapping
  mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/gen/feature/IcebergFeature.mapping
  mappings/net/minecraft/world/gen/structure/RuinedPortalStructure.mapping
Labels: new, snapshot
