Repository FabricMC/yarn, pull requests merged in 2023-01, with the labels that each got.

#3458 23w03a stuff
  mappings/net/minecraft/GameVersion.mapping
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/LogoDrawer.mapping
  mappings/net/minecraft/client/gui/NavigationType.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/NavigationAxis.mapping
  mappings/net/minecraft/client/gui/screen/NavigationDirection.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/LanguageOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/ResourcePackOrganizer.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/NarratedMultilineTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/gui/widget/Widget.mapping
  mappings/net/minecraft/client/gui/widget/WrapperWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/MultiplayerServerListPinger.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/VexEntityModel.mapping
  mappings/net/minecraft/client/resource/language/LanguageDefinition.mapping
  mappings/net/minecraft/client/resource/language/LanguageManager.mapping
  mappings/net/minecraft/client/resource/language/TranslationStorage.mapping
  mappings/net/minecraft/client/resource/metadata/LanguageResourceMetadata.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/command/argument/BlockPosArgumentType.mapping
  mappings/net/minecraft/command/argument/TimeArgumentType.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/pathing/LandPathNodeMaker.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/BundlePacket.mapping
  mappings/net/minecraft/network/packet/Packet.mapping
  mappings/net/minecraft/network/packet/s2c/play/DamageTiltS2CPacket.mapping
  mappings/net/minecraft/screen/ScreenTexts.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/text/TranslatableTextContent.mapping
  mappings/net/minecraft/util/Language.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
  mappings/net/minecraft/world/tick/WorldTickScheduler.mapping
Labels: refactor, new, snapshot

#3457 23w03a commands
  mappings/net/minecraft/command/argument/BlockPosArgumentType.mapping
  mappings/net/minecraft/server/command/CloneCommand.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/RideCommand.mapping
  mappings/net/minecraft/server/command/WeatherCommand.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: refactor, new, snapshot

#3459 23w03a networking
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/PacketBundleHandler.mapping
  mappings/net/minecraft/network/PacketBundler.mapping
  mappings/net/minecraft/network/PacketUnbundler.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/network/packet/BundleSplitterPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/BundleS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/PositionFlag.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
Labels: refactor, new, snapshot

#3460 More 23w03a stuff
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementDisplays.mapping
  mappings/net/minecraft/advancement/PlayerAdvancementTracker.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/datafixer/fix/OptionsAccessibilityOnboardFix.mapping
  mappings/net/minecraft/entity/mob/GuardianEntity.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/util/math/RotationCalculator.mapping
  mappings/net/minecraft/util/math/RotationPropertyHelper.mapping
Labels: new, snapshot, javadoc

#3452 Rename LivingEntity#getArrowType to getProjectileType
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: bug, snapshot

#3461 23w03a more stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/NavigationType.mapping
  mappings/net/minecraft/client/gui/ParentElement.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/navigation/FocusedPos.mapping
  mappings/net/minecraft/client/gui/navigation/FocusedRect.mapping
  mappings/net/minecraft/client/gui/navigation/GuiNavigation.mapping
  mappings/net/minecraft/client/gui/navigation/GuiNavigationPath.mapping
  mappings/net/minecraft/client/gui/navigation/GuiNavigationType.mapping
  mappings/net/minecraft/client/gui/navigation/NavigationAxis.mapping
  mappings/net/minecraft/client/gui/navigation/NavigationDirection.mapping
  mappings/net/minecraft/client/gui/screen/NavigationDirection.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsListWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/KeybindsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryEventWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/widget/AxisGridWidget.mapping
  mappings/net/minecraft/client/gui/widget/ElementListWidget.mapping
  mappings/net/minecraft/client/gui/widget/EmptyWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/GridWidget.mapping
  mappings/net/minecraft/client/gui/widget/NarratedMultilineTextWidget.mapping
  mappings/net/minecraft/client/gui/widget/ScrollableWidget.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/gui/widget/SliderWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/gui/widget/Widget.mapping
  mappings/net/minecraft/client/gui/widget/WrapperWidget.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/client/resource/language/LanguageDefinition.mapping
  mappings/net/minecraft/datafixer/DataFixTypes.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/pathing/EntityNavigation.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/entity/passive/CamelEntity.mapping
  mappings/net/minecraft/entity/passive/FrogEntity.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/ParrotEntity.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/Vec3i.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: refactor, new, snapshot, javadoc

#3462 23w04a stuff
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/class_8046.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/DrawableHelper.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackListWidget.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/Ownable.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/math/ColorHelper.mapping
Labels: new, snapshot

#3464 23w04a stuff
  mappings/net/minecraft/client/gui/screen/ingame/CyclingSlotIcon.mapping
  mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmithingScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeResultCollection.mapping
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
  mappings/net/minecraft/client/recipebook/ClientRecipeBook.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/entity/EntityRendererFactory.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/texture/atlas/AtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/PalettedPermutationsAtlasSource.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/data/client/Model.mapping
  mappings/net/minecraft/data/client/Models.mapping
  mappings/net/minecraft/data/client/TextureMap.mapping
  mappings/net/minecraft/data/server/advancement/AdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/OneTwentyHusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/advancement/VanillaHusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/loottable/ChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/OneTwentyChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/OneTwentyEntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/OneTwentyFishingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/VanillaChestLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/VanillaEntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/VanillaFishingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/recipe/LegacySmithingRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/data/server/recipe/SmithingTransformRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/SmithingTrimRecipeJsonBuilder.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/TntEntity.mapping
  mappings/net/minecraft/entity/mob/EvokerFangsEntity.mapping
  mappings/net/minecraft/entity/mob/VexEntity.mapping
  mappings/net/minecraft/item/ArmorItem.mapping
  mappings/net/minecraft/item/ArmorMaterial.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/item/trim/ArmorTrim.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPattern.mapping
  mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/SmithingTrimRecipe.mapping
  mappings/net/minecraft/screen/ForgingScreenHandler.mapping
  mappings/net/minecraft/screen/LegacySmithingScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerType.mapping
  mappings/net/minecraft/screen/slot/ForgingSlotsManager.mapping
  mappings/net/minecraft/server/command/SpawnArmorTrimsCommand.mapping
Labels: refactor, new, snapshot
