Repository FabricMC/yarn, pull requests merged in 2023-06, with the labels that each got.

#3590 1.20.1-rc1 stuff
  mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
Labels: new, snapshot

#3600 GameMenuScreen constants
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
Labels: new, release

#3598 Rename `unlockCraftedRecipe` to `onRecipeCrafted` in `PlayerEntity`
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
Labels: bug, refactor, release

#3599 Swapped parameters in DrawContext#fill to be the right way around
  mappings/net/minecraft/client/gui/DrawContext.mapping
Labels: bug, release

#3582 1.20 client mappings
  mappings/net/minecraft/block/ComposterBlock.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/client/gui/LogoDrawer.mapping
  mappings/net/minecraft/client/gui/PlayerSkinDrawer.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/hud/ClientBossBar.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/SpectatorHud.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenu.mapping
  mappings/net/minecraft/client/gui/screen/SplashTextRenderer.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/render/Frustum.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/debug/LightDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/SupportingBlockDebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/animation/AnimationHelper.mapping
  mappings/net/minecraft/client/render/entity/animation/Transformation.mapping
  mappings/net/minecraft/client/render/entity/model/CamelEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/FrogEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/SnifferEntityModel.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkStructuresTemplateRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkToProtoChunkFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityItemFrameDirectionFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityRedundantChanceTagsFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityTheRenameningBlockFix.mapping
  mappings/net/minecraft/datafixer/fix/LeavesFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsKeyLwjgl3Fix.mapping
  mappings/net/minecraft/datafixer/fix/TicksInWrongChunkFix.mapping
  mappings/net/minecraft/datafixer/fix/UntaggedSpawnerFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema99.mapping
  mappings/net/minecraft/screen/AnvilScreenHandler.mapping
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/screen/BrewingStandScreenHandler.mapping
  mappings/net/minecraft/screen/CartographyTableScreenHandler.mapping
  mappings/net/minecraft/screen/CraftingScreenHandler.mapping
  mappings/net/minecraft/screen/Generic3x3ContainerScreenHandler.mapping
  mappings/net/minecraft/screen/GenericContainerScreenHandler.mapping
  mappings/net/minecraft/screen/GrindstoneScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/screen/PlayerScreenHandler.mapping
  mappings/net/minecraft/screen/SmithingScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
Labels: new, release
