Repository FabricMC/yarn, pull requests merged in 2023-11, with the labels that each got.

#3713 Rename the Blocks.createStairs method to createStairsBlock
  mappings/net/minecraft/block/Blocks.mapping
Labels: bug, refactor, snapshot

#3714 23w44a stuff
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/class_8934.mapping
  mappings/net/minecraft/client/option/HotbarStorage.mapping
  mappings/net/minecraft/client/render/entity/model/BatEntityModel.mapping
  mappings/net/minecraft/inventory/LootableInventory.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: new, snapshot

#3715 Various mappings, renames, and fixes
  mappings/net/minecraft/advancement/AdvancementPositioner.mapping
  mappings/net/minecraft/advancement/criterion/BredAnimalsCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConsumeItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/CriterionProgress.mapping
  mappings/net/minecraft/advancement/criterion/CuredZombieVillagerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EffectsChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnchantedItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnterBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EntityHurtPlayerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FilledBucketCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FishingRodHookedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemDurabilityChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LevitationCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LightningStrikeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/OnKilledCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerHurtEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerInteractedWithEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/RecipeUnlockedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ShotCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SlideDownBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SummonedEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TameAnimalCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ThrownItemPickedUpByEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TickCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TravelCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedTotemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsingItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
  mappings/net/minecraft/block/AbstractCauldronBlock.mapping
  mappings/net/minecraft/block/BambooShootBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/BulbBlock.mapping
  mappings/net/minecraft/block/CropBlock.mapping
  mappings/net/minecraft/block/DoubleBlockProperties.mapping
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/MossBlock.mapping
  mappings/net/minecraft/block/OxidizableBulbBlock.mapping
  mappings/net/minecraft/block/SculkShriekerBlock.mapping
  mappings/net/minecraft/block/SpongeBlock.mapping
  mappings/net/minecraft/block/StructureVoidBlock.mapping
  mappings/net/minecraft/block/SweetBerryBushBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/entity/BeehiveBlockEntity.mapping
  mappings/net/minecraft/block/entity/BrushableBlockEntity.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSpreadManager.mapping
  mappings/net/minecraft/block/enums/Orientation.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/Model.mapping
  mappings/net/minecraft/state/property/DirectionProperty.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: bug, refactor, new, snapshot

#3717 23w44a more stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/inventory/LootableInventory.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/test/GameTestState.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/util/math/BlockBox.mapping
  mappings/net/minecraft/world/tick/TickManager.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3716 23w44a commands
  mappings/net/minecraft/command/CommandAction.mapping
  mappings/net/minecraft/command/CommandExecutionContext.mapping
  mappings/net/minecraft/command/CommandFunctionAction.mapping
  mappings/net/minecraft/command/ControlFlowAware.mapping
  mappings/net/minecraft/command/ExecutionControl.mapping
  mappings/net/minecraft/command/ExecutionFlags.mapping
  mappings/net/minecraft/command/FixedCommandAction.mapping
  mappings/net/minecraft/command/Forkable.mapping
  mappings/net/minecraft/command/Frame.mapping
  mappings/net/minecraft/command/ReturnValueConsumer.mapping
  mappings/net/minecraft/command/SingleCommandAction.mapping
  mappings/net/minecraft/command/SourcedCommandAction.mapping
  mappings/net/minecraft/command/SteppedCommandAction.mapping
  mappings/net/minecraft/server/command/AbstractServerCommandSource.mapping
  mappings/net/minecraft/server/command/DebugCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/FunctionCommand.mapping
  mappings/net/minecraft/server/command/ReturnCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/command/TickCommand.mapping
Labels: refactor, new, snapshot

#3720 Map trial spawner
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/TrialSpawnerBlock.mapping
  mappings/net/minecraft/block/entity/SpawnerBlockEntity.mapping
  mappings/net/minecraft/block/entity/TrialSpawnerBlockEntity.mapping
  mappings/net/minecraft/block/entity/spawner/EntityDetector.mapping
  mappings/net/minecraft/block/entity/spawner/TrialSpawnerData.mapping
  mappings/net/minecraft/block/entity/spawner/TrialSpawnerLogic.mapping
  mappings/net/minecraft/block/enums/TrialSpawnerState.mapping
  mappings/net/minecraft/class_8959.mapping
  mappings/net/minecraft/class_8965.mapping
  mappings/net/minecraft/class_8984.mapping
  mappings/net/minecraft/client/render/block/entity/MobSpawnerBlockEntityRenderer.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/world/MobSpawnerLogic.mapping
Labels: new, snapshot

#3721 more 23w45a stuff
  mappings/net/minecraft/block/spawner/EntityDetector.mapping
  mappings/net/minecraft/block/spawner/MobSpawnerEntry.mapping
  mappings/net/minecraft/block/spawner/MobSpawnerLogic.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerConfig.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerData.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerLogic.mapping
  mappings/net/minecraft/class_8965.mapping
  mappings/net/minecraft/command/FallthroughCommandAction.mapping
  mappings/net/minecraft/command/IsolatedCommandAction.mapping
  mappings/net/minecraft/command/SingleCommandAction.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeJumpTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeShootTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeSlideTowardsTargetTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
  mappings/net/minecraft/entity/mob/BreezeBrain.mapping
  mappings/net/minecraft/entity/mob/BreezeEntity.mapping
  mappings/net/minecraft/util/Uuids.mapping
  mappings/net/minecraft/util/math/LongJumpUtil.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
Labels: refactor, new, snapshot

#3722 23w45a Shinanigans
  mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
Labels: new, snapshot

#3723 23w45a advancements
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/AdvancementCriterion.mapping
  mappings/net/minecraft/advancement/AdvancementDisplay.mapping
  mappings/net/minecraft/advancement/AdvancementRewards.mapping
  mappings/net/minecraft/advancement/criterion/BeeNestDestroyedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BredAnimalsCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BrewedPotionCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ChangedDimensionCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ChanneledLightningCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConstructBeaconCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConsumeItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/CriterionConditions.mapping
  mappings/net/minecraft/advancement/criterion/CuredZombieVillagerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EffectsChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnchantedItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnterBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EntityHurtPlayerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FilledBucketCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FishingRodHookedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/InventoryChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemDurabilityChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/KilledByCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LevitationCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LightningStrikeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/OnKilledCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerGeneratesContainerLootCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerHurtEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerInteractedWithEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/RecipeCraftedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/RecipeUnlockedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ShotCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SlideDownBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/StartedRidingCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SummonedEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TameAnimalCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ThrownItemPickedUpByEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TickCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TravelCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedEnderEyeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedTotemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsingItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
Labels: bug, refactor, new, snapshot

#3724 23w45a predicates
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/DamagePredicate.mapping
  mappings/net/minecraft/predicate/FluidPredicate.mapping
  mappings/net/minecraft/predicate/LightPredicate.mapping
  mappings/net/minecraft/predicate/NumberRange.mapping
  mappings/net/minecraft/predicate/StatePredicate.mapping
  mappings/net/minecraft/predicate/TagPredicate.mapping
  mappings/net/minecraft/predicate/entity/DamageSourcePredicate.mapping
  mappings/net/minecraft/predicate/entity/DistancePredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityEquipmentPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityFlagsPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityTypePredicate.mapping
  mappings/net/minecraft/predicate/entity/FishingHookPredicate.mapping
  mappings/net/minecraft/predicate/entity/LightningBoltPredicate.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/predicate/entity/LootContextPredicate.mapping
  mappings/net/minecraft/predicate/entity/LootContextPredicateValidator.mapping
  mappings/net/minecraft/predicate/entity/PlayerPredicate.mapping
  mappings/net/minecraft/predicate/entity/SlimePredicate.mapping
  mappings/net/minecraft/predicate/entity/TypeSpecificPredicate.mapping
  mappings/net/minecraft/predicate/entity/VariantPredicates.mapping
  mappings/net/minecraft/predicate/item/EnchantmentPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
Labels: new, snapshot

#3726 23w45a misc
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerData.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/EnergySwirlOverlayFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/command/CommandQueueEntry.mapping
  mappings/net/minecraft/datafixer/schema/Schema3689.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/SpawnReason.mapping
  mappings/net/minecraft/entity/mob/BreezeEntity.mapping
  mappings/net/minecraft/entity/mob/SkeletonHorseEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieHorseEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/entity/vehicle/TntMinecartEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/LootTableReporter.mapping
  mappings/net/minecraft/loot/function/ApplyBonusLootFunction.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExplosionS2CPacket.mapping
  mappings/net/minecraft/registry/ExperimentalRegistriesValidator.mapping
  mappings/net/minecraft/registry/RegistryBuilder.mapping
  mappings/net/minecraft/registry/RegistryCloner.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
  mappings/net/minecraft/registry/RegistryLoader.mapping
  mappings/net/minecraft/registry/RegistryWrapper.mapping
  mappings/net/minecraft/registry/SimpleRegistry.mapping
  mappings/net/minecraft/screen/slot/Slot.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/command/AdvancementCommand.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/structure/TrialChamberData.mapping
  mappings/net/minecraft/structure/pool/alias/StructurePoolAliasBindings.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/DelegatingDataOutput.mapping
  mappings/net/minecraft/util/ErrorReporter.mapping
  mappings/net/minecraft/util/PngMetadata.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
  mappings/net/minecraft/world/gen/structure/OneTwentyOneStructures.mapping
  mappings/net/minecraft/world/spawner/SpecialSpawner.mapping
  unpick-definitions/world_events.unpick
Labels: bug, refactor, new, snapshot, javadoc, unpick

#3727 Rename `Uuids#INT_STREAM_LIST_CODEC`
  mappings/net/minecraft/util/Uuids.mapping
Labels: refactor, snapshot

#3728 More 23w45a stuff, including unpicks
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/enums/TrialSpawnerState.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/data/client/TexturedModel.mapping
  mappings/net/minecraft/data/server/loottable/vanilla/VanillaChestLootTableGenerator.mapping
  mappings/net/minecraft/entity/mob/BreezeEntity.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/dimension/NetherPortal.mapping
  unpick-definitions/entity_model_parts.unpick
  unpick-definitions/network_packets.unpick
  unpick-definitions/set_block_state_flags.unpick
  unpick-definitions/trial_spawner_state.unpick
Labels: new, snapshot, unpick

#3729 23w46a scoreboard
  mappings/net/minecraft/class_9013.mapping
  mappings/net/minecraft/class_9015.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/loot/provider/score/LootScoreProvider.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardObjectiveUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardPlayerUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardScoreResetS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ScoreboardScoreUpdateS2CPacket.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/scoreboard/ReadableScoreboardScore.mapping
  mappings/net/minecraft/scoreboard/ScoreAccess.mapping
  mappings/net/minecraft/scoreboard/ScoreHolder.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ScoreboardEntry.mapping
  mappings/net/minecraft/scoreboard/ScoreboardObjective.mapping
  mappings/net/minecraft/scoreboard/ScoreboardPlayerScore.mapping
  mappings/net/minecraft/scoreboard/ScoreboardScore.mapping
  mappings/net/minecraft/scoreboard/Scores.mapping
  mappings/net/minecraft/scoreboard/number/BlankNumberFormat.mapping
  mappings/net/minecraft/scoreboard/number/FixedNumberFormat.mapping
  mappings/net/minecraft/scoreboard/number/NumberFormat.mapping
  mappings/net/minecraft/scoreboard/number/NumberFormatType.mapping
  mappings/net/minecraft/scoreboard/number/NumberFormatTypes.mapping
  mappings/net/minecraft/scoreboard/number/StyledNumberFormat.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/ScoreboardCommand.mapping
  mappings/net/minecraft/server/command/TeamCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/command/TriggerCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/text/ScoreTextContent.mapping
Labels: refactor, new, snapshot

#3730 23w46a criterion
  mappings/net/minecraft/advancement/criterion/AbstractCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BeeNestDestroyedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BredAnimalsCriterion.mapping
  mappings/net/minecraft/advancement/criterion/BrewedPotionCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ChangedDimensionCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ChanneledLightningCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConstructBeaconCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ConsumeItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/CuredZombieVillagerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EffectsChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnchantedItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EnterBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/EntityHurtPlayerCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FilledBucketCriterion.mapping
  mappings/net/minecraft/advancement/criterion/FishingRodHookedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/InventoryChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ItemDurabilityChangedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/KilledByCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LevitationCriterion.mapping
  mappings/net/minecraft/advancement/criterion/LightningStrikeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/OnKilledCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerGeneratesContainerLootCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerHurtEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/PlayerInteractedWithEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/RecipeCraftedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/RecipeUnlockedCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ShotCrossbowCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SlideDownBlockCriterion.mapping
  mappings/net/minecraft/advancement/criterion/StartedRidingCriterion.mapping
  mappings/net/minecraft/advancement/criterion/SummonedEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TameAnimalCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
  mappings/net/minecraft/advancement/criterion/ThrownItemPickedUpByEntityCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TickCriterion.mapping
  mappings/net/minecraft/advancement/criterion/TravelCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedEnderEyeCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsedTotemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/UsingItemCriterion.mapping
  mappings/net/minecraft/advancement/criterion/VillagerTradeCriterion.mapping
Labels: bug, refactor, snapshot

#3731 23w46a misc stuff
  mappings/net/minecraft/block/BulbBlock.mapping
  mappings/net/minecraft/block/CrafterBlock.mapping
  mappings/net/minecraft/block/GrateBlock.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/ContainerWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/server/command/FillBiomeCommand.mapping
  mappings/net/minecraft/server/command/KickCommand.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/JsonReaderUtils.mapping
  mappings/net/minecraft/util/TypeFilter.mapping
  mappings/net/minecraft/util/Util.mapping
Labels: bug, new, snapshot

#3732 23w46a more
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/test/TestContext.mapping
Labels: bug, refactor, new, snapshot

#3733 Rename grass to short grass
  gradle.properties
  mappings/net/minecraft/block/ShortPlantBlock.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/server/loottable/BlockLootTableGenerator.mapping
  mappings/net/minecraft/item/Items.mapping
Labels: refactor, snapshot

#3734 1.20.3-pre1 Advancement Data
  mappings/net/minecraft/data/server/advancement/AdvancementTabGenerator.mapping
  mappings/net/minecraft/data/server/advancement/onetwentyone/OneTwentyOneAdvancementProviders.mapping
  mappings/net/minecraft/data/server/advancement/onetwentyone/OneTwentyOneAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
Labels: new, snapshot

#3735 1.20.3-pre1 stuff
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeShootWhenNotStandingTask.mapping
  mappings/net/minecraft/entity/projectile/WindChargeEntity.mapping
  mappings/net/minecraft/scoreboard/Scores.mapping
  mappings/net/minecraft/world/explosion/ExplosionBehavior.mapping
Labels: bug, refactor, new, snapshot

#3736 1.20.3-pre1 server resource pack
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ConnectScreen.mapping
  mappings/net/minecraft/client/network/ClientCommonNetworkHandler.mapping
  mappings/net/minecraft/client/realms/task/RealmsPrepareConnectionTask.mapping
  mappings/net/minecraft/client/resource/ServerResourcePackProvider.mapping
  mappings/net/minecraft/client/resource/server/DownloadQueuer.mapping
  mappings/net/minecraft/client/resource/server/PackStateChangeCallback.mapping
  mappings/net/minecraft/client/resource/server/ReloadScheduler.mapping
  mappings/net/minecraft/client/resource/server/ServerResourcePackLoader.mapping
  mappings/net/minecraft/client/resource/server/ServerResourcePackManager.mapping
  mappings/net/minecraft/client/util/NetworkUtils.mapping
  mappings/net/minecraft/network/listener/ClientCommonPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/common/ResourcePackRemoveS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/ResourcePackSendS2CPacket.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/ServerPackCommand.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/util/Downloader.mapping
  mappings/net/minecraft/util/NetworkUtils.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/thread/GroupAssigningThreadFactory.mapping
Labels: refactor, new, snapshot

#3738 1.20.3-pre2 stuff
  mappings/net/minecraft/client/gui/hud/SubtitlesHud.mapping
  mappings/net/minecraft/client/sound/SoundInstanceListener.mapping
  mappings/net/minecraft/client/sound/SoundListener.mapping
  mappings/net/minecraft/client/sound/SoundListenerTransform.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/command/CommandExecutionContext.mapping
  mappings/net/minecraft/command/argument/CommandFunctionArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
  mappings/net/minecraft/entity/ai/goal/EatGrassGoal.mapping
  mappings/net/minecraft/entity/effect/StatusEffectUtil.mapping
  mappings/net/minecraft/entity/projectile/ExplosiveProjectileEntity.mapping
  mappings/net/minecraft/potion/PotionUtil.mapping
  mappings/net/minecraft/util/StringHelper.mapping
Labels: new, snapshot

#3740 Enable reproducible builds
  build.gradle
Labels: snapshot, toolchain

#3741 Update `ClickableWidget#renderButton` to `ClickableWidget#renderWidget`
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
Labels: refactor, snapshot, impactful

#3742 Add more unpicks
  unpick-definitions/colors.unpick
  unpick-definitions/entity_flags.unpick
  unpick-definitions/key_bindings.unpick
  unpick-definitions/network.unpick
  unpick-definitions/network_packets.unpick
Labels: snapshot, unpick

#3744 1.20.3-pre3 stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/ClientCommonNetworkHandler.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/particle/ItemPickupParticle.mapping
  mappings/net/minecraft/client/realms/task/RealmsPrepareConnectionTask.mapping
  mappings/net/minecraft/client/resource/server/PackStateChangeCallback.mapping
  mappings/net/minecraft/client/resource/server/ServerResourcePackLoader.mapping
  mappings/net/minecraft/client/session/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/data/server/advancement/AdvancementTabGenerator.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/network/message/MessageChain.mapping
  mappings/net/minecraft/network/message/MessageSignatureStorage.mapping
  mappings/net/minecraft/network/message/MessageVerifier.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/c2s/common/ResourcePackStatusC2SPacket.mapping
  mappings/net/minecraft/server/command/AbstractServerCommandSource.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/util/ApiServices.mapping
  mappings/net/minecraft/util/Downloader.mapping
  mappings/net/minecraft/util/NetworkUtils.mapping
  mappings/net/minecraft/util/path/CacheFiles.mapping
Labels: bug, refactor, new, snapshot

#3746 Map CommandExecutionContext#currentDepth
  mappings/net/minecraft/command/CommandExecutionContext.mapping
Labels: new, snapshot

#3747 1.20.3-rc1 explosion packet
  mappings/net/minecraft/network/packet/s2c/play/ExplosionS2CPacket.mapping
Labels: new, snapshot
