Repository FabricMC/yarn, pull requests merged in 2023-10, with the labels that each got.

#3680 DebugHud.{show -> should}ShowPacketSizeAndPingCharts
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
Labels: bug, release

#3685 More 23w40a stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/PopupScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/realms/dto/RealmsNotification.mapping
  mappings/net/minecraft/client/realms/dto/RealmsText.mapping
  mappings/net/minecraft/client/realms/util/JsonUtils.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeModifier.mapping
  mappings/net/minecraft/test/GameTestState.mapping
  mappings/net/minecraft/test/TestContext.mapping
Labels: new, snapshot

#3683 23w40a text
  mappings/net/minecraft/class_8828.mapping
  mappings/net/minecraft/text/BlockNbtDataSource.mapping
  mappings/net/minecraft/text/ClickEvent.mapping
  mappings/net/minecraft/text/EntityNbtDataSource.mapping
  mappings/net/minecraft/text/HoverEvent.mapping
  mappings/net/minecraft/text/KeybindTextContent.mapping
  mappings/net/minecraft/text/NbtDataSource.mapping
  mappings/net/minecraft/text/NbtTextContent.mapping
  mappings/net/minecraft/text/PlainTextContent.mapping
  mappings/net/minecraft/text/ScoreTextContent.mapping
  mappings/net/minecraft/text/SelectorTextContent.mapping
  mappings/net/minecraft/text/StorageNbtDataSource.mapping
  mappings/net/minecraft/text/Style.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
  mappings/net/minecraft/text/TextContent.mapping
  mappings/net/minecraft/text/TranslatableTextContent.mapping
Labels: refactor, new, snapshot, javadoc

#3684 23w40a util
  mappings/net/minecraft/util/StringIdentifiable.mapping
  mappings/net/minecraft/util/UserCache.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/Uuids.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/dynamic/RuntimeOps.mapping
Labels: new, snapshot, javadoc

#3686 23w40a client
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/DownloadingTerrainScreen.mapping
  mappings/net/minecraft/client/gui/screen/PopupScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/OptimizeWorldScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/WorldLoadingState.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/dto/RealmsNotification.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/ResetWorldInfo.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/util/MacWindowUtil.mapping
Labels: new, snapshot

#3689 Rename the SnowmanPumpkinFeatureRenderer class to SnowGolemPumpkinFeatureRenderer
  mappings/net/minecraft/client/render/entity/feature/SnowGolemPumpkinFeatureRenderer.mapping
Labels: bug, refactor, snapshot

#3688 23w40a blocks
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AmethystClusterBlock.mapping
  mappings/net/minecraft/block/AttachedStemBlock.mapping
  mappings/net/minecraft/block/BannerBlock.mapping
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/BrushableBlock.mapping
  mappings/net/minecraft/block/ButtonBlock.mapping
  mappings/net/minecraft/block/CampfireBlock.mapping
  mappings/net/minecraft/block/CandleCakeBlock.mapping
  mappings/net/minecraft/block/ChorusFlowerBlock.mapping
  mappings/net/minecraft/block/ColoredFallingBlock.mapping
  mappings/net/minecraft/block/CommandBlock.mapping
  mappings/net/minecraft/block/ConcretePowderBlock.mapping
  mappings/net/minecraft/block/CoralBlock.mapping
  mappings/net/minecraft/block/CoralBlockBlock.mapping
  mappings/net/minecraft/block/CoralFanBlock.mapping
  mappings/net/minecraft/block/CoralWallFanBlock.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/DyedCarpetBlock.mapping
  mappings/net/minecraft/block/ExperienceDroppingBlock.mapping
  mappings/net/minecraft/block/FenceGateBlock.mapping
  mappings/net/minecraft/block/FlowerBlock.mapping
  mappings/net/minecraft/block/FlowerPotBlock.mapping
  mappings/net/minecraft/block/FluidBlock.mapping
  mappings/net/minecraft/block/FungusBlock.mapping
  mappings/net/minecraft/block/HangingSignBlock.mapping
  mappings/net/minecraft/block/InfestedBlock.mapping
  mappings/net/minecraft/block/LeveledCauldronBlock.mapping
  mappings/net/minecraft/block/MushroomPlantBlock.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/block/OxidizableBlock.mapping
  mappings/net/minecraft/block/OxidizableSlabBlock.mapping
  mappings/net/minecraft/block/OxidizableStairsBlock.mapping
  mappings/net/minecraft/block/PistonBlock.mapping
  mappings/net/minecraft/block/PressurePlateBlock.mapping
  mappings/net/minecraft/block/PropaguleBlock.mapping
  mappings/net/minecraft/block/RotatedInfestedBlock.mapping
  mappings/net/minecraft/block/SaplingBlock.mapping
  mappings/net/minecraft/block/ShulkerBoxBlock.mapping
  mappings/net/minecraft/block/SignBlock.mapping
  mappings/net/minecraft/block/SkullBlock.mapping
  mappings/net/minecraft/block/StainedGlassBlock.mapping
  mappings/net/minecraft/block/StainedGlassPaneBlock.mapping
  mappings/net/minecraft/block/StairsBlock.mapping
  mappings/net/minecraft/block/StemBlock.mapping
  mappings/net/minecraft/block/SuspiciousStewIngredient.mapping
  mappings/net/minecraft/block/TorchBlock.mapping
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/block/TripwireBlock.mapping
  mappings/net/minecraft/block/WallBannerBlock.mapping
  mappings/net/minecraft/block/WallHangingSignBlock.mapping
  mappings/net/minecraft/block/WallSignBlock.mapping
  mappings/net/minecraft/block/WallSkullBlock.mapping
  mappings/net/minecraft/block/WallTorchBlock.mapping
  mappings/net/minecraft/block/WeightedPressurePlateBlock.mapping
  mappings/net/minecraft/block/WitherRoseBlock.mapping
Labels: new, snapshot

#3691 23w41a misc
  mappings/net/minecraft/block/entity/DecoratedPotBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleEntity.mapping
  mappings/net/minecraft/item/BoatItem.mapping
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/resource/VanillaDataPackProvider.mapping
  mappings/net/minecraft/util/ItemScatterer.mapping
Labels: new, snapshot

#3698 23w41a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/gui/tooltip/FocusedTooltipPositioner.mapping
  mappings/net/minecraft/client/gui/tooltip/Tooltip.mapping
  mappings/net/minecraft/client/gui/tooltip/WidgetTooltipPositioner.mapping
  mappings/net/minecraft/client/realms/Request.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningMcoTaskScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/task/RealmsConnectTask.mapping
  mappings/net/minecraft/client/realms/task/RealmsPrepareConnectionTask.mapping
  mappings/net/minecraft/command/CommandAction.mapping
  mappings/net/minecraft/command/CommandExecutionContext.mapping
  mappings/net/minecraft/command/CommandQueueEntry.mapping
  mappings/net/minecraft/command/ControlFlowAware.mapping
  mappings/net/minecraft/command/ExecutionControl.mapping
  mappings/net/minecraft/command/Forkable.mapping
  mappings/net/minecraft/command/SingleCommandAction.mapping
  mappings/net/minecraft/command/SourcedCommandAction.mapping
  mappings/net/minecraft/command/SteppedCommandAction.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/entity/vehicle/VehicleEntity.mapping
  mappings/net/minecraft/server/command/AbstractServerCommandSource.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/DebugCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/server/command/ReturnCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/function/CommandFunction.mapping
  mappings/net/minecraft/server/function/CommandFunctionManager.mapping
  mappings/net/minecraft/server/function/Macro.mapping
  mappings/net/minecraft/test/GameTestState.mapping
  mappings/net/minecraft/util/Colors.mapping
  mappings/net/minecraft/util/ItemScatterer.mapping
  mappings/net/minecraft/util/dynamic/RuntimeOps.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3700 23w42a realms and world stuff
  mappings/net/minecraft/client/gui/screen/BackupPromptScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/RecoverWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SelectWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/dto/RealmsWorldOptions.mapping
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsParentalConsentScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSettingsScreen.mapping
  mappings/net/minecraft/client/realms/util/JsonUtils.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: new, snapshot

#3702 23w42a world loading
  mappings/net/minecraft/client/gui/screen/world/RecoverWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SymlinkWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/nbt/InvalidNbtException.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtCrashException.mapping
  mappings/net/minecraft/nbt/NbtException.mapping
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/level/storage/ParsedSaveProperties.mapping
Labels: refactor, new, snapshot

#3703 More 23w42a stuff
  mappings/net/minecraft/block/entity/CrafterBlockEntity.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/BackupPromptScreen.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/DatapackFailureScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/realms/dto/RealmsNotification.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectWorldTemplateScreen.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/BufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/chunk/BlockBufferBuilderPool.mapping
  mappings/net/minecraft/client/render/chunk/BlockBufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/client/util/GlAllocationUtils.mapping
  mappings/net/minecraft/command/ControlFlowAware.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceWriteReadFix.mapping
  mappings/net/minecraft/datafixer/fix/PrimedTntBlockStateFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3682.mapping
  mappings/net/minecraft/datafixer/schema/Schema3683.mapping
  mappings/net/minecraft/inventory/RecipeInputInventory.mapping
  mappings/net/minecraft/inventory/SimpleInventory.mapping
  mappings/net/minecraft/network/message/MessageChainTaskQueue.mapping
  mappings/net/minecraft/registry/OneTwentyOneBuiltinRegistries.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/function/Tracer.mapping
  mappings/net/minecraft/structure/pool/alias/DirectStructurePoolAliasBinding.mapping
  mappings/net/minecraft/structure/pool/alias/RandomGroupStructurePoolAliasBinding.mapping
  mappings/net/minecraft/structure/pool/alias/RandomStructurePoolAliasBinding.mapping
  mappings/net/minecraft/text/MutableText.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
  mappings/net/minecraft/util/Colors.mapping
  mappings/net/minecraft/util/Urls.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/thread/FutureQueue.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
Labels: refactor, new, snapshot

#3706 23w43a stuff
  mappings/net/minecraft/block/BlockSetType.mapping
  mappings/net/minecraft/block/CopperBulbBlock.mapping
  mappings/net/minecraft/block/CopperGrateBlock.mapping
  mappings/net/minecraft/block/Degradable.mapping
  mappings/net/minecraft/block/DoorBlock.mapping
  mappings/net/minecraft/block/OxidizableCopperBulbBlock.mapping
  mappings/net/minecraft/block/OxidizableDoorBlock.mapping
  mappings/net/minecraft/block/OxidizableTrapdoorBlock.mapping
  mappings/net/minecraft/block/TranslucentBlock.mapping
  mappings/net/minecraft/block/TransparentBlock.mapping
  mappings/net/minecraft/block/TrapdoorBlock.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryEventWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryInfoScreen.mapping
  mappings/net/minecraft/client/gui/widget/CheckboxWidget.mapping
  mappings/net/minecraft/client/render/entity/animation/BatAnimations.mapping
  mappings/net/minecraft/client/render/entity/model/BatEntityModel.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/client/Model.mapping
  mappings/net/minecraft/data/family/BlockFamilies.mapping
  mappings/net/minecraft/data/server/loottable/onetwentyone/OneTwentyOneBlockLootTableProvider.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/data/server/recipe/VanillaRecipeProvider.mapping
  mappings/net/minecraft/datafixer/fix/FixProjectileItemType.mapping
  mappings/net/minecraft/datafixer/fix/LevelLegacyWorldGenSettingsFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3685.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/passive/BatEntity.mapping
  mappings/net/minecraft/entity/projectile/ArrowEntity.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/SpectralArrowEntity.mapping
  mappings/net/minecraft/entity/projectile/TridentEntity.mapping
  mappings/net/minecraft/item/AxeItem.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/registry/OneTwentyOneBuiltinRegistries.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/math/Box.mapping
Labels: refactor, new, snapshot

#3708 Make remove and add tag method names more consistent
  mappings/net/minecraft/entity/Entity.mapping
Labels: bug, refactor, snapshot

#3707 23w43a tick stuff
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/render/RenderTickCounter.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/TickStepS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/UpdateTickRateS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/ServerTickManager.mapping
  mappings/net/minecraft/server/command/TickCommand.mapping
  mappings/net/minecraft/server/dedicated/DedicatedServerWatchdog.mapping
  mappings/net/minecraft/util/TimeHelper.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/tick/TickManager.mapping
Labels: new, snapshot

#3709 23w43a more stuff
  mappings/net/minecraft/block/Degradable.mapping
  mappings/net/minecraft/block/OxidizableGrateBlock.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/block/enums/DoubleBlockHalf.mapping
  mappings/net/minecraft/client/gui/hud/debug/TickChart.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CrafterScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  mappings/net/minecraft/datafixer/fix/ProjectileItemTypeFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema3685.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateJigsawC2SPacket.mapping
  mappings/net/minecraft/registry/ExperimentalRegistriesValidator.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/structure/pool/SinglePoolElement.mapping
  mappings/net/minecraft/test/GameTestState.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestRunner.mapping
  mappings/net/minecraft/text/MutableText.mapping
  mappings/net/minecraft/util/collection/PriorityIterator.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/tick/TickManager.mapping
Labels: bug, refactor, new, snapshot

#3711 Fix `IntRule#validate` mapping
  mappings/net/minecraft/world/GameRules.mapping
Labels: bug, refactor, javadoc

#3712 23w43b NetherWartBlock
  mappings/net/minecraft/block/NetherWartBlock.mapping
Labels: new, snapshot
