Repository FabricMC/yarn, pull requests merged in 2023-05, with the labels that each got.

#3561 Font type stuff
  mappings/net/minecraft/client/font/BitmapFont.mapping
  mappings/net/minecraft/client/font/FontLoader.mapping
  mappings/net/minecraft/client/font/FontType.mapping
  mappings/net/minecraft/client/font/SpaceFont.mapping
  mappings/net/minecraft/client/font/TrueTypeFontLoader.mapping
  mappings/net/minecraft/client/font/UnihexFont.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: refactor, new, snapshot

#3560 Loot additions and corrections
  mappings/net/minecraft/advancement/criterion/ItemCriterion.mapping
  mappings/net/minecraft/loot/condition/AllOfLootCondition.mapping
  mappings/net/minecraft/loot/condition/AlternativeLootCondition.mapping
  mappings/net/minecraft/loot/condition/AnyOfLootCondition.mapping
  mappings/net/minecraft/loot/condition/LootCondition.mapping
  mappings/net/minecraft/loot/condition/LootConditionTypes.mapping
  mappings/net/minecraft/predicate/entity/AdvancementEntityPredicateDeserializer.mapping
  mappings/net/minecraft/predicate/entity/EntityConditions.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/PlayerPredicate.mapping
Labels: refactor, new, snapshot

#3559 Telemetry stuff and Time recording
  mappings/net/minecraft/Bootstrap.mapping
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/util/telemetry/PropertyMap.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryEventProperty.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryEventType.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/client/util/telemetry/TimeRecorder.mapping
  mappings/net/minecraft/client/util/telemetry/WorldLoadedEvent.mapping
  mappings/net/minecraft/client/util/telemetry/WorldSession.mapping
  mappings/net/minecraft/client/util/telemetry/WorldUnloadedEvent.mapping
Labels: new, snapshot

#3563 23w18a stuff
  mappings/net/minecraft/advancement/Advancement.mapping
  mappings/net/minecraft/advancement/criterion/ItemCriterion.mapping
  mappings/net/minecraft/block/SculkSensorBlock.mapping
  mappings/net/minecraft/client/font/BitmapFont.mapping
  mappings/net/minecraft/client/font/FontType.mapping
  mappings/net/minecraft/client/font/SpaceFont.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/screen/LevelLoadingScreen.mapping
  mappings/net/minecraft/client/network/ClientAdvancementManager.mapping
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/debug/SupportingBlockDebugRenderer.mapping
  mappings/net/minecraft/client/util/telemetry/GameLoadTimeEvent.mapping
  mappings/net/minecraft/client/util/telemetry/TelemetryManager.mapping
  mappings/net/minecraft/client/util/telemetry/WorldLoadedEvent.mapping
  mappings/net/minecraft/client/util/telemetry/WorldSession.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/data/DataTracker.mapping
  mappings/net/minecraft/loot/condition/AllOfLootCondition.mapping
  mappings/net/minecraft/loot/condition/AnyOfLootCondition.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/LootContextPredicate.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/world/BlockCollisionSpliterator.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/MobSpawnerEntry.mapping
  mappings/net/minecraft/world/gen/chunk/placement/RandomSpreadStructurePlacement.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
Labels: refactor, new, snapshot

#3565 Fix `body`, `footer` and related methods incorrectly named in `ThreePartsLayoutWidget`
  mappings/net/minecraft/client/gui/widget/ThreePartsLayoutWidget.mapping
Labels: bug, refactor, snapshot

#3567 23w18a more stuff
  mappings/net/minecraft/client/font/FontLoader.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/world/chunk/light/LightStorage.mapping
Labels: refactor, new, snapshot

#3566 More buildscript updates
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release-filament.yml
  build.gradle
  filament/build.gradle
  filament/gradle.properties
  filament/src/main/java/net/fabricmc/filament/task/ExtractZipEntryTask.java
  filament/src/main/java/net/fabricmc/filament/task/RemapUnpickDefinitionsTask.java
  filament/src/main/java/net/fabricmc/filament/task/enigma/ConvertMappingsTask.java
  filament/src/main/java/net/fabricmc/filament/task/mappingio/ConvertMappingsTask.java
  filament/src/main/java/net/fabricmc/filament/task/mappingio/MappingOutputTask.java
  filament/src/main/java/net/fabricmc/filament/task/mappingio/MergeMappingsTask.java
  filament/src/main/java/net/fabricmc/filament/task/minecraft/MergeMinecraftTask.java
  gradle.properties
Labels: snapshot, toolchain

#3573 Rename `AbstractBlock.Settings.of()` to `AbstractBlock.Settings.create()`
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: refactor, impactful

#3570 Fix mappings related to MathHelper.atan2
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: refactor, snapshot, javadoc

#3571 1.20-pre1 stuff
  mappings/net/minecraft/block/DecoratedPotBlock.mapping
  mappings/net/minecraft/block/ShulkerBoxBlock.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/class_8567.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerInteractionManager.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupInfoScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongConfirmationScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/realms/util/RealmsUtil.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/damage/DamageSources.mapping
  mappings/net/minecraft/entity/damage/DamageTypes.mapping
  mappings/net/minecraft/inventory/CraftingInventory.mapping
  mappings/net/minecraft/inventory/RecipeInputInventory.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/loot/context/LootContextParameterSet.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRespawnS2CPacket.mapping
  mappings/net/minecraft/screen/ScreenTexts.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/server/command/LootCommand.mapping
  mappings/net/minecraft/server/world/ChunkLevelType.mapping
  mappings/net/minecraft/server/world/ChunkLevels.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/math/random/RandomSequence.mapping
  mappings/net/minecraft/util/math/random/RandomSequencesState.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandomImpl.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/gen/feature/EndPortalFeature.mapping
Labels: new, snapshot

#3577 1.20-pre1 more stuff
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/client/font/TrueTypeFont.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandomImpl.mapping
Labels: new, snapshot

#3578 Some entity constants
  mappings/net/minecraft/entity/mob/HoglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinBruteBrain.mapping
  mappings/net/minecraft/entity/mob/PillagerEntity.mapping
  mappings/net/minecraft/entity/mob/RavagerEntity.mapping
  mappings/net/minecraft/entity/mob/VexEntity.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/mob/ZoglinEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/entity/passive/AllayBrain.mapping
  mappings/net/minecraft/entity/passive/CamelBrain.mapping
  mappings/net/minecraft/entity/passive/FrogBrain.mapping
  mappings/net/minecraft/entity/passive/RabbitEntity.mapping
  mappings/net/minecraft/entity/passive/SnifferBrain.mapping
  mappings/net/minecraft/entity/passive/TadpoleBrain.mapping
Labels: new, snapshot

#3579 1.20-pre2 stuff
  mappings/net/minecraft/client/gui/screen/ingame/AnvilScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/LanguageOptionsScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsGenericErrorScreen.mapping
  mappings/net/minecraft/client/render/entity/model/SinglePartEntityModel.mapping
  mappings/net/minecraft/client/util/InputUtil.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
  mappings/net/minecraft/command/argument/NbtPathArgumentType.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/task/TemptTask.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFight.mapping
  mappings/net/minecraft/entity/passive/SnifferBrain.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/screen/AnvilScreenHandler.mapping
  mappings/net/minecraft/server/command/DataCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/math/random/RandomSeed.mapping
  mappings/net/minecraft/util/math/random/RandomSequence.mapping
  mappings/net/minecraft/util/math/random/Xoroshiro128PlusPlusRandom.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
Labels: refactor, new, snapshot

#3580 1.20-pre3 stuff
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldIcon.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/damage/DamageTracker.mapping
  mappings/net/minecraft/entity/damage/FallLocation.mapping
  mappings/net/minecraft/network/packet/s2c/play/DeathMessageS2CPacket.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/math/random/RandomSequence.mapping
Labels: new, snapshot

#3583 Fix param name in EndCombatS2CPacket
  mappings/net/minecraft/network/packet/s2c/play/EndCombatS2CPacket.mapping
Labels: snapshot

#3585 1.20-pre5 stuff
  mappings/net/minecraft/block/AbstractPressurePlateBlock.mapping
  mappings/net/minecraft/block/WearableCarvedPumpkinBlock.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantmentScreen.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsInviteScreen.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/data/server/recipe/RecipeProvider.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/math/random/RandomSeed.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
Labels: new, snapshot

#3588 1.20-pre7 symlink stuff
  mappings/net/minecraft/client/gui/screen/world/SymlinkWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldListWidget.mapping
  mappings/net/minecraft/screen/ScreenTexts.mapping
  mappings/net/minecraft/util/Urls.mapping
  mappings/net/minecraft/util/path/AllowedSymlinkPathMatcher.mapping
  mappings/net/minecraft/util/path/SymlinkEntry.mapping
  mappings/net/minecraft/util/path/SymlinkFinder.mapping
  mappings/net/minecraft/util/path/SymlinkValidationException.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: new, snapshot
