Repository FabricMC/yarn, pull requests merged in 2023-12, with the labels that each got.

#3752 Map DisplayEntityRenderer rotation util methods
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
Labels: new, release

#3753 Rename the NbtTagSizeTracker class to NbtSizeTracker
  mappings/net/minecraft/nbt/NbtIo.mapping
  mappings/net/minecraft/nbt/NbtSizeTracker.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  unpick-definitions/network.unpick
Labels: refactor, release

#3755 More 23w51 stuff
  mappings/net/minecraft/block/CandleCakeBlock.mapping
  mappings/net/minecraft/block/ChiseledBookshelfBlock.mapping
  mappings/net/minecraft/block/Fertilizable.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/gui/LayeredDrawer.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ServerInfo.mapping
  mappings/net/minecraft/client/render/Camera.mapping
  mappings/net/minecraft/client/render/entity/StriderEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/BreezeEyesFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/FeatureRenderer.mapping
  mappings/net/minecraft/client/util/ParticleUtil.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/fix/BlockNameFix.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeMovementUtil.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/SkeletonHorseEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieHorseEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractDonkeyEntity.mapping
  mappings/net/minecraft/entity/passive/ChickenEntity.mapping
  mappings/net/minecraft/entity/passive/CowEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/TurtleEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/item/DyeableAnimalArmorItem.mapping
  mappings/net/minecraft/item/DyeableHorseArmorItem.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/server/function/FunctionBuilder.mapping
  mappings/net/minecraft/server/function/Macro.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/WorldSaveHandler.mapping
  unpick-definitions/world_events.unpick
Labels: new, snapshot, javadoc, unpick

#3756 23w51b yet more stuff
  mappings/net/minecraft/block/BedBlock.mapping
  mappings/net/minecraft/block/Fertilizable.mapping
  mappings/net/minecraft/block/FlowerBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/network/MultiplayerServerListPinger.mapping
  mappings/net/minecraft/client/render/entity/StriderEntityRenderer.mapping
  mappings/net/minecraft/datafixer/schema/Schema3799.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityAttachments.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/SkeletonHorseEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieHorseEntity.mapping
  mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractDonkeyEntity.mapping
  mappings/net/minecraft/entity/passive/ChickenEntity.mapping
  mappings/net/minecraft/entity/passive/CowEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/HorseEntity.mapping
  mappings/net/minecraft/entity/passive/LlamaEntity.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/TurtleEntity.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateBeaconC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityStatusEffectS2CPacket.mapping
  mappings/net/minecraft/potion/PotionUtil.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/function/FunctionBuilder.mapping
  mappings/net/minecraft/server/function/Macro.mapping
  mappings/net/minecraft/world/WorldSaveHandler.mapping
  mappings/net/minecraft/world/event/Vibrations.mapping
Labels: refactor, new, snapshot
