Repository FabricMC/yarn, pull requests merged in 2024-03, with the labels that each got.

#3803 24w09a more stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/client/gui/EditBox.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeTypeCache.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/inventory/SimpleInventory.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/context/LootContextTypes.mapping
  mappings/net/minecraft/loot/entry/LootTableEntry.mapping
  mappings/net/minecraft/loot/function/CopyComponentsLootFunction.mapping
  mappings/net/minecraft/loot/function/CopyStateFunction.mapping
  mappings/net/minecraft/loot/function/SetAttributesLootFunction.mapping
  mappings/net/minecraft/loot/function/SetBannerPatternFunction.mapping
  mappings/net/minecraft/loot/function/SetContentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetEnchantmentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetLoreLootFunction.mapping
  mappings/net/minecraft/loot/function/SetNbtLootFunction.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
  mappings/net/minecraft/potion/Potion.mapping
  mappings/net/minecraft/registry/RegistryOps.mapping
  mappings/net/minecraft/scoreboard/Scoreboard.mapping
  mappings/net/minecraft/scoreboard/ScoreboardScore.mapping
  mappings/net/minecraft/scoreboard/ScoreboardState.mapping
  mappings/net/minecraft/scoreboard/Scores.mapping
  mappings/net/minecraft/screen/GrindstoneScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/PlaySoundCommand.mapping
  mappings/net/minecraft/server/command/ResetChunksCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/command/TestFinder.mapping
  mappings/net/minecraft/server/integrated/IntegratedServer.mapping
  mappings/net/minecraft/server/integrated/IntegratedServerLoader.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/OptionalChunk.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/TradedItem.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/CommandBlockExecutor.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/chunk/ChunkGenerating.mapping
  mappings/net/minecraft/world/chunk/ChunkGenerationContext.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/FullChunkConverter.mapping
  mappings/net/minecraft/world/gen/StructureAccessor.mapping
  mappings/net/minecraft/world/level/storage/LevelStorage.mapping
Labels: refactor, new, snapshot, javadoc

#3804 24w09a even more stuff
  mappings/net/minecraft/class_9273.mapping
  mappings/net/minecraft/client/color/item/ItemColors.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/MessageScreen.mapping
  mappings/net/minecraft/client/gui/screen/OutOfMemoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/WarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SoundOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryEventWidget.mapping
  mappings/net/minecraft/client/gui/screen/option/TelemetryInfoScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/NarratedMultilineTextWidget.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/render/entity/feature/IronGolemCrackFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/WolfArmorFeatureRenderer.mapping
  mappings/net/minecraft/data/report/BiomeParametersProvider.mapping
  mappings/net/minecraft/data/server/DynamicRegistriesProvider.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/ai/pathing/LandPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/PathContext.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeMaker.mapping
  mappings/net/minecraft/entity/passive/Cracks.mapping
  mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/projectile/BreezeWindChargeEntity.mapping
  mappings/net/minecraft/entity/projectile/WindChargeEntity.mapping
  mappings/net/minecraft/loot/function/CopyStateLootFunction.mapping
  mappings/net/minecraft/loot/function/SetBannerPatternLootFunction.mapping
  mappings/net/minecraft/loot/function/SetComponentsLootFunction.mapping
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/ComponentPredicate.mapping
  mappings/net/minecraft/predicate/FluidPredicate.mapping
  mappings/net/minecraft/predicate/NbtPredicate.mapping
  mappings/net/minecraft/predicate/StatePredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityEffectPredicate.mapping
  mappings/net/minecraft/predicate/entity/LocationPredicate.mapping
  mappings/net/minecraft/predicate/item/EnchantmentPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
  mappings/net/minecraft/recipe/RepairItemRecipe.mapping
Labels: refactor, new, snapshot

#3805 Clearer and more accurate naming for some component stuff
  mappings/net/minecraft/component/ComponentChanges.mapping
  mappings/net/minecraft/component/ComponentMapImpl.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: refactor, snapshot, javadoc

#3806 24w09a a little bit more
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/ChatOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/KeybindsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OnlineOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/gui/widget/OptionListWidget.mapping
  mappings/net/minecraft/client/gui/widget/TextIconButtonWidget.mapping
  mappings/net/minecraft/datafixer/FixUtil.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackComponentizationFix.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/projectile/ArrowEntity.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/loot/function/SetAttributesLootFunction.mapping
  mappings/net/minecraft/loot/function/SetCustomDataLootFunction.mapping
  unpick-definitions/entity_status.unpick
Labels: refactor, new, snapshot, unpick

#3807 Rename deceptively named `roll` field in `LivingEntity`
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: bug, snapshot

#3808 Fix a few javadocs
  mappings/net/minecraft/item/ItemStack.mapping
Labels: bug, snapshot, javadoc

#3811 Add formatMappings task
  .github/workflows/build.yml
  README.md
  build.gradle
  filament/gradle.properties
  filament/src/main/java/net/fabricmc/filament/task/mappingio/FormatMappingsTask.java
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/particle/DamageParticle.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/client/particle/FlameParticle.mapping
  mappings/net/minecraft/client/particle/SquidInkParticle.mapping
  mappings/net/minecraft/client/particle/SuspendParticle.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverride.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
  mappings/net/minecraft/loot/function/ApplyBonusLootFunction.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
Labels: toolchain

#3810 24w10a stuff
  mappings/net/minecraft/block/FlowerBlock.mapping
  mappings/net/minecraft/block/entity/BannerBlockEntity.mapping
  mappings/net/minecraft/block/entity/BannerPattern.mapping
  mappings/net/minecraft/block/entity/BannerPatterns.mapping
  mappings/net/minecraft/block/entity/LockableContainerBlockEntity.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/ScreenRect.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityRenderer.mapping
  mappings/net/minecraft/client/util/SpriteIdentifier.mapping
  mappings/net/minecraft/command/argument/SlotRangeArgumentType.mapping
  mappings/net/minecraft/component/type/AttributeModifiersComponent.mapping
  mappings/net/minecraft/component/type/BannerPatternsComponent.mapping
  mappings/net/minecraft/component/type/ContainerComponent.mapping
  mappings/net/minecraft/component/type/DyedColorComponent.mapping
  mappings/net/minecraft/component/type/ItemEnchantmentsComponent.mapping
  mappings/net/minecraft/component/type/LodestoneTrackerComponent.mapping
  mappings/net/minecraft/component/type/PotionContentsComponent.mapping
  mappings/net/minecraft/component/type/ProfileComponent.mapping
  mappings/net/minecraft/datafixer/fix/ComponentFix.mapping
  mappings/net/minecraft/datafixer/fix/LodestoneCompassComponentFix.mapping
  mappings/net/minecraft/datafixer/fix/PlayerHeadBlockProfileFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema705.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeModifier.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/passive/WolfVariant.mapping
  mappings/net/minecraft/entity/passive/WolfVariants.mapping
  mappings/net/minecraft/inventory/SlotRange.mapping
  mappings/net/minecraft/inventory/SlotRanges.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/predicate/entity/EntityEquipmentPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/entity/SlotsPredicate.mapping
  mappings/net/minecraft/screen/GrindstoneScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/PlayerScreenHandler.mapping
  mappings/net/minecraft/server/command/ClearCommand.mapping
  mappings/net/minecraft/server/command/ExecuteCommand.mapping
  mappings/net/minecraft/util/JsonReaderUtils.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
Labels: refactor, new, snapshot

#3814 Rename the ServerPlayerEntity#setGameMode method to readGameModeNbt
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: refactor, snapshot

#3815 24w10a more stuff
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/command/argument/ItemPredicateReader.mapping
  mappings/net/minecraft/command/argument/ItemSlotArgumentType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeModifier.mapping
  mappings/net/minecraft/inventory/Inventories.mapping
  mappings/net/minecraft/inventory/SlotRanges.mapping
  mappings/net/minecraft/registry/entry/RegistryEntryList.mapping
  mappings/net/minecraft/registry/entry/RegistryEntryListCodec.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: new, snapshot

#3818 24w11a stuff
  mappings/net/minecraft/block/HeavyCoreBlock.mapping
  mappings/net/minecraft/block/entity/OneTwentyOneBannerPatterns.mapping
  mappings/net/minecraft/block/entity/Sherds.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/TabButtonWidget.mapping
  mappings/net/minecraft/data/Main.mapping
  mappings/net/minecraft/datafixer/schema/Schema3822.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/passive/WolfVariants.mapping
  mappings/net/minecraft/entity/projectile/ExplosiveProjectileEntity.mapping
  mappings/net/minecraft/item/ArmorMaterial.mapping
  mappings/net/minecraft/item/trim/OneTwentyOneArmorTrimPatterns.mapping
  mappings/net/minecraft/loot/function/SetBookCoverLootFunction.mapping
  mappings/net/minecraft/loot/function/SetComponentsLootFunction.mapping
  mappings/net/minecraft/loot/function/SetFireworkExplosionLootFunction.mapping
  mappings/net/minecraft/loot/function/SetFireworksLootFunction.mapping
  mappings/net/minecraft/loot/function/SetWritableBookPagesLootFunction.mapping
  mappings/net/minecraft/loot/function/SetWrittenBookPagesLootFunction.mapping
  mappings/net/minecraft/network/packet/c2s/common/CustomPayloadC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/CustomPayloadS2CPacket.mapping
  mappings/net/minecraft/particle/EntityEffectParticleEffect.mapping
  mappings/net/minecraft/predicate/entity/EntitySubPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntitySubPredicateTypes.mapping
  mappings/net/minecraft/predicate/item/ComponentSubPredicate.mapping
  mappings/net/minecraft/predicate/item/CustomDataPredicate.mapping
  mappings/net/minecraft/predicate/item/DamagePredicate.mapping
  mappings/net/minecraft/predicate/item/EnchantmentsPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemSubPredicate.mapping
  mappings/net/minecraft/predicate/item/PotionContentsPredicate.mapping
  mappings/net/minecraft/util/Colors.mapping
  mappings/net/minecraft/util/collection/ListOperation.mapping
  mappings/net/minecraft/util/math/BlockArea.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/util/math/ImmutableBlockBox.mapping
  mappings/net/minecraft/util/shape/BitSetVoxelSet.mapping
  unpick-definitions/colors.unpick
Labels: bug, refactor, new, snapshot, javadoc

#3819 24w11a fix, some javadoc
  mappings/net/minecraft/component/ComponentHolder.mapping
  mappings/net/minecraft/component/type/LoreComponent.mapping
  mappings/net/minecraft/item/ItemStack.mapping
Labels: bug, refactor, snapshot, javadoc

#3823 24w12a more stuff
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/packrat/AnyIdParsingRule.mapping
  mappings/net/minecraft/command/argument/packrat/ArgumentParser.mapping
  mappings/net/minecraft/command/argument/packrat/Cut.mapping
  mappings/net/minecraft/command/argument/packrat/IdentifiableParsingRule.mapping
  mappings/net/minecraft/command/argument/packrat/IdentifierSuggestable.mapping
  mappings/net/minecraft/command/argument/packrat/Literals.mapping
  mappings/net/minecraft/command/argument/packrat/NbtParsingRule.mapping
  mappings/net/minecraft/command/argument/packrat/PackratParsing.mapping
  mappings/net/minecraft/command/argument/packrat/ParseError.mapping
  mappings/net/minecraft/command/argument/packrat/ParseErrorList.mapping
  mappings/net/minecraft/command/argument/packrat/ParseResults.mapping
  mappings/net/minecraft/command/argument/packrat/ParsingRule.mapping
  mappings/net/minecraft/command/argument/packrat/ParsingRules.mapping
  mappings/net/minecraft/command/argument/packrat/ParsingState.mapping
  mappings/net/minecraft/command/argument/packrat/ParsingStateImpl.mapping
  mappings/net/minecraft/command/argument/packrat/Suggestable.mapping
  mappings/net/minecraft/command/argument/packrat/Symbol.mapping
  mappings/net/minecraft/command/argument/packrat/Term.mapping
  mappings/net/minecraft/enchantment/DamageEnchantment.mapping
  mappings/net/minecraft/enchantment/ProtectionEnchantment.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/inventory/LootableInventory.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3824 Rename AbstractBlock.lootTableId -> lootTableKey
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: bug, refactor, snapshot

#3827 Revert ASM update for now
  gradle.properties
Labels: toolchain
