Repository FabricMC/yarn, pull requests merged in 2024-01, with the labels that each got.

#3761 Add basic class mappings for new packets added in 24w04a
  mappings/net/minecraft/network/packet/c2s/common/CookieRequestResponseC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/CookieRequestS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/ServerTransferS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/common/StoreCookieS2CPacket.mapping
Labels: new, snapshot

#3763 24w03a stuff (that isn't packets or networking)
  mappings/net/minecraft/advancement/criterion/AnyBlockUseCriterion.mapping
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/DefaultBlockUseCriterion.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/PlayerSkullBlock.mapping
  mappings/net/minecraft/block/WallTorchBlock.mapping
  mappings/net/minecraft/block/WitherSkullBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/ViewerCountManager.mapping
  mappings/net/minecraft/class_9104.mapping
  mappings/net/minecraft/class_9107.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/datafixer/fix/RenameEnchantmentFix.mapping
  mappings/net/minecraft/enchantment/DamageEnchantment.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ProjectileDeflector.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeModifier.mapping
  mappings/net/minecraft/entity/mob/BreezeEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/mob/SpiderEntity.mapping
  mappings/net/minecraft/entity/passive/ArmadilloBrain.mapping
  mappings/net/minecraft/entity/passive/ArmadilloEntity.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleInventory.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/screen/MerchantScreenHandler.mapping
  mappings/net/minecraft/server/WorldGenerationProgressListener.mapping
  mappings/net/minecraft/util/math/GlobalPos.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldProperties.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
Labels: new, snapshot

#3764 Make an implNote for spawnParticle methods
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: snapshot, javadoc

#3766 24w03a stuff
  mappings/net/minecraft/advancement/AdvancementDisplay.mapping
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/command/argument/TestFunctionArgumentType.mapping
  mappings/net/minecraft/data/DataCache.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/loot/context/LootContextTypes.mapping
  mappings/net/minecraft/network/codec/PacketCodec.mapping
  mappings/net/minecraft/network/packet/CustomPayload.mapping
  mappings/net/minecraft/network/packet/Packet.mapping
  mappings/net/minecraft/network/packet/PacketIdentifier.mapping
  mappings/net/minecraft/network/packet/UnknownCustomPayload.mapping
  mappings/net/minecraft/particle/DustColorTransitionParticleEffect.mapping
  mappings/net/minecraft/particle/DustParticleEffect.mapping
  mappings/net/minecraft/particle/ItemStackParticleEffect.mapping
  mappings/net/minecraft/particle/ParticleTypes.mapping
  mappings/net/minecraft/particle/SculkChargeParticleEffect.mapping
  mappings/net/minecraft/recipe/CuttingRecipe.mapping
  mappings/net/minecraft/recipe/RawShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/registry/RegistryKey.mapping
  mappings/net/minecraft/scoreboard/number/FixedNumberFormat.mapping
  mappings/net/minecraft/scoreboard/number/StyledNumberFormat.mapping
  mappings/net/minecraft/server/WorldGenerationProgressLogger.mapping
  mappings/net/minecraft/server/WorldGenerationProgressTracker.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/command/TestFinder.mapping
  mappings/net/minecraft/test/BatchListener.mapping
  mappings/net/minecraft/test/Batches.mapping
  mappings/net/minecraft/test/GameTestBatch.mapping
  mappings/net/minecraft/test/GameTestState.mapping
  mappings/net/minecraft/test/StructureBlockFinder.mapping
  mappings/net/minecraft/test/StructureTestListener.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestAttemptConfig.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/test/TestFunction.mapping
  mappings/net/minecraft/test/TestFunctionFinder.mapping
  mappings/net/minecraft/test/TestFunctions.mapping
  mappings/net/minecraft/test/TestListener.mapping
  mappings/net/minecraft/test/TestManager.mapping
  mappings/net/minecraft/test/TestRunContext.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/test/TestSet.mapping
  mappings/net/minecraft/test/TestStructurePlacer.mapping
  mappings/net/minecraft/test/TestUtil.mapping
  mappings/net/minecraft/util/math/BlockPos.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/village/VillagerData.mapping
  mappings/net/minecraft/world/GameRules.mapping
  mappings/net/minecraft/world/event/BlockPositionSource.mapping
  mappings/net/minecraft/world/event/EntityPositionSource.mapping
  mappings/net/minecraft/world/level/storage/LevelSummary.mapping
Labels: refactor, new, snapshot, javadoc

#3768 24w03a/b networking
  mappings/net/minecraft/client/network/ClientLoginNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/NetworkStateBuilder.mapping
  mappings/net/minecraft/network/NetworkStateType.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/RegistryByteBuf.mapping
  mappings/net/minecraft/network/codec/PacketCodec.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/network/codec/PacketDecoder.mapping
  mappings/net/minecraft/network/codec/PacketEncoder.mapping
  mappings/net/minecraft/network/codec/ValueFirstEncoder.mapping
  mappings/net/minecraft/network/encoding/StringEncoding.mapping
  mappings/net/minecraft/network/handler/DecoderHandler.mapping
  mappings/net/minecraft/network/handler/EncoderHandler.mapping
  mappings/net/minecraft/network/handler/HandlerNames.mapping
  mappings/net/minecraft/network/handler/NetworkStateTransitionHandler.mapping
  mappings/net/minecraft/network/handler/NetworkStateTransitions.mapping
  mappings/net/minecraft/network/handler/PacketBundleHandler.mapping
  mappings/net/minecraft/network/handler/PacketBundler.mapping
  mappings/net/minecraft/network/handler/PacketCodecDispatcher.mapping
  mappings/net/minecraft/network/handler/PacketEncoder.mapping
  mappings/net/minecraft/network/handler/PacketUnbundler.mapping
  mappings/net/minecraft/network/handler/SideValidatingDispatchingCodecBuilder.mapping
  mappings/net/minecraft/network/packet/s2c/common/CustomPayloadS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/login/LoginHelloS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/StatisticsS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/SynchronizeRecipesS2CPacket.mapping
  mappings/net/minecraft/network/state/ConfigurationStates.mapping
  mappings/net/minecraft/network/state/HandshakeStates.mapping
  mappings/net/minecraft/network/state/LoginStates.mapping
  mappings/net/minecraft/network/state/PlayStateFactories.mapping
  mappings/net/minecraft/network/state/QueryStates.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ServerHandshakeNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerLoginNetworkHandler.mapping
Labels: bug, refactor, new, snapshot, javadoc

#3767 24w03a/b more stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/cauldron/CauldronBehavior.mapping
  mappings/net/minecraft/client/font/FreeTypeUtil.mapping
  mappings/net/minecraft/client/font/RenderableGlyph.mapping
  mappings/net/minecraft/client/font/TrueTypeFont.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/gui/screen/AccessibilityOnboardingScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipState.mapping
  mappings/net/minecraft/client/gui/widget/ClickableWidget.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityAttachmentType.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreedTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/LookTargetUtil.mapping
  mappings/net/minecraft/entity/data/DataTracker.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/recipe/CookingRecipeSerializer.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/server/QueueingWorldGenerationProgressListener.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/sound/SoundEvent.mapping
  mappings/net/minecraft/village/TradeOffer.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  unpick-definitions/world_events.unpick
Labels: bug, refactor, new, snapshot

#3769 24w03b a few packet related renames
  mappings/net/minecraft/network/packet/BrandCustomPayload.mapping
  mappings/net/minecraft/network/packet/PacketType.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugBeeCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugBrainCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugBreezeCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugGameEventCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugGameEventListenersCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugGameTestAddMarkerCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugGameTestClearCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugGoalSelectorCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugHiveCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugNeighborsUpdateCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugPathCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugPoiAddedCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugPoiRemovedCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugPoiTicketCountCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugRaidsCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugStructuresCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugVillageSectionsCustomPayload.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugWorldgenAttemptCustomPayload.mapping
Labels: refactor, snapshot

#3770 24w03b wind charge
  mappings/net/minecraft/client/render/entity/model/WindChargeEntityModel.mapping
Labels: new, snapshot

#3771 Some more renames
  mappings/net/minecraft/network/NetworkPhase.mapping
  mappings/net/minecraft/network/NetworkStateType.mapping
  mappings/net/minecraft/network/codec/PacketCodec.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/recipe/SpecialRecipeSerializer.mapping
Labels: bug, refactor, javadoc

#3772 Some 24w04a stuff
  mappings/net/minecraft/entity/SpawnLocation.mapping
  mappings/net/minecraft/entity/SpawnLocationTypes.mapping
  mappings/net/minecraft/entity/mob/BreezeEntity.mapping
  mappings/net/minecraft/entity/passive/ArmadilloEntity.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/server/dedicated/command/TransferCommand.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/world/StructureLocator.mapping
  mappings/net/minecraft/world/gen/chunk/placement/StructurePlacement.mapping
Labels: new, snapshot

#3774 24w04a stuff
  mappings/net/minecraft/block/spawner/MobSpawnerEntry.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/debug/DebugChart.mapping
  mappings/net/minecraft/client/network/ClientConfigurationNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientRegistries.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsSelectFileToUploadScreen.mapping
  mappings/net/minecraft/entity/SpawnRestriction.mapping
  mappings/net/minecraft/entity/passive/ArmadilloBrain.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/network/RegistryByteBuf.mapping
  mappings/net/minecraft/network/codec/PacketCodec.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChatMessageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChunkDataS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommonPlayerSpawnInfo.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityAttributesS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityDamageS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/GameJoinS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/RemoveEntityStatusEffectS2CPacket.mapping
  mappings/net/minecraft/registry/MutableRegistry.mapping
  mappings/net/minecraft/registry/RegistryLoader.mapping
  mappings/net/minecraft/registry/SerializableRegistries.mapping
  mappings/net/minecraft/registry/tag/TagPacketSerializer.mapping
  mappings/net/minecraft/server/Main.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/dedicated/command/TransferCommand.mapping
  mappings/net/minecraft/server/network/ServerConfigurationNetworkHandler.mapping
  mappings/net/minecraft/util/collection/PriorityIterator.mapping
  mappings/net/minecraft/util/profiler/PerformanceLog.mapping
  mappings/net/minecraft/util/profiler/ServerTickType.mapping
  mappings/net/minecraft/world/gen/StructureAccessor.mapping
  mappings/net/minecraft/world/storage/ChunkCompressionFormat.mapping
  mappings/net/minecraft/world/storage/ChunkPosKeyedStorage.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/RecreatedChunkStorage.mapping
  mappings/net/minecraft/world/storage/RecreationStorage.mapping
  mappings/net/minecraft/world/storage/RegionFile.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: refactor, new, snapshot

#3777 createMockCreativePlayer -> createMockPlayer
  mappings/net/minecraft/test/TestContext.mapping
Labels: refactor, snapshot
