Repository FabricMC/yarn, pull requests merged in 2024-04, with the labels that each got.

#3832 Update Enigma to 2.4.2
  gradle.properties
Labels: snapshot, toolchain

#3833 24w14a stuff
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/block/entity/SkullBlockEntity.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/DeathScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/item/TooltipType.mapping
  mappings/net/minecraft/component/type/AttributeModifierSlot.mapping
  mappings/net/minecraft/component/type/BundleContentsComponent.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
  mappings/net/minecraft/datafixer/TypeReferences.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceTypesFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemStackComponentizationFix.mapping
  mappings/net/minecraft/entity/mob/PhantomEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/raid/RaiderEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/MaceItem.mapping
  mappings/net/minecraft/loot/function/SetAttributesLootFunction.mapping
  mappings/net/minecraft/network/listener/ClientPlayPacketListener.mapping
  mappings/net/minecraft/network/packet/s2c/play/ProjectilePowerS2CPacket.mapping
  mappings/net/minecraft/screen/BeaconScreenHandler.mapping
  mappings/net/minecraft/util/collection/ArrayListDeque.mapping
  mappings/net/minecraft/util/collection/ListDeque.mapping
  mappings/net/minecraft/util/collection/Weighted.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
Labels: refactor, new, snapshot

#3835 A couple of 24w14a stuff
  mappings/net/minecraft/datafixer/fix/StructuresToConfiguredStructuresFix.mapping
  mappings/net/minecraft/server/network/ServerCommonNetworkHandler.mapping
Labels: new, snapshot

#3840 Rename and document the SimpleParticleType class
  mappings/net/minecraft/particle/DefaultParticleType.mapping
  mappings/net/minecraft/particle/SimpleParticleType.mapping
Labels: refactor, snapshot, javadoc

#3843 1.20.5-pre1 more stuff
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/particle/SpellParticle.mapping
  mappings/net/minecraft/client/render/entity/FishingBobberEntityRenderer.mapping
  mappings/net/minecraft/client/sound/AudioStream.mapping
  mappings/net/minecraft/client/sound/BufferedAudioStream.mapping
  mappings/net/minecraft/client/sound/ChannelList.mapping
  mappings/net/minecraft/client/sound/NonRepeatingAudioStream.mapping
  mappings/net/minecraft/client/sound/OggAudioStream.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/component/ComponentMap.mapping
  mappings/net/minecraft/component/ComponentMapImpl.mapping
  mappings/net/minecraft/component/type/ContainerComponent.mapping
  mappings/net/minecraft/component/type/ItemEnchantmentsComponent.mapping
  mappings/net/minecraft/component/type/WritableBookContentComponent.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EquipmentTable.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/player/HungerManager.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/inventory/StackReference.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/NetworkThreadUtils.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/particle/ParticleTypes.mapping
  mappings/net/minecraft/screen/BrewingStandScreenHandler.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/command/TestFinder.mapping
  mappings/net/minecraft/util/collection/ListOperation.mapping
  mappings/net/minecraft/util/dynamic/NullOps.mapping
  unpick-definitions/entity_status.unpick
Labels: bug, refactor, new, snapshot, unpick

#3845 1.20.5-pre2 stuff
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/screen/DownloadingTerrainScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/loot/function/SetFireworksLootFunction.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/network/NetworkThreadUtils.mapping
  mappings/net/minecraft/network/listener/PacketListener.mapping
  mappings/net/minecraft/network/listener/ServerCrashSafePacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/play/ButtonClickC2SPacket.mapping
  mappings/net/minecraft/network/packet/c2s/play/CreativeInventoryActionC2SPacket.mapping
  mappings/net/minecraft/particle/AbstractDustParticleEffect.mapping
  mappings/net/minecraft/particle/DustColorTransitionParticleEffect.mapping
  mappings/net/minecraft/particle/DustParticleEffect.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/resource/featuretoggle/FeatureSet.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/collection/ListOperation.mapping
Labels: new, snapshot

#3846 1.20.5-pre3 stuff
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/OptionListWidget.mapping
  mappings/net/minecraft/client/option/SimpleOption.mapping
  mappings/net/minecraft/component/DataComponentType.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/type/ContainerComponent.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ProjectileDeflection.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/registry/RegistryOps.mapping
  mappings/net/minecraft/structure/ShipwreckGenerator.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/dynamic/CodecCache.mapping
Labels: refactor, new, snapshot

#3848 1.20.5-pre4 stuff
  mappings/net/minecraft/world/biome/BuiltinBiomes.mapping
  mappings/net/minecraft/world/biome/OneTwentyOneBiomes.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
Labels: new, snapshot

#3849 1.20.5-rc1 stuff
  mappings/net/minecraft/client/network/ClientCommonNetworkHandler.mapping
  mappings/net/minecraft/datafixer/fix/HorseArmorFix.mapping
  mappings/net/minecraft/datafixer/fix/RemoveEmptyItemInSuspiciousBlockFix.mapping
Labels: new, snapshot

#3851 1.20.5-rc2 stuff
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: new, snapshot

#3854 Map one field in `SimpleRegistry`
  mappings/net/minecraft/registry/SimpleRegistry.mapping
Labels: new, snapshot

#3856 1.20.6-rc1 stuff
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/datafixer/schema/Schema3808_2.mapping
Labels: new, snapshot

#3855 Fix renderFood parameter (left -> right)
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
Labels: bug, ready to merge, snapshot

#3853 Fix a couple of inverted mapping semantics
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
Labels: bug, refactor, ready to merge, snapshot
