Repository FabricMC/yarn, pull requests merged in 2024-12, with the labels that each got.

#4072 Fix typo in AbstractFurnaceScreenHandler
  mappings/net/minecraft/screen/AbstractFurnaceScreenHandler.mapping
Labels: bug, release

#4066 Add attack damage field
  mappings/net/minecraft/entity/mob/CreakingEntity.mapping
Labels: new, release

#4071 Rename the LootTable#shuffle method to spreadStacks
  mappings/net/minecraft/loot/LootTable.mapping
Labels: refactor, release

#4065 Fix/Refactor `VillagerEntity.canBreed` and `wantsToStartBreeding`
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
Labels: bug, refactor, release
