Repository FabricMC/yarn, pull requests merged in 2024-11, with the labels that each got.

#4044 24w44a client
  mappings/net/minecraft/client/font/BakedGlyph.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/gl/PostEffectPipeline.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/ScreenRect.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HorseScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CustomizeFlatLevelScreen.mapping
  mappings/net/minecraft/client/particle/Particle.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/render/SkyRendering.mapping
  mappings/net/minecraft/client/render/WeatherRendering.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/model/BannerFlagBlockModel.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
Labels: refactor, new, snapshot

#4031 Various issue fixes
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/MerchantScreen.mapping
  mappings/net/minecraft/client/render/entity/feature/EmissiveFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/state/WardenEntityRenderState.mapping
  mappings/net/minecraft/datafixer/fix/VillagerExperienceRebuildFix.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/Monster.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/network/packet/s2c/custom/DebugBrainCustomPayload.mapping
  mappings/net/minecraft/server/command/ExperienceCommand.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: bug, refactor, snapshot, impactful

#4036 Renamed `Direction.idHorizontal` and related methods
  mappings/net/minecraft/util/math/Direction.mapping
Labels: snapshot

#4050 24w46a small stuff
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/CreakingHeartBlockEntity.mapping
  mappings/net/minecraft/client/data/BlockStateModelGenerator.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/LoadedEntityModels.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/entity/mob/CreakingEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
Labels: bug, refactor, new, snapshot

#4055 Fix setupTransforms Parameters
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
Labels: bug, snapshot

#4054 1.21.4-pre1 more stuff
  mappings/net/minecraft/client/font/GlyphAtlasTexture.mapping
  mappings/net/minecraft/client/item/ItemAssetsLoader.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/network/OpaqueByteBufHolder.mapping
  mappings/net/minecraft/network/handler/LocalBufPacker.mapping
  mappings/net/minecraft/network/handler/LocalBufUnpacker.mapping
Labels: new, snapshot

#4057 Fix Parm name in AgeableMobEntityRenderer
  mappings/net/minecraft/client/render/entity/AgeableMobEntityRenderer.mapping
Labels: bug, snapshot

#4056 Fix expect entity in world
  mappings/net/minecraft/test/TestContext.mapping
Labels: bug, snapshot

#4058 1.21.4-pre2 stuff
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityFurnaceBurnTimeFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/ai/brain/task/FindPointOfInterestTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/ForgetCompletedPointOfInterestTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/VillagerTaskListProvider.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
Labels: new, snapshot

#4059 Rename ColorIndex to TintIndex to match model jsons
  mappings/net/minecraft/client/render/model/BakedQuad.mapping
Labels: refactor, snapshot

#4062 1.21.4-rc3 stuff
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/EntityAttributeBaseFix.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
Labels: new, snapshot

#4063 Rename CocoaBeansTreeDecorator
  mappings/net/minecraft/world/gen/treedecorator/CocoaTreeDecorator.mapping
Labels: bug, refactor, snapshot
