Repository FabricMC/yarn, pull requests merged in 2024-09, with the labels that each got.

#3976 Change Sherds#stream() to Sherds#toList()
  mappings/net/minecraft/block/entity/Sherds.mapping
Labels: bug

#3978 More 24w36a stuff
  mappings/net/minecraft/block/NetherPortalBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/class_10178.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/hud/debug/PieChart.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/EnchantmentScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/LoomScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SignEditScreen.mapping
  mappings/net/minecraft/client/gui/widget/PlayerSkinWidget.mapping
  mappings/net/minecraft/client/input/Input.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/option/ServerList.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/model/ItemModel.mapping
  mappings/net/minecraft/client/render/model/ReferencedModelsCollector.mapping
  mappings/net/minecraft/client/session/telemetry/ThreadedLogWriter.mapping
  mappings/net/minecraft/command/argument/PosArgument.mapping
  mappings/net/minecraft/data/client/ItemModelGenerator.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/player/PlayerPosition.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/PotionItem.mapping
  mappings/net/minecraft/item/TippedArrowItem.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerPositionLookS2CPacket.mapping
  mappings/net/minecraft/registry/ReloadableRegistries.mapping
  mappings/net/minecraft/resource/JsonDataLoader.mapping
  mappings/net/minecraft/resource/ResourcePackManager.mapping
  mappings/net/minecraft/server/QueueingWorldGenerationProgressListener.mapping
  mappings/net/minecraft/server/ServerAdvancementLoader.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/world/ChunkTaskScheduler.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/LevelPrioritizedQueue.mapping
  mappings/net/minecraft/server/world/ServerChunkLoadingManager.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/server/world/ThrottledChunkTaskScheduler.mapping
  mappings/net/minecraft/util/math/Box.mapping
  mappings/net/minecraft/util/thread/ConsecutiveExecutor.mapping
  mappings/net/minecraft/util/thread/PrioritizedConsecutiveExecutor.mapping
  mappings/net/minecraft/util/thread/SimpleConsecutiveExecutor.mapping
  mappings/net/minecraft/util/thread/TaskExecutor.mapping
  mappings/net/minecraft/world/TeleportTarget.mapping
  mappings/net/minecraft/world/chunk/AbstractChunkHolder.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
Labels: new, snapshot

#3979 24w36a minor things
  mappings/net/minecraft/client/render/entity/PlayerEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/state/BipedEntityRenderState.mapping
  mappings/net/minecraft/client/render/entity/state/PlayerEntityRenderState.mapping
  mappings/net/minecraft/client/render/model/BasicBakedModel.mapping
  mappings/net/minecraft/client/render/model/BuiltinBakedModel.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  unpick-definitions/entity_flags.unpick
Labels: refactor, new, snapshot

#3981 24w37a some stuff
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/InitialWorldOptions.mapping
  mappings/net/minecraft/client/gui/screen/world/WorldCreator.mapping
  mappings/net/minecraft/client/world/GeneratorOptionsFactory.mapping
  mappings/net/minecraft/command/CommandRegistryAccess.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/codec/PacketCodec.mapping
  mappings/net/minecraft/predicate/entity/EntitySubPredicateTypes.mapping
  mappings/net/minecraft/registry/tag/TagKey.mapping
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/resource/SinglePreparationResourceReloader.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/server/command/GameRuleCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/state/StateManager.mapping
  mappings/net/minecraft/state/property/DirectionProperty.mapping
  mappings/net/minecraft/state/property/EnumProperty.mapping
  mappings/net/minecraft/state/property/Property.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/gen/GeneratorOptions.mapping
  mappings/net/minecraft/world/gen/WorldPresets.mapping
  mappings/net/minecraft/world/gen/foliage/FoliagePlacer.mapping
Labels: new, snapshot

#3982 24w37a stuff
  mappings/net/minecraft/advancement/criterion/Criteria.mapping
  mappings/net/minecraft/advancement/criterion/KilledByArrowCriterion.mapping
  mappings/net/minecraft/block/dispenser/ShearsDispenserBehavior.mapping
  mappings/net/minecraft/block/entity/BrushableBlockEntity.mapping
  mappings/net/minecraft/block/entity/LecternBlockEntity.mapping
  mappings/net/minecraft/block/entity/VaultBlockEntity.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/screen/TitleScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BookEditScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipSubmenuHandler.mapping
  mappings/net/minecraft/client/render/entity/PlayerEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/CapeFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/type/DamageResistantComponent.mapping
  mappings/net/minecraft/component/type/DeathProtectionComponent.mapping
  mappings/net/minecraft/component/type/EquippableComponent.mapping
  mappings/net/minecraft/component/type/PotionContentsComponent.mapping
  mappings/net/minecraft/datafixer/fix/FireResistantToDamageResistantComponentFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/Shearable.mapping
  mappings/net/minecraft/entity/ai/brain/task/GiveGiftsToHeroTask.mapping
  mappings/net/minecraft/entity/mob/BoggedEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/passive/CatEntity.mapping
  mappings/net/minecraft/entity/passive/PandaEntity.mapping
  mappings/net/minecraft/entity/passive/SnifferEntity.mapping
  mappings/net/minecraft/entity/passive/SnowGolemEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EnderPearlEntity.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/network/codec/PacketCodec.mapping
  mappings/net/minecraft/registry/tag/TagKey.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/state/property/DirectionProperty.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
Labels: new, snapshot

#3984 Fix slightly incorrect names in LongJumpTask
  mappings/net/minecraft/entity/ai/brain/task/LongJumpTask.mapping
Labels: refactor, snapshot

#3986 24w37a stuff
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/RunArgs.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/chunk/Octree.mapping
  mappings/net/minecraft/client/render/entity/state/PlayerEntityRenderState.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/util/BufferAllocator.mapping
  mappings/net/minecraft/client/util/Window.mapping
  mappings/net/minecraft/client/util/tracy/TracyFrameCapturer.mapping
  mappings/net/minecraft/client/util/tracy/TracyLoader.mapping
  mappings/net/minecraft/component/MergedComponentMap.mapping
  mappings/net/minecraft/component/type/BundleContentsComponent.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeNavigator.mapping
  mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
  mappings/net/minecraft/loot/ContainerComponentModifier.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/profiler/Profiler.mapping
  mappings/net/minecraft/util/profiler/Profilers.mapping
  mappings/net/minecraft/util/profiler/ScopedProfiler.mapping
  mappings/net/minecraft/util/profiler/TracyProfiler.mapping
  mappings/net/minecraft/util/thread/NameableExecutor.mapping
Labels: bug, refactor, new, snapshot

#3985 Consistent 3F and 4F suffix usage
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: refactor, snapshot

#3988 24w38a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/dispenser/BoatDispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/MinecartDispenserBehavior.mapping
  mappings/net/minecraft/class_10225.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldCallback.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/realms/UploadStatus.mapping
  mappings/net/minecraft/client/realms/dto/RealmsWorldOptions.mapping
  mappings/net/minecraft/client/realms/exception/RealmsUploadException.mapping
  mappings/net/minecraft/client/realms/exception/upload/CancelledRealmsUploadException.mapping
  mappings/net/minecraft/client/realms/exception/upload/CloseFailureRealmsUploadException.mapping
  mappings/net/minecraft/client/realms/exception/upload/FailedRealmsUploadException.mapping
  mappings/net/minecraft/client/realms/exception/upload/TooBigRealmsUploadException.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateWorldScreen.mapping
  mappings/net/minecraft/data/Main.mapping
  mappings/net/minecraft/data/server/recipe/TransmuteRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/tag/bundle/BundleItemTagProvider.mapping
  mappings/net/minecraft/entity/passive/SquidEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/entity/vehicle/FurnaceMinecartEntity.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/MinecartItem.mapping
  mappings/net/minecraft/recipe/CraftingTransmuteRecipe.mapping
  mappings/net/minecraft/state/property/EnumProperty.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/TickView.mapping
  mappings/net/minecraft/world/dimension/NetherPortal.mapping
Labels: new, snapshot

#3989 24w38a a bit more stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/AbstractCoralBlock.mapping
  mappings/net/minecraft/block/AbstractPlantPartBlock.mapping
  mappings/net/minecraft/block/FireBlock.mapping
  mappings/net/minecraft/block/NoteBlock.mapping
  mappings/net/minecraft/block/ObserverBlock.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/item/BundleItem.mapping
Labels: refactor, new, snapshot

#3991 More 24w38a stuff
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/gl/GlBufferTarget.mapping
  mappings/net/minecraft/client/gl/GlFenceSync.mapping
  mappings/net/minecraft/client/gl/GlUsage.mapping
  mappings/net/minecraft/client/gl/GpuBuffer.mapping
  mappings/net/minecraft/client/gl/Usage.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldCallback.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/realms/FileUpload.mapping
  mappings/net/minecraft/client/realms/dto/RealmsServer.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsCreateRealmScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsUploadScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsWorldCreating.mapping
  mappings/net/minecraft/client/realms/util/RealmsUploader.mapping
  mappings/net/minecraft/client/realms/util/UploadCompressor.mapping
  mappings/net/minecraft/client/realms/util/UploadProgress.mapping
  mappings/net/minecraft/client/realms/util/UploadProgressTracker.mapping
  mappings/net/minecraft/client/realms/util/UploadResult.mapping
  mappings/net/minecraft/client/util/tracy/TracyFrameCapturer.mapping
  mappings/net/minecraft/data/server/recipe/BundleRecipeGenerator.mapping
  mappings/net/minecraft/data/server/recipe/VanillaRecipeGenerator.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/recipe/TransmuteRecipe.mapping
  mappings/net/minecraft/server/command/TeleportCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/state/property/BooleanProperty.mapping
  mappings/net/minecraft/state/property/EnumProperty.mapping
  mappings/net/minecraft/test/GameTestState.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/util/Cooldown.mapping
  mappings/net/minecraft/util/math/Vec3d.mapping
  mappings/net/minecraft/world/block/NeighborUpdater.mapping
  mappings/net/minecraft/world/dimension/NetherPortal.mapping
  mappings/net/minecraft/world/tick/ScheduledTickView.mapping
Labels: refactor, new, snapshot

#3995 fix: autojump -> autoJump
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
Labels: bug, refactor, snapshot

#3997 24w39a boat stuff + datafixes
  mappings/net/minecraft/class_10255.mapping
  mappings/net/minecraft/client/render/entity/AbstractBoatEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/BoatEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderers.mapping
  mappings/net/minecraft/client/render/entity/RaftEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/AbstractBoatEntityModel.mapping
  mappings/net/minecraft/datafixer/fix/BoatSplitFix.mapping
  mappings/net/minecraft/datafixer/fix/ContainerBlockEntityLockPredicateFix.mapping
  mappings/net/minecraft/datafixer/fix/LockComponentPredicateFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema4067.mapping
  mappings/net/minecraft/entity/vehicle/AbstractBoatEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractChestBoatEntity.mapping
  mappings/net/minecraft/entity/vehicle/ChestRaftEntity.mapping
  mappings/net/minecraft/entity/vehicle/RaftEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleEntity.mapping
  mappings/net/minecraft/item/BoatItem.mapping
Labels: new, snapshot

#3999 24w39a stuff
  mappings/net/minecraft/block/dispenser/BoatDispenserBehavior.mapping
  mappings/net/minecraft/class_10245.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CreativeInventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/InventoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/RecipeBookScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StatusEffectsDisplay.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/GhostRecipe.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/OminousItemSpawnerEntity.mapping
  mappings/net/minecraft/entity/ai/TargetPredicate.mapping
  mappings/net/minecraft/entity/ai/brain/LivingTargetCache.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/BreezeAttackablesSensor.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/NearestVisibleLivingEntitySensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/ForgetAttackTargetTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/PrepareRamTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/UpdateAttackTargetTask.mapping
  mappings/net/minecraft/entity/ai/goal/ActiveTargetGoal.mapping
  mappings/net/minecraft/entity/ai/goal/DisableableFollowTargetGoal.mapping
  mappings/net/minecraft/entity/ai/goal/FleeEntityGoal.mapping
  mappings/net/minecraft/entity/ai/goal/LookAtEntityGoal.mapping
  mappings/net/minecraft/entity/ai/goal/RaidGoal.mapping
  mappings/net/minecraft/entity/ai/goal/TemptGoal.mapping
  mappings/net/minecraft/entity/ai/goal/TrackTargetGoal.mapping
  mappings/net/minecraft/entity/ai/goal/UntamedActiveTargetGoal.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/phase/SittingScanningPhase.mapping
  mappings/net/minecraft/entity/decoration/EndCrystalEntity.mapping
  mappings/net/minecraft/entity/decoration/ItemFrameEntity.mapping
  mappings/net/minecraft/entity/effect/InfestedStatusEffect.mapping
  mappings/net/minecraft/entity/mob/BoggedEntity.mapping
  mappings/net/minecraft/entity/mob/BreezeBrain.mapping
  mappings/net/minecraft/entity/mob/EndermanEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinBrain.mapping
  mappings/net/minecraft/entity/mob/ZombieEntity.mapping
  mappings/net/minecraft/entity/passive/FoxEntity.mapping
  mappings/net/minecraft/entity/passive/PufferfishEntity.mapping
  mappings/net/minecraft/entity/player/HungerManager.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/FireworkRocketEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/TridentEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/entity/vehicle/ExperimentalMinecartController.mapping
  mappings/net/minecraft/entity/vehicle/MinecartController.mapping
  mappings/net/minecraft/entity/vehicle/VehicleEntity.mapping
  mappings/net/minecraft/entity/vehicle/VehicleInventory.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/world/EntityLookupView.mapping
Labels: new, snapshot

#4001 24w39a more mappings
  mappings/net/minecraft/block/AbstractFireBlock.mapping
  mappings/net/minecraft/block/CommandBlock.mapping
  mappings/net/minecraft/block/TurtleEggBlock.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerLogic.mapping
  mappings/net/minecraft/client/realms/gui/RealmsWorldSlotButton.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsWorldCreating.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/component/type/UseRemainderComponent.mapping
  mappings/net/minecraft/data/server/recipe/VanillaRecipeGenerator.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/inventory/ContainerLock.mapping
  mappings/net/minecraft/item/AnimalArmorItem.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/equipment/ArmorMaterial.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/recipe/RecipeUnlocker.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
Labels: new, snapshot
