Repository FabricMC/yarn, pull requests merged in 2024-02, with the labels that each got.

#3775 Add distinct names to `Sprite` classes
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/texture/atlas/AtlasSprite.mapping
Labels: refactor, snapshot

#3780 24w05a stuff
  mappings/net/minecraft/block/spawner/TrialSpawnerConfig.mapping
  mappings/net/minecraft/block/vault/VaultConfig.mapping
  mappings/net/minecraft/class_9187.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/DebugSampleSubscriber.mapping
  mappings/net/minecraft/client/option/HotbarStorage.mapping
  mappings/net/minecraft/client/option/HotbarStorageEntry.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/command/CommandRegistryAccess.mapping
  mappings/net/minecraft/command/DataCommandStorage.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateReader.mapping
  mappings/net/minecraft/command/argument/ItemPredicateStringReader.mapping
  mappings/net/minecraft/command/argument/ItemStackArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/command/argument/TagKeyArgumentType.mapping
  mappings/net/minecraft/command/argument/TextArgumentType.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/entity/passive/MerchantEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/map/MapBannerMarker.mapping
  mappings/net/minecraft/item/map/MapIcon.mapping
  mappings/net/minecraft/loot/context/LootContextTypes.mapping
  mappings/net/minecraft/network/PacketByteBuf.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/network/packet/s2c/common/StoreCookieS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandSuggestionsS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/MapUpdateS2CPacket.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/registry/RegistryOps.mapping
  mappings/net/minecraft/screen/HorseScreenHandler.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/SampleSubscriptionTracker.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/util/DebugSampleType.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/MatrixUtil.mapping
  mappings/net/minecraft/util/profiler/MultiValueDebugSampleLogImpl.mapping
  mappings/net/minecraft/util/profiler/PerformanceLog.mapping
  mappings/net/minecraft/util/profiler/log/ArrayDebugSampleLog.mapping
  mappings/net/minecraft/util/profiler/log/DebugSampleLog.mapping
  mappings/net/minecraft/util/profiler/log/DebugSampleType.mapping
  mappings/net/minecraft/util/profiler/log/MultiValueDebugSampleLog.mapping
  mappings/net/minecraft/util/profiler/log/SubscribableDebugSampleLog.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  mappings/net/minecraft/world/storage/ChunkCompressionFormat.mapping
Labels: refactor, new, snapshot

#3784 A little more 24w06 stuff
  mappings/net/minecraft/class_9224.mapping
  mappings/net/minecraft/class_9243.mapping
  mappings/net/minecraft/class_9247.mapping
  mappings/net/minecraft/network/packet/VersionedIdentifier.mapping
  mappings/net/minecraft/resource/ResourcePackProfile.mapping
  mappings/net/minecraft/util/profiling/jfr/event/ChunkRegionEvent.mapping
Labels: new, snapshot

#3783 24w06a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/class_9236.mapping
  mappings/net/minecraft/client/gui/screen/option/FontOptionsScreen.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/entity/animation/ArmadilloAnimations.mapping
  mappings/net/minecraft/data/server/loottable/onetwentyone/OneTwentyOneEntityLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/FixUtil.mapping
  mappings/net/minecraft/datafixer/fix/BlockPosFormatFix.mapping
  mappings/net/minecraft/datafixer/fix/LegacyDragonFightFix.mapping
  mappings/net/minecraft/datafixer/fix/MapBannerBlockPosFormatFix.mapping
  mappings/net/minecraft/datafixer/fix/StatusEffectFix.mapping
  mappings/net/minecraft/datafixer/fix/WolfHealthFix.mapping
  mappings/net/minecraft/entity/AnimationState.mapping
  mappings/net/minecraft/entity/DataTracked.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/data/DataTracker.mapping
  mappings/net/minecraft/entity/passive/ArmadilloBrain.mapping
  mappings/net/minecraft/entity/passive/ArmadilloEntity.mapping
  mappings/net/minecraft/entity/passive/TameableEntity.mapping
  mappings/net/minecraft/entity/projectile/AbstractWindChargeEntity.mapping
  mappings/net/minecraft/entity/projectile/BreezeWindChargeEntity.mapping
  mappings/net/minecraft/entity/projectile/WindChargeEntity.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/item/WindChargeItem.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/network/listener/ClientConfigurationPacketListener.mapping
  mappings/net/minecraft/network/listener/ServerConfigurationPacketListener.mapping
  mappings/net/minecraft/network/packet/ConfigPackets.mapping
  mappings/net/minecraft/network/packet/c2s/config/SelectKnownPacksC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/config/SelectKnownPacksS2CPacket.mapping
  mappings/net/minecraft/server/network/SynchronizeRegistriesTask.mapping
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/state/StateManager.mapping
  mappings/net/minecraft/world/explosion/ExplosionBehavior.mapping
  unpick-definitions/entity_status.unpick
Labels: new, snapshot, unpick

#3785 Update buildscript
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release-filament.yml
  build.gradle
  filament/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: toolchain

#3781 Correct ConnectScreen.BLOCKED_HOST_TEXT -> ConnectScreen.UNKNOWN_HOST_TEXT
  mappings/net/minecraft/client/gui/screen/multiplayer/ConnectScreen.mapping
Labels: snapshot

#3790 24w07a stuff
  mappings/net/minecraft/block/HopperBlock.mapping
  mappings/net/minecraft/block/entity/Hopper.mapping
  mappings/net/minecraft/client/render/entity/BoggedEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/SkeletonOverlayFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/datafixer/schema/Schema3816.mapping
  mappings/net/minecraft/entity/ai/pathing/LandPathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/PathNodeMaker.mapping
  mappings/net/minecraft/entity/ai/pathing/WaterPathNodeMaker.mapping
  mappings/net/minecraft/entity/mob/AbstractSkeletonEntity.mapping
  mappings/net/minecraft/entity/mob/BoggedEntity.mapping
  mappings/net/minecraft/server/command/TeleportCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/test/GameTest.mapping
  mappings/net/minecraft/test/StructureTestUtil.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/math/Direction.mapping
Labels: new, snapshot

#3793 More 24w07a stuff
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/registry/RegistryBuilder.mapping
  mappings/net/minecraft/registry/RegistryOps.mapping
  mappings/net/minecraft/registry/RegistryWrapper.mapping
Labels: new, snapshot

#3797 Rename `SculkShriekerWarningManager#canIncreaseWarningLevel` to `isWardenNearby`
  mappings/net/minecraft/block/entity/SculkShriekerWarningManager.mapping
Labels: refactor, snapshot

#3796 Add Javadoc descriptions to the fields of AbstractBlock
  mappings/net/minecraft/block/AbstractBlock.mapping
Labels: snapshot, javadoc

#3795 Map some fields in a couple of item classes
  mappings/net/minecraft/item/BrushItem.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/SpyglassItem.mapping
  mappings/net/minecraft/item/map/MapState.mapping
Labels: new, snapshot

#3798 A few minor things
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/ConnectScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsLongRunningTickableTaskScreen.mapping
  mappings/net/minecraft/network/state/HandshakeStates.mapping
  mappings/net/minecraft/structure/processor/JigsawReplacementStructureProcessor.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/util/profiling/jfr/event/PacketEvent.mapping
  mappings/net/minecraft/util/shape/VoxelSet.mapping
  mappings/net/minecraft/util/thread/LockHelper.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
  mappings/net/minecraft/world/gen/feature/LargeDripstoneFeature.mapping
Labels: new, snapshot

#3799 Let's not do that again
  .gitignore
  build.gradle
  filament/.gitignore
Labels: toolchain

#3801 Fix mappings being ignored
  .gitignore
Labels: bug, toolchain

#3802 Map misc screen and gui changes
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gl/PostEffectProcessor.mapping
  mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/screen/OutOfMemoryScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/StatsScreen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BeaconScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerServerListWidget.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/MouseOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/ExperimentalWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/pack/PackScreen.mapping
  mappings/net/minecraft/client/gui/screen/report/AbuseReportReasonScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CreateWorldScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/CustomizeBuffetLevelScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditGameRulesScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/ExperimentsScreen.mapping
  mappings/net/minecraft/client/gui/widget/EntryListWidget.mapping
  mappings/net/minecraft/client/gui/widget/ThreePartsLayoutWidget.mapping
  mappings/net/minecraft/client/model/ModelPart.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/particle/DamageParticle.mapping
  mappings/net/minecraft/client/particle/FireworksSparkParticle.mapping
  mappings/net/minecraft/client/particle/FlameParticle.mapping
  mappings/net/minecraft/client/particle/SquidInkParticle.mapping
  mappings/net/minecraft/client/particle/SuspendParticle.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsBackupScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsClientIncompatibleScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsInviteScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsPlayerScreen.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelOverride.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
  mappings/net/minecraft/loot/function/ApplyBonusLootFunction.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
Labels: refactor, new, snapshot
