Repository FabricMC/yarn, pull requests merged in 2024-06, with the labels that each got.

#3893 1.21-pre3 stuff
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/enchantment/effect/entity/ReplaceDiskEnchantmentEffect.mapping
  mappings/net/minecraft/entity/Leashable.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/entity/decoration/LeashKnotEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/LeadItem.mapping
  mappings/net/minecraft/item/TridentItem.mapping
  mappings/net/minecraft/item/map/MapState.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/Colors.mapping
  unpick-definitions/colors.unpick
Labels: refactor, new, snapshot

#3895 Map 1.21-pre4 TNT
  mappings/net/minecraft/entity/TntEntity.mapping
Labels: new, snapshot

#3898 Map Tameable.getWorld()
  mappings/net/minecraft/entity/Tameable.mapping
Labels: release

#3896 Rename id in entity-related packets to entityId
  mappings/net/minecraft/network/packet/s2c/play/EntityAnimationS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityEquipmentUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityPassengersSetS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityPositionS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntitySetHeadYawS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntitySpawnS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityStatusS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/EntityVelocityUpdateS2CPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExperienceOrbSpawnS2CPacket.mapping
Labels: refactor, snapshot

#3897 fix: Rename `videoMode` to `fullscreenVideoMode`
  mappings/net/minecraft/client/util/Window.mapping
Labels: release

#3900 Migrate name proposal code to filament
  build.gradle
  filament/gradle.properties
  filament/src/main/java/net/fabricmc/filament/nameproposal/Constants.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/FieldNameFinder.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/MappingEntry.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/MappingNameCompleter.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/NameFinder.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/NameFinderVisitor.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/RecordComponentNameFinder.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/enigma/EnigmaNameProposalService.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/enigma/IntermediaryObfuscationTestService.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/enigma/NameProposalServiceEnigmaPlugin.java
  filament/src/main/resources/META-INF/services/cuchaz.enigma.api.EnigmaPlugin
  gradle.properties
Labels: toolchain

#3908 Fix FoodComponent constructor having outdated names
  mappings/net/minecraft/component/type/FoodComponent.mapping
Labels: bug, release
