Repository FabricMC/yarn, pull requests merged in 2024-08, with the labels that each got.

#3919 1.21.1-rc1 stuff
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/command/argument/EntityArgumentType.mapping
  mappings/net/minecraft/command/argument/GameProfileArgumentType.mapping
  mappings/net/minecraft/command/argument/MessageArgumentType.mapping
  mappings/net/minecraft/command/argument/ScoreHolderArgumentType.mapping
Labels: new, snapshot

#3918 Add more ocean monument mappings
  mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
Labels: new, release

#3921 Document ContainerComponent and fix a method name
  mappings/net/minecraft/component/type/ContainerComponent.mapping
Labels: bug, release, javadoc

#3924 Util: Rename and document error methods that pause the game
  mappings/net/minecraft/util/Util.mapping
Labels: refactor, snapshot, javadoc

#3926 Suppress some warnings from name proposal
  filament/src/main/java/net/fabricmc/filament/nameproposal/RecordComponentNameFinder.java
  mappings/net/minecraft/component/type/BookContent.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
Labels: toolchain

#3927 Update dependencies
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release-filament.yml
  .github/workflows/update-base.yml
  .github/workflows/version-label.yml
  filament/build.gradle
  filament/src/main/java/net/fabricmc/filament/FilamentGradlePlugin.java
  filament/src/main/java/net/fabricmc/filament/util/MinecraftVersionMetaHelper.java
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: toolchain

#3930 Rename PistonBlock#move boolean argument to 'extend'
  mappings/net/minecraft/block/PistonBlock.mapping
Labels: bug, snapshot

#3931 Fix incorrect method name in EnchantmentHelper
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
Labels: bug, new, snapshot

#3932 Use NON_NEGATIVE spelling convention
  mappings/net/minecraft/util/dynamic/Codecs.mapping
  mappings/net/minecraft/util/math/intprovider/IntProvider.mapping
Labels: refactor, new, snapshot

#3933 More 24w33a stuff
  mappings/net/minecraft/class_10093.mapping
  mappings/net/minecraft/class_9884.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/component/ComponentMapImpl.mapping
  mappings/net/minecraft/component/type/BundleContentsComponent.mapping
  mappings/net/minecraft/data/server/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/server/loottable/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/vanilla/VanillaBlockLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/vanilla/VanillaEntityLootTableGenerator.mapping
  mappings/net/minecraft/data/server/loottable/vanilla/VanillaShearingLootTableGenerator.mapping
  mappings/net/minecraft/data/server/recipe/RecipeExporter.mapping
  mappings/net/minecraft/data/server/recipe/RecipeGenerator.mapping
  mappings/net/minecraft/data/server/recipe/ShapedRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/ShapelessRecipeJsonBuilder.mapping
  mappings/net/minecraft/data/server/recipe/VanillaRecipeGenerator.mapping
  mappings/net/minecraft/datafixer/fix/AttributeIdPrefixFix.mapping
  mappings/net/minecraft/datafixer/fix/AttributeRenameFix.mapping
  mappings/net/minecraft/datafixer/fix/CarvingStepRemoveFix.mapping
  mappings/net/minecraft/datafixer/fix/OminousBannerRarityFix.mapping
  mappings/net/minecraft/entity/damage/DamageSources.mapping
  mappings/net/minecraft/entity/damage/DamageTypes.mapping
  mappings/net/minecraft/item/AxeItem.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/GoatHornItem.mapping
  mappings/net/minecraft/item/HoeItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/MiningToolItem.mapping
  mappings/net/minecraft/item/PickaxeItem.mapping
  mappings/net/minecraft/item/ShovelItem.mapping
  mappings/net/minecraft/item/SwordItem.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
  mappings/net/minecraft/loot/LootTables.mapping
  mappings/net/minecraft/recipe/Ingredient.mapping
  mappings/net/minecraft/registry/entry/RegistryEntryList.mapping
  mappings/net/minecraft/util/Colors.mapping
  mappings/net/minecraft/util/math/ColorHelper.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/world/block/WireOrientation.mapping
  unpick-definitions/colors.unpick
  unpick-definitions/entity_model_parts.unpick
Labels: refactor, new, snapshot

#3934 Use lowercase name for non-static final list in EntityEffectPredicate.Builder
  mappings/net/minecraft/predicate/entity/EntityEffectPredicate.mapping
Labels: bug, refactor, snapshot

#3942 Fix ClientTickEnd packet incorrect name and package
  mappings/net/minecraft/network/packet/c2s/play/ClientTickEndC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ClientTickEndS2CPacket.mapping
Labels: bug, snapshot

#3939 Correctly name Raid-``ravager``-spawn methods
  mappings/net/minecraft/village/raid/Raid.mapping
Labels: bug, refactor, snapshot

#3941 Continue mapping 24w33a (redstone, entity rendering)
  mappings/net/minecraft/block/RedstoneWireBlock.mapping
  mappings/net/minecraft/class_9847.mapping
  mappings/net/minecraft/class_9929.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/option/InactivityFpsLimiter.mapping
  mappings/net/minecraft/client/render/entity/BipedEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/DragonEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ElytraEntityModel.mapping
  mappings/net/minecraft/client/render/entity/state/BipedEntityRenderState.mapping
  mappings/net/minecraft/client/render/entity/state/EnderDragonEntityRenderState.mapping
  mappings/net/minecraft/client/render/entity/state/LivingEntityRenderState.mapping
  mappings/net/minecraft/client/resource/language/DeprecatedLanguageData.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonFrameTracker.mapping
  mappings/net/minecraft/entity/mob/ElytraFlightController.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/filter/AbstractTextFilterer.mapping
  mappings/net/minecraft/server/filter/NewTextFilterer.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/InterpolatedFlipFlop.mapping
  mappings/net/minecraft/world/DefaultRedstoneController.mapping
  mappings/net/minecraft/world/ExperimentalRedstoneController.mapping
  mappings/net/minecraft/world/RedstoneController.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/block/NeighborUpdater.mapping
  mappings/net/minecraft/world/block/OrientationHelper.mapping
  mappings/net/minecraft/world/block/WireOrientation.mapping
  mappings/net/minecraft/world/explosion/Explosion.mapping
  mappings/net/minecraft/world/explosion/ExplosionBehavior.mapping
  mappings/net/minecraft/world/explosion/ExplosionImpl.mapping
Labels: new, snapshot

#3940 24w33a more headache
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/ShapeContext.mapping
  mappings/net/minecraft/class_9929.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/EntitySelectorOptions.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/type/ToolComponent.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/recipe/InputSlotFiller.mapping
  mappings/net/minecraft/recipe/MapExtendingRecipe.mapping
  mappings/net/minecraft/recipe/RawShapedRecipe.mapping
  mappings/net/minecraft/recipe/RecipeGridAligner.mapping
  mappings/net/minecraft/recipe/RecipeManager.mapping
  mappings/net/minecraft/recipe/RecipeMatcher.mapping
  mappings/net/minecraft/recipe/ShapedRecipe.mapping
  mappings/net/minecraft/recipe/ShapelessRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTransformRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTrimRecipe.mapping
  mappings/net/minecraft/server/DataPackContents.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/GameRuleCommand.mapping
  mappings/net/minecraft/server/command/ScheduleCommand.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/ServerPropertiesHandler.mapping
  mappings/net/minecraft/server/network/DebugInfoSender.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkLoadingManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/State.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/text/ParsedSelector.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/util/crash/SuppressedExceptionsTracker.mapping
  mappings/net/minecraft/world/CollisionView.mapping
  mappings/net/minecraft/world/SimulationDistanceLevelPropagator.mapping
  mappings/net/minecraft/world/World.mapping
Labels: new, snapshot

#3946 Remove duplicate methods and class mappings
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/server/filter/V0TextFilterer.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
Labels: bug, snapshot

#3875 Add checkMappings task
  build.gradle
  filament/src/main/java/net/fabricmc/filament/task/mappingio/CheckMappingsTask.java
  filament/src/main/java/net/fabricmc/filament/task/mappingio/CheckMergedMappingsTask.java
Labels: snapshot, toolchain

#3949 24w33a more
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/CurrentIndexProvider.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/GhostRecipe.mapping
  mappings/net/minecraft/client/render/WeatherRendering.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/datafixer/FixUtil.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceWriteReadFix.mapping
  mappings/net/minecraft/datafixer/fix/ChunkToProtoChunkFix.mapping
  mappings/net/minecraft/datafixer/fix/EntityPaintingMotiveFix.mapping
  mappings/net/minecraft/datafixer/fix/ItemLoreToTextFix.mapping
  mappings/net/minecraft/datafixer/fix/OptionsAmbientOcclusionFix.mapping
  mappings/net/minecraft/datafixer/fix/StriderGravityFix.mapping
  mappings/net/minecraft/datafixer/fix/VillagerXpRebuildFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/LimbAnimator.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/OminousItemSpawnerEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/fluid/FlowableFluid.mapping
  mappings/net/minecraft/fluid/Fluid.mapping
  mappings/net/minecraft/fluid/FluidState.mapping
  mappings/net/minecraft/item/RangedWeaponItem.mapping
  mappings/net/minecraft/item/SmithingTemplateItem.mapping
  mappings/net/minecraft/item/WindChargeItem.mapping
  mappings/net/minecraft/particle/ParticlesMode.mapping
  mappings/net/minecraft/screen/AbstractCraftingScreenHandler.mapping
  mappings/net/minecraft/screen/AbstractFurnaceScreenHandler.mapping
  mappings/net/minecraft/screen/AbstractRecipeScreenHandler.mapping
  mappings/net/minecraft/screen/AnvilScreenHandler.mapping
  mappings/net/minecraft/screen/CurrentIndexProvider.mapping
  mappings/net/minecraft/screen/EnchantmentScreenHandler.mapping
  mappings/net/minecraft/screen/GenericContainerScreenHandler.mapping
  mappings/net/minecraft/screen/LoomScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/StonecutterScreenHandler.mapping
  mappings/net/minecraft/world/BlockView.mapping
Labels: bug, refactor, new, snapshot

#3950 24w33a some more stuff
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementsScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/AbstractFurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/BlastFurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/CartographyTableScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/FurnaceScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/SmokerScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/MultiplayerWarningScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/AccessibilityOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/ControlsOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/GameOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/OptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/option/SkinOptionsScreen.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AbstractCraftingRecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AbstractFurnaceRecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeGroupButtonWidget.mapping
  mappings/net/minecraft/client/gui/screen/world/BackupPromptScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/EditWorldScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/CatCollarFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/DolphinHeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/DrownedOverlayFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ElytraFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/EnergySwirlOverlayFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/FoxHeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/HorseArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/LlamaDecorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/PandaHeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/PlayerHeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ShoulderParrotFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/StuckObjectsFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/TridentRiptideFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/VillagerHeldItemFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/WolfArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/DonkeyEntityModel.mapping
  mappings/net/minecraft/client/toast/AdvancementToast.mapping
  mappings/net/minecraft/client/toast/RecipeToast.mapping
  mappings/net/minecraft/client/toast/SystemToast.mapping
  mappings/net/minecraft/client/toast/Toast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/client/world/WorldEventHandler.mapping
  mappings/net/minecraft/entity/vehicle/DefaultMinecartController.mapping
  mappings/net/minecraft/entity/vehicle/MinecartController.mapping
  mappings/net/minecraft/item/ItemGroup.mapping
  mappings/net/minecraft/item/RangedWeaponItem.mapping
  unpick-definitions/world_events.unpick
Labels: new, snapshot

#3952 24w33a just a little more
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/NearestPlayersSensor.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/Sensor.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeJumpTask.mapping
  mappings/net/minecraft/entity/ai/brain/task/BreezeMovementUtil.mapping
  mappings/net/minecraft/entity/ai/goal/ActiveTargetGoal.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingVariants.mapping
  mappings/net/minecraft/entity/mob/BreezeBrain.mapping
  mappings/net/minecraft/entity/mob/PiglinBruteEntity.mapping
  mappings/net/minecraft/entity/mob/RavagerEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/DolphinEntity.mapping
  mappings/net/minecraft/entity/passive/MooshroomEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EggEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EnderPearlEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/ExperienceBottleEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/SnowballEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/ThrownItemEntity.mapping
  mappings/net/minecraft/entity/raid/RaiderEntity.mapping
  mappings/net/minecraft/item/FuelRegistry.mapping
  mappings/net/minecraft/loot/LootTables.mapping
  mappings/net/minecraft/predicate/entity/EntityEquipmentPredicate.mapping
  mappings/net/minecraft/recipe/RecipeFinder.mapping
  mappings/net/minecraft/screen/Generic3x3ContainerScreenHandler.mapping
  mappings/net/minecraft/world/World.mapping
Labels: bug, new, snapshot

#3953 24w33a final mappings
  mappings/net/minecraft/client/render/debug/ChunkDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/RedstoneUpdateOrderDebugRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/Baker.mapping
  mappings/net/minecraft/client/render/model/BlockStatesLoader.mapping
  mappings/net/minecraft/client/render/model/GroupableModel.mapping
  mappings/net/minecraft/client/render/model/MissingModel.mapping
  mappings/net/minecraft/client/render/model/ModelBaker.mapping
  mappings/net/minecraft/client/render/model/ModelGrouper.mapping
  mappings/net/minecraft/client/render/model/Models.mapping
  mappings/net/minecraft/client/render/model/ReferencedModelsCollector.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/TemptationsSensor.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/decoration/ArmorStandEntity.mapping
  mappings/net/minecraft/entity/mob/BoggedEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/WardenEntity.mapping
  mappings/net/minecraft/entity/mob/WaterCreatureEntity.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/entity/projectile/AbstractFireballEntity.mapping
  mappings/net/minecraft/entity/projectile/FishingBobberEntity.mapping
  mappings/net/minecraft/entity/projectile/WindChargeEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/entity/vehicle/ExperimentalMinecartController.mapping
Labels: new, snapshot

#3955 24w34a small stuff
  mappings/net/minecraft/client/render/entity/state/ArmorStandEntityRenderState.mapping
  mappings/net/minecraft/component/type/ConsumableComponent.mapping
  mappings/net/minecraft/item/BundleItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/util/hit/BlockHitResult.mapping
Labels: bug, new, snapshot

#3958 Rename the FuelRegistry.Builder#featureSet field to enabledFeatures
  mappings/net/minecraft/item/FuelRegistry.mapping
Labels: bug, snapshot

#3957 24w34a fixes and minor renames
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/data/server/recipe/RecipeGenerator.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/recipe/Recipe.mapping
  mappings/net/minecraft/recipe/input/RecipeInput.mapping
Labels: bug, refactor, snapshot

#3966 ItemStack#damage(int, SW, SPE) -> calculateDamage
  mappings/net/minecraft/item/ItemStack.mapping
Labels: bug, refactor, snapshot

#3969 Map rendering stuff
  mappings/net/minecraft/class_9916.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gl/PostEffectProcessor.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/hud/debug/DebugChart.mapping
  mappings/net/minecraft/client/gui/hud/debug/PieChart.mapping
  mappings/net/minecraft/client/render/FrameGraphBuilder.mapping
  mappings/net/minecraft/client/render/Frustum.mapping
  mappings/net/minecraft/client/render/RenderPass.mapping
  mappings/net/minecraft/client/render/VertexConsumer.mapping
  mappings/net/minecraft/client/render/VertexRendering.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/chunk/ChunkRenderTaskScheduler.mapping
  mappings/net/minecraft/client/render/chunk/Octree.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/OctreeDebugRenderer.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/BasicBakedModel.mapping
  mappings/net/minecraft/client/render/model/BlockStatesLoader.mapping
  mappings/net/minecraft/client/render/model/ModelBaker.mapping
  mappings/net/minecraft/client/render/model/MultipartUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
  mappings/net/minecraft/client/render/model/json/BlockPropertiesPredicate.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariantMap.mapping
  mappings/net/minecraft/client/render/model/json/MultipartModelComponent.mapping
  mappings/net/minecraft/client/render/model/json/WeightedUnbakedModel.mapping
  mappings/net/minecraft/client/util/ObjectAllocator.mapping
Labels: bug, refactor, new, snapshot

#3970 24w34a a few minor things
  mappings/net/minecraft/block/CommandBlock.mapping
  mappings/net/minecraft/client/gui/hud/PlayerListHud.mapping
  mappings/net/minecraft/client/gui/screen/report/AbuseReportReasonScreen.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/PlayerListEntry.mapping
  mappings/net/minecraft/client/session/report/AbuseReportReason.mapping
  mappings/net/minecraft/entity/Entity.mapping
Labels: new, snapshot

#3971 24w34a last minute mappings
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/net/minecraft/block/RedstoneTorchBlock.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerData.mapping
  mappings/net/minecraft/client/font/TrueTypeFont.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AbstractCraftingRecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AbstractFurnaceRecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/AnimatedResultButton.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/GhostRecipe.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeAlternativesWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookResults.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeBookWidget.mapping
  mappings/net/minecraft/client/gui/screen/recipebook/RecipeResultCollection.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/util/Pool.mapping
  mappings/net/minecraft/datafixer/fix/ChunkPalettedStorageFix.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/entity/vehicle/ExperimentalMinecartController.mapping
  mappings/net/minecraft/entity/vehicle/HopperMinecartEntity.mapping
  mappings/net/minecraft/entity/vehicle/MinecartController.mapping
  mappings/net/minecraft/util/thread/ThreadExecutor.mapping
Labels: new, snapshot

#3972 24w35a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerConfig.mapping
  mappings/net/minecraft/block/spawner/TrialSpawnerConfigs.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/tooltip/BundleTooltipComponent.mapping
  mappings/net/minecraft/client/gui/tooltip/TooltipComponent.mapping
  mappings/net/minecraft/client/item/ModelPredicateProviderRegistry.mapping
  mappings/net/minecraft/client/model/Model.mapping
  mappings/net/minecraft/client/render/BackgroundRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BannerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BedBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/HangingSignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/ShulkerBoxBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SkullBlockEntityModel.mapping
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/ProjectileEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/WitherSkullEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ArmorFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/ShoulderParrotFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/TridentRiptideEntityModel.mapping
  mappings/net/minecraft/client/util/SpriteIdentifier.mapping
  mappings/net/minecraft/data/client/BlockStateModelGenerator.mapping
  mappings/net/minecraft/data/server/loottable/EntityLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/fix/TrialSpawnerConfigInRegistryFix.mapping
  mappings/net/minecraft/enchantment/EnchantmentEffectContext.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/EquipmentTable.mapping
  mappings/net/minecraft/entity/passive/BeeEntity.mapping
  mappings/net/minecraft/entity/passive/SalmonEntity.mapping
  mappings/net/minecraft/entity/projectile/TridentEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/predicate/entity/SheepPredicate.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/registry/RegistryEntryLookup.mapping
  mappings/net/minecraft/registry/RegistryKeyedValue.mapping
  mappings/net/minecraft/server/command/LootCommand.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/block/NeighborUpdater.mapping
Labels: new, snapshot

#3974 24w35a more stuff
  mappings/net/minecraft/block/AbstractChestBlock.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/passive/SnowGolemEntity.mapping
  mappings/net/minecraft/entity/passive/TraderLlamaEntity.mapping
  mappings/net/minecraft/entity/passive/VillagerEntity.mapping
  mappings/net/minecraft/registry/DynamicRegistryManager.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/registry/RegistryEntryLookup.mapping
  mappings/net/minecraft/registry/RegistryWrapper.mapping
Labels: refactor, new, snapshot

#3973 Add more 24w35a mappings
  mappings/net/minecraft/block/spawner/TrialSpawnerLogic.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/PlayerSkinDrawer.mapping
  mappings/net/minecraft/client/gui/hud/spectator/SpectatorMenuCommand.mapping
  mappings/net/minecraft/client/main/Main.mapping
  mappings/net/minecraft/client/render/BuiltChunkStorage.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/DefaultFramebufferSet.mapping
  mappings/net/minecraft/client/render/DimensionEffects.mapping
  mappings/net/minecraft/client/render/Frustum.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/WeatherRendering.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/debug/ChunkDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/OctreeDebugRenderer.mapping
  mappings/net/minecraft/client/world/ClientChunkManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/entity/vehicle/ExperimentalMinecartController.mapping
  mappings/net/minecraft/entity/vehicle/MinecartController.mapping
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
Labels: new, snapshot
