Repository FabricMC/yarn, pull requests merged in 2024-05, with the labels that each got.

#3857 Map painting changes
  mappings/net/minecraft/entity/decoration/AbstractDecorationEntity.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingEntity.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingVariants.mapping
  mappings/net/minecraft/util/math/Box.mapping
Labels: new, snapshot

#3864 24w19 stuff
  mappings/net/minecraft/block/DecoratedPotPattern.mapping
  mappings/net/minecraft/block/DecoratedPotPatterns.mapping
  mappings/net/minecraft/block/LecternBlock.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/ItemDispenserBehavior.mapping
  mappings/net/minecraft/block/entity/CampfireBlockEntity.mapping
  mappings/net/minecraft/client/gui/hud/SubtitlesHud.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/block/entity/DecoratedPotBlockEntityRenderer.mapping
  mappings/net/minecraft/component/type/FoodComponent.mapping
  mappings/net/minecraft/data/report/ItemListProvider.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentValueEffectType.mapping
  mappings/net/minecraft/enchantment/effect/entity/ReplaceBlockEnchantmentEffectType.mapping
  mappings/net/minecraft/enchantment/effect/entity/ReplaceDiscEnchantmentEffectType.mapping
  mappings/net/minecraft/enchantment/effect/entity/SetBlockPropertiesEnchantmentEffectType.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/damage/DamageSource.mapping
  mappings/net/minecraft/entity/player/HungerManager.mapping
  mappings/net/minecraft/entity/projectile/DragonFireballEntity.mapping
  mappings/net/minecraft/entity/projectile/ExplosiveProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/FireballEntity.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/SmallFireballEntity.mapping
  mappings/net/minecraft/entity/projectile/WindChargeEntity.mapping
  mappings/net/minecraft/entity/projectile/WitherSkullEntity.mapping
  mappings/net/minecraft/inventory/RecipeInputInventory.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/LootTable.mapping
  mappings/net/minecraft/loot/context/LootContext.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/network/packet/s2c/play/ProjectilePowerS2CPacket.mapping
  mappings/net/minecraft/predicate/entity/DamageSourcePredicate.mapping
  mappings/net/minecraft/recipe/input/CraftingRecipeInput.mapping
  mappings/net/minecraft/registry/RegistryKeys.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/event/GameEvent.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
Labels: new, snapshot

#3865 More 24w19a stuff
  mappings/net/minecraft/block/enums/NoteBlockInstrument.mapping
  mappings/net/minecraft/class_9761.mapping
  mappings/net/minecraft/client/gui/hud/SubtitlesHud.mapping
  mappings/net/minecraft/client/render/debug/GameTestDebugRenderer.mapping
  mappings/net/minecraft/data/server/recipe/StonecuttingRecipeJsonBuilder.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/attribute/EntityAttribute.mapping
  mappings/net/minecraft/entity/projectile/thrown/EggEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/packet/c2s/play/CraftRequestC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ChangeUnlockedRecipesS2CPacket.mapping
  mappings/net/minecraft/particle/SimpleParticleType.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/network/ChunkDataSender.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/world/ChunkHolder.mapping
  mappings/net/minecraft/server/world/ChunkLevels.mapping
  mappings/net/minecraft/server/world/ChunkTicketManager.mapping
  mappings/net/minecraft/server/world/ServerChunkLoadingManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerLightingProvider.mapping
  mappings/net/minecraft/structure/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/StructurePiece.mapping
  mappings/net/minecraft/structure/pool/StructurePool.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/text/MutableText.mapping
  mappings/net/minecraft/util/collection/BoundedRegionArray.mapping
  mappings/net/minecraft/util/function/Finishable.mapping
  mappings/net/minecraft/util/math/ChunkPos.mapping
  mappings/net/minecraft/util/profiling/jfr/Finishable.mapping
  mappings/net/minecraft/world/ChunkLoadingManager.mapping
  mappings/net/minecraft/world/ChunkRegion.mapping
  mappings/net/minecraft/world/SpawnDensityCapper.mapping
  mappings/net/minecraft/world/chunk/AbstractChunkHolder.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkGenerating.mapping
  mappings/net/minecraft/world/chunk/ChunkGenerationStep.mapping
  mappings/net/minecraft/world/chunk/ChunkGenerationSteps.mapping
  mappings/net/minecraft/world/chunk/ChunkLoader.mapping
  mappings/net/minecraft/world/chunk/ChunkStatus.mapping
  mappings/net/minecraft/world/chunk/GenerationDependencies.mapping
  mappings/net/minecraft/world/chunk/GenerationTask.mapping
  mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
Labels: bug, refactor, new, snapshot

#3868 24w20a stuff
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/block/dispenser/DispenserBehavior.mapping
  mappings/net/minecraft/block/dispenser/ShearsDispenserBehavior.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/LayeredDrawer.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderTickCounter.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/component/type/AttributeModifiersComponent.mapping
  mappings/net/minecraft/datafixer/fix/OptionsMenuBlurrinessFix.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentEffectContext.mapping
  mappings/net/minecraft/enchantment/EnchantmentHelper.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EquipmentSlot.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/goal/SkeletonHorseTrapTriggerGoal.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/attribute/EntityAttribute.mapping
  mappings/net/minecraft/entity/damage/DamageType.mapping
  mappings/net/minecraft/entity/decoration/ArmorStandEntity.mapping
  mappings/net/minecraft/entity/decoration/painting/PaintingVariant.mapping
  mappings/net/minecraft/entity/effect/OozingStatusEffect.mapping
  mappings/net/minecraft/entity/effect/StatusEffect.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/passive/CatVariant.mapping
  mappings/net/minecraft/entity/passive/FrogVariant.mapping
  mappings/net/minecraft/entity/passive/WolfVariant.mapping
  mappings/net/minecraft/entity/projectile/PersistentProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/TridentEntity.mapping
  mappings/net/minecraft/entity/raid/RaiderEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/network/message/MessageType.mapping
  mappings/net/minecraft/network/packet/c2s/play/PlayerInteractItemC2SPacket.mapping
  mappings/net/minecraft/potion/Potion.mapping
  mappings/net/minecraft/predicate/collection/CollectionCountsPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/recipe/RecipeCache.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/text/Decoration.mapping
  mappings/net/minecraft/util/math/MathHelper.mapping
  mappings/net/minecraft/util/math/random/RandomSplitter.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
  mappings/net/minecraft/world/TeleportTarget.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/dimension/DimensionType.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/structure/DimensionPadding.mapping
  mappings/net/minecraft/world/gen/structure/JigsawStructure.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
Labels: refactor, new, snapshot

#3869 Migrate Mapping poet to yarn repo
  build.gradle
  filament/build.gradle
  filament/src/main/java/net/fabricmc/filament/mappingpoet/ClassBuilder.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/Environment.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/FieldBuilder.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/MappingPoet.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/MappingsStore.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/MethodBuilder.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/ModifierBuilder.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/Signatures.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/jd/MappingTaglet.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/AnnotationAwareDescriptors.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/AnnotationAwareSignatures.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/ClassSignature.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/ClassStaticContext.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/MethodSignature.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/PoetClassMethodSignatureVisitor.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/PoetTypeSignatureWriter.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/TypeAnnotationBank.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/TypeAnnotationMapping.java
  filament/src/main/java/net/fabricmc/filament/mappingpoet/signature/TypeAnnotationStorage.java
  filament/src/main/java/net/fabricmc/filament/task/MappingPoetTask.java
  filament/src/test/java/net/fabricmc/filament/test/mappingpoet/BorkAnno.java
  filament/src/test/java/net/fabricmc/filament/test/mappingpoet/SignaturesTest.java
  filament/src/test/java/net/fabricmc/filament/test/mappingpoet/TestAnno.java
  filament/src/test/java/net/fabricmc/filament/test/mappingpoet/TestOuter.java
  filament/src/test/resources/dummy.tiny
  gradle.properties
  gradle/javadoc/copy_on_click.js
  gradle/javadoc/forms.css
  gradle/javadoc/header.txt
Labels: toolchain

#3878 24w21b fix
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/particle/ParticleTextureSheet.mapping
  mappings/net/minecraft/client/render/VertexConsumerProvider.mapping
  mappings/net/minecraft/client/render/chunk/BlockBufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/entity/model/PigEntityModel.mapping
  mappings/net/minecraft/enchantment/Enchantment.mapping
  mappings/net/minecraft/enchantment/EnchantmentLevelBasedValue.mapping
  mappings/net/minecraft/enchantment/effect/AllOfEnchantmentEffects.mapping
  mappings/net/minecraft/enchantment/effect/AttributeEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/DamageImmunityEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentEntityEffect.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentLocationBasedEffect.mapping
  mappings/net/minecraft/enchantment/effect/EnchantmentValueEffect.mapping
  mappings/net/minecraft/enchantment/effect/TargetedEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/ApplyMobEffectEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/DamageEntityEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/DamageItemEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/ExplodeEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/IgniteEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/PlaySoundEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/ReplaceBlockEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/ReplaceDiscEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/RunFunctionEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/SetBlockPropertiesEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/entity/SummonEntityEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/value/AddEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/value/MultiplyEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/value/RemoveBinomialEnchantmentEffect.mapping
  mappings/net/minecraft/enchantment/effect/value/SetEnchantmentEffect.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/ItemUsageContext.mapping
  mappings/net/minecraft/loot/condition/EnchantmentActiveCheckLootCondition.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/network/packet/Packet.mapping
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/world/ModifiableWorld.mapping
  mappings/net/minecraft/world/PlayerSaveHandler.mapping
  mappings/net/minecraft/world/TeleportTarget.mapping
  src/constants/java/net/fabricmc/yarn/constants/MiningLevels.java
  unpick-definitions/entity_flags.unpick
  unpick-definitions/mining_levels.unpick
  unpick-definitions/world_events.unpick
Labels: bug, refactor, javadoc

#3881 Map some Misc mappings
  mappings/net/minecraft/client/gl/JsonEffectShaderProgram.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/entity/ai/brain/sensor/NearestVisibleAdultSensor.mapping
  mappings/net/minecraft/entity/decoration/InteractionEntity.mapping
Labels: new

#3879 Enforce sidedness for client packages
  mappings/net/minecraft/block/enums/CameraSubmersionType.mapping
  mappings/net/minecraft/client/item/BundleTooltipData.mapping
  mappings/net/minecraft/client/item/TooltipData.mapping
  mappings/net/minecraft/client/render/entity/feature/SkinOverlayOwner.mapping
  mappings/net/minecraft/entity/SkinOverlayOwner.mapping
  mappings/net/minecraft/entity/player/BlockBreakingInfo.mapping
  mappings/net/minecraft/entity/player/PlayerModelPart.mapping
  mappings/net/minecraft/item/tooltip/BundleTooltipData.mapping
  mappings/net/minecraft/item/tooltip/TooltipAppender.mapping
  mappings/net/minecraft/item/tooltip/TooltipData.mapping
  mappings/net/minecraft/item/tooltip/TooltipType.mapping
  mappings/net/minecraft/particle/ParticleGroup.mapping
  mappings/net/minecraft/particle/ParticleUtil.mapping
  mappings/net/minecraft/sound/MusicType.mapping
  mappings/net/minecraft/util/math/Smoother.mapping
  mappings/net/minecraft/world/biome/FoliageColors.mapping
  mappings/net/minecraft/world/biome/GrassColors.mapping
  mappings/net/minecraft/world/entity/ClientEntityManager.mapping
Labels: bug, refactor, impactful

#3882 Remove some now-useless unpicks
  mappings/net/minecraft/client/render/entity/model/EntityModelPartNames.mapping
  src/constants/java/net/fabricmc/yarn/constants/LlamaVariants.java
  src/constants/java/net/fabricmc/yarn/constants/ParrotVariants.java
  unpick-definitions/entity_model_parts.unpick
  unpick-definitions/llama_variants.unpick
  unpick-definitions/parrot_variants.unpick
  unpick-definitions/rabbit_types.unpick
Labels: bug, new, snapshot, unpick

#3885 Rename `getEnchantmentsMap` to `getEnchantmentEntries`
  mappings/net/minecraft/component/type/ItemEnchantmentsComponent.mapping
Labels: refactor, snapshot

#3886 1.21-pre1 more stuff
  mappings/net/minecraft/class_9820.mapping
  mappings/net/minecraft/class_9824.mapping
  mappings/net/minecraft/client/gui/screen/ConfirmLinkScreen.mapping
  mappings/net/minecraft/client/gui/screen/DisconnectedScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/screen/advancement/AdvancementWidget.mapping
  mappings/net/minecraft/client/gui/screen/ingame/HorseScreen.mapping
  mappings/net/minecraft/client/gui/screen/ingame/JigsawBlockScreen.mapping
  mappings/net/minecraft/client/gui/screen/world/SymlinkWarningScreen.mapping
  mappings/net/minecraft/client/render/VertexConsumer.mapping
  mappings/net/minecraft/client/render/VertexConsumerProvider.mapping
  mappings/net/minecraft/client/render/model/BlockStatesLoader.mapping
  mappings/net/minecraft/client/render/model/ModelLoader.mapping
  mappings/net/minecraft/client/session/Bans.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/data/report/PacketReportProvider.mapping
  mappings/net/minecraft/enchantment/EnchantmentLevelBasedValue.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/ZombieVillagerEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/projectile/AbstractFireballEntity.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/loot/LootTableReporter.mapping
  mappings/net/minecraft/network/NetworkState.mapping
  mappings/net/minecraft/network/packet/c2s/query/QueryPingC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/play/ExperienceOrbSpawnS2CPacket.mapping
  mappings/net/minecraft/network/state/ConfigurationStates.mapping
  mappings/net/minecraft/network/state/HandshakeStates.mapping
  mappings/net/minecraft/network/state/LoginStates.mapping
  mappings/net/minecraft/network/state/QueryStates.mapping
  mappings/net/minecraft/screen/HorseScreenHandler.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/world/ChunkErrorHandler.mapping
  mappings/net/minecraft/server/world/ServerChunkLoadingManager.mapping
  mappings/net/minecraft/structure/PoolStructurePiece.mapping
  mappings/net/minecraft/structure/StructureTemplateManager.mapping
  mappings/net/minecraft/structure/pool/StructurePoolBasedGenerator.mapping
  mappings/net/minecraft/test/Batches.mapping
  mappings/net/minecraft/test/StructureTestListener.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/test/TestRunContext.mapping
  mappings/net/minecraft/test/TestStructurePlacer.mapping
  mappings/net/minecraft/text/Text.mapping
  mappings/net/minecraft/util/PathUtil.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/util/crash/CrashReport.mapping
  mappings/net/minecraft/world/ChunkSerializer.mapping
  mappings/net/minecraft/world/dimension/PortalForcer.mapping
  mappings/net/minecraft/world/gen/structure/Structure.mapping
  mappings/net/minecraft/world/poi/PointOfInterestStorage.mapping
  mappings/net/minecraft/world/storage/ChunkPosKeyedStorage.mapping
  mappings/net/minecraft/world/storage/EntityChunkDataAccess.mapping
  mappings/net/minecraft/world/storage/RegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/SerializingRegionBasedStorage.mapping
  mappings/net/minecraft/world/storage/StorageIoWorker.mapping
  mappings/net/minecraft/world/storage/VersionedChunkStorage.mapping
Labels: refactor, new, snapshot
