Repository FabricMC/yarn, pull requests merged in 2025-03, with the labels that each got.

#4140 more 25w09 stuff
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BrewingStandBlockEntity.mapping
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/block/entity/CommandBlockBlockEntity.mapping
  mappings/net/minecraft/block/entity/ComparatorBlockEntity.mapping
  mappings/net/minecraft/block/entity/CrafterBlockEntity.mapping
  mappings/net/minecraft/block/entity/EndGatewayBlockEntity.mapping
  mappings/net/minecraft/block/entity/HopperBlockEntity.mapping
  mappings/net/minecraft/block/entity/JigsawBlockEntity.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkSensorBlockEntity.mapping
  mappings/net/minecraft/block/entity/SculkShriekerBlockEntity.mapping
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/block/entity/TestBlockEntity.mapping
  mappings/net/minecraft/block/spawner/MobSpawnerLogic.mapping
  mappings/net/minecraft/datafixer/fix/BlockStateFlattening.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/ExperienceOrbEntity.mapping
  mappings/net/minecraft/entity/FallingBlockEntity.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/TntEntity.mapping
  mappings/net/minecraft/entity/attribute/AttributeContainer.mapping
  mappings/net/minecraft/entity/attribute/EntityAttributeInstance.mapping
  mappings/net/minecraft/entity/boss/WitherEntity.mapping
  mappings/net/minecraft/entity/boss/dragon/EnderDragonEntity.mapping
  mappings/net/minecraft/entity/decoration/ArmorStandEntity.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/entity/decoration/EndCrystalEntity.mapping
  mappings/net/minecraft/entity/decoration/InteractionEntity.mapping
  mappings/net/minecraft/entity/decoration/ItemFrameEntity.mapping
  mappings/net/minecraft/entity/mob/AbstractPiglinEntity.mapping
  mappings/net/minecraft/entity/mob/BoggedEntity.mapping
  mappings/net/minecraft/entity/mob/CreeperEntity.mapping
  mappings/net/minecraft/entity/mob/EndermiteEntity.mapping
  mappings/net/minecraft/entity/mob/EvokerFangsEntity.mapping
  mappings/net/minecraft/entity/mob/GhastEntity.mapping
  mappings/net/minecraft/entity/mob/HoglinEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/PatrolEntity.mapping
  mappings/net/minecraft/entity/mob/PiglinEntity.mapping
  mappings/net/minecraft/entity/mob/RavagerEntity.mapping
  mappings/net/minecraft/entity/mob/ShulkerEntity.mapping
  mappings/net/minecraft/entity/mob/SkeletonEntity.mapping
Labels: new, snapshot

#4138 25w09a rendering stuff
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/class_10859.mapping
  mappings/net/minecraft/class_10865.mapping
  mappings/net/minecraft/client/RunArgs.mapping
  mappings/net/minecraft/client/gl/ARBDirectFramebufferManager.mapping
  mappings/net/minecraft/client/gl/BufferManager.mapping
  mappings/net/minecraft/client/gl/CompiledShader.mapping
  mappings/net/minecraft/client/gl/CompiledShaderPipeline.mapping
  mappings/net/minecraft/client/gl/DebugLabelManager.mapping
  mappings/net/minecraft/client/gl/FramebufferManager.mapping
  mappings/net/minecraft/client/gl/GlBackend.mapping
  mappings/net/minecraft/client/gl/GlDebug.mapping
  mappings/net/minecraft/client/gl/GlGpuBuffer.mapping
  mappings/net/minecraft/client/gl/GlResourceManager.mapping
  mappings/net/minecraft/client/gl/GlUniform.mapping
  mappings/net/minecraft/client/gl/GlUsage.mapping
  mappings/net/minecraft/client/gl/GpuBuffer.mapping
  mappings/net/minecraft/client/gl/LegacyGlFramebufferManager.mapping
  mappings/net/minecraft/client/gl/RenderBackend.mapping
  mappings/net/minecraft/client/gl/RenderPassImpl.mapping
  mappings/net/minecraft/client/gl/ShaderPipeline.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gl/Uniform.mapping
  mappings/net/minecraft/client/gl/UniformContainer.mapping
  mappings/net/minecraft/client/gl/UniformType.mapping
  mappings/net/minecraft/client/render/ColorLogic.mapping
  mappings/net/minecraft/client/render/FramePass.mapping
  mappings/net/minecraft/client/render/PolygonMode.mapping
  mappings/net/minecraft/client/render/RenderPass.mapping
  mappings/net/minecraft/client/render/RenderResourceManager.mapping
  mappings/net/minecraft/client/render/ScissorBox.mapping
  mappings/net/minecraft/client/texture/GlTexture.mapping
Labels: new, snapshot

#4143 25w10a: Some additional Rendering items
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/class_10895.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gl/GpuBuffer.mapping
  mappings/net/minecraft/client/gl/PostEffectPipeline.mapping
  mappings/net/minecraft/client/gl/ShaderPipelines.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/render/CloudRenderer.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/RenderResourceManager.mapping
  mappings/net/minecraft/client/render/SkyRendering.mapping
  mappings/net/minecraft/client/render/VertexFormat.mapping
  mappings/net/minecraft/client/render/WorldBorderRendering.mapping
  mappings/net/minecraft/client/render/model/MultipartBlockStateModel.mapping
Labels: new, snapshot

#4144 25w10a stuff
  mappings/net/minecraft/data/advancement/vanilla/VanillaHusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/predicate/BlockPredicate.mapping
  mappings/net/minecraft/predicate/component/ComponentMapPredicate.mapping
  mappings/net/minecraft/predicate/component/ComponentPredicate.mapping
  mappings/net/minecraft/predicate/component/ComponentPredicateTypes.mapping
  mappings/net/minecraft/predicate/component/ComponentSubPredicate.mapping
  mappings/net/minecraft/predicate/component/ComponentsPredicate.mapping
  mappings/net/minecraft/predicate/component/CustomDataPredicate.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicate.mapping
  mappings/net/minecraft/predicate/item/ItemPredicate.mapping
  mappings/net/minecraft/world/gen/placementmodifier/BlockFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/CountMultilayerPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/CountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/EnvironmentScanPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/HeightmapPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/NoiseBasedCountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/NoiseThresholdCountPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/RandomOffsetPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/RarityFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/SurfaceThresholdFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/placementmodifier/SurfaceWaterDepthFilterPlacementModifier.mapping
  mappings/net/minecraft/world/gen/root/MangroveRootPlacer.mapping
  mappings/net/minecraft/world/gen/root/RootPlacer.mapping
Labels: refactor, new, snapshot

#4145 25w10a packrat parser
  mappings/net/minecraft/class_10846.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemPredicateParsing.mapping
  mappings/net/minecraft/command/argument/NbtElementArgumentType.mapping
  mappings/net/minecraft/command/argument/ParserBackedArgumentType.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/command/argument/TextArgumentType.mapping
  mappings/net/minecraft/command/argument/packrat/AnyIdParsingRule.mapping
  mappings/net/minecraft/command/argument/packrat/ArgumentParser.mapping
  mappings/net/minecraft/command/argument/packrat/Cut.mapping
  mappings/net/minecraft/command/argument/packrat/IdentifierSuggestable.mapping
  mappings/net/minecraft/command/argument/packrat/Literals.mapping
  mappings/net/minecraft/command/argument/packrat/ParseError.mapping
  mappings/net/minecraft/command/argument/packrat/ParseResults.mapping
  mappings/net/minecraft/command/argument/packrat/ParsingStateImpl.mapping
  mappings/net/minecraft/command/argument/packrat/Term.mapping
  mappings/net/minecraft/nbt/NbtByte.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/nbt/NbtDouble.mapping
  mappings/net/minecraft/nbt/NbtFloat.mapping
  mappings/net/minecraft/nbt/NbtHelper.mapping
  mappings/net/minecraft/nbt/NbtInt.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/nbt/NbtLong.mapping
  mappings/net/minecraft/nbt/NbtParsingRule.mapping
  mappings/net/minecraft/nbt/NbtShort.mapping
  mappings/net/minecraft/nbt/NbtString.mapping
  mappings/net/minecraft/nbt/SnbtOperation.mapping
  mappings/net/minecraft/nbt/SnbtParsing.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/nbt/scanner/NbtCollector.mapping
  mappings/net/minecraft/nbt/visitor/NbtTextFormatter.mapping
  mappings/net/minecraft/nbt/visitor/StringNbtWriter.mapping
  mappings/net/minecraft/util/packrat/AnyIdParsingRule.mapping
  mappings/net/minecraft/util/packrat/CursorExceptionType.mapping
  mappings/net/minecraft/util/packrat/Cut.mapping
  mappings/net/minecraft/util/packrat/IdentifiableParsingRule.mapping
  mappings/net/minecraft/util/packrat/IdentifierSuggestable.mapping
  mappings/net/minecraft/util/packrat/Literals.mapping
  mappings/net/minecraft/util/packrat/NumeralParsingRule.mapping
  mappings/net/minecraft/util/packrat/PackratParser.mapping
  mappings/net/minecraft/util/packrat/ParseError.mapping
  mappings/net/minecraft/util/packrat/ParseErrorList.mapping
  mappings/net/minecraft/util/packrat/ParseResults.mapping
  mappings/net/minecraft/util/packrat/Parser.mapping
  mappings/net/minecraft/util/packrat/ParsingRule.mapping
  mappings/net/minecraft/util/packrat/ParsingRuleEntry.mapping
  mappings/net/minecraft/util/packrat/ParsingRules.mapping
  mappings/net/minecraft/util/packrat/ParsingState.mapping
  mappings/net/minecraft/util/packrat/ParsingStateImpl.mapping
  mappings/net/minecraft/util/packrat/PatternParsingRule.mapping
  mappings/net/minecraft/util/packrat/ReaderBackedParsingState.mapping
  mappings/net/minecraft/util/packrat/Suggestable.mapping
  mappings/net/minecraft/util/packrat/Symbol.mapping
  mappings/net/minecraft/util/packrat/Term.mapping
  mappings/net/minecraft/util/packrat/TokenParsingRule.mapping
  mappings/net/minecraft/util/packrat/UnquotedStringParsingRule.mapping
Labels: refactor, new, snapshot

#4146 25w10a render
  mappings/com/mojang/blaze3d/platform/GlConst.mapping
  mappings/com/mojang/blaze3d/platform/GlStateManager.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/data/BlockStateModelGenerator.mapping
  mappings/net/minecraft/client/data/MultipartBlockModelDefinitionCreator.mapping
  mappings/net/minecraft/client/gl/BufferManager.mapping
  mappings/net/minecraft/client/gl/ColorLogic.mapping
  mappings/net/minecraft/client/gl/DebugLabelManager.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gl/FramebufferManager.mapping
  mappings/net/minecraft/client/gl/GlBackend.mapping
  mappings/net/minecraft/client/gl/GlDebug.mapping
  mappings/net/minecraft/client/gl/GlGpuBuffer.mapping
  mappings/net/minecraft/client/gl/GlResourceManager.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gl/PostEffectPipeline.mapping
  mappings/net/minecraft/client/gl/PostEffectProcessor.mapping
  mappings/net/minecraft/client/gl/RenderBackend.mapping
  mappings/net/minecraft/client/gl/RenderPass.mapping
  mappings/net/minecraft/client/gl/RenderPassImpl.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gl/ShaderPipeline.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gl/ShaderType.mapping
  mappings/net/minecraft/client/gui/CubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/gui/widget/SimplePositioningWidget.mapping
  mappings/net/minecraft/client/option/ServerList.mapping
  mappings/net/minecraft/client/realms/RealmsClient.mapping
  mappings/net/minecraft/client/render/ColorLogic.mapping
  mappings/net/minecraft/client/render/FrameGraphBuilder.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/RenderResourceManager.mapping
  mappings/net/minecraft/client/render/ScissorBox.mapping
  mappings/net/minecraft/client/render/VertexFormat.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockRenderManager.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/entity/animation/Transformation.mapping
  mappings/net/minecraft/client/render/model/Baker.mapping
  mappings/net/minecraft/client/render/model/BlockModelPart.mapping
  mappings/net/minecraft/client/render/model/BlockStateModel.mapping
  mappings/net/minecraft/client/render/model/ModelBaker.mapping
  mappings/net/minecraft/client/render/model/MultipartBlockStateModel.mapping
  mappings/net/minecraft/client/render/model/WeightedBlockStateModel.mapping
  mappings/net/minecraft/client/render/model/json/BlockModelDefinition.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariant.mapping
  mappings/net/minecraft/client/render/model/json/WeightedVariant.mapping
  mappings/net/minecraft/client/texture/ClampedTexture.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/client/texture/TextureClampMode.mapping
  mappings/net/minecraft/client/texture/TextureType.mapping
  mappings/net/minecraft/client/util/MacWindowUtil.mapping
  mappings/net/minecraft/client/util/tracy/TracyFrameCapturer.mapping
  unpick-definitions/gl.unpick
Labels: bug, refactor, new, snapshot, unpick

#4147 Bump vineflower to v1.11.1
  gradle.properties
Labels: toolchain

#4150 25w10a fixes
  mappings/net/minecraft/block/CrafterBlock.mapping
  mappings/net/minecraft/block/entity/BlockEntityType.mapping
  mappings/net/minecraft/block/entity/PistonBlockEntity.mapping
  mappings/net/minecraft/block/enums/CameraSubmersionType.mapping
  mappings/net/minecraft/client/ClientWatchdog.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSwitcherScreen.mapping
  mappings/net/minecraft/client/gui/screen/multiplayer/SocialInteractionsPlayerListEntry.mapping
  mappings/net/minecraft/client/particle/ParticleTextureSheet.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/VertexConsumerProvider.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/util/BufferAllocator.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/Leashable.mapping
  mappings/net/minecraft/entity/ai/WardenAngerManager.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/passive/AxolotlBrain.mapping
  mappings/net/minecraft/entity/passive/FrogBrain.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/equipment/ArmorMaterial.mapping
  mappings/net/minecraft/nbt/AbstractNbtNumber.mapping
  mappings/net/minecraft/nbt/NbtList.mapping
  mappings/net/minecraft/network/encryption/PlayerKeyPair.mapping
  mappings/net/minecraft/particle/ParticleGroup.mapping
  mappings/net/minecraft/registry/Registry.mapping
  mappings/net/minecraft/registry/entry/RegistryEntry.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/server/command/SpreadPlayersCommand.mapping
  mappings/net/minecraft/server/filter/FilteredMessage.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/state/property/BooleanProperty.mapping
  mappings/net/minecraft/util/Identifier.mapping
  mappings/net/minecraft/util/thread/AsyncHelper.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
  mappings/net/minecraft/world/WorldEvents.mapping
  unpick-definitions/nbt_type_ids.unpick
Labels: bug, refactor, snapshot, javadoc

#4152 1.21.5-pre1: client.gl (re?) mappings / blaze3d
  mappings/com/mojang/blaze3d/systems/RenderPass.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/vertex/VertexFormat.mapping
  mappings/net/minecraft/client/gl/BufferManager.mapping
  mappings/net/minecraft/client/gl/CompiledShader.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gl/FramebufferManager.mapping
  mappings/net/minecraft/client/gl/GlBackend.mapping
  mappings/net/minecraft/client/gl/GlResourceManager.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gl/PostEffectPipeline.mapping
  mappings/net/minecraft/client/gl/RenderPassImpl.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gl/ShaderPipelines.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gl/UniformType.mapping
  mappings/net/minecraft/client/gl/WindowFramebuffer.mapping
  mappings/net/minecraft/client/render/BuiltBuffer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/VertexFormats.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
Labels: new, snapshot

#4154 1.21.5-pre2 stuff
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  mappings/net/minecraft/command/argument/ParticleEffectArgumentType.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/command/argument/TextArgumentType.mapping
  mappings/net/minecraft/component/ComponentChanges.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/network/message/AcknowledgmentValidator.mapping
  mappings/net/minecraft/network/message/LastSeenMessageList.mapping
  mappings/net/minecraft/network/message/MessageSignatureData.mapping
  mappings/net/minecraft/network/message/SignedMessage.mapping
  mappings/net/minecraft/network/packet/c2s/play/ClickSlotC2SPacket.mapping
  mappings/net/minecraft/network/state/ContextAwareNetworkStateFactory.mapping
  mappings/net/minecraft/network/state/NetworkState.mapping
  mappings/net/minecraft/network/state/NetworkStateBuilder.mapping
  mappings/net/minecraft/network/state/NetworkStateFactory.mapping
  mappings/net/minecraft/network/state/PlayStateFactories.mapping
  mappings/net/minecraft/screen/ScreenHandler.mapping
  mappings/net/minecraft/screen/ScreenHandlerSyncHandler.mapping
  mappings/net/minecraft/screen/sync/ComponentChangesHash.mapping
  mappings/net/minecraft/screen/sync/ItemStackHash.mapping
  mappings/net/minecraft/screen/sync/TrackedSlot.mapping
  mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/util/dynamic/ForwardingDynamicOps.mapping
  mappings/net/minecraft/util/dynamic/HashCodeOps.mapping
Labels: refactor, new, snapshot

#4155 1.21.5-pre2 client
  mappings/com/mojang/blaze3d/buffers/BufferUsage.mapping
  mappings/com/mojang/blaze3d/buffers/GpuBuffer.mapping
  mappings/com/mojang/blaze3d/buffers/GpuFence.mapping
  mappings/com/mojang/blaze3d/opengl/GlConst.mapping
  mappings/com/mojang/blaze3d/opengl/GlStateManager.mapping
  mappings/com/mojang/blaze3d/pipeline/BlendFunction.mapping
  mappings/com/mojang/blaze3d/pipeline/CompiledRenderPipeline.mapping
  mappings/com/mojang/blaze3d/pipeline/RenderPipeline.mapping
  mappings/com/mojang/blaze3d/platform/TextureUtil.mapping
  mappings/com/mojang/blaze3d/shaders/ShaderType.mapping
  mappings/com/mojang/blaze3d/systems/CommandEncoder.mapping
  mappings/com/mojang/blaze3d/systems/GpuDevice.mapping
  mappings/com/mojang/blaze3d/systems/RenderPass.mapping
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/systems/ScissorState.mapping
  mappings/com/mojang/blaze3d/textures/GpuTexture.mapping
  mappings/com/mojang/blaze3d/textures/TextureFormat.mapping
  mappings/com/mojang/blaze3d/vertex/VertexFormat.mapping
  mappings/com/mojang/blaze3d/vertex/VertexFormatElement.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/font/RenderableGlyph.mapping
  mappings/net/minecraft/client/gl/BufferManager.mapping
  mappings/net/minecraft/client/gl/CompiledShader.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gl/FramebufferManager.mapping
  mappings/net/minecraft/client/gl/GlBackend.mapping
  mappings/net/minecraft/client/gl/GlGpuBuffer.mapping
  mappings/net/minecraft/client/gl/GlResourceManager.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gl/PostEffectPipeline.mapping
  mappings/net/minecraft/client/gl/RenderPipelines.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gl/WindowFramebuffer.mapping
  mappings/net/minecraft/client/gui/CubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/BufferBuilder.mapping
  mappings/net/minecraft/client/render/BuiltBuffer.mapping
  mappings/net/minecraft/client/render/CloudRenderer.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/Tessellator.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/state/EntityDebugInfo.mapping
  mappings/net/minecraft/client/render/entity/state/EntityHitbox.mapping
  mappings/net/minecraft/client/render/entity/state/EntityHitboxAndView.mapping
  mappings/net/minecraft/client/render/entity/state/EntityRenderState.mapping
  mappings/net/minecraft/client/texture/Animator.mapping
  mappings/net/minecraft/client/texture/GlTexture.mapping
  mappings/net/minecraft/client/texture/Sprite.mapping
  mappings/net/minecraft/client/texture/SpriteContents.mapping
  mappings/net/minecraft/client/util/ScreenshotRecorder.mapping
  mappings/net/minecraft/client/util/tracy/TracyFrameCapturer.mapping
  unpick-definitions/gl.unpick
Labels: refactor, new, snapshot

#4157 1.21.5-pre3 stuff
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/FilledMapItem.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
Labels: new, snapshot

#4159 1.21.5-rc1 stuff
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockModelRenderer.mapping
  mappings/net/minecraft/entity/decoration/Brightness.mapping
Labels: new, snapshot

#4160 Unify the names of watching sender fields in the EntityTrackerEntry class
  mappings/net/minecraft/server/network/EntityTrackerEntry.mapping
Labels: bug, snapshot
