Repository FabricMC/yarn, pull requests merged in 2025-09, with the labels that each got.

#4268 25w35a Mapped ``TextWidget``
  mappings/net/minecraft/client/gui/widget/TextWidget.mapping
Labels: new, snapshot

#4276 Add better names for light mappings
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
Labels: new, snapshot

#4277 Update Clipboard.mapping to follow CONVENTIONS.md
  mappings/net/minecraft/client/util/Clipboard.mapping
Labels: bug, refactor, snapshot

#4280 25w36b Mapped `NbtDataSourceTypes`
  mappings/net/minecraft/text/NbtDataSource.mapping
  mappings/net/minecraft/text/NbtDataSourceTypes.mapping
Labels: new, snapshot

#4279 25w36b `NumberRange$Bounds` and `NumberRange$AngleRange` mappings
  mappings/net/minecraft/predicate/NumberRange.mapping
Labels: new, snapshot

#4287 25w36b stuff
  build.gradle
  mappings/net/minecraft/block/EntityShapeContext.mapping
  mappings/net/minecraft/block/ShapeContext.mapping
  mappings/net/minecraft/block/SideChaining.mapping
  mappings/net/minecraft/block/entity/CopperGolemStatueBlockEntity.mapping
  mappings/net/minecraft/class_11895.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gl/GlobalSettings.mapping
  mappings/net/minecraft/client/network/ClientMannequinEntity.mapping
  mappings/net/minecraft/client/option/KeyBinding.mapping
  mappings/net/minecraft/client/render/entity/model/WardenEntityModel.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/item/BucketItem.mapping
  mappings/net/minecraft/network/NetworkThreadUtils.mapping
  mappings/net/minecraft/network/PacketApplyBatcher.mapping
  mappings/net/minecraft/network/packet/s2c/play/PlayerRotationS2CPacket.mapping
  mappings/net/minecraft/particle/DragonBreathParticleEffect.mapping
  mappings/net/minecraft/particle/EffectParticleEffect.mapping
  mappings/net/minecraft/predicate/NumberRange.mapping
  mappings/net/minecraft/server/PlayerManager.mapping
  mappings/net/minecraft/server/command/LocateCommand.mapping
  mappings/net/minecraft/server/command/SpectateCommand.mapping
  mappings/net/minecraft/server/dedicated/management/ManagementConnectionHandler.mapping
  mappings/net/minecraft/server/dedicated/management/dispatch/PropertiesRpcDispatcher.mapping
  mappings/net/minecraft/server/dedicated/management/dispatch/ServerRpcDispatcher.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerPlayerInteractionManager.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/util/StringHelper.mapping
  mappings/net/minecraft/world/GameMode.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
  mappings/net/minecraft/world/chunk/ArrayPalette.mapping
  mappings/net/minecraft/world/chunk/BiMapPalette.mapping
  mappings/net/minecraft/world/chunk/Chunk.mapping
  mappings/net/minecraft/world/chunk/ChunkSection.mapping
  mappings/net/minecraft/world/chunk/Palette.mapping
  mappings/net/minecraft/world/chunk/PaletteProvider.mapping
  mappings/net/minecraft/world/chunk/PaletteResizeListener.mapping
  mappings/net/minecraft/world/chunk/PaletteType.mapping
  mappings/net/minecraft/world/chunk/PalettedContainer.mapping
  mappings/net/minecraft/world/chunk/PalettesFactory.mapping
  mappings/net/minecraft/world/chunk/ProtoChunk.mapping
  mappings/net/minecraft/world/chunk/ReadableContainer.mapping
  mappings/net/minecraft/world/chunk/SerializedChunk.mapping
  mappings/net/minecraft/world/chunk/SingularPalette.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/level/LevelProperties.mapping
  mappings/net/minecraft/world/level/ServerWorldProperties.mapping
Labels: bug, refactor, new, snapshot

#4289 25w36b more stuff
  mappings/com/mojang/blaze3d/systems/RenderSystem.mapping
  mappings/com/mojang/blaze3d/systems/VertexSorter.mapping
  mappings/net/minecraft/class_11912.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/font/BakedGlyph.mapping
  mappings/net/minecraft/client/font/BakedGlyphImpl.mapping
  mappings/net/minecraft/client/gui/widget/TextIconButtonWidget.mapping
  mappings/net/minecraft/client/info/BakedGlyph.mapping
  mappings/net/minecraft/client/model/ElderGuardianParticleModel.mapping
  mappings/net/minecraft/client/network/AbstractClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientConfigurationNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerLikeState.mapping
  mappings/net/minecraft/client/option/KeyBinding.mapping
  mappings/net/minecraft/client/option/StickyKeyBinding.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsMainScreen.mapping
  mappings/net/minecraft/client/sound/SoundExecutor.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/texture/PlayerSkinCache.mapping
  mappings/net/minecraft/client/texture/PlayerSkinProvider.mapping
  mappings/net/minecraft/client/texture/PlayerSkinTextureDownloader.mapping
  mappings/net/minecraft/client/util/Clipboard.mapping
  mappings/net/minecraft/client/util/DefaultSkinHelper.mapping
  mappings/net/minecraft/client/util/InputUtil.mapping
  mappings/net/minecraft/client/util/MacWindowUtil.mapping
  mappings/net/minecraft/client/util/SelectionManager.mapping
  mappings/net/minecraft/client/util/math/Vec3fArray.mapping
  mappings/net/minecraft/command/EntitySelectorReader.mapping
  mappings/net/minecraft/data/loottable/BlockLootTableGenerator.mapping
  mappings/net/minecraft/data/loottable/vanilla/VanillaBlockLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/AddFieldFix.mapping
  mappings/net/minecraft/datafixer/fix/LegacyWorldBorderFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema4543.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/player/PlayerSkinType.mapping
  mappings/net/minecraft/network/listener/ClientConfigurationPacketListener.mapping
  mappings/net/minecraft/network/packet/c2s/config/AcceptCodeOfConductC2SPacket.mapping
  mappings/net/minecraft/network/packet/s2c/config/CodeOfConductS2CPacket.mapping
  mappings/net/minecraft/server/CodeOfConduct.mapping
  mappings/net/minecraft/util/function/Object2FloatFunction.mapping
Labels: bug, refactor, new, snapshot

#4292 25w36b final
  mappings/net/minecraft/block/EndPortalFrameBlock.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/input/SystemKeycodes.mapping
  mappings/net/minecraft/client/particle/AscendingParticle.mapping
  mappings/net/minecraft/client/particle/BillboardParticle.mapping
  mappings/net/minecraft/client/particle/BlockLeakParticle.mapping
  mappings/net/minecraft/client/particle/CampfireSmokeParticle.mapping
  mappings/net/minecraft/client/particle/ConnectionParticle.mapping
  mappings/net/minecraft/client/particle/ExplosionLargeParticle.mapping
  mappings/net/minecraft/client/particle/LeavesParticle.mapping
  mappings/net/minecraft/client/particle/NoteParticle.mapping
  mappings/net/minecraft/client/particle/OminousSpawningParticle.mapping
  mappings/net/minecraft/client/particle/ParticleManager.mapping
  mappings/net/minecraft/client/particle/ShriekParticle.mapping
  mappings/net/minecraft/client/particle/SweepAttackParticle.mapping
  mappings/net/minecraft/client/particle/TrailParticle.mapping
  mappings/net/minecraft/client/particle/VibrationParticle.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BedBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactories.mapping
  mappings/net/minecraft/client/render/block/entity/MobSpawnerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/TrialSpawnerBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderManager.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/PlayerEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/ArmorStandArmorEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModels.mapping
  mappings/net/minecraft/client/render/entity/model/VillagerResemblingModel.mapping
  mappings/net/minecraft/client/render/entity/state/PlayerEntityRenderState.mapping
  mappings/net/minecraft/client/render/entity/state/WitherSkullEntityRenderState.mapping
  mappings/net/minecraft/client/render/item/model/special/CopperGolemStatueModelRenderer.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/ai/brain/task/MoveItemsTask.mapping
  mappings/net/minecraft/entity/ai/goal/TemptGoal.mapping
  mappings/net/minecraft/entity/decoration/AbstractDecorationEntity.mapping
  mappings/net/minecraft/server/dedicated/management/RpcDiscover.mapping
  mappings/net/minecraft/server/dedicated/management/RpcRequestParameter.mapping
  mappings/net/minecraft/server/dedicated/management/schema/RpcSchema.mapping
  mappings/net/minecraft/util/Atlases.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
Labels: bug, refactor, new, snapshot

#4296 Rename the WitherEntity#shouldRenderOverlay method to isArmored
  mappings/net/minecraft/client/render/entity/state/WitherEntityRenderState.mapping
  mappings/net/minecraft/entity/boss/WitherEntity.mapping
Labels: refactor, snapshot

#4291 Add field name providers to name proposal
  build.gradle
  filament/src/main/java/net/fabricmc/filament/nameproposal/ConflictChecker.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/FieldNameFinder.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/MappingNameCompleter.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/NameFinder.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/NameProposalConfig.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/enigma/EnigmaNameProposalService.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/enigma/NameProposalServiceEnigmaPlugin.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/FieldData.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/nameprovider/ConditionalFieldNameProvider.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/nameprovider/ConstantFieldNameProvider.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/nameprovider/FieldNameProvider.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/nameprovider/SequenceFieldNameProvider.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/nameprovider/StringArgumentFieldNameProvider.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/ArgumentFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/DescriptorFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/EnumFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/FieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/InternalInitFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/MethodNameFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/MethodOwnerFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/NameFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/OwnerFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/StaticFieldPredicate.java
  filament/src/main/java/net/fabricmc/filament/nameproposal/field/predicate/StringFieldPredicate.java
  filament/src/test/java/net/fabricmc/filament/test/nameproposal/FieldTestMain.java
  filament/src/test/java/net/fabricmc/filament/test/nameproposal/TestClass.java
Labels: toolchain

#4297 Disable the ConflictChecker logger to work around Enigma freeze
  filament/src/main/java/net/fabricmc/filament/nameproposal/ConflictChecker.java
Labels: snapshot, toolchain

#4298 Propose names for static codec fields
  filament/src/main/java/net/fabricmc/filament/nameproposal/NameProposalConfig.java
Labels: snapshot

#4302 Add more mappings for 25w37a
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/render/state/TiledTexturedQuadGuiElementRenderState.mapping
  mappings/net/minecraft/client/network/ClientDebugSubscriptionManager.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/render/debug/BrainDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/EntityBlockIntersectionsDebugRenderer.mapping
  mappings/net/minecraft/client/render/debug/PoiDebugRenderer.mapping
  mappings/net/minecraft/client/sound/SoundPreviewer.mapping
  mappings/net/minecraft/world/debug/DebugDataStore.mapping
Labels: new, snapshot

#4308 1.21.9-pre1 mappings
  mappings/net/minecraft/class_12078.mapping
  mappings/net/minecraft/client/ClientAssets.mapping
  mappings/net/minecraft/client/particle/BillboardParticleSubmittable.mapping
  mappings/net/minecraft/client/render/SkyRendering.mapping
  mappings/net/minecraft/client/render/Submittable.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/command/LayeredCustomCommandRenderer.mapping
  mappings/net/minecraft/client/render/command/OrderedRenderCommandQueue.mapping
  mappings/net/minecraft/client/render/command/RenderCommandQueue.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderStates.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/state/BreakingBlockRenderState.mapping
  mappings/net/minecraft/client/render/state/CameraRenderState.mapping
  mappings/net/minecraft/client/render/state/OutlineRenderState.mapping
  mappings/net/minecraft/client/render/state/SkyRnederState.mapping
  mappings/net/minecraft/client/render/state/WeatherRenderState.mapping
  mappings/net/minecraft/client/render/state/WorldBorderRenderState.mapping
  mappings/net/minecraft/client/render/state/WorldRenderState.mapping
  mappings/net/minecraft/datafixer/fix/PlayerRespawnDataFix.mapping
  mappings/net/minecraft/datafixer/fix/WorldSpawnDataFix.mapping
  mappings/net/minecraft/server/dedicated/management/UriUtil.mapping
  unpick-definitions/lightmap_coordinates.unpick
Labels: new, snapshot

#4311 Rename the SkyRnederState class to SkyRenderState
  mappings/net/minecraft/client/render/state/SkyRenderState.mapping
Labels: bug, refactor, snapshot
