Repository FabricMC/yarn, pull requests merged in 2025-02, with the labels that each got.

#4107 random mappings
  mappings/net/minecraft/client/render/block/FluidRenderer.mapping
  mappings/net/minecraft/client/render/entity/LivingEntityRenderer.mapping
  mappings/net/minecraft/entity/vehicle/DefaultMinecartController.mapping
  mappings/net/minecraft/network/ClientConnection.mapping
  mappings/net/minecraft/resource/ProfiledResourceReload.mapping
  mappings/net/minecraft/world/Heightmap.mapping
  mappings/net/minecraft/world/chunk/light/ChunkLightProvider.mapping
  mappings/net/minecraft/world/chunk/light/ChunkSkyLightProvider.mapping
Labels: new, snapshot

#4108 25w06a stuff
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/CactusBlock.mapping
  mappings/net/minecraft/block/CactusFlowerBlock.mapping
  mappings/net/minecraft/block/DryVegetationBlock.mapping
  mappings/net/minecraft/block/Fertilizable.mapping
  mappings/net/minecraft/block/FireflyBushBlock.mapping
  mappings/net/minecraft/block/ShortDryGrassBlock.mapping
  mappings/net/minecraft/block/TallDryGrassBlock.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/entity/ChickenEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/ChickenEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ColdChickenEntityModel.mapping
  mappings/net/minecraft/client/render/entity/state/ChickenEntityRenderState.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/type/ChargedProjectilesComponent.mapping
  mappings/net/minecraft/component/type/FireworksComponent.mapping
  mappings/net/minecraft/datafixer/fix/PlayerEquipmentFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema4312.mapping
  mappings/net/minecraft/entity/EntityEquipment.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/Tameable.mapping
  mappings/net/minecraft/entity/ai/goal/EatGrassGoal.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/passive/ChickenEntity.mapping
  mappings/net/minecraft/entity/passive/ChickenVariant.mapping
  mappings/net/minecraft/entity/passive/ChickenVariants.mapping
  mappings/net/minecraft/entity/player/PlayerEquipment.mapping
  mappings/net/minecraft/entity/player/PlayerInventory.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/server/world/ChunkLevelManager.mapping
  mappings/net/minecraft/server/world/ServerChunkLoadingManager.mapping
  mappings/net/minecraft/server/world/ServerChunkManager.mapping
  mappings/net/minecraft/server/world/ServerWorld.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationPlacedFeatures.mapping
  unpick-definitions/set_block_state_flags.unpick
Labels: new, snapshot, unpick

#4110 More block state flag changes
  mappings/net/minecraft/block/Block.mapping
  mappings/net/minecraft/block/MangroveLeavesBlock.mapping
  mappings/net/minecraft/block/entity/BlockEntity.mapping
  unpick-definitions/set_block_state_flags.unpick
Labels: bug, refactor, snapshot, unpick

#4112 Fix swapped groupEntry/sequenceEntry
  mappings/net/minecraft/loot/entry/LootPoolEntry.mapping
Labels: bug, refactor, snapshot

#4111 World border rendering is cool
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/WorldBorderRendering.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/world/border/WorldBorder.mapping
Labels: new, snapshot

#4114 25w06a more
  mappings/net/minecraft/client/gui/CubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EggEntity.mapping
  mappings/net/minecraft/registry/entry/LazyRegistryEntryReference.mapping
  mappings/net/minecraft/village/raid/RaidManager.mapping
Labels: bug, refactor, new, snapshot

#4118 25w07a: shader programs (shader program layers)
  mappings/net/minecraft/class_10785.mapping
  mappings/net/minecraft/client/gl/BlendPrograms.mapping
  mappings/net/minecraft/client/gl/Defines.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gl/ShaderProgramLayers.mapping
Labels: new, snapshot

#4119 25w07a: Additional Rendering / Shader / Model maps
  mappings/net/minecraft/TextureType.mapping
  mappings/net/minecraft/block/ItemFrameBlockStates.mapping
  mappings/net/minecraft/class_10792.mapping
  mappings/net/minecraft/client/gl/ShaderProgramLayer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderState.mapping
  mappings/net/minecraft/client/render/model/BakedQuadFactory.mapping
  mappings/net/minecraft/client/render/model/BakedSimpleModel.mapping
  mappings/net/minecraft/client/render/model/Baker.mapping
  mappings/net/minecraft/client/render/model/ErrorCollectingSpriteGetter.mapping
  mappings/net/minecraft/client/render/model/FutureModel.mapping
  mappings/net/minecraft/client/render/model/Geometry.mapping
  mappings/net/minecraft/client/render/model/ModelBakeSettings.mapping
  mappings/net/minecraft/client/render/model/ModelSettings.mapping
  mappings/net/minecraft/client/render/model/ResolvableModel.mapping
  mappings/net/minecraft/client/render/model/SimpleModel.mapping
  mappings/net/minecraft/client/render/model/UnbakedGeometry.mapping
  mappings/net/minecraft/client/render/model/json/ModelElementFace.mapping
  mappings/net/minecraft/client/texture/ClampedTexture.mapping
  mappings/net/minecraft/client/texture/DrawableTexture.mapping
  mappings/net/minecraft/client/texture/FilteredTexture.mapping
  mappings/net/minecraft/client/texture/NativeImage.mapping
  mappings/net/minecraft/entity/passive/SheepColors.mapping
  mappings/net/minecraft/item/equipment/EquipmentHolder.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/util/math/Rotation.mapping
Labels: new, snapshot

#4120 25w07a small things
  mappings/net/minecraft/client/render/model/json/ModelVariant.mapping
  mappings/net/minecraft/datafixer/Schemas.mapping
  mappings/net/minecraft/datafixer/fix/ChunkTicketUnpackPosFix.mapping
  mappings/net/minecraft/datafixer/fix/InlineBlockPosFormatFix.mapping
  mappings/net/minecraft/entity/passive/AllayEntity.mapping
  mappings/net/minecraft/entity/passive/SheepColors.mapping
  mappings/net/minecraft/entity/passive/SheepEntity.mapping
  mappings/net/minecraft/entity/player/PlayerEntity.mapping
  mappings/net/minecraft/entity/vehicle/AbstractMinecartEntity.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/util/math/Direction.mapping
  mappings/net/minecraft/village/TradeOffers.mapping
Labels: refactor, new, snapshot

#4122 25w07a: more stuff
  mappings/net/minecraft/class_10806.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gl/PostEffectProcessor.mapping
  mappings/net/minecraft/client/gl/ShaderProgramLayer.mapping
  mappings/net/minecraft/client/gl/SimpleFramebuffer.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/gui/hud/DebugHud.mapping
  mappings/net/minecraft/client/item/ItemModelManager.mapping
  mappings/net/minecraft/client/render/BufferBuilderStorage.mapping
  mappings/net/minecraft/client/render/CloudRenderer.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/RenderPhase.mapping
  mappings/net/minecraft/client/render/entity/ItemEntityRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderState.mapping
  mappings/net/minecraft/client/render/item/model/BasicItemModel.mapping
  mappings/net/minecraft/client/render/item/model/MissingItemModel.mapping
  mappings/net/minecraft/client/render/item/model/SpecialItemModel.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/BakedQuadFactory.mapping
  mappings/net/minecraft/client/render/model/ErrorCollectingSpriteGetter.mapping
  mappings/net/minecraft/client/render/model/ModelRotation.mapping
  mappings/net/minecraft/client/render/model/ReferencedModelsCollector.mapping
  mappings/net/minecraft/client/render/model/json/ModelElementFace.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariant.mapping
  mappings/net/minecraft/client/render/model/json/ModelVariants.mapping
  mappings/net/minecraft/client/render/model/json/MultipartModelCondition.mapping
  mappings/net/minecraft/client/render/model/json/MultipartModelConditionBuilder.mapping
  mappings/net/minecraft/client/render/model/json/MultipartModelSelector.mapping
  mappings/net/minecraft/client/render/model/json/SimpleMultipartModelSelector.mapping
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
Labels: new, snapshot

#4124 More 25w07a stuff, fixing TextureType and GeometryBakedModel pathing
  mappings/net/minecraft/TextureType.mapping
  mappings/net/minecraft/block/entity/AbstractFurnaceBlockEntity.mapping
  mappings/net/minecraft/block/entity/BeaconBlockEntity.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/DiffuseLighting.mapping
  mappings/net/minecraft/client/render/Tessellator.mapping
  mappings/net/minecraft/client/render/VertexFormatElement.mapping
  mappings/net/minecraft/client/render/WorldBorderRendering.mapping
  mappings/net/minecraft/client/render/chunk/ChunkBuilder.mapping
  mappings/net/minecraft/client/render/model/ErrorCollectingSpriteGetter.mapping
  mappings/net/minecraft/client/render/model/GeometryBakedModel.mapping
  mappings/net/minecraft/client/render/model/ModelBaker.mapping
  mappings/net/minecraft/client/render/model/ModelRotation.mapping
  mappings/net/minecraft/client/render/model/MultipartBakedModel.mapping
  mappings/net/minecraft/client/render/model/MultipartUnbakedModel.mapping
  mappings/net/minecraft/client/render/model/UnbakedGeometry.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
  mappings/net/minecraft/client/render/model/json/GeneratedItemModel.mapping
  mappings/net/minecraft/client/render/model/json/ModelElementFace.mapping
  mappings/net/minecraft/client/render/model/json/MultipartModelComponent.mapping
  mappings/net/minecraft/client/render/model/json/MultipartModelSelector.mapping
  mappings/net/minecraft/client/render/model/json/WeightedUnbakedModel.mapping
  mappings/net/minecraft/client/texture/TextureType.mapping
  mappings/net/minecraft/util/math/AffineTransformations.mapping
Labels: new, snapshot

#4125 Fix issues with previous PR
  mappings/net/minecraft/client/gl/ShaderProgramLayer.mapping
  mappings/net/minecraft/client/gl/ShaderProgramLayers.mapping
  mappings/net/minecraft/client/render/RenderLayer.mapping
  mappings/net/minecraft/client/render/model/BakedModel.mapping
  mappings/net/minecraft/client/render/model/BakedSimpleModel.mapping
  mappings/net/minecraft/client/render/model/GeometryBakedModel.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/WeightedBakedModel.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/texture/MapTextureManager.mapping
Labels: bug, refactor, snapshot

#4128 25w08a stuff
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/color/world/BiomeColors.mapping
  mappings/net/minecraft/client/render/entity/feature/SheepWoolFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/SheepWoolUndercoatFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/client/render/entity/state/SheepEntityRenderState.mapping
  mappings/net/minecraft/client/render/model/UnbakedModel.mapping
  mappings/net/minecraft/client/render/model/json/JsonUnbakedModel.mapping
  mappings/net/minecraft/client/resource/DryFoliageColormapResourceSupplier.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/passive/WolfEntity.mapping
  mappings/net/minecraft/entity/passive/WolfSoundVariant.mapping
  mappings/net/minecraft/entity/passive/WolfSoundVariants.mapping
  mappings/net/minecraft/sound/SoundEvents.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/BiomeColors.mapping
  mappings/net/minecraft/world/biome/BiomeEffects.mapping
  mappings/net/minecraft/world/biome/DryFoliageColors.mapping
  mappings/net/minecraft/world/biome/FoliageColors.mapping
  mappings/net/minecraft/world/biome/GrassColors.mapping
  mappings/net/minecraft/world/biome/OverworldBiomeCreator.mapping
Labels: new, snapshot

#4130 25w08a render
  mappings/com/mojang/blaze3d/platform/TextureUtil.mapping
  mappings/net/minecraft/client/font/GlyphAtlasTexture.mapping
  mappings/net/minecraft/client/gl/Defines.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/gl/GlUniform.mapping
  mappings/net/minecraft/client/gl/GpuBuffer.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gl/ShaderLoader.mapping
  mappings/net/minecraft/client/gl/ShaderPipeline.mapping
  mappings/net/minecraft/client/gl/ShaderPipelines.mapping
  mappings/net/minecraft/client/gl/ShaderProgram.mapping
  mappings/net/minecraft/client/gl/VertexBuffer.mapping
  mappings/net/minecraft/client/gl/WindowFramebuffer.mapping
  mappings/net/minecraft/client/item/ItemModelManager.mapping
  mappings/net/minecraft/client/render/ChunkRenderingDataPreparer.mapping
  mappings/net/minecraft/client/render/CloudRenderer.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/WorldBorderRendering.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/render/item/ItemRenderState.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/item/model/ItemModel.mapping
  mappings/net/minecraft/client/render/item/model/special/SimpleSpecialModelRenderer.mapping
  mappings/net/minecraft/client/render/item/model/special/SpecialModelRenderer.mapping
  mappings/net/minecraft/client/render/item/property/PropertyTester.mapping
  mappings/net/minecraft/client/render/item/property/select/SelectProperty.mapping
  mappings/net/minecraft/client/render/model/BakedModelManager.mapping
  mappings/net/minecraft/client/render/model/BakedQuad.mapping
  mappings/net/minecraft/client/render/model/BakedQuadFactory.mapping
  mappings/net/minecraft/client/render/model/BlockStateManagers.mapping
  mappings/net/minecraft/client/render/model/ModelGrouper.mapping
  mappings/net/minecraft/client/render/model/ModelRotation.mapping
  mappings/net/minecraft/client/render/model/ReferencedModelsCollector.mapping
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
  mappings/net/minecraft/client/texture/DrawableTexture.mapping
  mappings/net/minecraft/client/texture/NativeImageBackedTexture.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/TextureManager.mapping
  mappings/net/minecraft/client/texture/TextureType.mapping
  mappings/net/minecraft/entity/decoration/DisplayEntity.mapping
  mappings/net/minecraft/item/ItemDisplayContext.mapping
Labels: bug, refactor, new, snapshot
