Repository FabricMC/yarn, pull requests merged in 2025-05, with the labels that each got.

#4188 25w18a stuff
  mappings/com/mojang/blaze3d/systems/CommandEncoder.mapping
  mappings/net/minecraft/client/gl/PostEffectPass.mapping
  mappings/net/minecraft/client/gui/EditBox.mapping
  mappings/net/minecraft/client/gui/ScreenRect.mapping
  mappings/net/minecraft/client/gui/render/state/ColoredQuadGuiElementRenderState.mapping
  mappings/net/minecraft/client/gui/render/state/special/ProfilerChartGuiElementRenderState.mapping
  mappings/net/minecraft/client/gui/render/state/special/SignGuiElementRenderState.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
  mappings/net/minecraft/data/tag/SimpleTagProvider.mapping
  mappings/net/minecraft/data/tag/ValueLookupTagProvider.mapping
  mappings/net/minecraft/data/tag/vanilla/VanillaBlockItemTags.mapping
  mappings/net/minecraft/network/codec/PacketCodecs.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/storage/NbtReadView.mapping
  mappings/net/minecraft/storage/NbtWriteView.mapping
  mappings/net/minecraft/structure/StructureTemplate.mapping
  mappings/net/minecraft/world/chunk/ChunkGenerating.mapping
  mappings/net/minecraft/world/chunk/WorldChunk.mapping
  unpick-definitions/entity_model_parts.unpick
  unpick-definitions/gl.unpick
  unpick-definitions/gui_widget.unpick
  unpick-definitions/nbt_type_ids.unpick
  unpick-definitions/network_packets.unpick
Labels: bug, refactor, new, snapshot, unpick

#4190 25w19a stuff
  mappings/com/mojang/blaze3d/textures/GpuTexture.mapping
  mappings/com/mojang/blaze3d/textures/GpuTextureView.mapping
  mappings/net/minecraft/class_11400.mapping
  mappings/net/minecraft/client/RunArgs.mapping
  mappings/net/minecraft/client/gui/CubeMapRenderer.mapping
  mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
  mappings/net/minecraft/client/main/Main.mapping
  mappings/net/minecraft/client/render/BlindnessFogModifier.mapping
  mappings/net/minecraft/client/render/DarknessFogModifier.mapping
  mappings/net/minecraft/client/render/FogData.mapping
  mappings/net/minecraft/client/render/StatusEffectFogModifier.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/fog/AtmosphericFogModifier.mapping
  mappings/net/minecraft/client/render/fog/BlindnessEffectFogModifier.mapping
  mappings/net/minecraft/client/render/fog/DarknessEffectFogModifier.mapping
  mappings/net/minecraft/client/render/fog/DimensionOrBossFogModifier.mapping
  mappings/net/minecraft/client/render/fog/FogData.mapping
  mappings/net/minecraft/client/render/fog/FogModifier.mapping
  mappings/net/minecraft/client/render/fog/FogRenderer.mapping
  mappings/net/minecraft/client/render/fog/LavaFogModifier.mapping
  mappings/net/minecraft/client/render/fog/PowderSnowFogModifier.mapping
  mappings/net/minecraft/client/render/fog/StandardFogModifier.mapping
  mappings/net/minecraft/client/render/fog/StatusEffectFogModifier.mapping
  mappings/net/minecraft/client/render/fog/WaterFogModifier.mapping
  mappings/net/minecraft/client/render/item/ItemRenderState.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/texture/AbstractTexture.mapping
  mappings/net/minecraft/client/texture/CubemapTexture.mapping
  mappings/net/minecraft/client/texture/GlTexture.mapping
  mappings/net/minecraft/client/texture/GlTextureView.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/data/advancement/vanilla/VanillaAdventureTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/EntityStatuses.mapping
  mappings/net/minecraft/entity/EyeOfEnderEntity.mapping
  mappings/net/minecraft/entity/ItemEntity.mapping
  mappings/net/minecraft/entity/LazyEntityReference.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/conversion/EntityConversionType.mapping
  mappings/net/minecraft/entity/mob/GhastEntity.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/mob/RavagerEntity.mapping
  mappings/net/minecraft/entity/passive/HappyGhastEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileEntity.mapping
  mappings/net/minecraft/entity/projectile/ProjectileUtil.mapping
  mappings/net/minecraft/entity/projectile/ShulkerBulletEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/EnderPearlEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/SplashPotionEntity.mapping
  mappings/net/minecraft/predicate/entity/EntityPredicates.mapping
  mappings/net/minecraft/server/network/ServerPlayerEntity.mapping
  mappings/net/minecraft/server/network/ServerWaypointHandler.mapping
  mappings/net/minecraft/test/TestManager.mapping
  unpick-definitions/entity_status.unpick
Labels: refactor, new, snapshot

#4192 Rename the BlockPredicatesChecker class to BlockPredicatesComponent
  mappings/net/minecraft/component/type/BlockPredicatesComponent.mapping
Labels: refactor, snapshot, javadoc

#4196 25w20a a little more
  mappings/net/minecraft/block/entity/SignBlockEntity.mapping
  mappings/net/minecraft/class_11456.mapping
  mappings/net/minecraft/client/gui/render/state/GlyphEffectGuiElementRenderState.mapping
  mappings/net/minecraft/client/gui/screen/CreditsScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/CyclingButtonWidget.mapping
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/realms/RealmsError.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConnectingScreen.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsScreen.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/command/PermissionLevelPredicate.mapping
  mappings/net/minecraft/command/PermissionLevelSource.mapping
  mappings/net/minecraft/command/suggestion/SuggestionProviders.mapping
  mappings/net/minecraft/entity/Leashable.mapping
  mappings/net/minecraft/entity/decoration/AbstractDecorationEntity.mapping
  mappings/net/minecraft/entity/passive/AbstractHorseEntity.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/PublishCommand.mapping
  mappings/net/minecraft/server/command/ScheduleCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/world/Difficulty.mapping
Labels: new, snapshot

#4197 More 25w20a mappings
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/network/ClientCommandSource.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/argument/ArgumentHelper.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
Labels: new, snapshot

#4198 25w20a more stuff
  mappings/net/minecraft/client/gl/RenderPipelines.mapping
  mappings/net/minecraft/client/gui/screen/GameMenuScreen.mapping
  mappings/net/minecraft/client/gui/screen/GameModeSwitcherScreen.mapping
  mappings/net/minecraft/client/gui/screen/dialog/ColumnsDialogScreen.mapping
  mappings/net/minecraft/client/gui/screen/dialog/InputControlHandler.mapping
  mappings/net/minecraft/client/gui/screen/dialog/SimpleInputFormDialogScreen.mapping
  mappings/net/minecraft/client/gui/screen/dialog/SubmitMethodHandler.mapping
  mappings/net/minecraft/client/gui/screen/dialog/SubmitMethodHandlers.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/realms/dto/RegionSelectionMethod.mapping
  mappings/net/minecraft/client/realms/gui/screen/RealmsConfigureWorldScreen.mapping
  mappings/net/minecraft/client/render/CloudRenderer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/sound/SoundManager.mapping
  mappings/net/minecraft/client/sound/SoundSystem.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/command/CommandSource.mapping
  mappings/net/minecraft/command/argument/ArgumentHelper.mapping
  mappings/net/minecraft/dialog/submit/CustomFormSubmitMethod.mapping
  mappings/net/minecraft/dialog/submit/CustomSubmitMethod.mapping
  mappings/net/minecraft/dialog/submit/ParsedTemplate.mapping
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/command/CommandManager.mapping
  mappings/net/minecraft/server/command/GameModeCommand.mapping
  mappings/net/minecraft/server/command/ServerCommandSource.mapping
  mappings/net/minecraft/world/gen/chunk/FlatChunkGeneratorLayer.mapping
Labels: new, snapshot

#4199 Clarify functionality of ChatHud#getMessageIndex(..) and some Formatting methods
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/util/Formatting.mapping
Labels: snapshot
