Repository FabricMC/yarn, pull requests merged in 2025-08, with the labels that each got.

#4228 25w31a render command queue renderer
  mappings/net/minecraft/class_11689.mapping
  mappings/net/minecraft/class_11690.mapping
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/gui/render/EntityGuiElementRenderer.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/WorldRenderer.mapping
  mappings/net/minecraft/client/render/block/BlockRenderManager.mapping
  mappings/net/minecraft/client/render/block/entity/BlockEntityRenderManager.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderManager.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderStates.mapping
  mappings/net/minecraft/client/render/entity/EntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/BatchingEntityRenderCommandQueue.mapping
  mappings/net/minecraft/client/render/entity/command/CustomCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/DebugHitboxCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/EntityRenderDispatcher.mapping
  mappings/net/minecraft/client/render/entity/command/FallingBlockCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/FireCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/ItemCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/LabelCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/LeashCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/ModelCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/ShadowPiecesCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/TextCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModelLayers.mapping
  mappings/net/minecraft/client/render/entity/model/EquipmentModelData.mapping
  mappings/net/minecraft/client/render/entity/model/ZombieVillagerEntityModel.mapping
  mappings/net/minecraft/client/render/item/HeldItemRenderer.mapping
  mappings/net/minecraft/client/texture/AtlasManager.mapping
  mappings/net/minecraft/client/texture/SpriteAtlasTexture.mapping
  mappings/net/minecraft/client/texture/SpriteHolder.mapping
Labels: refactor, new, snapshot

#4234 25w31a more rendering things
  mappings/net/minecraft/class_11566.mapping
  mappings/net/minecraft/client/font/FontManager.mapping
  mappings/net/minecraft/client/font/FontStorage.mapping
  mappings/net/minecraft/client/font/GlyphBaker.mapping
  mappings/net/minecraft/client/font/GlyphProvider.mapping
  mappings/net/minecraft/client/font/OnceBakedGlyph.mapping
  mappings/net/minecraft/client/font/TextRenderer.mapping
  mappings/net/minecraft/client/model/ModelPartData.mapping
  mappings/net/minecraft/client/render/block/entity/ShelfBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/SignBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/DisplayEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/command/BatchingEntityRenderCommandQueue.mapping
  mappings/net/minecraft/client/render/entity/command/ShadowPiecesCommandRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/BipedEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/BreezeEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CopperGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/CreakingEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/EntityModels.mapping
  mappings/net/minecraft/client/render/entity/model/ModelWithHat.mapping
  mappings/net/minecraft/client/render/entity/model/PiglinBaseEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/PlayerEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/WardenEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ZombieVillagerEntityModel.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/item/model/ItemModel.mapping
  mappings/net/minecraft/client/render/item/model/special/SignModelRenderer.mapping
  mappings/net/minecraft/client/render/item/property/numeric/CompassState.mapping
  mappings/net/minecraft/client/render/item/property/numeric/NeedleAngleState.mapping
  mappings/net/minecraft/client/render/item/property/numeric/NumericProperty.mapping
  mappings/net/minecraft/client/texture/AtlasManager.mapping
  mappings/net/minecraft/resource/ProfiledResourceReload.mapping
  mappings/net/minecraft/resource/ResourceReloader.mapping
  mappings/net/minecraft/resource/SimpleResourceReload.mapping
  mappings/net/minecraft/util/EntityPos.mapping
  unpick-definitions/entity_model_parts.unpick
Labels: new, snapshot

#4246 Rename Entity.getWorld() -> getEntityWorld()
  mappings/net/minecraft/entity/Tameable.mapping
  mappings/net/minecraft/entity/vehicle/VehicleInventory.mapping
  mappings/net/minecraft/util/HeldItemContext.mapping
Labels: bug, refactor, impactful

#4245 25w33a mappings
  mappings/net/minecraft/client/gui/hud/bar/LocatorBar.mapping
  mappings/net/minecraft/client/render/DimensionEffects.mapping
  mappings/net/minecraft/client/render/EndLightFlashManager.mapping
  mappings/net/minecraft/client/render/LightmapTextureManager.mapping
  mappings/net/minecraft/client/render/SkyRendering.mapping
  mappings/net/minecraft/client/render/entity/CopperGolemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/CopperGolemHeadBlockFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/FeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/CopperGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/state/CopperGolemEntityRenderState.mapping
  mappings/net/minecraft/client/sound/EndLightFlashSoundInstance.mapping
  mappings/net/minecraft/client/world/BlockParticleEffectsManager.mapping
  mappings/net/minecraft/client/world/ClientWorld.mapping
  mappings/net/minecraft/particle/BlockParticleEffect.mapping
  mappings/net/minecraft/util/collection/Pool.mapping
  mappings/net/minecraft/util/collection/Weighted.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/waypoint/EntityTickProgress.mapping
  mappings/net/minecraft/world/waypoint/TrackedWaypoint.mapping
Labels: new, snapshot

#4244 Publish unpick as intermediary
  build.gradle
  unpick-definitions/unpick.json
Labels: snapshot

#4247 25w33a chat drafts
  mappings/net/minecraft/client/MinecraftClient.mapping
  mappings/net/minecraft/client/Mouse.mapping
  mappings/net/minecraft/client/gui/Element.mapping
  mappings/net/minecraft/client/gui/hud/ChatHud.mapping
  mappings/net/minecraft/client/gui/screen/ChatScreen.mapping
  mappings/net/minecraft/client/gui/screen/Screen.mapping
  mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
  mappings/net/minecraft/client/network/ClientCommonNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientConfigurationNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/screen/ScreenTexts.mapping
Labels: new, snapshot

#4253 Improved name for ``Selectable#isNarratable``
  mappings/net/minecraft/client/gui/Selectable.mapping
Labels: bug, snapshot

#4266 25w35a Fix Mapping of `/server/dedicated/management`
  mappings/net/minecraft/server/MinecraftServer.mapping
  mappings/net/minecraft/server/dedicated/MinecraftDedicatedServer.mapping
  mappings/net/minecraft/server/dedicated/management/IncomingRpcMethod.mapping
  mappings/net/minecraft/server/dedicated/management/IncomingRpcMethods.mapping
  mappings/net/minecraft/server/dedicated/management/OutgoingRpcMethod.mapping
  mappings/net/minecraft/server/dedicated/management/OutgoingRpcMethods.mapping
  mappings/net/minecraft/server/dedicated/management/dispatch/GameRuleRpcDispatcher.mapping
  mappings/net/minecraft/server/dedicated/management/dispatch/IpBansRpcDispatcher.mapping
  mappings/net/minecraft/server/dedicated/management/handler/GameRuleManagementHandler.mapping
  mappings/net/minecraft/server/dedicated/management/handler/PropertiesManagementHandler.mapping
  mappings/net/minecraft/server/dedicated/management/listener/ManagementListener.mapping
  mappings/net/minecraft/server/dedicated/management/listener/NotificationManagementListener.mapping
Labels: new, snapshot
