Repository FabricMC/yarn, pull requests merged in 2025-01, with the labels that each got.

#4073 Rename `CommandTreeS2CPacket.rootSize` to `rootIndex`
  mappings/net/minecraft/network/packet/s2c/play/CommandTreeS2CPacket.mapping
Labels: bug, release

#4075 Rename the LootContext#requireParameter method to getOrThrow
  mappings/net/minecraft/loot/context/LootContext.mapping
Labels: bug, refactor, release

#4074 Fix misleading `LEVEL_3_MIN` field
  mappings/net/minecraft/state/property/Properties.mapping
Labels: bug, refactor, release

#4047 fix: always use 'fps' instead of 'framerate'
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/session/telemetry/PerformanceMetricsEvent.mapping
Labels: bug, refactor, release

#4077 25w02a changes
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/FlowerbedBlock.mapping
  mappings/net/minecraft/block/LeafLitterBlock.mapping
  mappings/net/minecraft/block/LeavesBlock.mapping
  mappings/net/minecraft/block/SegmentedFlowerBlock.mapping
  mappings/net/minecraft/client/particle/LeavesParticle.mapping
  mappings/net/minecraft/command/argument/ArgumentReaderUtils.mapping
  mappings/net/minecraft/command/argument/StyleArgumentType.mapping
  mappings/net/minecraft/component/type/WrittenBookContentComponent.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/server/command/FillCommand.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/text/ClickEvent.mapping
  mappings/net/minecraft/text/HoverEvent.mapping
  mappings/net/minecraft/text/TextCodecs.mapping
  mappings/net/minecraft/util/JsonHelper.mapping
  mappings/net/minecraft/util/JsonReaderUtils.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, snapshot

#4080 Map pig variants
  mappings/net/minecraft/client/model/BabyModelPair.mapping
  mappings/net/minecraft/client/render/entity/PigEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/ColdPigEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/PigEntityModel.mapping
  mappings/net/minecraft/client/render/entity/state/PigEntityRenderState.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/passive/AnimalTemperature.mapping
  mappings/net/minecraft/entity/passive/PigEntity.mapping
  mappings/net/minecraft/entity/passive/PigVariant.mapping
  mappings/net/minecraft/entity/passive/PigVariants.mapping
Labels: new, snapshot

#4078 25w02a stuff
  mappings/net/minecraft/block/Falling.mapping
  mappings/net/minecraft/block/FlowerbedBlock.mapping
  mappings/net/minecraft/block/Segmented.mapping
  mappings/net/minecraft/block/SegmentedFlowerBlock.mapping
  mappings/net/minecraft/block/enums/CreakingHeartState.mapping
  mappings/net/minecraft/class_10565.mapping
  mappings/net/minecraft/client/data/BlockStateModelGenerator.mapping
  mappings/net/minecraft/client/data/TexturedModel.mapping
  mappings/net/minecraft/component/DataComponentTypes.mapping
  mappings/net/minecraft/component/type/WeaponComponent.mapping
  mappings/net/minecraft/datafixer/fix/AreaEffectCloudDurationScaleFix.mapping
  mappings/net/minecraft/datafixer/fix/BlockEntityCustomNameToTextFix.mapping
  mappings/net/minecraft/datafixer/fix/DropChancesFormatFix.mapping
  mappings/net/minecraft/datafixer/fix/ForcedChunkToTicketFix.mapping
  mappings/net/minecraft/datafixer/fix/LegacyHoverEventFix.mapping
  mappings/net/minecraft/datafixer/fix/TextComponentHoverAndClickEventFix.mapping
  mappings/net/minecraft/datafixer/fix/TextComponentStrictJsonFix.mapping
  mappings/net/minecraft/datafixer/fix/TextComponentStringyFlagsFix.mapping
  mappings/net/minecraft/datafixer/fix/UnflattenTextComponentFix.mapping
  mappings/net/minecraft/datafixer/schema/Schema1488.mapping
  mappings/net/minecraft/datafixer/schema/Schema1925.mapping
  mappings/net/minecraft/datafixer/schema/Schema3439.mapping
  mappings/net/minecraft/datafixer/schema/Schema3813.mapping
  mappings/net/minecraft/datafixer/schema/Schema4290.mapping
  mappings/net/minecraft/datafixer/schema/Schema4292.mapping
  mappings/net/minecraft/entity/EquipmentDropChances.mapping
  mappings/net/minecraft/entity/mob/MobEntity.mapping
  mappings/net/minecraft/entity/projectile/ArrowEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
  mappings/net/minecraft/recipe/SmithingTransformRecipe.mapping
  mappings/net/minecraft/recipe/TransmuteRecipe.mapping
  mappings/net/minecraft/recipe/TransmuteRecipeResult.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/util/Unit.mapping
  mappings/net/minecraft/util/collection/Pool.mapping
  mappings/net/minecraft/util/collection/Present.mapping
  mappings/net/minecraft/world/gen/feature/TreeConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/feature/TreeFeature.mapping
  mappings/net/minecraft/world/gen/feature/TreePlacedFeatures.mapping
  mappings/net/minecraft/world/gen/feature/VegetationConfiguredFeatures.mapping
  mappings/net/minecraft/world/gen/treedecorator/PlaceOnGroundTreeDecorator.mapping
Labels: new, snapshot

#4082 25w02a more stuff
  mappings/net/minecraft/block/entity/StructureBlockBlockEntity.mapping
  mappings/net/minecraft/class_10598.mapping
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/gui/screen/ingame/StructureBlockScreen.mapping
  mappings/net/minecraft/client/input/Input.mapping
  mappings/net/minecraft/command/argument/BlockStateArgument.mapping
  mappings/net/minecraft/component/type/PotionContentsComponent.mapping
  mappings/net/minecraft/data/loottable/BlockLootTableGenerator.mapping
  mappings/net/minecraft/enchantment/EnchantmentLevelEntry.mapping
  mappings/net/minecraft/entity/AreaEffectCloudEntity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/entity/effect/StatusEffectInstance.mapping
  mappings/net/minecraft/entity/mob/WaterCreatureEntity.mapping
  mappings/net/minecraft/entity/passive/AxolotlEntity.mapping
  mappings/net/minecraft/entity/passive/FrogVariant.mapping
  mappings/net/minecraft/item/BucketItem.mapping
  mappings/net/minecraft/item/FluidModificationItem.mapping
  mappings/net/minecraft/item/ItemStack.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/equipment/ArmorMaterials.mapping
  mappings/net/minecraft/nbt/NbtCompound.mapping
  mappings/net/minecraft/network/packet/c2s/play/UpdateStructureBlockC2SPacket.mapping
  mappings/net/minecraft/registry/Registries.mapping
  mappings/net/minecraft/resource/DefaultResourcePackBuilder.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
  mappings/net/minecraft/test/TestContext.mapping
  mappings/net/minecraft/test/TestFunction.mapping
  mappings/net/minecraft/util/Urls.mapping
  mappings/net/minecraft/util/Util.mapping
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/biome/Biome.mapping
  mappings/net/minecraft/world/biome/FoliageColors.mapping
Labels: new, snapshot

#4083 Map pool and weighting stuff
  mappings/net/minecraft/util/collection/Pool.mapping
  mappings/net/minecraft/util/collection/Weighted.mapping
  mappings/net/minecraft/util/collection/Weighting.mapping
Labels: new, snapshot

#4052 Add 'Client' suffix to some 'World' methods to indicate that they only work on the client
  mappings/net/minecraft/world/World.mapping
  mappings/net/minecraft/world/WorldAccess.mapping
Labels: refactor, snapshot, javadoc, impactful

#4089 25w02a missing stuff
  mappings/net/minecraft/client/WindowSettings.mapping
  mappings/net/minecraft/client/gl/Framebuffer.mapping
  mappings/net/minecraft/client/option/GameOptions.mapping
  mappings/net/minecraft/client/option/InactivityFpsLimiter.mapping
  mappings/net/minecraft/client/particle/BillboardParticle.mapping
  mappings/net/minecraft/client/realms/dto/RealmsWorldOptions.mapping
  mappings/net/minecraft/client/render/GameRenderer.mapping
  mappings/net/minecraft/client/render/entity/feature/HorseMarkingFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/PigEntityModel.mapping
  mappings/net/minecraft/client/toast/AdvancementToast.mapping
  mappings/net/minecraft/client/toast/Toast.mapping
  mappings/net/minecraft/client/toast/ToastManager.mapping
  mappings/net/minecraft/client/util/ClosableFactory.mapping
  mappings/net/minecraft/client/util/NarratorManager.mapping
  mappings/net/minecraft/client/util/Pool.mapping
  mappings/net/minecraft/client/util/math/MatrixStack.mapping
  mappings/net/minecraft/util/profiler/TickTimeTracker.mapping
  mappings/net/minecraft/world/gen/feature/DefaultBiomeFeatures.mapping
  unpick-definitions/set_block_state_flags.unpick
Labels: new, snapshot

#4090 25w02a finishing stuff
  mappings/net/minecraft/client/gl/PostEffectPipeline.mapping
  mappings/net/minecraft/client/gui/DrawContext.mapping
  mappings/net/minecraft/client/gui/hud/InGameHud.mapping
  mappings/net/minecraft/client/sound/SoundEngine.mapping
  mappings/net/minecraft/util/dynamic/Codecs.mapping
Labels: new, snapshot

#4098 25w04a a bit more
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/entity/Sherds.mapping
  mappings/net/minecraft/block/entity/Spawner.mapping
  mappings/net/minecraft/client/color/block/BlockColors.mapping
  mappings/net/minecraft/client/gui/screen/option/VideoOptionsScreen.mapping
  mappings/net/minecraft/data/advancement/vanilla/VanillaHusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/entity/LivingEntity.mapping
  mappings/net/minecraft/item/ThrowablePotionItem.mapping
  mappings/net/minecraft/predicate/NbtPredicate.mapping
  mappings/net/minecraft/predicate/NumberRange.mapping
  mappings/net/minecraft/predicate/item/ComponentSubPredicate.mapping
  mappings/net/minecraft/recipe/SmithingTransformRecipe.mapping
  mappings/net/minecraft/recipe/SmithingTrimRecipe.mapping
  mappings/net/minecraft/server/command/SpawnArmorTrimsCommand.mapping
  mappings/net/minecraft/server/command/TestCommand.mapping
  mappings/net/minecraft/test/TestEntry.mapping
  mappings/net/minecraft/test/TestEnvironmentDefinition.mapping
Labels: new, snapshot

#4099 25w04a stuff I missed
  mappings/net/minecraft/client/network/ClientPlayNetworkHandler.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/client/render/entity/UndeadHorseEntityRenderer.mapping
  mappings/net/minecraft/client/render/item/model/WorldDependentModelData.mapping
  mappings/net/minecraft/client/render/item/property/PropertyTester.mapping
  mappings/net/minecraft/client/texture/atlas/Atlases.mapping
  mappings/net/minecraft/client/texture/atlas/DirectoryAtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/FilterAtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/PalettedPermutationsAtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/SingleAtlasSource.mapping
  mappings/net/minecraft/client/texture/atlas/UnstitchAtlasSource.mapping
  mappings/net/minecraft/client/world/DataCache.mapping
  mappings/net/minecraft/command/argument/ArgumentReaderUtils.mapping
  mappings/net/minecraft/command/argument/ItemPredicateArgumentType.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/packrat/NbtParsingRule.mapping
  mappings/net/minecraft/command/argument/packrat/PackratParsing.mapping
  mappings/net/minecraft/data/advancement/vanilla/VanillaHusbandryTabAdvancementGenerator.mapping
  mappings/net/minecraft/data/loottable/EntityLootTableGenerator.mapping
  mappings/net/minecraft/data/recipe/RecipeGenerator.mapping
  mappings/net/minecraft/data/recipe/SmithingTrimRecipeJsonBuilder.mapping
  mappings/net/minecraft/entity/passive/CatVariants.mapping
  mappings/net/minecraft/entity/passive/FrogVariants.mapping
  mappings/net/minecraft/entity/passive/PigVariant.mapping
  mappings/net/minecraft/entity/passive/PigVariants.mapping
  mappings/net/minecraft/entity/passive/WolfVariants.mapping
  mappings/net/minecraft/entity/projectile/thrown/LingeringPotionEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/entity/projectile/thrown/SplashPotionEntity.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/equipment/trim/ArmorTrim.mapping
  mappings/net/minecraft/predicate/item/ItemSubPredicate.mapping
Labels: refactor, new, snapshot

#4100 25w04a more stuff
  mappings/net/minecraft/block/entity/TestInstanceBlockEntity.mapping
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
  mappings/net/minecraft/command/argument/ItemStringReader.mapping
  mappings/net/minecraft/command/argument/RegistryEntryArgumentType.mapping
  mappings/net/minecraft/component/type/ChargedProjectilesComponent.mapping
  mappings/net/minecraft/datafixer/fix/ChoiceFix.mapping
  mappings/net/minecraft/datafixer/fix/TypeChangeFix.mapping
  mappings/net/minecraft/entity/projectile/thrown/PotionEntity.mapping
  mappings/net/minecraft/item/BlockPredicatesChecker.mapping
  mappings/net/minecraft/item/CrossbowItem.mapping
  mappings/net/minecraft/item/equipment/trim/ArmorTrimMaterial.mapping
  mappings/net/minecraft/item/equipment/trim/ArmorTrimMaterials.mapping
  mappings/net/minecraft/nbt/StringNbtReader.mapping
  mappings/net/minecraft/predicate/item/ItemSubPredicate.mapping
  mappings/net/minecraft/world/gen/treedecorator/PlaceOnGroundTreeDecorator.mapping
  mappings/net/minecraft/world/spawner/CatSpawner.mapping
Labels: new, snapshot

#4101 Rename the LivingEntity#getKnockbackAgainst method to getAttackKnockbackAgainst
  mappings/net/minecraft/entity/LivingEntity.mapping
Labels: bug

#4103 Fix ClientPlayerEntity field conflicts
  mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
Labels: bug, refactor, snapshot

#4105 25w05a stuff I missed
  mappings/net/minecraft/block/DeadBushBlock.mapping
  mappings/net/minecraft/block/entity/SculkSpreadManager.mapping
  mappings/net/minecraft/datafixer/FixUtil.mapping
  mappings/net/minecraft/datafixer/fix/RaidRenamesDataFix.mapping
  mappings/net/minecraft/entity/Entity.mapping
  mappings/net/minecraft/sound/AmbientDesertBlockSounds.mapping
  mappings/net/minecraft/test/BlockBasedTestInstance.mapping
  mappings/net/minecraft/test/FunctionTestInstance.mapping
  mappings/net/minecraft/test/TestServer.mapping
  mappings/net/minecraft/util/InvalidHierarchicalFileException.mapping
  mappings/net/minecraft/util/InvalidIdentifierException.mapping
  mappings/net/minecraft/util/collection/PackedIntegerArray.mapping
  mappings/net/minecraft/village/raid/Raid.mapping
  mappings/net/minecraft/world/PersistentStateManager.mapping
  mappings/net/minecraft/world/updater/WorldUpdater.mapping
Labels: new, snapshot

#4106 Fix the capitalization of the FireflyBushBlock class
  mappings/net/minecraft/block/FireflyBushBlock.mapping
Labels: bug
