Repository FabricMC/yarn, pull requests merged in 2025-07, with the labels that each got.

#4215 Remove outdated comments regarding getRenderType and BlockWithEntity rendering
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/BlockWithEntity.mapping
Labels: release, javadoc

#4221 Rename the EntityEffectParticleEffect class to TintedParticleEffect
  mappings/net/minecraft/particle/TintedParticleEffect.mapping
Labels: refactor, release

#4222 Map the AMD cleanup hack method introduced in Minecraft 1.21.7 release candidate 2
  mappings/net/minecraft/client/gl/GlBackend.mapping
Labels: new, release

#4223 Port #4222 to 1.21.8-rc1
  mappings/net/minecraft/client/gl/GlBackend.mapping
Labels: snapshot

#4225 25w31a stuff
  mappings/net/minecraft/block/AbstractBlock.mapping
  mappings/net/minecraft/block/Blocks.mapping
  mappings/net/minecraft/block/ChestBlock.mapping
  mappings/net/minecraft/block/CopperChestBlock.mapping
  mappings/net/minecraft/block/CopperGolemStatueBlock.mapping
  mappings/net/minecraft/block/InteractibleSlotContainer.mapping
  mappings/net/minecraft/block/Oxidizable.mapping
  mappings/net/minecraft/block/OxidizableCopperChestBlock.mapping
  mappings/net/minecraft/block/OxidizableCopperGolemStatueBlock.mapping
  mappings/net/minecraft/block/OxidizableLightningRodBlock.mapping
  mappings/net/minecraft/block/ShelfBlock.mapping
  mappings/net/minecraft/block/SideChaining.mapping
  mappings/net/minecraft/block/entity/ChiseledBookshelfBlockEntity.mapping
  mappings/net/minecraft/block/entity/CopperGolemStatueBlockEntity.mapping
  mappings/net/minecraft/block/entity/EnderChestBlockEntity.mapping
  mappings/net/minecraft/block/entity/ShelfBlockEntity.mapping
  mappings/net/minecraft/block/entity/ViewerCountManager.mapping
  mappings/net/minecraft/block/enums/SideChainPart.mapping
  mappings/net/minecraft/client/data/BlockStateModelGenerator.mapping
  mappings/net/minecraft/client/model/Model.mapping
  mappings/net/minecraft/client/render/TexturedRenderLayers.mapping
  mappings/net/minecraft/client/render/block/entity/CopperGolemStatueBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/block/entity/ShelfBlockEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/CopperGolemEntityRenderer.mapping
  mappings/net/minecraft/client/render/entity/animation/CopperGolemAnimations.mapping
  mappings/net/minecraft/client/render/entity/feature/EmissiveFeatureRenderer.mapping
  mappings/net/minecraft/client/render/entity/model/CopperGolemEntityModel.mapping
  mappings/net/minecraft/client/render/entity/model/ModelWithArms.mapping
  mappings/net/minecraft/client/render/entity/state/CopperGolemEntityRenderState.mapping
  mappings/net/minecraft/client/render/item/ItemRenderer.mapping
  mappings/net/minecraft/client/render/item/model/special/ChestModelRenderer.mapping
  mappings/net/minecraft/client/render/item/model/special/CopperGolemStatueModelRenderer.mapping
  mappings/net/minecraft/client/render/item/model/special/SpecialModelRenderer.mapping
  mappings/net/minecraft/client/render/model/json/WeightedVariant.mapping
  mappings/net/minecraft/component/type/NbtComponent.mapping
  mappings/net/minecraft/data/loottable/vanilla/VanillaBrushLootTableGenerator.mapping
  mappings/net/minecraft/data/loottable/vanilla/VanillaChargedCreeperLootTableGenerator.mapping
  mappings/net/minecraft/data/loottable/vanilla/VanillaHarvestLootTableGenerator.mapping
  mappings/net/minecraft/datafixer/schema/Schema4531.mapping
  mappings/net/minecraft/datafixer/schema/Schema4532.mapping
  mappings/net/minecraft/datafixer/schema/Schema4533.mapping
  mappings/net/minecraft/entity/ContainerUser.mapping
  mappings/net/minecraft/entity/EntityType.mapping
  mappings/net/minecraft/entity/TypedEntityData.mapping
  mappings/net/minecraft/entity/data/TrackedDataHandlerRegistry.mapping
  mappings/net/minecraft/entity/passive/CopperGolemBrain.mapping
  mappings/net/minecraft/entity/passive/CopperGolemEntity.mapping
  mappings/net/minecraft/entity/passive/CopperGolemOxidationLevel.mapping
  mappings/net/minecraft/entity/passive/CopperGolemOxidationLevels.mapping
  mappings/net/minecraft/entity/passive/CopperGolemState.mapping
  mappings/net/minecraft/inventory/Inventory.mapping
  mappings/net/minecraft/inventory/ListInventory.mapping
  mappings/net/minecraft/item/Item.mapping
  mappings/net/minecraft/item/Items.mapping
  mappings/net/minecraft/item/ToolMaterial.mapping
  mappings/net/minecraft/item/equipment/ArmorMaterials.mapping
  mappings/net/minecraft/sound/BlockSoundGroup.mapping
  mappings/net/minecraft/state/property/Properties.mapping
Labels: new, snapshot

#4233 25w31a DebugOptionsScreen
  mappings/net/minecraft/client/gui/screen/DebugOptionsScreen.mapping
Labels: new, snapshot
